### ISSUE TITLE
BigQuery Storage API Error for Help

### ISSUE THREAD

**Issue by dkicenan** [googleapis/google-cloud-python#10025]
when I use bq storage API to get data from bq. I got an error message: "google.api_core.exceptions.InvalidArgument: 400 Invalid resource field value in the request."
The field is correct in the code. (I can get correct result from bq sql : select user_id from project_id.dataset_id.table_id)

### code:
def google_client(self):
        client = bigquery_storage_v1beta1.BigQueryStorageClient()

	table_ref = bigquery_storage_v1beta1.types.TableReference()
	table_ref.project_id = self.project_id
	table_ref.dataset_id = self.dataset_id
	table_ref.table_id = self.table_id

	read_options = bigquery_storage_v1beta1.types.TableReadOptions()
	read_options.selected_fields.append("user_id")
	modifiers = None

	parent = "project/{}".format(self.project_id)
	session = client.create_read_session(
		table_ref,
		parent,
		table_modifiers=modifiers,
		read_options=read_options,
		format_ = bigquery_storage_v1beta1.enums.DataFormat.AVRO,
		sharding_strategy=(bigquery_storage_v1beta1.enums.ShardingStrategy.LIQUID),
        )
	reader = client.read_rows(
            bigquery_storage_v1beta1.types.StreamPosition(stream=session.streams[0])
        )
    return reader, session

### error message:
"google.api_core.exceptions.InvalidArgument: 400 Invalid resource field value in the request."

**Comment by tswast** [comment]
I believe you need `parent = "projects/{}".format(self.project_id)`, not `parent = "project/{}".format(self.project_id)`.

**Comment by tswast** [comment]
See: https://googleapis.dev/python/bigquerystorage/latest/gapic/v1beta1/api.html#google.cloud.bigquery_storage_v1beta1.BigQueryStorageClient.create_read_session

**Comment by dkicenan** [comment]
> I believe you need `parent = "projects/{}".format(self.project_id)`, not `parent = "project/{}".format(self.project_id)`.
> 
> Note that `projects` is plural.

Thank you for your concern. I have solved it by your advice. Best wishes.

**Comment by dkicenan** [comment]
@tswast Thank you for your concern. I have solved it by your advice. Best wishes.
