### ISSUE TITLE
How to use google cloud api with microphone 

### ISSUE THREAD

**Issue by sumantafinarb** [googleapis/google-cloud-python#10033]
How to pass microphone data to speech to text api in python.I have tried with speech_recognition api and the same is working how to make the microphone work with google cloud speech rocgnition api .

**Comment by busunkim96** [comment]
@sumantafinarb We have some samples that show how to use the API with streaming input. Please see [Performing streaming speech recognition on an audio stream](https://cloud.google.com/speech-to-text/docs/streaming-recognize#performing_streaming_speech_recognition_on_an_audio_stream).

Please file an issue on that page if you have problems with the sample.

Thanks!
