### ISSUE TITLE
Typo in "Python Client for BigQuery Data Transfer API (Alpha)"

### ISSUE THREAD

**Issue by thomas-woodruff** [googleapis/google-cloud-python#10063]
The library name in various places on this [page](https://google-cloud-python.readthedocs.io/en/0.32.0/bigquery_datatransfer/index.html) is given as `google-cloud-bigquerydatatransfer`, rather than `google-cloud-bigquery-datatransfer`.

**Comment by HemangChothani** [comment]
@thomas-woodruff  Here is the updated [document](https://googleapis.dev/python/bigquerydatatransfer/latest/index.html) for the  `google-cloud-bigquery-datatransfer` library.
