### ISSUE TITLE
Drop Python 3.4 Support

### ISSUE THREAD

**Issue by hiranya911** [googleapis/google-cloud-python#10136]
Python 3.4 EoL'ed in March, 2019 and we'd like to drop support for Python 3.4 in downstream libraries like `firebase-admin`. Any plans to drop Py3.4 support in the google-cloud-python clients?

**Comment by busunkim96** [comment]
@hiranya911 IWe dropped 3.4 support for google-cloud-python last year. If it's lingering in READMEs or setup.py's that is unintentional. (Please feel free to file an issue if you see any).

You can treat the descriptors in the setup.py as the source of truth.

https://github.com/googleapis/google-cloud-python/blob/7a645026c6fe7ca5a812c2f5b418986fd25e0d75/firestore/setup.py#L72-L78

**Comment by tseaver** [comment]
@hiranya911 I'm not sure why having an upstream library continue to support a Python version would have any impact on the downstream's choice to drop it.  We are likely to make final releases having 2.7 / 3.4 support at around the time of the final 2.7 release (April), and then drop support for both, making major version number changes to mark the break.

**Comment by hiranya911** [comment]
Thanks for the info.

@busunkim96 almost all the setup files in this repo still allow installing on Python 3.4. But I see a separate issue has been reported to fix it at (at least for PubSub) #10167.

@tseaver it's not a blocker for us. We just prefer to keep our Python requirements in alignment with gcloud. Makes things easier for our users. However, April is a bit too far for us, so we will be looking to drop Python 3.4 support sometime in the next few weeks.
