### ISSUE TITLE
Docs: Some intersphinx references not linked as expected 

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-cloud-python#10177]
Originally raised in https://github.com/googleapis/docuploader/issues/18

![image](https://user-images.githubusercontent.com/8822365/72842163-aca69200-3c4c-11ea-9639-66e2477162df.png)

https://googleapis.dev/python/language/latest/gapic/v1/api.html#google.cloud.language_v1.LanguageServiceClient

**Comment by vchudnov-g** [comment]
With the current doc architecture, the error no longer exists on this page. We should be mindful that it doesn't come up during future doc work.
