### ISSUE TITLE
Please Google Cloud Composer Support!

### ISSUE THREAD

**Issue by eknis** [googleapis/google-cloud-python#10284]
Hello!

I use Cloud Composer every day!
It is troublesome to install sdk separately…

I want to add
```
・Adding or updating a DAG
・Deleting a DAG
```

**Comment by tswast** [comment]
@leahecole

**Comment by leahecole** [comment]
Hi @eknis! Right now Composer isn't part of this client library, but it does have gcloud commands where you can pass airflow [CLI arguments](https://airflow.apache.org/docs/stable/cli.html) - including those to list dags, delete dags, update, and create them.

**Comment by eknis** [comment]
Thank you for your reply @leahecole ! 
I know that commands can be used.  Are there plans to add that functionality to this client library? I'm trying to get information and create a dag from my own tools, but using commands and client libraries together isn't cool ...

**Comment by leahecole** [comment]
I can reach out to the product team to see its status in the backlog, but I can't speak to its timeline. Right now, the [Composer API](https://cloud.google.com/composer/docs/reference/rest/), which powers the gcloud commands, is constructed differently than libraries found here, and the change is non-trivial. We do accept community contributions though, if you are interested in adding the functionality. (Make sure you check out the [Contributing.rst](https://github.com/googleapis/google-cloud-python/blob/master/CONTRIBUTING.rst))

I do also want to take a second to remind you that there are people (including me) behind this software - people who work hard every day to improve the Composer developer experience, bit by bit. While your request and your criticisms are both valid, saying that using commands and client libraries together "isn't cool" is neither kind nor productive. I'll also take this time to remind you of the project's [code of conduct](https://github.com/googleapis/google-cloud-python/blob/master/CODE_OF_CONDUCT.md)

**Comment by eknis** [comment]
I'm sorry if I was offended.
Think about how to do it well. 
Thank you very much!
