### ISSUE TITLE
ERROR: Command errored out with exit status 1:      command: 'c:\program files (x86)\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\andre\\AppData\\Local\\Temp\\pip-install-7avnsone\\pyobjc-framework-CoreLocation\\setup.py'"'"'; __file__='"'"'C:\\Users\\andre\\AppData\\Local\\Temp\\pip-install-7avnsone\\pyobjc-framework-CoreLocation\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\andre\AppData\Local\Temp\pip-install-7avnsone\pyobjc-framework-CoreLocation\pip-egg-info'

### ISSUE THREAD

**Issue by anderoot** [googleapis/google-cloud-python#10396]
PS C:\Windows\system32> pip3 install pyttsx3
Collecting pyttsx3
  Using cached pyttsx3-2.84-py3-none-any.whl (39 kB)
Collecting comtypes; "win32" in sys_platform
  Using cached comtypes-1.1.7.zip (180 kB)
Collecting pyobjc>=2.4
  Using cached pyobjc-6.1-py3-none-any.whl (2.9 kB)
Collecting pyobjc-framework-AppleScriptKit==6.1
  Downloading pyobjc_framework_AppleScriptKit-6.1-py2.py3-none-any.whl (3.8 kB)
Collecting pyobjc-framework-XgridFoundation==6.1; platform_release < "12.0"
  Using cached pyobjc_framework_XgridFoundation-6.1-py2.py3-none-any.whl (5.1 kB)
Collecting pyobjc-framework-ApplicationServices==6.1
  Using cached pyobjc_framework_ApplicationServices-6.1-py2.py3-none-any.whl (20 kB)
Collecting pyobjc-framework-CoreLocation==6.1; platform_release >= "10.0"
  Downloading pyobjc-framework-CoreLocation-6.1.tar.gz (51 kB)
     |████████████████████████████████| 51 kB 32 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\andre\\AppData\\Local\\Temp\\pip-install-7avnsone\\pyobjc-framework-CoreLocation\\setup.py'"'"'; __file__='"'"'C:\\Users\\andre\\AppData\\Local\\Temp\\pip-install-7avnsone\\pyobjc-framework-CoreLocation\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\andre\AppData\Local\Temp\pip-install-7avnsone\pyobjc-framework-CoreLocation\pip-egg-info'
         cwd: C:\Users\andre\AppData\Local\Temp\pip-install-7avnsone\pyobjc-framework-CoreLocation\
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\andre\AppData\Local\Temp\pip-install-7avnsone\pyobjc-framework-CoreLocation\setup.py", line 22, in <module>
        Extension(
      File "C:\Users\andre\AppData\Local\Temp\pip-install-7avnsone\pyobjc-framework-CoreLocation\pyobjc_setup.py", line 408, in Extension
        os_level = get_os_level()
      File "C:\Users\andre\AppData\Local\Temp\pip-install-7avnsone\pyobjc-framework-CoreLocation\pyobjc_setup.py", line 218, in get_os_level
        pl = plistlib.readPlist("/System/Library/CoreServices/SystemVersion.plist")
      File "c:\program files (x86)\python38-32\lib\plistlib.py", line 99, in readPlist
        with _maybe_open(pathOrFile, 'rb') as fp:
      File "c:\program files (x86)\python38-32\lib\contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "c:\program files (x86)\python38-32\lib\plistlib.py", line 82, in _maybe_open
        with open(pathOrFile, mode) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
PS C:\Windows\system32>

###ja tentei de tudo mas não consegui nada ate agora
Alguem ajuda ai por favor

**Comment by plamut** [comment]
@anderoot It seems that you are trying to install the `pyttsx3` library? I'm afraid this is not the right place to ask for support, please ask in the [library's repository](https://github.com/nateshmbhat/pyttsx3).

**Comment by mohammadtaleb** [comment]
ERROR: Command errored out with exit status 1: 'c:\python\scripts\python.exe' 'c:\python\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users
\LUTOSC~1\AppData\Local\Temp\tmp6pb09ok6' Check the logs for full command output.

> **What Solution please**

**Comment by plamut** [comment]
@mohammadtaleb Which package are you trying to install?

Is it `google-cloud-texttospeech` or `pyttsx3` like the original poster? The latter is a different package not maintained by Google, thus its best to ask that library's maintainers as noted above.

On the other hand, if it's `google-cloud-texttospeech` causing the problems, I suggest opening the issue in the [respective repository](https://github.com/googleapis/python-texttospeech) (this `google-cloud-python` is the old monolithic repository which is not active anymore, thus the library maintainers might miss the questions posted here).

**Comment by mohammadtaleb** [comment]
I would install library numpy

**Comment by plamut** [comment]
@mohammadtaleb I see, thanks. In that case it would probably be best to ask `numpy` maintainers in the library [repository](https://github.com/numpy/numpy), as `numpy` is not developed and maintained by Google.

**Comment by hen1xx** [comment]
C:\Users\HP>pip install pyinstaller --no-cache-dir
Collecting pyinstaller
  Downloading pyinstaller-4.0.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB 819 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: setuptools in c:\python\lib\site-packages (from pyinstaller) (49.6.0)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in c:\python\lib\site-packages (from pyinstaller) (2020.7)
Requirement already satisfied: pywin32-ctypes>=0.2.0; sys_platform == "win32" in c:\python\lib\site-packages (from pyinstaller) (0.2.0)
Requirement already satisfied: pefile>=2017.8.1; sys_platform == "win32" in c:\python\lib\site-packages (from pyinstaller) (2019.4.18)
Requirement already satisfied: altgraph in c:\python\lib\site-packages (from pyinstaller) (0.17)
Requirement already satisfied: future in c:\python\lib\site-packages (from pefile>=2017.8.1; sys_platform == "win32"->pyinstaller) (0.18.2)
Building wheels for collected packages: pyinstaller
  Building wheel for pyinstaller (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python\python.exe' 'c:\python\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\HP\AppData\Local\Temp\tmpryskd1jw'
       cwd: C:\Users\HP\AppData\Local\Temp\pip-install-0879jtzr\pyinstaller
  Complete output (65 lines):
  running bdist_wheel
  running build
  running build_bootloader
  running build_py
  creating build
  creating build\lib
  creating build\lib\PyInstaller
  copying PyInstaller\compat.py -> build\lib\PyInstaller
  copying PyInstaller\config.py -> build\lib\PyInstaller
  copying PyInstaller\configure.py -> build\lib\PyInstaller
  copying PyInstaller\exceptions.py -> build\lib\PyInstaller
  copying PyInstaller\log.py -> build\lib\PyInstaller
  copying PyInstaller\__init__.py -> build\lib\PyInstaller
  copying PyInstaller\__main__.py -> build\lib\PyInstaller
  running egg_info
  writing pyinstaller.egg-info\PKG-INFO
  writing dependency_links to pyinstaller.egg-info\dependency_links.txt
  writing entry points to pyinstaller.egg-info\entry_points.txt
  writing requirements to pyinstaller.egg-info\requires.txt
  writing top-level names to pyinstaller.egg-info\top_level.txt
  reading manifest file 'pyinstaller.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'pyinstaller-gui.py'
  no previously-included directories found matching 'bootloader\build'
  no previously-included directories found matching 'bootloader\.waf-*'
  no previously-included directories found matching 'bootloader\.waf3-*'
  no previously-included directories found matching 'bootloader\waf-*'
  no previously-included directories found matching 'bootloader\waf3-*'
  no previously-included directories found matching 'bootloader\_sdks'
  no previously-included directories found matching 'bootloader\.vagrant'
  warning: no previously-included files found matching 'bootloader\.lock-waf*'
  no previously-included directories found matching 'doc\source'
  no previously-included directories found matching 'doc\_build'
  warning: no previously-included files matching '*.tmp' found under directory 'doc'
  warning: no files found matching 'news\_template.rst'
  no previously-included directories found matching 'news'
  no previously-included directories found matching 'old'
  no previously-included directories found matching 'scripts'
  no previously-included directories found matching 'tests\scripts'
  no previously-included directories found matching '.github'
  warning: no previously-included files found matching '.*'
  warning: no previously-included files found matching '*.yml'
  warning: no previously-included files found matching '*~'
  warning: no previously-included files found matching '.directory'
  writing manifest file 'pyinstaller.egg-info\SOURCES.txt'
  creating build\lib\PyInstaller\archive
  copying PyInstaller\archive\__init__.py -> build\lib\PyInstaller\archive
  copying PyInstaller\archive\pyz_crypto.py -> build\lib\PyInstaller\archive
  copying PyInstaller\archive\readers.py -> build\lib\PyInstaller\archive
  copying PyInstaller\archive\writers.py -> build\lib\PyInstaller\archive
  creating build\lib\PyInstaller\bootloader
  creating build\lib\PyInstaller\bootloader\Darwin-64bit
  copying PyInstaller\bootloader\Darwin-64bit\run -> build\lib\PyInstaller\bootloader\Darwin-64bit
  copying PyInstaller\bootloader\Darwin-64bit\run_d -> build\lib\PyInstaller\bootloader\Darwin-64bit
  copying PyInstaller\bootloader\Darwin-64bit\runw -> build\lib\PyInstaller\bootloader\Darwin-64bit
  copying PyInstaller\bootloader\Darwin-64bit\runw_d -> build\lib\PyInstaller\bootloader\Darwin-64bit
  creating build\lib\PyInstaller\bootloader\Linux-32bit
  copying PyInstaller\bootloader\Linux-32bit\run -> build\lib\PyInstaller\bootloader\Linux-32bit
  copying PyInstaller\bootloader\Linux-32bit\run_d -> build\lib\PyInstaller\bootloader\Linux-32bit
  creating build\lib\PyInstaller\bootloader\Linux-64bit
  copying PyInstaller\bootloader\Linux-64bit\run -> build\lib\PyInstaller\bootloader\Linux-64bit
  copying PyInstaller\bootloader\Linux-64bit\run_d -> build\lib\PyInstaller\bootloader\Linux-64bit
  creating build\lib\PyInstaller\bootloader\Windows-32bit
  copying PyInstaller\bootloader\Windows-32bit\run.exe -> build\lib\PyInstaller\bootloader\Windows-32bit
  error: could not open 'PyInstaller\bootloader\Windows-32bit\run.exe': Invalid argument
  ----------------------------------------
  ERROR: Failed building wheel for pyinstaller
Failed to build pyinstaller
ERROR: Could not build wheels for pyinstaller which use PEP 517 and cannot be installed directly

**### Как решить данную проблему?Уже переустанавливал python,и все способы перепробывал**
