### ISSUE TITLE
Collection Counter for Firestore Angular

### ISSUE THREAD

**Issue by PragadeeshwaranPasupathi** [googleapis/google-cloud-python#10408]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

**Comment by plamut** [comment]
@PragadeeshwaranPasupathi It is not clear what the issue / feature request is about, unfortunately. Could you please update the description?

Is this related to the `firestore` client library?

**Comment by busunkim96** [comment]
Closing as it is unclear which API is being targeted. Feel free to open a new issue at https://github.com/googleapis/python-firestore/issues if this is firestore related.

Thanks!
