### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

### ISSUE THREAD

**Issue by Saurav-KT** [googleapis/google-cloud-python#10419]
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
import pymssql
Traceback (most recent call last):
File "src\pymssql.pyx", line 636, in pymssql.connect
File "src_mssql.pyx", line 1957, in _mssql.connect
File "src_mssql.pyx", line 676, in _mssql.MSSQLConnection.init
File "src_mssql.pyx", line 1683, in _mssql.maybe_raise_MSSQLDatabaseException
_mssql.MSSQLDatabaseException: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (xxx:1433)\nNet-Lib error during Unknown
I'm getting this error on windows machine Please suggest how to resolve.Code Mentioned below for reference.
pip install pymssql

import pymssql

conn = pymssql.connect(server='xxxxx', user='abc', password='abc', database='test')
cursor = conn.cursor()
cursor.execute('SELECT * FROM tbl_Test')
row = cursor.fetchone()
while row:
    print(row[0]) + " " + str(row[1]) + " " + str(row[2])

**Comment by plamut** [comment]
@Saurav-KT It is not clear which Google cloud library the warning relates to.

The [pymssql package](https://pypi.org/project/pymssql/) used in the example is not maintained by Google, thus it would be best to ask the maintainers of that package.
