### ISSUE TITLE
Cloud Build library status

### ISSUE THREAD

**Issue by jwp23** [googleapis/google-cloud-python#10439]
The Cloud Build library status is listed as Alpha in this repo's README. The version listed in the Cloud Build LIbrary's documentation is GA and the latest release version is 1.0.0. Which is correct?

**Comment by busunkim96** [comment]
@jwp23 Apologies for the discrepancy. You can treat the Development Status listed in PyPI (and the setup.py) as the source of truth.

https://pypi.org/project/google-cloud-build/

google-cloud-build is GA.

**Comment by matthewayne** [comment]
@busunkim96 Can this be closed now? Looks like Cloud build is now labeled as GA in this repo
