### ISSUE TITLE
Secrets: Line-Feed is Included When Loading From File

### ISSUE THREAD

**Issue by jalseth** [googleapis/google-cloud-python#10436]
When adding a secret version from a file (EG: `gcloud secrets versions add MY_SECRET --data-file=my_secret.txt` if the file has a line-feed (LF) at the end of it, that is included in the secret which can cause issues when an application attempts to use it. 

Many text editors automatically insert a LF at the end of the file if one doesn't exist so that when `cat` or similar is run, the file displays correctly in a terminal. I cannot think of a scenario when a secret should end in a LF (or CRLF on Windows), so I think the `gcloud` utility should remove these before updating the secret.

**Comment by danoscarmike** [comment]
@jalseth thanks for reaching out. This seems like general product feedback / feature request -- is that right? Or are you seeing this behavior specifically using the `gcloud` CLI or Python client library?

**Comment by jalseth** [comment]
I am seeing this behavior in the `gcloud` utility and had it cause an issue in one of my environments this week. I saved an API token using my normal text editor, which added the LF without my knowledge (as noted, many text editors do this). I then had to spend time troubleshooting why my code was working locally with the secret loaded from environment variables, but not after I ran it in GCP where it pulled the secret from the secrets manager API, even though it was the same container and (from what I thought) was the same configuration.

While there isn't technically anything wrong with including the line feed byte when adding the secret version (it exists in the file on disk), I think it would make sense to remove it before adding the secret version as I cannot think of a scenario where a LF would intentionally be included at the end of a secret.

**Comment by danoscarmike** [comment]
Thanks for the additional information. I think the best place to get help with this will be the public issue trackers for gcloud, or for the Secret Manager product itself. This is a legacy repo for the Python server-side client libraries. Aside, you can find the Secret Manager Python client library, [here](https://github.com/googleapis/python-secret-manager).

You can find links to browse currently open issues in the public issue trackers and to create new issues, [here](https://cloud.google.com/support/docs/issue-trackers#trackers-list). Search for 'Cloud SDK'.

If you do file a new issue please post the link here and I'll follow up internally to see that it gets some attention.

**Comment by jalseth** [comment]
Thanks for the quick responses! Here's the link: https://issuetracker.google.com/issues/157867791

I'll close this and use the other issue for tracking.
