### ISSUE TITLE
Add Python 3.9 tests

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-cloud-python#10442]
Choose a few libraries (mix of GAPIC, handwrittens) to add 3.9 tests before the 3.9.0 release is made ([release schedule](https://www.python.org/dev/peps/pep-0596/#id4)).

Steps:

* Add 3.9 to the [docker image](https://github.com/googleapis/testing-infra-docker/blob/4040f69470a80613a3e342031b78cca535d30a23/python/googleapis/python-multi/Dockerfile).
* Add 3.9 unit/system tests to a handful of libraries. The extra version can be added via templates ([see example](https://github.com/googleapis/python-texttospeech/blob/b68df446daa7983cad1d31553ece6df569c932b2/synth.py#L43-L48)).

CC @plamut

**Comment by meredithslota** [comment]
We are way past 3.9 — 3.11 was added recently. Closing as "fixed" and also "obsolete". :) https://github.com/googleapis/google-cloud-python/pull/10812
