### ISSUE TITLE
CloudSQL Admin Support

### ISSUE THREAD

**Issue by arvindwill** [googleapis/google-cloud-python#10451]
Is the MYSQL Admin APIs support already in roadmap? 
https://cloud.google.com/sql/docs/mysql/admin-api/libraries

**Comment by busunkim96** [comment]
Given that that API only has a REST interface at the moment I don't think so. @kurtisvg?

**Comment by kurtisvg** [comment]
Unfortunately v1beta4 only provides a REST interface, but you can use the [discovery-based clients](https://cloud.google.com/sql/docs/mysql/admin-api/libraries#python).

**Comment by sciurus** [comment]
Why does the fact that it only has a REST interface mean a better client won't be developed for it?

**Comment by busunkim96** [comment]
@sciurus The generator currently is only able to produce the more modern libraries for for gRPC APIs. That said, that may change in the future.
