### ISSUE TITLE
Enable master branch protection

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-python#10459]
This repository does not seem to have master branch
          protection enabled, at least in the way I'm expecting.
          I was hoping for:

          - master branch protection
          - requiring at least one code reviewer
          - requiring at least two status checks
          - enforcing rules for admins

          Please turn it on!

**Comment by caltrops6490** [comment]
Hey! Thanks

**Comment by busunkim96** [comment]
@JustinBeckwith This is a README-only library at this point. Should I just choose conventional commits and cla as the two required status checks? 😄

**Comment by JustinBeckwith** [comment]
Heh, sure!

**Comment by busunkim96** [comment]
It looks like I don't have admin on this repo 😆 . Could you wave the magic wand @JustinBeckwith?

**Comment by JustinBeckwith** [comment]
That's... weird.  I added `yoshi-python-admins` back with admin access.  Try now?

**Comment by busunkim96** [comment]
It works now! I've updated the master branch rules to meet the requires.
