### ISSUE TITLE
Use existing OAuth2 access token

### ISSUE THREAD

**Issue by stephencroberts** [googleapis/google-cloud-python#10481]
## Feature Request

When running jobs in CI/CD with only a Google OAuth2 access token available, I would love the convenience of using `gcloud` and `gsutil` with the existing token. The constraints are:

- cannot use Application Default Credentials
- cannot generate service account keys
- must use only OAuth2 Google access token that is already generated in the environment

## Proposed Solution

Allow `gcloud` to be configured with an existing access token, preferably with an environment variable, similar to how Terraform does it: https://www.terraform.io/docs/providers/google/guides/provider_reference.html#access_token-1.

## Alternative Solutions/Workarounds

The current workaround is to use simple `curl` with a bearer token. 

I have also considered inserting the token into the gcloud sqlite database -- not ideal!

If anyone has already solved this, please share!

**Comment by busunkim96** [comment]
Hi @stephencroberts,

This issue tracker is the for Python client libraries (google-cloud-*). It looks like this is a feature request for gcloud. Would you mind filing an issue [here](https://issuetracker.google.com/savedsearches/559662)? Thanks!

**Comment by stephencroberts** [comment]
@busunkim96 Thank you! I could not figure out where the right place was.
