### ISSUE TITLE
python hooks problem when I try to download it in windowspowershell:

### ISSUE THREAD

**Issue by shayan1111** [googleapis/google-cloud-python#10500]
I want to download python hooks. but every damn time I write: "pip install hooks" it gives me this error:

```
> ERROR: Command errored out with exit status 1:
>      command: 'c:\users\shayan\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Shayan\\AppData\\Local\\Temp\\pip-install-ox3hcw4_\\hooks\\setup.py'"'"'; __file__='"'"'C:\\Users\\Shayan\\AppData\\Local\\Temp\\pip-install-ox3hcw4_\\hooks\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Shayan\AppData\Local\Temp\pip-pip-egg-info-d33jq8zc'
>          cwd: C:\Users\Shayan\AppData\Local\Temp\pip-install-ox3hcw4_\hooks\
>     Complete output (5 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\Shayan\AppData\Local\Temp\pip-install-ox3hcw4_\hooks\setup.py", line 3, in <module>
>         install_requires = open('requirements.txt').readlines()
>     FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> 
```

can anybody help me or give me any advise?
I want to continue to programming:(

**Comment by busunkim96** [comment]
Hi @shayan1111,

What package are you installing?

**Comment by shayan1111** [comment]
python hooks. I want it because I want to continue programming. I want to download it in windows powershell. the site 
(www.PYPI.org) says that I have to write (pip install hooks) but every time I do that it doesn't work. either the code has changed, or there's someting else instead. can anyone help me please? I will also help if you have a problem.

**Comment by shayan1111** [comment]
@busunkim96, Can you respond to my question please?

**Comment by software-dov** [comment]
Please file an issue on the hooks repository.
https://github.com/kevinjqiu/githooks

That project looks abandoned, so I don't think it's likely the problem will be resolved.

**Comment by shayan1111** [comment]
Hello **@software-dov**, nice to meet you. Thanks for the file but I have a few questions:
1. What should I do with the file?(please tell me the instructions step by step)
2. As you said it, it's abandoned. so if it doesn't work, If it doesn't solve my problem, what should I do or at what site do you suggest that I have to use to download hooks?

**Comment by busunkim96** [comment]
Hi @shayan1111,

This issue tracker is for the `google-cloud-*` python libraries. It doesn't look like your issue is related to those libraries.

**Comment by shayan1111** [comment]
hello @busunkim96,
what do you mean by my issue tracker is for the google-cloud? Can you explain that to me please?

**Comment by busunkim96** [comment]
The libraries listed [here](https://cloud.google.com/python/docs/reference) are the Python libraries for Google Cloud.

**Comment by shayan1111** [comment]
hello @busunkim96. I'm sorry for that. It's my first time asking questions almost online. So forgive me. Please help me solve my problem. If you scroll up, you'll see my problem. And I need you're help to solve my problem. Can you do that for me please?

**Comment by software-dov** [comment]
The repo for hooks looks like it's been abandoned, so the package may just be broken and not usable.
If you're new to programming, take a look at https://wiki.python.org/moin/BeginnersGuide . It describes a few editors and development environments that may help you get started. [PyCharm](https://www.jetbrains.com/pycharm/) seems to be very popular with some people. [Thonny](https://thonny.org/) looks like it may be good for beginners as well.

Out of curiosity, why do you want to install the hooks package? Is there a tutorial somewhere that recommends it?
