### ISSUE TITLE
Automate constraints file updates

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-cloud-python#10521]
Constraints files are being added to library repositories to test lower bounds declared in `setup.py`. These files currently have to be added and maintained manually.

Explore automating this in some fashion to reduce the manual toil.

**Comment by parthea** [comment]
Closing as obsolete. These constraints files are part of the generator code: https://github.com/googleapis/gapic-generator-python/tree/main/gapic/templates/testing
