### ISSUE TITLE
Unable to add multiple port forwarding rules

### ISSUE THREAD

**Issue by KShivendu** [googleapis/google-cloud-python#10548]
Hi there,
I was trying to port forward to my GCP VM instances using the method described in https://cloud.google.com/solutions/connecting-securely#port-forwarding-over-ssh. The first example( single port forwarding ) worked seamlessly but the second example didn't work ( none of the ports were forwarded ). Also, I noticed that, since the LOCAL_PORT field is used twice, whenever I change one of the values, the other value also changes. Same goes with REMOTE_PORT field. 

Cheers !

**Comment by parthea** [comment]
Hi @KShivendu,

This issue tracker is for google-cloud-* python libraries. It looks like you are having problems SSHing into a Google Compute Engine instance. Please see https://cloud.google.com/compute/docs/troubleshooting/troubleshooting-ssh for troubleshooting help.

For additional support, reach out to https://cloud.google.com/support if you have a support contract with Google. If you do not have a support contract, please open an issue on Compute Engine's public issue tracker: https://issuetracker.google.com/savedsearches/559755
