### ISSUE TITLE
AttributeError: module 'google.cloud' has no attribute 'firestore'This repository is geared toward the clients themselves, and generally doesn't discuss Beam.

### ISSUE THREAD

**Issue by KALYJADH** [googleapis/google-cloud-python#10546]
I am getting above issue while running dataflow pipeline. I also refer this one but giving same issue while running dataflow pipeline

**Comment by busunkim96** [comment]
Hi,

It's not clear to me what the issue is from the information provided. Could you provide a code snippet and the environment the code is being run in?

**Comment by parthea** [comment]
Hi @KALYJADH,

I'm going to close this issue due to inactivity but please feel free to re-open it with additional information.
