### ISSUE TITLE
google-cloud-* libraries should allow `google-api-core`, `google-cloud-core`, `google-auth` >1, <3

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-cloud-python#10565]
For all `google-cloud-*` libraries that require `python >=3.6`, expand `google-api-core`, `google-cloud-core` and `google-auth` pins to `>1.x.x, <3.0.0dev`. 

Leave a comment in the setup.py for these libraries asking library maintainers to not require >=2.x.x versions until https://github.com/googleapis/google-cloud-python/issues/10566 has been closed. 

Release `google-cloud-*` libraries with expanded pins.

```py
dependencies = [
    # NOTE: Maintainers, please do not require google-api-core>=2.x.x
    # Until this issue is resolved:  https://github.com/googleapis/google-cloud-python/issues/10566
    "google-api-core[grpc] >= 1.26.0, <3.0.0dev",
    "proto-plus >= 1.15.0",
    "packaging >= 14.3",
]
```

This issue can be closed when all google-cloud-* libraries have latest releases with <3.0.0dev pins.

**Comment by tseaver** [comment]
Possibly usefulGithub searches  for eyeball-verification of the pins:

- [`api-core`](https://github.com/search?l=&q=org%3Agoogleapis+google-api-core+filename%3Asetup.py&ref=advsearch&type=Code)
- [`cloud-core`](https://github.com/search?l=&q=org%3Agoogleapis+google-cloud-core+filename%3Asetup.py&ref=advsearch&type=Code)
- [`auth`](https://github.com/search?l=&q=org%3Agoogleapis+google-auth+filename%3Asetup.py&ref=advsearch&type=Code)
- [`resumable-media`](https://github.com/search?l=&q=org%3Agoogleapis+google-resumable-media+filename%3Asetup.py&ref=advsearch&type=Code)

**Comment by busunkim96** [comment]
Thanks Tres!

I looked through repos (using the list in the README)  and it looks like expanded pins have been released almost everywhere. These were the stragglers I found:

- Logging (release pending in https://github.com/googleapis/python-logging/pull/337)
- Spanner (release pending in https://github.com/googleapis/python-spanner/pull/398)
- BQ Logging Protos (change pending in https://github.com/googleapis/python-bigquery-logging/pull/22)
- Composer (change pending in https://github.com/googleapis/python-orchestration-airflow/pull/9)
- IAM Logging Protos (change pending in https://github.com/googleapis/python-iam-logging/pull/20)

**Comment by tseaver** [comment]
I've been working today to get the Spanner release done -- it has been blocked by a breaking OpenTelemetry change.  Looks like you merged the Logging one:  I will review the other three.

**Comment by tseaver** [comment]
Uh, oh, the [Spanner 3.7.0 release PR](https://github.com/googleapis/python-spanner/pull/398) is held up: @larkee marked it as `do not release` last night.
