### ISSUE TITLE
google-cloud-* libraries **should not** require `google-api-core`, `google-auth` or `google-cloud-core` `>=2.x.x`

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-cloud-python#10566]
While this issue is open, dependents of `google-api-core`, `google-cloud-core`. and `google-auth` should preserve `>1, <3` pins on these  packages.

This is to prevent diamond dependency conflicts for users using multiple libraries. A more detailed rationale is provided in [this document](https://docs.google.com/document/d/1euAvUsia_4zf98lNvpwA3K0o2b4y5Xr9xAkyzCnIMzQ/edit#).

If you believe you need to begin requiring `>=2.x.x` versions of these libraries, please comment here or reach out before releasing your library. 

This issue is currently expected to be closed 3 months (90 days) after all `google-*` packages have been released with expanded pins (see #10565), however the specific amount of time is under discussion.

**Comment by plamut** [comment]
@busunkim96 In BigQuery, we would like to make a few extras required dependencies ([PR](https://github.com/googleapis/python-bigquery/pull/776)), and we will do it as a [major version bump](https://github.com/googleapis/python-bigquery/pull/776#discussion_r672629358).

Being a major bump, would pinning the dependencies to `>=2.x.x` be justifiable?

I'm trying to find the best way to both honour this PR and not having to keep the non-trivial [refactoring PR](https://github.com/googleapis/python-bigquery/pull/776) open for too long.

**Comment by parthea** [comment]
I need to use `google-api-core>=2.1.0` for python-compute in this PR https://github.com/googleapis/python-compute/pull/147

The specific feature I need is [PR 275 here](https://github.com/googleapis/python-api-core/pull/275) which is available in [2.1.0](https://github.com/googleapis/python-api-core/releases/tag/v2.1.0).

**Comment by tswast** [comment]
Some packages are still stuck on `google-api-core` 1.x

For example, NBD: https://github.com/googleapis/python-ndb/blob/f113dbd6332ebc1dd1ebfed3b90e19d9101b785b/setup.py#L28

It requires `google-cloud-datastore` 1.x, which does not have a release that allows `google-api-core` 2.x. https://github.com/googleapis/python-datastore/blob/v1.15.3/setup.py#L32

**Comment by busunkim96** [comment]
As of April 7, 2022, the latest release of all google-cloud-* libraries are compatible with google-api-core, google-cloud-core, google-auth 2.x.x.

In addition, patch releases have been made to libraries with previous major releases if there were breaking changes between that release and the current major version.

If you experience dependency conflicts (older google-cloud-* libraries incompatible with a newer gooogle-cloud-* library due to `google-api-core` or `google-auth`, please open an issue on the library repository for help.

**Comment by snarfed** [comment]
Great news, congrats, and thank you! I know how tricky (and thankless) wrangling this many interdependent packages can be.

I don't know if you meant to include `google-cloud-ndb` (and `google-cloud-datastore`) here, but sadly `google-cloud-ndb` is still stuck on the 1.x trees of all of these libraries so that it can maintain support for Python 2.7 and classic GAE. More background in https://github.com/googleapis/python-ndb/issues/733#issuecomment-946069353 and https://github.com/snarfed/bridgy/issues/1115.

https://github.com/googleapis/python-ndb/blob/06a7392228a794a26e8e50aca87c5af89da88e08/setup.py#L28=

As an ndb user, I'd love to find a way onto the 2.x trees, but I don't know what that would be yet.

**Comment by busunkim96** [comment]
Hey @snarfed,

Unfortunately I don't know of plans to make `google-cloud-ndb` compatible with `google-cloud-datastore` 2.x. I've left a note with the folks who own that library to see if they have additional insight beyond the issue you linked.

I see one of your concerns was that you were no longer able to update past the 1.x versions of `google-auth`, `google-api-core`, `google-cloud-core`. `google-cloud-datastore==1.15.4` allows newer versions of those libraries, so you should be able to update pins on those libraries in a Python 3 environment.

This `requirements.txt` with latest versions of `google-auth`, `google-api-core` is now resolvable:
```
google-cloud-tasks==2.8.1
google-auth==2.6.3
google-api-core==2.7.1
google-cloud-core==2.2.3
google-cloud-logging==3.0.0
google-cloud-ndb==1.11.1
google-cloud-datastore==1.15.4

```

**Comment by snarfed** [comment]
Oh wow, that's great news. Thank you @busunkim96! Getting onto 2.x of the the core libs is a great step, definitely appreciated.

**Comment by busunkim96** [comment]
@snarfed The current owners of the Datastore libraries team let me know that NDB is not currently being developed, but things may change in the future.

If you see issues or have other inquiries about development plans, please open them on https://github.com/googleapis/python-datastore.
