### ISSUE TITLE
Switch all googleapis python repos to use a default branch of main

### ISSUE THREAD

**Issue by parthea** [googleapis/google-cloud-python#10579]
Please follow these steps to change the default branch from master to main:

1. Before you start the migration add your Github user to the end of the list item to avoid overlapping efforts.
2. In the majority of python repositories, @googleapis/yoshi-python is listed as the code owner in .github/CODEOWNERS. If there are additional code owners listed, please reach out to the team listed to notify them about the effort.
3. In the “Settings” section for the Github repository, rename the default branch from master to main. If you don’t see the settings section, you will need to reach out to an admin of the repository to complete this step. Once you’re in the settings section, look for the “Default branch” section under the branches tab.  For example, for python-datastream, the link to the branches tab is  https://github.com/googleapis/python-datastream/settings/branches 
4. Search the github repo for the term `master` in the repository. Open a PR in the repo to replace the term `master` with `main`. We have automation which will revert changes made to templated files so we also need to add replacements in `owlbot.py` to replace `master` with `main` similar to [this PR](https://github.com/googleapis/python-apigee-connect/pull/33). See [this bash script](https://github.com/googleapis/google-cloud-python/files/7022747/migratemain.zip) that I used to create the branch for the linked PR. Note: Once [this synthtool PR is merged](https://github.com/googleapis/synthtool/pull/1188) and the synthtool templates have propagated to the repo via owlbot, we can remove the replacements in owlbot.py added in this step.
5. Make sure that replacements are not reverted by owlbot
6. Notify a Googler to complete the remaining steps at go/python-main-branch-migration.
7. Check the box below when the repo has been successfully migrated and verified that the continuous/nightly builds pass after the migration.

- [x] - [google-api-python-client](https://github.com/googleapis/google-api-python-client) @parthea https://github.com/googleapis/google-api-python-client/pull/1498
- [x] - [google-auth-library-python](https://github.com/googleapis/google-auth-library-python) @parthea https://github.com/googleapis/google-auth-library-python/pull/849
- [x] - [google-auth-library-python-httplib2](https://github.com/googleapis/google-auth-library-python-httplib2) @parthea https://github.com/googleapis/google-auth-library-python-httplib2/pull/42
- [x] - [google-auth-library-python-oauthlib](https://github.com/googleapis/google-auth-library-python-oauthlib) @parthea https://github.com/googleapis/google-auth-library-python-oauthlib/pull/148
- [x] - [google-cloudevents-python](https://github.com/googleapis/google-cloudevents-python) @parthea https://github.com/googleapis/google-cloudevents-python/pull/71
- [x] - [google-resumable-media-python](https://github.com/googleapis/google-resumable-media-python) @parthea https://github.com/googleapis/google-resumable-media-python/pull/260
- [x] - [python-access-approval](https://github.com/googleapis/python-access-approval) @parthea https://github.com/googleapis/python-access-approval/pull/108
- [x] - [python-access-context-manager](https://github.com/googleapis/python-access-context-manager) @dandhlee https://github.com/googleapis/python-access-context-manager/pull/76
- [x] - [python-aiplatform](https://github.com/googleapis/python-aiplatform) @parthea https://github.com/googleapis/python-aiplatform/pull/661
- [x] - [python-analytics-admin](https://github.com/googleapis/python-analytics-admin) @parthea https://github.com/googleapis/python-analytics-admin/pull/122
- [x] - [python-analytics-data](https://github.com/googleapis/python-analytics-data) @parthea https://github.com/googleapis/python-analytics-data/pull/124
- [x] - [python-api-common-protos](https://github.com/googleapis/python-api-common-protos) @parthea https://github.com/googleapis/python-api-common-protos/pull/57
- [x] - [python-api-core](https://github.com/googleapis/python-api-core) @tseaver https://github.com/googleapis/python-api-core/pull/264
- [x] - [python-api-gateway](https://github.com/googleapis/python-api-gateway) @parthea https://github.com/googleapis/python-api-gateway/pull/59
- [x] - [python-apigee-connect](https://github.com/googleapis/python-apigee-connect) @parthea  https://github.com/googleapis/python-apigee-connect/pull/33
- [x] - [python-appengine-admin](https://github.com/googleapis/python-appengine-admin) @parthea https://github.com/googleapis/python-appengine-admin/pull/60
- [x] - [python-appengine-logging](https://github.com/googleapis/python-appengine-logging) @parthea https://github.com/googleapis/python-appengine-logging/pull/29
- [x]  - [python-area120-tables](https://github.com/googleapis/python-area120-tables) @parthea https://github.com/googleapis/python-area120-tables/pull/81
- [x] - [python-artifact-registry](https://github.com/googleapis/python-artifact-registry) @parthea https://github.com/googleapis/python-artifact-registry/pull/67
- [x] - [python-asset](https://github.com/googleapis/python-asset) @parthea https://github.com/googleapis/python-asset/pull/274
- [x] - [python-assured-workloads](https://github.com/googleapis/python-assured-workloads) @parthea https://github.com/googleapis/python-assured-workloads/pull/75
- [x] - [python-audit-log](https://github.com/googleapis/python-audit-log) @parthea https://github.com/googleapis/python-audit-log/pull/28
- [x] - [python-automl](https://github.com/googleapis/python-automl) @parthea https://github.com/googleapis/python-automl/pull/234
- [x] - [python-bigquery](https://github.com/googleapis/python-bigquery)  @plamut https://github.com/googleapis/python-bigquery/pull/910
- [x] - [python-bigquery-connection](https://github.com/googleapis/python-bigquery-connection)  @plamut https://github.com/googleapis/python-bigquery-connection/pull/111
- [x] - [python-bigquery-datatransfer](https://github.com/googleapis/python-bigquery-datatransfer)  @plamut https://github.com/googleapis/python-bigquery-datatransfer/pull/206
- [x] - [python-bigquery-logging](https://github.com/googleapis/python-bigquery-logging)  @plamut https://github.com/googleapis/python-bigquery-logging/pull/28
- [x] - [python-bigquery-reservation](https://github.com/googleapis/python-bigquery-reservation)  @plamut https://github.com/googleapis/python-bigquery-reservation/pull/153
- [x] - [python-bigquery-sqlalchemy](https://github.com/googleapis/python-bigquery-sqlalchemy) @jimfulton https://github.com/googleapis/python-bigquery-sqlalchemy/pull/301
- [x] - [python-bigquery-storage](https://github.com/googleapis/python-bigquery-storage)  @plamut https://github.com/googleapis/python-bigquery-storage/pull/283
- [x] - [python-bigtable](https://github.com/googleapis/python-bigtable) @tseaver https://github.com/googleapis/python-bigtable/pull/411
- [x] - [python-billing](https://github.com/googleapis/python-billing) @parthea https://github.com/googleapis/python-billing/pull/107
- [x] - [python-billingbudgets](https://github.com/googleapis/python-billingbudgets) @parthea https://github.com/googleapis/python-billingbudgets/pull/129
- [x] - [python-binary-authorization](https://github.com/googleapis/python-binary-authorization) @parthea https://github.com/googleapis/python-binary-authorization/pull/66
- [x] - [python-channel](https://github.com/googleapis/python-channel) @parthea https://github.com/googleapis/python-channel/pull/83
- [x] - [python-cloud-core](https://github.com/googleapis/python-cloud-core) @tseaver https://github.com/googleapis/python-cloud-core/pull/136
- [x] - [python-cloudbuild](https://github.com/googleapis/python-cloudbuild) @parthea https://github.com/googleapis/python-cloudbuild/pull/157
- [x] - [python-compute](https://github.com/googleapis/python-compute) @parthea https://github.com/googleapis/python-compute/pull/110
- [x] - [python-contact-center-insights](https://github.com/googleapis/python-contact-center-insights) @parthea https://github.com/googleapis/python-contact-center-insights/pull/31
- [x] - [python-container](https://github.com/googleapis/python-container) @parthea https://github.com/googleapis/python-container/pull/141
- [x] - [python-containeranalysis](https://github.com/googleapis/python-containeranalysis) @parthea https://github.com/googleapis/python-containeranalysis/pull/173
- [x] - [python-crc32c](https://github.com/googleapis/python-crc32c) @tseaver https://github.com/googleapis/python-crc32c/pull/80
- [x] - [python-data-fusion](https://github.com/googleapis/python-data-fusion) @dandhlee https://github.com/googleapis/python-data-fusion/pull/20
- [x] - [python-data-qna](https://github.com/googleapis/python-data-qna) @dandhlee https://github.com/googleapis/python-data-qna/pull/78
- [x] - [python-datacatalog](https://github.com/googleapis/python-datacatalog) @dandhlee https://github.com/googleapis/python-datacatalog/pull/211
- [x] - [python-datalabeling](https://github.com/googleapis/python-datalabeling) @dandhlee https://github.com/googleapis/python-datalabeling/pull/138
- [x] - [python-dataproc](https://github.com/googleapis/python-dataproc) @dandhlee https://github.com/googleapis/python-dataproc/pull/248
- [x] - [python-dataproc-metastore](https://github.com/googleapis/python-dataproc-metastore) @dandhlee https://github.com/googleapis/python-dataproc-metastore/pull/67 
- [x] - [python-datastore](https://github.com/googleapis/python-datastore) @dandhlee https://github.com/googleapis/python-datastore/pull/217 
- [x] - [python-datastream](https://github.com/googleapis/python-datastream) @parthea https://github.com/googleapis/python-datastream/pull/17
- [x] - [python-debugger-client](https://github.com/googleapis/python-debugger-client) @nicain https://github.com/googleapis/python-debugger-client/pull/23
- [x] - [python-dialogflow](https://github.com/googleapis/python-dialogflow) @dandhlee https://github.com/googleapis/python-dialogflow/pull/372
- [x] - [python-dialogflow-cx](https://github.com/googleapis/python-dialogflow-cx) @dandhlee https://github.com/googleapis/python-dialogflow-cx/pull/154
- [x] - [python-dlp](https://github.com/googleapis/python-dlp) @dandhlee https://github.com/googleapis/python-dlp/pull/239
- [x] - [python-dms](https://github.com/googleapis/python-dms) @dandhlee https://github.com/googleapis/python-dms/pull/34
- [x] - [python-dns](https://github.com/googleapis/python-dns) @dandhlee https://github.com/googleapis/python-dns/pull/76
- [x] - [python-documentai](https://github.com/googleapis/python-documentai) @dandhlee https://github.com/googleapis/python-documentai/pull/201
- [x] - [python-domains](https://github.com/googleapis/python-domains) @dandhlee https://github.com/googleapis/python-domains/pull/55
- [x] - [python-error-reporting](https://github.com/googleapis/python-error-reporting) @dandhlee https://github.com/googleapis/python-error-reporting/pull/165
- [x] - [python-essential-contacts](https://github.com/googleapis/python-essential-contacts) @dandhlee https://github.com/googleapis/python-essential-contacts/pull/34
- [x] - [python-firestore](https://github.com/googleapis/python-firestore) @dandhlee https://github.com/googleapis/python-firestore/pull/434
- [x] - [python-functions](https://github.com/googleapis/python-functions) @dandhlee https://github.com/googleapis/python-functions/pull/102
- [x] - [python-game-servers](https://github.com/googleapis/python-game-servers) @dandhlee https://github.com/googleapis/python-game-servers/pull/178
- [x] - [python-gke-connect-gateway](https://github.com/googleapis/python-gke-connect-gateway) @dandhlee https://github.com/googleapis/python-gke-connect-gateway/pull/26
- [x] - [python-gke-hub](https://github.com/googleapis/python-gke-hub) @dandhlee https://github.com/googleapis/python-gke-hub/pull/68
- [x] - [python-grafeas](https://github.com/googleapis/python-grafeas) @dandhlee https://github.com/googleapis/python-grafeas/pull/98
- [x] - [python-iam](https://github.com/googleapis/python-iam) @dandhlee https://github.com/googleapis/python-iam/pull/111
- [x] - [python-iam-logging](https://github.com/googleapis/python-iam-logging) @dandhlee https://github.com/googleapis/python-iam-logging/pull/26
- [x] - [python-iap](https://github.com/googleapis/python-iap) @dandhlee https://github.com/googleapis/python-iap/pull/19
- [x] - [python-iot](https://github.com/googleapis/python-iot) @dandhlee https://github.com/googleapis/python-iot/pull/175
- [x] - [python-kms](https://github.com/googleapis/python-kms) @parthea https://github.com/googleapis/python-kms/pull/166
- [x] - [python-language](https://github.com/googleapis/python-language) @leahecole  https://github.com/googleapis/python-language/pull/188
- [x] - [python-life-sciences](https://github.com/googleapis/python-life-sciences) (good first issue) @dandhlee https://github.com/googleapis/python-life-sciences/pull/32
- [x] - [python-logging](https://github.com/googleapis/python-logging) @dandhlee https://github.com/googleapis/python-logging/pull/385
- [x] - [python-managed-identities](https://github.com/googleapis/python-managed-identities) @dandhlee https://github.com/googleapis/python-managed-identities/pull/65
- [x] - [python-media-translation](https://github.com/googleapis/python-media-translation) @nicain https://github.com/googleapis/python-media-translation/pull/99
- [x] - [python-memcache](https://github.com/googleapis/python-memcache) @dandhlee https://github.com/googleapis/python-memcache/pull/97
- [x] - [python-monitoring](https://github.com/googleapis/python-monitoring) @nicain https://github.com/googleapis/python-monitoring/pull/206
- [x] - [python-monitoring-dashboards](https://github.com/googleapis/python-monitoring-dashboards) @dandhlee  https://github.com/googleapis/python-monitoring-dashboards/pull/107
- [x] - [python-ndb](https://github.com/googleapis/python-ndb) @dandhlee https://github.com/googleapis/python-ndb/pull/714
- [x] - [python-network-connectivity](https://github.com/googleapis/python-network-connectivity) @dandhlee https://github.com/googleapis/python-network-connectivity/pull/74
- [x] - [python-network-management](https://github.com/googleapis/python-network-management) (good first issue) @dandhlee https://github.com/googleapis/python-network-management/pull/25
- [x] - [python-network-security](https://github.com/googleapis/python-network-security) @parthea https://github.com/googleapis/python-network-security/pull/21
- [x] - [python-notebooks](https://github.com/googleapis/python-notebooks) @dandhlee https://github.com/googleapis/python-notebooks/pull/80
- [x] - [python-orchestration-airflow](https://github.com/googleapis/python-orchestration-airflow) (good first issue)  @leahecole https://github.com/googleapis/python-orchestration-airflow/pull/18
- [x] - [python-org-policy](https://github.com/googleapis/python-org-policy) @dandhlee https://github.com/googleapis/python-org-policy/pull/79
- [x] - [python-os-config](https://github.com/googleapis/python-os-config) @dandhlee https://github.com/googleapis/python-os-config/pull/113
- [x] - [python-oslogin](https://github.com/googleapis/python-oslogin) @dandhlee https://github.com/googleapis/python-oslogin/pull/111
- [x] - [python-phishingprotection](https://github.com/googleapis/python-phishingprotection) @dandhlee https://github.com/googleapis/python-phishingprotection/pull/110
- [x] - [python-policy-troubleshooter](https://github.com/googleapis/python-policy-troubleshooter) @dandhlee https://github.com/googleapis/python-policy-troubleshooter/pull/57
- [x] - [python-private-catalog](https://github.com/googleapis/python-private-catalog) @dandhlee https://github.com/googleapis/python-private-catalog/pull/35
- [x] - [python-pubsub](https://github.com/googleapis/python-pubsub)  @plamut https://github.com/googleapis/python-pubsub/pull/479
- [x] - [python-pubsublite](https://github.com/googleapis/python-pubsublite) @dandhlee https://github.com/googleapis/python-pubsublite/pull/226
- [x] - [python-recaptcha-enterprise](https://github.com/googleapis/python-recaptcha-enterprise)  @plamut https://github.com/googleapis/python-recaptcha-enterprise/pull/114
- [x] - [python-recommendations-ai](https://github.com/googleapis/python-recommendations-ai)  @plamut https://github.com/googleapis/python-recommendations-ai/pull/80
- [x] - [python-recommender](https://github.com/googleapis/python-recommender)  @plamut  https://github.com/googleapis/python-recommender/pull/122
- [x] - [python-redis](https://github.com/googleapis/python-redis)  @plamut  https://github.com/googleapis/python-redis/pull/110
- [x] - [python-resource-manager](https://github.com/googleapis/python-resource-manager)  @plamut  https://github.com/googleapis/python-resource-manager/pull/105
- [x] - [python-resource-settings](https://github.com/googleapis/python-resource-settings)  @plamut  https://github.com/googleapis/python-resource-settings/pull/35
- [x] - [python-retail](https://github.com/googleapis/python-retail)  @plamut https://github.com/googleapis/python-retail/pull/86
- [x] - [python-runtimeconfig](https://github.com/googleapis/python-runtimeconfig)  @plamut https://github.com/googleapis/python-runtimeconfig/pull/85
- [x] - [python-scheduler](https://github.com/googleapis/python-scheduler)  @plamut https://github.com/googleapis/python-scheduler/pull/126
- [x] - [python-secret-manager](https://github.com/googleapis/python-secret-manager)  @plamut https://github.com/googleapis/python-secret-manager/pull/187
- [x] - [python-security-private-ca](https://github.com/googleapis/python-security-private-ca)  @plamut https://github.com/googleapis/python-security-private-ca/pull/112
- [x] - [python-securitycenter](https://github.com/googleapis/python-securitycenter)  @plamut https://github.com/googleapis/python-securitycenter/pull/212
- [x] - [python-service-control](https://github.com/googleapis/python-service-control) @parthea 
- [x] - [python-service-directory](https://github.com/googleapis/python-service-directory) @dandhlee https://github.com/googleapis/python-service-directory/pull/110
- [x] - [python-service-management](https://github.com/googleapis/python-service-management) @dandhlee https://github.com/googleapis/python-service-management/pull/51
- [x] - [python-service-usage](https://github.com/googleapis/python-service-usage) @nicain https://github.com/googleapis/python-service-usage/pull/34
- [x] - [python-source-context](https://github.com/googleapis/python-source-context) @nicain https://github.com/googleapis/python-source-context/pull/17
- [x] - [python-spanner](https://github.com/googleapis/python-spanner) @dandhlee https://github.com/googleapis/python-spanner/pull/549
- [x] - [python-spanner-django](https://github.com/googleapis/python-spanner-django) @dandhlee https://github.com/googleapis/python-spanner-django/pull/706
- [x] - [python-speech](https://github.com/googleapis/python-speech) @dandhlee https://github.com/googleapis/python-speech/pull/242
- [x] - [python-storage](https://github.com/googleapis/python-storage) @dandhlee https://github.com/googleapis/python-storage/pull/563
- [x] - [python-storage-transfer](https://github.com/googleapis/python-storage-transfer) (good first issue) @dandhlee https://github.com/googleapis/python-storage-transfer/pull/13
- [x] - [python-talent](https://github.com/googleapis/python-talent) @dandhlee https://github.com/googleapis/python-talent/pull/154
- [x] - [python-tasks](https://github.com/googleapis/python-tasks) @dandhlee https://github.com/googleapis/python-tasks/pull/157
- [x] - [python-test-utils](https://github.com/googleapis/python-test-utils) @tseaver https://github.com/googleapis/python-test-utils/pull/52
- [x] - [python-texttospeech](https://github.com/googleapis/python-texttospeech) @dandhlee https://github.com/googleapis/python-texttospeech/pull/184
- [x] - [python-tpu](https://github.com/googleapis/python-tpu) (good first issue) @dandhlee https://github.com/googleapis/python-tpu/pull/36
- [x] - [python-trace](https://github.com/googleapis/python-trace) @dandhlee https://github.com/googleapis/python-trace/pull/126
- [x] - [python-translate](https://github.com/googleapis/python-translate) @dandhlee https://github.com/googleapis/python-translate/pull/240
- [x] - [python-video-transcoder](https://github.com/googleapis/python-video-transcoder)  @plamut  https://github.com/googleapis/python-video-transcoder/pull/88
- [x] - [python-videointelligence](https://github.com/googleapis/python-videointelligence)  @plamut  https://github.com/googleapis/python-videointelligence/pull/206
- [x] - [python-vision](https://github.com/googleapis/python-vision)  @plamut  https://github.com/googleapis/python-vision/pull/220
- [x] - [python-vpc-access](https://github.com/googleapis/python-vpc-access) @parthea 
- [x] - [python-webrisk](https://github.com/googleapis/python-webrisk)  @plamut  https://github.com/googleapis/python-webrisk/pull/118
- [x] - [python-websecurityscanner](https://github.com/googleapis/python-websecurityscanner)  @plamut  https://github.com/googleapis/python-websecurityscanner/pull/101
- [x] - [python-workflows](https://github.com/googleapis/python-workflows)  @plamut  https://github.com/googleapis/python-workflows/pull/89

**Comment by nicain** [comment]
@dandhlee @plamut FYI [this PR](https://github.com/googleapis/google-cloud-python/pull/10581) provides a one-liner to pull and run the migration script via cURL; the [main-migration](https://github.com/googleapis/google-cloud-python/tree/main-migration) branch within google-cloud-python holds the scripts, so if they need to be updated or modified, you will be able to access the most recent versions via cURL.

(for example, I just pushed a [PR](https://github.com/googleapis/google-cloud-python/pull/10582) that uses "chore:" instead of "docs:" for the commit message)

**Comment by plamut** [comment]
@nicain Thanks, that's useful.

One side note, the name of the remote is hardcoded and [assumed](https://github.com/googleapis/google-cloud-python/pull/10581/files#diff-1b94e3e305023886f6178043f33706c183d02923febc8442be1043478f575f10R8) to be `origin`, while I personally use `origin` for my own forks and refer to the original repo as `upstream`.

Something to keep in mind if anybody else uses a similar setup. Best to read the script source first, it's pretty short and straightforward anyway.

**Comment by dandhlee** [comment]
@tseaver we're not marking entries checked off until we've verified that the continuous tests run after the migration, I'll unmark the ones you've checked off for my PRs!

**Comment by tseaver** [comment]
Hmm, OK, sorry about that.  The continuous tests tend to run against the last release -- is that going to be an issue?

**Comment by dandhlee** [comment]
No worries, I'll edit the snippet up top to reflect that, it was only referenced in our internal doc iirc.

I think that's fine, as long as Kokoro runs against `main` and not `master` and there's no issues on those then it should be fine.

**Comment by tseaver** [comment]
@dandhlee, @parthea PR needing review: https://github.com/googleapis/python-bigtable/pull/411

**Comment by parthea** [comment]
All task are complete
