### ISSUE TITLE
Support for Cloud Run admin

### ISSUE THREAD

**Issue by yan-hic** [googleapis/google-cloud-python#10605]
We want to query the metadata server for Cloud Run (CR) services to get the current url, revision and other details for a given service. We use airflow but there is no provider for CR. 
There is no Python Client library either.

Workaround: 
1. use `gcloud` - want avoid installing it - or 
2. Google API Library. This is a big library to import for just a GET call, and there is very little documentation on how to interact with the CR service endpoint.

Others have struggled with this too: https://pretired.dazwilkin.com/posts/210316/

**Comment by danoscarmike** [comment]
@grayside for vis

**Comment by gabriel-milan** [comment]
+1 for this feature

**Comment by parthea** [comment]
Closing as obsolete. The package exists here: https://pypi.org/project/google-cloud-run/
