### ISSUE TITLE
Support for Deployment Manager

### ISSUE THREAD

**Issue by Lczyrny** [googleapis/google-cloud-python#10636]
Hello

I've tried to automate some actions done by "Deployment Manager" service (mostly listing done deployments) using Cloud Functions, however I didn't found any google-cloud-* Python sdk related to that. Can you provide some info is this kind of SDK will be created or shall I use standard REST calls?

Kind regards,
Łukasz Czyrny

**Comment by busunkim96** [comment]
Hi @Lczyrny,

There doesn't appear to be a google-cloud-* library for this API right now. I'm looking into when we expect a client to be published.

Standard REST calls should work well! You can also use the legacy client `google-api-python-client`, which is a thin wrapper around the REST API:

```py
from googleapiclient import discovery

service = discovery.build("deploymentmanager", "v2")

request = service.deployments().list(project="my-project-id")

while request is not None:
    deployments = request.execute()
    request = service.list_next(request, deployments)
```
https://googleapis.github.io/google-api-python-client/docs/dyn/deploymentmanager_v2.deployments.html#list

**Comment by Lczyrny** [comment]
Thanks @busunkim96! Fingers crossed for that new client to be published - for now I will use the old google-api-python-client
