### ISSUE TITLE
Support for Workspace Admin SDK Directory API

### ISSUE THREAD

**Issue by lyricnz** [googleapis/google-cloud-python#10646]
It would be nice to have a proper client for Workspace Admin SDK, in particular (for me) users/groups/members

https://developers.google.com/admin-sdk/directory/reference/rest

Using the discovery interface is a bit clunky, not typeful, and not async.

**Comment by lyricnz** [comment]
Was raised in google-api-python-client project, but rejected as that project is in maintenance-only mode
https://github.com/googleapis/google-api-python-client/issues/1819

**Comment by parthea** [comment]
Googlers see b/179723031

**Comment by SamLindsay** [comment]
I'm not sure if there is a need for a "I'd like this too" post, but this would be good.

If there is a more preferable way to vote for this, please let me know.

**Comment by parthea** [comment]
I've requested an update on b/179723031

**Comment by simon-anz** [comment]
Hi @parthea - any updates? We can use our google support contract to +1 if that would help?

**Comment by samllin** [comment]
Excuse my ignorance, but what is "b/179723031"? (I'm very new to github)

**Comment by parthea** [comment]
b/179723031 is the internal ticket number that we use to track this feature request. Please share the ticket number with Google support as your Google support contract will help with prioritizing this feature.

**Comment by vam-google** [comment]
I have responded in the internal bug. tl;dr; - it is doable, but it is a non-trivial amount of work and it needs to be prioritized.

**Comment by Kolumbs** [comment]
Voting for this too. I needed only to use GET /admin/directory/v1/users from Google and forced to install google-api-python-client, which is heavy and includes many things I don't need.
On async problem i just use asyncio.to_thread

**Comment by parthea** [comment]
Closing as an internal feature request has already been filed (Googlers see b/179723031)

**Comment by lyricnz** [comment]
Completed?  How about "ignored" (it's been 18 months thusfar)
