### ISSUE TITLE
Use Github Search repositories instead of getting all repos

### ISSUE THREAD

**Issue by av1m** [googleapis/google-cloud-python#10678]
I noticed that the script uses the [`List organization repositories`](https://docs.github.com/en/rest/repos/repos#list-organization-repositories) endpoint. However, this command asks to recover all the repos (useless data) then to filter.
It would be more relevant to use the [`Search repositories`](https://docs.github.com/en/rest/search#search-repositories) endpoint.

A simple example would be : https://api.github.com/search/repositories?q=org:googleapis+python%20in:name

We can of course improve, what do you think?

**Comment by parthea** [comment]
Hello @av1m,

Thanks for the suggestion! PRs are welcome if you're interested in contributing.

**Comment by av1m** [comment]
Ok, I'll do that when I have a moment. Thanks 🙂
