### ISSUE TITLE
Update README to fix links and include package names. Currently only the `pretty name` is included in the list

### ISSUE THREAD

**Issue by parthea** [googleapis/google-cloud-python#10799]
The title should include both the package name and the pretty name

https://github.com/googleapis/google-cloud-python/blob/c2da566a711b7b354346c901c49a83f1c49f570f/scripts/updateapilist.py#L36

**Comment by atulep** [comment]
So are you looking for something like: 

`self.title = `${repo["package_name"]}${repo["name_pretty"].replace("Google ", "").replace("Cloud ", "")}` `

**Comment by vchudnov-g** [comment]
Related: #11147

**Comment by parthea** [comment]
Bumping this to P1 because there is another issue where links on the README don't work

**Comment by vchudnov-g** [comment]
This should likely wait until #11147, since that addresses the GitHub action that generates the `README` and may subsume this issue. At the very least, changes there can be a starting point for any changes needed here.

**Comment by parthea** [comment]
Closing as obsolete as the issue in https://github.com/googleapis/google-cloud-python/issues/10799#issuecomment-1924428083 is fixed.
