### ISSUE TITLE
support SQL admin APIs

### ISSUE THREAD

**Issue by ohadgranica** [googleapis/google-cloud-python#10806]
Hi,

We want to use the sqladmin APIs as described [here](https://cloud.google.com/sql/docs/mysql/admin-api/libraries). But it is only supported by the deprecated [client](https://github.com/googleapis/google-api-python-client), and they strongly recommend using this client. Are there any plans on adding those APIs?

Thanks

**Comment by parthea** [comment]
Googlers see b/189986195

**Comment by parthea** [comment]
Closing as an internal feature request was filed.
