### ISSUE TITLE
New docs site doesn't contain `objects.inv`

### ISSUE THREAD

**Issue by ashb** [googleapis/google-cloud-python#10814]
The newly published docs site for the python libraries does not contain the `objects.inv` anymore which makes it hard nicely link to it form downstream projects.

For example, `https://googleapis.dev/python/storage/latest/objects.inv` used to exist, but that now 301s to `https://cloud.google.com/python/docs/reference/storage/latest/index.html` and I wasn't able to guess at a working URL on that `cloud.google.com/python/docs/` site that has an `objects.inv`?

Is this file available anymore? Can it be brought back if it is not currently?

**Comment by parthea** [comment]
Hi @ashb ! Thanks for reporting this issue! We're looking into it.

**Comment by ashb** [comment]
The issue is specifically that objects.inv (a binary file created as part of the sphinx build process) is not available anywhere.

**Comment by dandhlee** [comment]
Ah, I see what the problem is.

If we get `https://googleapis.dev/python/storage/latest/objects.inv` to be available again, would that work even though we'll be redirecting the content for `googleapis.dev/python/$package/latest` to `cloud.google.com/python/docs/reference/$package/latest`? Or do you need `objects.inv` to be available for the local reference for this to work?

**Comment by csm10495** [comment]
I think it can 301 as long as it 301s to the actual inv file again. (The problem now is it 301s to a generic docs page instead of the actual inv file). The inv file is used by the sphinx build process of airflow to properly link to google cloud docs

**Comment by dandhlee** [comment]
Thank you! I'll try and work on having `googleapis.dev/python/$package/latest/objects.inv` files be available ASAP. I'll update once that's done.

As per `cloud.google.com/python/docs/reference/$package/latest/objecs.inv` - that will take some more time. I _might_ try and redirect them to the `googleapis.dev` one in the meantime, but I'll try to figure out a more permanent solution that makes sense.

**Comment by ashb** [comment]
Having the 301 be right would be nice, but having it available anywhere is good enough to fix our CI pipeline

**Comment by potiuk** [comment]
> Thank you! I'll try and work on having googleapis.dev/python/$package/latest/objects.inv files be available ASAP. I'll update once that's done.

Keep fingers crossed.

**Comment by dandhlee** [comment]
Hi folks, sorry for the delay. While the documentation has been redirected, the original `objects.inv` files have been restored and will continue to exist in the original location and not near the `cloud.google.com` domain for now. Should things change, updates will be sent out to let you know where they can be found.

**Comment by potiuk** [comment]
Thanks! Running the PR with reverted changes ^^ to check it.
