### ISSUE TITLE
cannot run maps-fleetengine-delivery-v1

### ISSUE THREAD

**Issue by abhi-hkmci** [googleapis/google-cloud-python#10828]
in the beta libary pip install https://storage.googleapis.com/fleetengine-gapic/dist/793/2022-07-19/maps-fleetengine-delivery-v1-py.tar.gz I am getting error as below :+1: 

ModuleNotFoundError: No module named 'google.geo.type'

when in install google-geo-type 0.3.0 module then I get the next error as 

ImportError: cannot import name 'viewport_pb2' from 'google.geo.type

Reference :
[https://developers.google.com/maps/documentation/transportation-logistics/last-mile-fleet-solution/fleet-performance/fleet-engine/gapic_client](https://developers.google.com/maps/documentation/transportation-logistics/last-mile-fleet-solution/fleet-performance/fleet-engine/gapic_client)

**Comment by parthea** [comment]
Hi @abhi-hkmci,

Thanks for reporting this issue. I've added internal bug numbers below that we'll use to track the fix.

Googlers see b/263306233 and b/266837434 . Also related https://github.com/googleapis/gapic-generator-python/issues/1376.

**Comment by parthea** [comment]
The build rules will be updated in cl/516494358

**Comment by parthea** [comment]
I'm going to close this issue as the issue can no longer be produced with the latest version.

```
>>>pip install https://storage.googleapis.com/fleetengine-gapic/dist/1708/2023-03-29/maps-fleetengine-delivery-v1-py.tar.gz
...
Successfully installed cachetools-5.3.0 certifi-2022.12.7 charset-normalizer-3.1.0 google-api-core-2.11.0 google-auth-2.17.2 googleapis-common-protos-1.59.0 grpcio-1.53.0 grpcio-status-1.53.0 idna-3.4 libcst-0.4.9 maps-fleetengine-delivery-0.1.0 mypy-extensions-1.0.0 proto-plus-1.22.2 protobuf-4.22.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyyaml-6.0 requests-2.28.2 rsa-4.9 six-1.16.0 typing-extensions-4.5.0 typing-inspect-0.8.0 urllib3-1.26.15
>>> import maps.fleetengine.delivery_v1
>>>
>>> import maps.fleetengine.delivery
>>>
```
