### ISSUE TITLE
Adopt split repo: _python-aiplatform_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10888]
Migrate the split-repo https://github.com/googleapis/python-aiplatform to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
I've marked this issue as blocked because the source of truth for the repository is not in GitHub. There are no plans to migrate `python-aiplatform` to the mono repository. I'm going to keep this issue open so that we can track related discussions in one place.

**Comment by dizcology** [comment]
This library contains the generated library as submodules, but has a very significant amount of handwritten code, and its configurations and release model have heavily diverged from other generated libraries.  It should NOT be considered for migration to the monorepo.
