### ISSUE TITLE
Adopt split repo: _python-asset_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10901]
Migrate the split-repo https://github.com/googleapis/python-asset to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by meredithslota** [comment]
Samples were migrated and then removed in https://github.com/googleapis/python-asset/pull/561.

**Comment by parthea** [comment]
The  `migration:workaround:protoplus` label should be removed once https://github.com/googleapis/python-asset/pull/564 is merged.
