### ISSUE TITLE
Adopt split repo: _python-assured-workloads_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10902]
Migrate the split-repo https://github.com/googleapis/python-assured-workloads to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
Opened https://github.com/googleapis/python-assured-workloads/pull/241 to remove the obsolete replacement in owlbot.py

**Comment by parthea** [comment]
Wait for https://github.com/googleapis/gapic-generator-python/pull/1645 and https://github.com/googleapis/gapic-generator-python/pull/1646

**Comment by parthea** [comment]
Ready to migrate once https://github.com/googleapis/python-assured-workloads/pull/241 is merged
