### ISSUE TITLE
Adopt split repo: _python-monitoring-dashboards_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10914]
Migrate the split-repo https://github.com/googleapis/python-monitoring-dashboards to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
Resolving the following issue would result in a breaking change for the library: https://github.com/googleapis/python-monitoring-dashboards/issues/73

I'll mark this as blocked for now.

**Comment by suztomo** [comment]
owlbot.py difference:

suztomo@suztomo:/tmp/python-monitoring-dashboards$ git diff -- owlbot.py
diff --git a/owlbot.py b/owlbot.py
index 6354828..ce738f0 100644
--- a/owlbot.py
+++ b/owlbot.py
@@ -35,7 +35,7 @@ for library in s.get_staging_dirs(default_version):
     if clean_up_generated_samples:
         shutil.rmtree("samples/generated_samples", ignore_errors=True)
         clean_up_generated_samples = False
-    s.move([library], excludes=["**/gapic_version.py", "docs/index.rst"])
+    s.move([library], excludes=["**/gapic_version.py"])
 s.remove_staging_dirs()
 
 # ----------------------------------------------------------------------------
@@ -47,10 +47,10 @@ templated_files = gcp.CommonTemplates().py_library(
     microgenerator=True,
     versions=gcp.common.detect_versions(path="./google", default_first=True),
 )
-s.move(templated_files, excludes=[".coveragerc", ".github/release-please.yml", "docs/index.rst"])
+s.move(templated_files, excludes=[".coveragerc", ".github/release-please.yml"])
 
 python.py_samples(skip_readmes=True)
 
 # run format session for all directories which have a noxfile
 for noxfile in Path(".").glob("**/noxfile.py"):
-    s.shell.run(["nox", "-s", "blacken"], cwd=noxfile.parent, hide_output=False)
+    s.shell.run(["nox", "-s", "format"], cwd=noxfile.parent, hide_output=False)
