### ISSUE TITLE
Adopt split repo: _python-oslogin_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10926]
Migrate the split-repo https://github.com/googleapis/python-oslogin to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
There is a workaround in owlbot.py which is captured in go/proto-plus-cross-api-issue and blocked by https://github.com/googleapis/proto-plus-python/pull/348
