### ISSUE TITLE
Adopt split repo: _python-pubsub_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10930]
Migrate the split-repo https://github.com/googleapis/python-pubsub to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
I've marked this issue as blocked while we determine how to migrate the `python-pubsub` repository to the mono repository.

Note: We should coordinate this effort across various languages. The https://github.com/googleapis/nodejs-pubsub and https://github.com/googleapis/java-pubsub repositories have not migrated to their corresponding mono repositories.

The packages aren't present here:
https://github.com/googleapis/google-cloud-node/tree/main/packages
https://github.com/googleapis/google-cloud-java

**Comment by parthea** [comment]
Closing as the migration is now complete and we won't be migrating these remaining repositories. We can re-open this issue if we want to onboard this repository to the monorepo.
