### ISSUE TITLE
Adopt split repo: _python-scheduler_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10941]
Migrate the split-repo https://github.com/googleapis/python-scheduler to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by MiaCY** [comment]
PR https://github.com/GoogleCloudPlatform/python-docs-samples/pull/9558 under review to migrate handwritten samples.

**Comment by cojenco** [comment]
> PR [GoogleCloudPlatform/python-docs-samples#9558](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/9558) under review to migrate handwritten samples.

Handwritten samples migration complete via above PR and https://github.com/googleapis/python-scheduler/pull/333
