### ISSUE TITLE
Adopt split repo: _python-security-private-ca_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10944]
Migrate the split-repo https://github.com/googleapis/python-security-private-ca to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
PR https://github.com/googleapis/python-security-private-ca/pull/347 will remove the obsolete replacement in owlbot.py
