### ISSUE TITLE
Adopt split repo: _python-secret-manager_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10942]
Migrate the split-repo https://github.com/googleapis/python-secret-manager to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by meredithslota** [comment]
Samples migrated and then removed with https://github.com/googleapis/python-secret-manager/pull/413.
