### ISSUE TITLE
Adopt split repo: _python-storage-transfer_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10957]
Migrate the split-repo https://github.com/googleapis/python-storage-transfer to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by cojenco** [comment]
@MiaCY and I resolved open issues in this repo, including transferring one FR https://github.com/googleapis/google-cloud-python/issues/11061
Updated migration:issues related labels
