### ISSUE TITLE
Adopt split repo: _python-storage_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10956]
Migrate the split-repo https://github.com/googleapis/python-storage to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
This client does not contain any autogenerated code. I'm going to mark is as blocked while we determine if it should be migrated to the mono repository.

**Comment by cojenco** [comment]
As one of the handwritten libraries, the python-storage client should be excluded from being migrated to the mono repository at this point in time.

**Comment by parthea** [comment]
Sounds good. I'm going to close this issue but we can re-open it if more discussion is needed.
