### ISSUE TITLE
Adopt split repo: _python-video-transcoder_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10968]
Migrate the split-repo https://github.com/googleapis/python-video-transcoder to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
I'm going to transfer this issue to the `google-cloud-python` repository as we are preparing to move the code for `google-cloud-video-transcoder` to that repository in the next 1-2 weeks.

**Comment by parthea** [comment]
Wait for cl/538850316

**Comment by suztomo** [comment]
@parthea cl/538850316 has been submitted.
