### ISSUE TITLE
Adopt split repo: _python-trace_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10963]
Migrate the split-repo https://github.com/googleapis/python-trace to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
Let's decide if we want to introduce a breaking change now or not.

```
    # Rename field `type_` to `type` in v1 and v2 to avoid breaking change
    s.replace(
        library / "google/**/types/*.py",
        "type_",
        "type"
    )
```
