### ISSUE TITLE
Adopt split repo: _python-bigquery-storage_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10991]
Migrate the split-repo https://github.com/googleapis/python-bigquery-storage to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
I've marked this issue as blocked while we determine how to migrate the `python-bigquery-storage` repository to the mono repository.

Note: We should coordinate this effort across various languages. The https://github.com/googleapis/nodejs-bigquery-storage and https://github.com/googleapis/java-bigquerystorage repositories have not migrated to their corresponding mono repositories.

The packages aren't present here:
https://github.com/googleapis/google-cloud-node/tree/main/packages
https://github.com/googleapis/google-cloud-java

**Comment by meredithslota** [comment]
I think this one is out-of-scope for the initial move — it has significant handwritten code. cc: @brijk@google.com to determine path forward.

**Comment by meredithslota** [comment]
Reclassifying this as a feature request since the handwritten libraries will be the last to migrate (e.g. after all the autogenerated libraries are done).

**Comment by meredithslota** [comment]
Updating ownership accordingly.

**Comment by parthea** [comment]
Closing as the migration is now complete and we won't be migrating these remaining repositories. We can re-open this issue if we want to onboard this repository to the monorepo.

**Comment by parthea** [comment]
This is actively being worked on
