### ISSUE TITLE
Adopt split repo: _python-binary-authorization_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10995]
Migrate the split-repo https://github.com/googleapis/python-binary-authorization to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
Googlers see go/fix-gapic-depends-on-gapic-with-proto-plus-types for how to configure Bazel Build rules to remove replacements in owlbot.py [here](https://github.com/googleapis/python-binary-authorization/blob/main/owlbot.py#L40).

**Comment by chalmerlowe** [comment]
In collaborating with @parthea we discovered that there appears to be some form of error in the generator that impacts revisions to BUILD.bazel to support proto-plus. When we run bazel there are two errors that occur (under different circumstances/different development environments). One type of error is:

```
from grafeas_v1.types import attestation as g_attestation
E   ModuleNotFoundError: No module named 'grafeas_v1'
```

The other type error that we came across was:
```
ModuleNotFoundError: No module named 'google.cloud.binaryauthorization_v1'
```
