### ISSUE TITLE
Adopt split repo: _python-dataflow-client_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#11007]
Migrate the split-repo https://github.com/googleapis/python-dataflow-client to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
We either need to take a breaking change for the below workaround, or add `set` to the list of reserved words for the python gapic generator

```
    # Work around to avoid a breaking change
    # Replace `set` with `set_` 
    s.replace(
        library / "google/cloud/dataflow_v1beta3/types/metrics.py",
        "set \(google.protobuf.struct_pb2.Value\)",
        "set_ (google.protobuf.struct_pb2.Value)",
    )

    s.replace(
        library / "google/cloud/dataflow_v1beta3/types/metrics.py",
        "set: struct_pb2.Value = proto.Field",
        "set_: struct_pb2.Value = proto.Field",
    )
```
