### ISSUE TITLE
Adopt split repo: _python-dataproc_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#11012]
Migrate the split-repo https://github.com/googleapis/python-dataproc to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
Wait for cl/524949091

**Comment by parthea** [comment]
Ready to migrate once https://github.com/googleapis/python-dataproc/pull/531 is merged
