### ISSUE TITLE
Adopt split repo: _python-gke-backup_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#11037]
Migrate the split-repo https://github.com/googleapis/python-gke-backup to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
Wait for cl/546268592 and https://github.com/googleapis/gapic-generator-python/pull/1687

**Comment by parthea** [comment]
I checked the workarounds in `owlbot.py` and none of them are needed. We just need to migrate to the standard owlbot.py

**Comment by suztomo** [comment]
Memo: Issues and pull requests are zero.
