### ISSUE TITLE
Adopt split repo: _python-game-servers_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#11036]
Migrate the split-repo https://github.com/googleapis/python-game-servers to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
This repository should not be migrated. Googlers see b/266495523. I'll keep this issue open so we can track discussions in one place.

**Comment by parthea** [comment]
I'm going to mark this one as ready to migrate to reduce the number of split repositories that we maintain

**Comment by parthea** [comment]
Closed. The repository is archived: https://github.com/googleapis/python-game-servers
