### ISSUE TITLE
Adopt split repo: _python-ids_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#11047]
Migrate the split-repo https://github.com/googleapis/python-ids to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by vchudnov-g** [comment]
@parthea   Should we wait until we archive the split repo to apply the `migration:stage:split-repo-archived` label to this issue? I can also separately modify the issue-update scripts to close issues after all the `migration:stage:*` labels are present.

**Comment by parthea** [comment]
> Should we wait until we archive the split repo to apply the migration:stage:split-repo-archived label to this issue?
The split repo was archived

>I can also separately modify the issue-update scripts to close issues after all the migration:stage:* labels are present.
SGTM

**Comment by parthea** [comment]
Migration complete.
