### ISSUE TITLE
Adopt split repo: _python-iot_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#11048]
Migrate the split-repo https://github.com/googleapis/python-iot to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
`Google Cloud IoT Core is being retired on August 16, 2023`. See https://cloud.google.com/iot-core. I'm going to mark this issue as blocked until then. This issue can be closed once the `python-iot` repository has been archived after August 16, 2023.

**Comment by suztomo** [comment]
test

**Comment by suztomo** [comment]
Turn down repositories after cleaning up.

**Comment by suztomo** [comment]
From https://github.com/ddixit14/repo_tracker/blob/main/document_reference_count.tsv, there are 34 documents still referencing the old sample code.

row_id | repo_name | document_url | file
-- | -- | -- | --
217 | python-iot | https://cloud.google.com/iot/docs/how-tos/commands | googleapis/python-iot/samples/api-client/manager/manager.py
218 | python-iot | https://cloud.google.com/iot/docs/how-tos/config/configuring-devices | googleapis/python-iot/samples/api-client/manager/manager.py
219 | python-iot | https://cloud.google.com/iot/docs/how-tos/config/getting-state | googleapis/python-iot/samples/api-client/manager/manager.py
220 | python-iot | https://cloud.google.com/iot/docs/how-tos/credentials/authenticating-applications | googleapis/python-iot/samples/api-client/manager/manager.py
221 | python-iot | https://cloud.google.com/iot/docs/how-tos/devices | googleapis/python-iot/samples/api-client/manager/manager.py
222 | python-iot | https://cloud.google.com/iot/docs/how-tos/gateway-demo | googleapis/python-iot/samples/api-client/manager/manager.py
223 | python-iot | https://cloud.google.com/iot/docs/how-tos/gateways/create-gateways | googleapis/python-iot/samples/api-client/manager/manager.py
224 | python-iot | https://cloud.google.com/iot/docs/how-tos/gateways/mqtt-demo | googleapis/python-iot/samples/api-client/manager/manager.py
225 | python-iot | https://cloud.google.com/iot/docs/how-tos/iam | googleapis/python-iot/samples/api-client/manager/manager.py
226 | python-iot | https://cloud.google.com/iot/docs/samples/iot-bind-device-to-gateway | googleapis/python-iot/samples/api-client/manager/manager.py
227 | python-iot | https://cloud.google.com/iot/docs/samples/iot-create-device | googleapis/python-iot/samples/api-client/manager/manager.py
228 | python-iot | https://cloud.google.com/iot/docs/samples/iot-create-es-device | googleapis/python-iot/samples/api-client/manager/manager.py
229 | python-iot | https://cloud.google.com/iot/docs/samples/iot-create-gateway | googleapis/python-iot/samples/api-client/manager/manager.py
230 | python-iot | https://cloud.google.com/iot/docs/samples/iot-create-registry | googleapis/python-iot/samples/api-client/manager/manager.py
231 | python-iot | https://cloud.google.com/iot/docs/samples/iot-create-rsa-device | googleapis/python-iot/samples/api-client/manager/manager.py
232 | python-iot | https://cloud.google.com/iot/docs/samples/iot-create-unauth-device | googleapis/python-iot/samples/api-client/manager/manager.py
233 | python-iot | https://cloud.google.com/iot/docs/samples/iot-delete-device | googleapis/python-iot/samples/api-client/manager/manager.py
234 | python-iot | https://cloud.google.com/iot/docs/samples/iot-delete-registry | googleapis/python-iot/samples/api-client/manager/manager.py
235 | python-iot | https://cloud.google.com/iot/docs/samples/iot-get-device | googleapis/python-iot/samples/api-client/manager/manager.py
236 | python-iot | https://cloud.google.com/iot/docs/samples/iot-get-device-configs | googleapis/python-iot/samples/api-client/manager/manager.py
237 | python-iot | https://cloud.google.com/iot/docs/samples/iot-get-device-state | googleapis/python-iot/samples/api-client/manager/manager.py
238 | python-iot | https://cloud.google.com/iot/docs/samples/iot-get-iam-policy | googleapis/python-iot/samples/api-client/manager/manager.py
239 | python-iot | https://cloud.google.com/iot/docs/samples/iot-get-registry | googleapis/python-iot/samples/api-client/manager/manager.py
240 | python-iot | https://cloud.google.com/iot/docs/samples/iot-list-devices | googleapis/python-iot/samples/api-client/manager/manager.py
241 | python-iot | https://cloud.google.com/iot/docs/samples/iot-list-devices-for-gateway | googleapis/python-iot/samples/api-client/manager/manager.py
242 | python-iot | https://cloud.google.com/iot/docs/samples/iot-list-gateways | googleapis/python-iot/samples/api-client/manager/manager.py
243 | python-iot | https://cloud.google.com/iot/docs/samples/iot-list-registries | googleapis/python-iot/samples/api-client/manager/manager.py
244 | python-iot | https://cloud.google.com/iot/docs/samples/iot-patch-es | googleapis/python-iot/samples/api-client/manager/manager.py
245 | python-iot | https://cloud.google.com/iot/docs/samples/iot-patch-rsa | googleapis/python-iot/samples/api-client/manager/manager.py
246 | python-iot | https://cloud.google.com/iot/docs/samples/iot-send-command | googleapis/python-iot/samples/api-client/manager/manager.py
247 | python-iot | https://cloud.google.com/iot/docs/samples/iot-set-device-config | googleapis/python-iot/samples/api-client/manager/manager.py
248 | python-iot | https://cloud.google.com/iot/docs/samples/iot-set-iam-policy | googleapis/python-iot/samples/api-client/manager/manager.py
249 | python-iot | https://cloud.google.com/iot/docs/samples/iot-unbind-device-from-gateway | googleapis/python-iot/samples/api-client/manager/manager.py
250 | python-iot | https://cloud.google.com/iot/docs/how-tos/config/configuring-devices | googleapis/python-iot/samples/api-client/mqtt_example/cloudiot_mqtt_example.py

**Comment by parthea** [comment]
Docs were addressed in cl/555317637. Closing as obsolete. The repository is now archived.
