### ISSUE TITLE
Adopt split repo: _python-iam_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#11044]
Migrate the split-repo https://github.com/googleapis/python-iam to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
The repository includes clients from 2 different APIs : `iamcredentials` and `iam`. This is not supported in the mono repository yet. I'm going to add the blocked tag while I investigate how we can support it.

FYI @vchudnov-g

**Comment by parthea** [comment]
The issue mentioned in https://github.com/googleapis/google-cloud-python/issues/11044#issuecomment-1497109023 was fixed in https://github.com/googleapis/python-iam/pull/296
