### ISSUE TITLE
Adopt split repo: _python-gsuiteaddons_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#11043]
Migrate the split-repo https://github.com/googleapis/python-gsuiteaddons to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
This is the only split repository that has a manual workaround which is not documented in owlbot.py. I'll work on removing it.

**Comment by parthea** [comment]
cl/522004674 should solve the issue with manual workarounds.

**Comment by parthea** [comment]
Presubmits are failing in cl/522004674 but not in GitHub with the same code.

**Comment by parthea** [comment]
I was able to get cl/522004674  to pass locally by adding `google-apps-script-type` to the requirements here: https://github.com/googleapis/gapic-generator-python/blob/main/requirements.in

and making the following changes in `google/cloud/gsuiteaddons/v1/BUILD.bazel`
```
load("@gapic_generator_python_pip_deps//:requirements.bzl", "requirement")

py_gapic_library(
    name = "gsuiteaddons_py_gapic",
    srcs = [":gsuiteaddons_proto"],
    grpc_service_config = "gsuiteaddons_grpc_service_config.json",
    rest_numeric_enums = True,
    service_yaml = "gsuiteaddons_v1.yaml",
    transport = "grpc+rest",
    opt_args = [
        "proto-plus-deps=\
google.apps.script.type.calendar+\
google.apps.script.type.docs+\
google.apps.script.type.drive+\
google.apps.script.type.gmail+\
google.apps.script.type.sheets+\
google.apps.script.type.slides+\
google.apps.script.type"
    ],
    deps = [requirement("google-apps-script-type")]
)
```

This is effectively pulling the `google-apps-script-type` from PyPI. An alternative solution is to figure out how to bundle all of the `google.apps.script.type` subpackages in a single packages via bazel rules.
