### ISSUE TITLE
Adopt split repo: _python-iam-logging_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#11045]
Migrate the split-repo https://github.com/googleapis/python-iam-logging to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
- [x] No open issues
- [x] No open PRs
- [x] No handwritten samples
- [x] No system tests
- [x] No client specific customizations
