### ISSUE TITLE
FeatReq: New get_processor_name() to retrieve by display name

### ISSUE THREAD

**Issue by yan-hic** [googleapis/google-cloud-python#11072]
Console shows the display name, which is supposedly the alias that user refers to when id'ing a processor.
I understand the `name` is required in all API calls as it is fully qualified, however, there is no method to return the name based on its display name (which always exists).

Request to add a new helper method to do so. Params would be `display_name`, `project_id`, `location`.

Workaround: retrieve the list of all processors and loop through until matching `display_name` is found

**Comment by vchudnov-g** [comment]
@yan-hic Thanks for filing this issue! Is this still a deficiency that you'd like addressed? It sounds like a back-end feature request, so we'll contact the right team. If you have a support contract, you can file a feature request there to ensure prompt attention.

**Comment by yan-hic** [comment]
Honestly after 2 yrs, I have moved on and used a for loop to return the matching processor. Probably what an official helper would do too.

**Comment by parthea** [comment]
I'm going to close issue due to inactivity. As this is a back-end feature request, we recommend filing a feature request [here](https://issuetracker.google.com/issues/new?component=1132231).
