### ISSUE TITLE
SecretManagerServiceClient() should automatically grab the project from the runtime environment. 

### ISSUE THREAD

**Issue by Kharms** [googleapis/google-cloud-python#11070]
**Is your feature request related to a problem? Please describe.**
It's more a matter of consistency that a problem. Other gcp client libraries initialize with a project property which is grabbed from the environment variables at runtime. See for example:
```
>>>from google.cloud import storage

>>>gs_client = storage.Client()
>>>gs_client.project
'some-project-name'
```

 **Describe the solution you'd like**
```
>>>from google.cloud import secretmanager

>>>sm_client = secretmanager.SecretManagerServiceClient()
>>>sm_client.project
'some-project-name'
```

**Comment by parthea** [comment]
Closing as obsolete based on https://github.com/googleapis/google-cloud-python/issues/11070#issuecomment-1509842785. Please open a new issue if this feature request is still desired.
