### ISSUE TITLE
replace mentions of "master" in the proto

### ISSUE THREAD

**Issue by dandhlee** [googleapis/google-cloud-python#11074]
@parthea, there are few mentions of "master" in the proto files. Namely:

https://github.com/googleapis/python-documentai/blob/main/google/cloud/documentai_v1/types/document.py#L677-L688
and
https://github.com/googleapis/python-documentai/blob/main/google/cloud/documentai_v1beta3/types/document.py#L681-L692.

Could you fix these up in the proto, or assign someone to handle it?

**Comment by parthea** [comment]
Closing as duplicate of https://github.com/googleapis/gapic-generator-python/issues/1851
