### ISSUE TITLE
`--properties-file` flag not available job classes

### ISSUE THREAD

**Issue by d0choa** [googleapis/google-cloud-python#11088]
The flag `--properties-file=PROPERTIES_FILE` from `gcloud dataproc jobs submit pyspark` [[doc](https://cloud.google.com/sdk/gcloud/reference/dataproc/jobs/submit/pyspark#--properties)] does not seem available through the `PySparkJob` [python class](https://github.com/googleapis/python-dataproc/blob/2107cf8bc54096b7bb14b4de38a9abef5eeada59/google/cloud/dataproc_v1/types/jobs.py#L300).

This flag is very handy to add properties that depend on the cluster initialisation actions, such as the path of library installed during initialisation.

**Comment by vchudnov-g** [comment]
Thanks for submitting this isse, @d0choa ! To be clear, what you're suggesting is that it would be useful to have an option to specify a properties file rather than a list of key/value pairs?

**Comment by parthea** [comment]
The [properties field](https://github.com/googleapis/python-dataproc/blob/2107cf8bc54096b7bb14b4de38a9abef5eeada59/google/cloud/dataproc_v1/types/jobs.py#L330-L337) is the recommended way to provide properties when using the Python Client Library. When using the `gcloud` CLI, there is a strong argument to have a convenience method for reading properties from a file but for client libraries we would need a strong reason to add these helpers to ensure that we're not introducing clutter. This seems like it's better handled at the application layer. I'm going to close this issue but please feel free to open a new feature request with more information.

**Comment by d0choa** [comment]
thanks!
