### ISSUE TITLE
PredictionService don't go to project id as per placement

### ISSUE THREAD

**Issue by parfaire** [googleapis/google-cloud-python#11084]
PredictionService is unable to define the project_id accurately. I notice that my key.json (generated from service account) is targeting a certain project id; while my retail API lives in different project id.

I already set the placement to the correct project number, however the error seems that predict request goes to the project as per my key.json define instead of the placement.

I couldn't find a way to set PredictionServiceClient to a certain gcp_project_id, please help and advise

To reproduce:
```python

from google.cloud import retail_v2
# Create a client
client = retail_v2.PredictionServiceClient()
# Initialize request argument(s)
user_event = retail_v2.UserEvent(visitor_id="")
project_number=1000
request = retail_v2.PredictRequest(
    placement=f'projects/{project_number}/locations/global/catalogs/default_catalog/placements/product_detail',
    user_event=user_event
)
print(request.placement) # projects/1000/locations/global/catalogs/default_catalog/placements/product_detail


client.predict(request) # this is throwing error as below

# raise exceptions.from_grpc_error(exc) from exc
# google.api_core.exceptions.PermissionDenied: 403 Retail API has not been used in project <OTHER_PROJECT_NUMBER> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/retail.googleapis.com/overview?project=<OTHER_PROJECT_NUMBER> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [links {
#  description: "Google developers console API activation"

```

**Comment by parthea** [comment]
This issue appears to be obsolete. I'm not able to re-create the error. I can use the retail API in different projects by changing the project Id in the snippet shared in the first post. If anyone encounters this problem, please file a new issue.
