### ISSUE TITLE
Timestamp of the file (if given)

### ISSUE THREAD

**Issue by arnavmehta7** [googleapis/google-cloud-python#11083]
**Is your feature request related to a problem? Please describe.**
It would be amazing to also save the transcription generated into a .srt like object then we would be able to do some changes with it.

 **Describe the solution you'd like**
I'd like it to have a variable in each response which can point me to "how  many seconds of audio is read ".

 **Describe alternatives you've considered**
 Using the chunks to find the timestamp, but no, doesn't works

**Comment by vchudnov-g** [comment]
Thanks for filing this issue, @arnavmehta7 . This seems like a server-side feature request rather than a client library request; we'll contact that team. If  you have a support contract, file a feature request directly so you can get prompt attention.

**Comment by arnavmehta7** [comment]
Sorry guys I figured out ways. Thanks
