### ISSUE TITLE
Add ability to list assets from Organizations and Folders along with Projects

### ISSUE THREAD

**Issue by shashyajoshi** [googleapis/google-cloud-python#11094]
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**
Current code accepts only projects as "parent" for the Asset API, whereas the API can list assets from Orgs and Folders as well. A small change to accept the other two options for "parent" will make the code more useful. Many people use Asset API to search for resources across multiple projects

 **Describe the solution you'd like**
Current code at samples/snippets/quickstart_listassets.py has `project_id` as an argument, instead we can have `parent_resource` as an argument, with the "help" text describing `"Parent resource. Either projects/<project id> or folders/<folder id> or organizations/<organization id>"`. We then can change references to `project_id` with `parent_resource` in other places. 

 **Describe alternatives you've considered**
NA

 **Additional context**
https://cloud.google.com/asset-inventory/docs/reference/rest/v1/assets/list#path-parameters

**Comment by vchudnov-g** [comment]
@shashyajoshi Is this a missing feature in the library, or an error in the sample? Could you confirm the deficiency still exists? In this repo, I believe the relevant sample is [here](https://github.com/googleapis/google-cloud-python/blob/main/packages/google-cloud-asset/samples/generated_samples/cloudasset_v1_generated_asset_service_list_assets_sync.py), and the method is  [here](https://github.com/googleapis/google-cloud-python/blob/41a3afda46a7c3f02bff3f92f15cd49daf92083e/packages/google-cloud-asset/google/cloud/asset_v1/services/asset_service/client.py#L899).

**Comment by vchudnov-g** [comment]
No response, so closing the issue.

Note that the [arg description](https://github.com/googleapis/google-cloud-python/blob/41a3afda46a7c3f02bff3f92f15cd49daf92083e/packages/google-cloud-asset/google/cloud/asset_v1/services/asset_service/client.py#L943) lists orgs and folders as acceptable parents.

Feel free to file a new issue if needed.
