### ISSUE TITLE
Loosen version constraints on `protobuf`

### ISSUE THREAD

**Issue by alexandreyc** [googleapis/google-cloud-python#11380]
Hello,

We would like to use `google-cloud-batch` within [Google Cloud Composer](https://cloud.google.com/composer). Unfortunately there is no way to install it at the moment because of a conflicting requirement on `protobuf`. 

In particular, `google-cloud-batch` requires `protobuf!=3.20.0` whereas almost all recent versions of Composer have `protobuf==3.20.0` installed as can be seen [here](https://cloud.google.com/composer/docs/concepts/versioning/composer-versions).

Do you think it is possible to loosen this requirement on your side?

Thank you for you help,

**Comment by alexandreyc** [comment]
Ok. In the meantime we've opened an issue with the support and they told us that the next release of Composer should include `protobuf >= 4.x`.

**Comment by parthea** [comment]
`composer-2.3.0-airflow-2.5.1` now allows protobuf >= 4. I'm going to close this issue as resolved but please feel free to open a new issue if required.

https://cloud.google.com/composer/docs/concepts/versioning/composer-versions#images
