### ISSUE TITLE
We are Unable to activate / configure custom metric developed..

### ISSUE THREAD

**Issue by Pratik-kadu** [googleapis/google-cloud-python#11454]
Unable to activate / configure custom metric developed.

We are currently working on creating custom metrics to track the successful job count in a data flow. We have implemented the code to create these custom metrics, but when we check the Google Cloud Console, the metrics appear as inactive. This indicates that the metric data is not being loaded properly.

To assist you further, could you please provide some screenshots of the Google Cloud Console where the inactive metrics are displayed?  If possible, we provide the code in a file format so that you can review it more effectively. Once you have reviewed the code, you will be able to suggest any necessary changes or explore alternative methods to create custom metric.
Screenshots:
![image](https://github.com/googleapis/google-cloud-python/assets/138665867/8f3a7590-b596-456b-8ad9-f0de9bb277d8)
![image](https://github.com/googleapis/google-cloud-python/assets/138665867/458652a4-399a-4052-93ec-2f45326e4c90)

[Custom_metric_code.txt](https://github.com/googleapis/google-cloud-python/files/11956681/Custom_metric_code.txt)

**Comment by parthea** [comment]
Hello @Pratik-kadu , Thanks for sharing the sample code. If you haven't reported any data in the last 24 hours for the given metric, the metric will be shown as inactive in the metric explorer. Please let me know if you have additional questions.

**Comment by parthea** [comment]
I'm going to close this issue but please feel free to open a new issue if you have additional questions.
