### ISSUE TITLE
GCP workflows executions library lacks `filter` and `orderBy` support

### ISSUE THREAD

**Issue by xSAVIKx** [googleapis/google-cloud-python#11549]
The REST API (https://cloud.google.com/workflows/docs/reference/executions/rest/v1/projects.locations.workflows.executions/list) has support for `filter` and `orderBy` params while the Python library for `gcp-workflows` has no such fields.

It'd be great to regenerate the client / add support for the missing fields while filtering represents a major feature available in the API.

![image](https://github.com/googleapis/google-cloud-python/assets/5675689/cf87c0b6-6df4-41d7-a94f-da1d0ba58c43)

**Comment by parthea** [comment]
Hi @xSAVIKx,

Thanks for reporting this issue! I've filed an internal bug for the Google Cloud Workflows Executions API team to update the public `*proto` [file](https://github.com/googleapis/googleapis/blob/master/google/cloud/workflows/executions/v1/executions.proto) that is used to generate the client library. (Googlers see b/295500871)

**Comment by xSAVIKx** [comment]
@parthea any updates or ETA?
