### ISSUE TITLE
Policy Type Missing

### ISSUE THREAD

**Issue by nitishxp** [googleapis/google-cloud-python#11553]
Hi Team,

In google-bigquerydatapolicy we have only 3 data policy types defined in [1].

But in google documentation[2] there are 7 types can we add it to the SDK 

[1]
https://cloud.google.com/python/docs/reference/bigquerydatapolicy/latest/google.cloud.bigquery.datapolicies_v1.types.DataMaskingPolicy.PredefinedExpression

[2] https://cloud.google.com/bigquery/docs/column-data-masking-intro#masking_options

**Comment by parthea** [comment]
Hi @nitishxp,

Thanks for reporting this issue! I've filed an internal bug for the API team to update the public `*proto` [file](https://github.com/googleapis/googleapis/blob/master/google/cloud/bigquery/datapolicies/v1/datapolicy.proto) that is used to generate the client library. (Googlers see b/295366058)
