### ISSUE TITLE
Update `CONTRIBUTING.rst` to indicate that source is autogenerated using `gapic-generator-python`

### ISSUE THREAD

**Issue by parthea** [googleapis/google-cloud-python#11618]
We should update the [CONTRIBUTING.rst ](https://github.com/googleapis/google-cloud-python/blob/main/CONTRIBUTING.rst) to mention that all of the client libraries are automatically generated. Open source contributions for autogenerated code should be made in https://github.com/googleapis/gapic-generator-python instead.

**Comment by antvega98** [comment]
I am working on this with Victoria Liu and Sebastian Ramos.
