### ISSUE TITLE
504 Deadline Exceeded in google-cloud-batch from mysterious global deadline

### ISSUE THREAD

**Issue by benbuckman** [googleapis/google-cloud-python#11656]
I am trying to debug behavior involving the interaction of `google-cloud-batch` with [Apache Airflow](https://github.com/apache/airflow). I have verified this behavior with `google-cloud-batch` versions `0.9.0` through the latest `0.17.0`.

In our Airflow application we have a sensor ([essentially](https://github.com/apache/airflow/blob/2.7.0/airflow/sensors/base.py/#L236-L279) a `while True: <poll>, sleep` loop – where the poll (aka `poke`) callable is doing:

```python
from google.cloud.batch_v1 import BatchServiceClient, GetJobRequest, Job

def get_batch_job_by_name(name: str) -> Job:
    return BatchServiceClient().get_job(
        request=GetJobRequest(name=name),
        timeout=20.0,  # <-- IMPT
    )
```

The `timeout=20.0` in that snippet is replacing the [default 60s timeout](https://github.com/googleapis/python-batch/blob/de68b7c772bdd90f258139b7dc1f5268dfe5eb8e/google/cloud/batch_v1/services/batch_service/transports/base.py#L146).
The behavior I'm observing is that it runs that code successfully, sleeps the prescribed seconds (I've tried with 5 and 10), and repeats; but as soon as the number of seconds specified there, _from the start_, has passed, I get a `Deadline Exceeeded` error. For example, at the default 60s `timeout`, with the interval at 10 seconds, it fails consistently on the 7th poll. At `timeout=20` it fails faster, etc, and this is very consistent.

This is confusing because:
1. I understand that `timeout` parameter in `get_job()` to be _per request_. In this case, each request succeeds. The timeout on that individual request should then be irrelevant on the next request.
2. This code is also instantiating a new `BatchServiceClient()` on each poll. So if state were being held on the client, that should also disappear.

Making this more confusing, I can't repro this with a plain `while (True) ... sleep(5):` loop in a python REPL.

So far it seems like something in Airflow is causing a _global_ deadline to be set (based on the `timeout` param to each call) across multiple requests. This sounds far-fetched, but that's the only hypothesis I can devise so far that fits. But I haven't found any code that would be doing this, or documentation that such functionality exists.

I'm going to keep digging and hopefully be able to reproduce this in a generic (non-Airflow) context.
In the meantime, does this ring any bells, does anyone have an idea what might be causing this?
Or perhaps I'm just confused and this is expected?

Thank you very much.

**Comment by benbuckman** [comment]
OK, this is embarrassing. The cause was `freezegun.freeze_time()` in the tests in which we were observing this behavior. I suspect the interaction of the client's fake timestamp (stuck "in the past") and the server's actual time caused the deadline exceeded error.

**Comment by kristopherkane** [comment]
I arrived here seeing similar behavior in GCP Dataproc + Airflow all of a sudden.
