### ISSUE TITLE
Determine if the presubmit checks should be `strict` or `loose`

### ISSUE THREAD

**Issue by parthea** [googleapis/google-cloud-python#11655]
See the definition of `strict` and `loose` here:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-status-checks-before-merging

It is toilsome to require branches to be upto date before merging. Having a `loose` check will allow us to merge branches that aren't up to date. The downside of having a `loose` check  is that `Status checks may fail after you merge your branch if there are incompatible changes with the base branch.` 

Note: we will still require a linear git history regardless if we choose `strict` or `loose`.

https://github.com/googleapis/repo-automation-bots/blob/main/packages/sync-repo-settings/src/required-checks.json#L43C10-L43C36

**Comment by parthea** [comment]
If we decide to have `loose` status checks, we could add a presubmit check to the release PR to fail if the branch is not upto date with `main` so that merged commits which do not have public release notes still land in the release.

**Comment by tswast** [comment]
My 2 cents: I like the safety of the strict checks but after about 4 or more active contributors to a repo it can really slow things down on a repo with a lot of system tests like https://github.com/googleapis/python-bigquery-dataframes

If there was a way to require strict checks only on Release PRs that would be my ideal setup, though for the most part the release-please bot is pretty good about staying synced with main.

**Comment by vchudnov-g** [comment]
Let's write a one-pager describing this proposal, its downsides, and also any alternatives (eg GitHub merge queue) that might be easier/safer.

**Comment by parthea** [comment]
Presubmit checks will be kept as `strict` but we will use GitHub merge queue to remove the manual toil to keep branches up to date.
