### ISSUE TITLE
CloudBillingClient.update_project_billing_info

### ISSUE THREAD

**Issue by aaron-tillekeratne** [googleapis/google-cloud-python#11756]
As per the API documentation, `CloudBillingClient().update_project_billing_info` specifies a `name` required parameter, which denotes the GCP project which the billing info is to be updated for. However the current behaviour DOES NOT reflect this. 

Currently, this value is just simply thrown away, and whatever project is associated with Service Account / ADC credentials are used.

**Comment by aaron-tillekeratne** [comment]
Steps to reproduce:
```
from google.cloud import billing_v1

    client = billing_v1.CloudBillingClient() # ADC with quota project A
    request = billing_v1.UpdateProjectBillingInfoRequest(
        name="projects/project-B",
        project_billing_info=billing_v1.ProjectBillingInfo(billing_account_name = "SOME_BILLING_ACCOUNT")
    )
    client.update_project_billing_info(request=request)
```

**Comment by parthea** [comment]
Hi @aaron-tillekeratne,

Regrettably, I wasn't able to re-produce the issue. I was able to change the project set via the `name` argument of `UpdateProjectBillingInfoRequest` and see the change with the associated billing information for 2 different projects without any changes to ADC. 

I was able to verify the changes using the following snippets.

```
# Lists the projects associated with a billing account
from google.cloud import billing_v1
client = billing_v1.CloudBillingClient()
print(client.list_project_billing_info( name="billingAccounts/<Your billing account>")
```

```
# Gets the billing information for a project.
from google.cloud import billing_v1
client = billing_v1.CloudBillingClient()
print(client.get_project_billing_info(name="projects/<Your project>"))
```

The `name` argument of `UpdateProjectBillingInfoRequest` wasn't ignored in my testing. I'm going to close this issue as not reproducible but please feel free to open a new issue with more information.

**Comment by aaron-tillekeratne** [comment]
ok no problem. I actually just used a workaround. Thanks.
