### ISSUE TITLE
Are old versions removed from pypi ? (google-cloud-datacatalog-lineage==0.1.7)

### ISSUE THREAD

**Issue by andres-lowrie** [googleapis/google-cloud-python#11768]
Hello and apologies if this is the wrong place to ask this but I figured I'd give a shot

I'm using Google Cloud Composer and I'm looking for the following package `google-cloud-datacatalog-lineage==0.1.7` as it's installed on the worker node for composer and mentioned as a dependency. I noticed however that [pypi](https://pypi.org/project/google-cloud-datacatalog-lineage/#history) doesn't have any release going back that far so I'm wondering

are old version removed from pypi? 

if so, any way for me to get this package in order to align our environments?

appreciate the time

**Comment by meredithslota** [comment]
Hello @andres-lowrie — I don't know if those earliest versions were even released to PyPi. The release history for that package in this repo also starts at `0.2.0`: https://github.com/googleapis/google-cloud-python/releases?q=google-cloud-datacatalog-lineage Can you let me know which version of Cloud Composer you're using? I'm peeking at https://cloud.google.com/composer/docs/concepts/versioning/composer-versions and I do see very early versions of `google-cloud-datacatalog-lineage` installed even on the most recent releases which makes me think we should file an internal issue with the Cloud Composer team. 

I've filed internal issue 304862247 with that team.

**Comment by andres-lowrie** [comment]
sorry for the late response I was OOO. We're using `

```
composer == 2.4.2
airflow == 2.5.3
```

**Comment by parthea** [comment]
I'm going to close this issue as the internal bug is closed: b/304862247 . To answer the question in https://github.com/googleapis/google-cloud-python/issues/11768#issue-1918292739, old versions are not removed from PyPI. I don't believe `google-cloud-datacatalog-lineage==0.1.7` was ever published to PyPI.

**Comment by daniel-dylag-openx** [comment]
@parthea what is the resolution of the internal bug? Can you provide a link (if it's accessible externally)? Can I set up my local environment to somehow access the same dependency?

**Comment by parthea** [comment]
The library `google-cloud-datacatalog-lineage==0.1.7` was never shipped to PyPI. It came as a preinstalled dependency in Composer images. According to b/304862247, `google-cloud-datacatalog-lineage==0.1.7` was not intended to be installed outside of the composer image.
