### ISSUE TITLE
chore: references to "googleapis" master branch

### ISSUE THREAD

**Issue by nicain** [googleapis/google-cloud-python#11832]
During the master --> main migration, I noticed references that point to the master branch of https://github.com/googleapis/googleapis

After that repo is migrated, we will need to circle back to this repo (and potentially others) and fix these references

- [ ] google/cloud/automl_v1/types/io.py
- [ ] google/cloud/automl_v1beta1/types/io.py

xref: googleapis/google-cloud-python#10579

**Comment by parthea** [comment]
Closing as duplicate of https://github.com/googleapis/gapic-generator-python/issues/1851
