### ISSUE TITLE
BuildTrigger Object do not have approvalConfig property 

### ISSUE THREAD

**Issue by mbohri-cslt** [googleapis/google-cloud-python#11857]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-cloudbuild/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-cloud-build` version: `pip show google-cloud-build`

#### Steps to reproduce

  1. ?
  2. ?

#### Code example

```python
# example
```

#### Stack trace
```
# example
```
Please refer to this REST API documentation here https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers#BuildTrigger

it has the property ApprovalConfig but Python libraries equivalent type ( BuildTrigger)  does not have the same property. Please refer documentation here 
 https://cloud.google.com/python/docs/reference/cloudbuild/latest/google.cloud.devtools.cloudbuild_v1.types.BuildTrigger

Can you please let me know if I am missing anything ?

Thanks!

**Comment by parthea** [comment]
Hi @mbohri-cslt , I've created an internal issue to request an update to the [public *.proto files](https://github.com/googleapis/googleapis/blob/bd9393d6f6fc86c13f5763f16a9c7130b4ad4e8e/google/devtools/cloudbuild/v1/cloudbuild.proto#L1685) which are used to generate this client library. Googlers see b/306657626.

**Comment by mbohri-cslt** [comment]
Thanks !! @parthea

**Comment by parthea** [comment]
I'm going to close this issue as there is already an issue in the public issue tracker for the API: https://issuetracker.google.com/issues/307501897
