### ISSUE TITLE
transcribe_streaming_infinite.py does not support Cloud Speech-to-Text V2

### ISSUE THREAD

**Issue by dadaofeng** [googleapis/google-cloud-python#11856]
[transcribe_streaming_infinite.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/speech/microphone/transcribe_streaming_infinite.py) does not support Cloud Speech-to-Text V2 and cannot be used with V2.

The source code referenced from [this page (see the endless streaming tutorial)](https://cloud.google.com/speech-to-text/v2/quotas) is [this file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/speech/microphone/transcribe_streaming_infinite.py), but it is V1 code and cannot be used in V2.

Please let me know if there is already a page or file that can be referenced in V2.

**Comment by parthea** [comment]
Hi @dadaofeng, Thanks for reporting this issue. I've opened https://github.com/GoogleCloudPlatform/python-docs-samples/issues/10910 to track updating the sample code for `google-cloud-speech`
