### ISSUE TITLE
how to get the box of ocr text[0] Detect text in images detail api

### ISSUE THREAD

**Issue by cumthxy** [googleapis/google-cloud-python#11862]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

i use Detect text in images detail api.

 response = self.client.text_detection(image=image, timeout=10, retry = self.retry)
 texts = response.text_annotations
how to get the texts[0] box? 
the code ： 
for text in texts:
    allextractList.append(text.description) 
    vertices = (['({},{})'.format(vertex.x, vertex.y)
        for vertex in text.bounding_poly.vertices])

can only get each text box but can't get the text[0] box

**Comment by vchudnov-g** [comment]
Thanks for filing this issue!. We'll look into this and post updates.

Could you clarify what you mean by the following?
> can only get each text box but can't get the text[0] box

**Comment by vchudnov-g** [comment]
Closing this issue due to no response. Please feel free to re-open with the additional info.
