### ISSUE TITLE
method set_ labels from compute_v1.InstancesClient is not working

### ISSUE THREAD

**Issue by RubenGres** [googleapis/google-cloud-python#11872]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-compute/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Linux
  - Python version: `3.10.12`
  - pip version: `23.2.1`
  - `google-cloud-compute` version: `1.14.0`

#### Steps to reproduce

  1. Create a GCP instance
  2. Call the InstancesClient.set_labels method on your instance
  3. Notice error logs

#### Code example

```python
# Create a client
client = compute_v1.InstancesClient()

# Initialize request argument(s)
request = compute_v1.SetLabelsInstanceRequest(
    project=project_id,
    zone=zone,
    instance=instance.name,
)

# Make the request
response = client.set_labels(project=str(project_id),
    zone=str(zone),
    instance=str(instance.name))

# Handle the response
print(response)
```

#### Stack trace
```
URI: "/compute/v1/projects/{project}/zones/{zone}/instances/{instance}/setLabels"
Required request fields:
field: "project", pattern: "*"
field: "zone", pattern: "*"
field: "instance", pattern: "*"
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by parthea** [comment]
The `instances_set_labels_request_resource` argument which contains the `labels` also needs to be set
https://github.com/googleapis/google-cloud-python/blob/bf8e6573fdf2233d91dec050c462f42a95624c5f/packages/google-cloud-compute/google/cloud/compute_v1/services/instances/client.py#L6240-L6244


See working example here:
```
def set_labels(instances: list):
    for instance in instances:
        set_labels_request = compute_v1.InstancesSetLabelsRequest(label_fingerprint=instance.label_fingerprint, labels=labels)

        operation = instance_client.set_labels(
            project=project,
            zone=instance.zone.rsplit('/', maxsplit=1)[1],
            instance=instance.name,
            instances_set_labels_request_resource=set_labels_request
        )
        
        # wait for operation
        operation.result(timeout=60)
```

I'm going to close this issue as resolved but please feel free to open a new issue if you still encounter the error.
