### ISSUE TITLE
Support for Container.depends_on

### ISSUE THREAD

**Issue by petersalas** [googleapis/google-cloud-python#11871]
It looks like this library doesn't yet support setting container dependencies:

https://cloud.google.com/run/docs/reference/rpc/google.cloud.run.v2#container shows a `depends_on` field but it's absent from https://cloud.google.com/python/docs/reference/run/latest/google.cloud.run_v2.types.Container. (Setting it via annotation is not an option because system annotations are rejected.)

**Comment by parthea** [comment]
Closing as obsolete. This feature was added in version `0.10.0`

https://github.com/googleapis/google-cloud-python/blob/bf8e6573fdf2233d91dec050c462f42a95624c5f/packages/google-cloud-run/google/cloud/run_v2/types/k8s_min.py#L103-L105
