### ISSUE TITLE
[python-compute] Add option to run commands inside GCE instances

### ISSUE THREAD

**Issue by BDopke** [googleapis/google-cloud-python#11873]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
Right now this library does not support to run commands inside instances and the workaround for it is to run `gcloud compute ssh --command <command>` inside Python (for example with `subprocess` library).
 **Describe the solution you'd like**
I'd like to have command which connects to an instance (via SSH or RDP) and invokes a command.
 **Describe alternatives you've considered**
As mentioned above - right now I invoke `gcloud compute ssh` to get into an instance and then invoke a command like installing software.
 **Additional context**

**Comment by parthea** [comment]
Closing as a feature request was filed internally (b/286527703) for the API team.
