### ISSUE TITLE
Incorrect description of encoding types. Wrong link to webm container details.

### ISSUE THREAD

**Issue by npv256** [googleapis/google-cloud-python#11925]
<img width="695" alt="image" src="https://github.com/googleapis/python-speech/assets/23137115/7487315f-8a27-402b-8db8-526bb4502afc">

**Comment by parthea** [comment]
Googlers see cl/578806899

**Comment by parthea** [comment]
I'm going to close this issue as cl/578806899 was submitted and the issue was fixed at the source.
