### ISSUE TITLE
CloudBuild: 404 when polling build on specific location result

### ISSUE THREAD

**Issue by denis-ikomia** [googleapis/google-cloud-python#12123]
Hi,

When it build on a specific location using "parent" property on build request, i'm unable to get operation result, it raises a `NotFound: 404 Requested entity was not found.`

Here code snippet to reproduce error:
```python
>>> from google.cloud.devtools import cloudbuild_v1

>>> project_id="my_fancy_project"
>>> location = "europe-west-9"
>>> request = {
	"parent": f"projects/{project_id}/locations/{location}",
	"project_id": project_id,
        "build": {
        	# No matter what's here as build works
	}
}

>>> operation = cloudbuild_v1.CloudBuildClient().create_build(request=request)
>>> operation.result()
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.NOT_FOUND
        details = "Requested entity was not found."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.179.74:443 {created_time:"2023-12-14T14:10:24.305372763+01:00", grpc_status:5, grpc_message:"Requested entity was not found."}"
>
NotFound: 404 Requested entity was not found.
```

When i activate debug mode on gRPC, i can see a `HTTP:0:HDR:CLI:x-goog-request-params: location=europe-west9` when i create build, but not when i'm retrieving operation status.

If i hot patch my lib adding `grpc_metadata=list(metadata),` here https://github.com/googleapis/google-cloud-python/blob/main/packages/google-cloud-build/google/cloud/devtools/cloudbuild_v1/services/cloud_build/client.py#L810, all works as expected.

As i'm really new on google cloud and its python API, i don't known if i'm doing it the wrong way or if i find a bug ( and in this case, i'll do a pull request with pleasure).

Thanks for your reply !

**Comment by ohmayr** [comment]
I'm not able to replicate this issue on my end and `CloudBuildClient.create_build()` seems to be working as expected for me. 
   
Code snippet that works as expected:

```python3
from google.cloud.devtools import cloudbuild_v1
from google.api_core import client_options

project_id="<your_project_id>"
location = "europe-west9"
request = {
    "parent": f"projects/{project_id}/locations/{location}",
    "project_id": project_id,
    "build": {
        "steps": [
            cloudbuild_v1.BuildStep(
                name="ubuntu",
                entrypoint="bash",
                args=["-c", "echo Hello World!"]
            ),
        ]
    }
}

client_options = client_options.ClientOptions(
    api_endpoint="europe-west9-cloudbuild.googleapis.com"
)
operation = cloudbuild_v1.CloudBuildClient(client_options=client_options, transport="rest").create_build(request=request)
result = operation.result()
print(result)

```

A couple of things to note:

- Ensure that the specified location is correct and exists on the server. 
- Ensure that `client_options.api_endpoint` is specified since it's a required field in the case of private pools. 
   - The format for the endpoint is `api_endpoint: {location}-cloudbuild.googleapis.com`

**Comment by denis-ikomia** [comment]
Hi,

Thanks for your reply.

As you noticed, i missed the point about `api_endpoint` on documentation for non-global build.
Your code snippet works for me too.
