### ISSUE TITLE
Client/API to get daily amortized cost group by service in GCP 

### ISSUE THREAD

**Issue by KartikSareen18** [googleapis/google-cloud-python#12173]
Hi Team

Is there any python api/client to get daily amortized cost group by service in GCP? Can you pls help

**Comment by KartikSareen18** [comment]
Hi Team

Is there any info regarding above?

**Comment by ohmayr** [comment]
HI @KartikSareen18, can you please provide more information regarding what you're trying to achieve including the GCP service name (for which you're looking for a python client) that you're trying to use?

For reference, you can take a look at the following [packages](https://github.com/googleapis/google-cloud-python/tree/main/packages) for a list of packages supported by the google cloud python client.

**Comment by KartikSareen18** [comment]
Hi @ohmayr 
I want fetch daily cost of GCP services like compute, kubernetes etc. so is there any api/client to get daily cost of our billing account?

**Comment by ohmayr** [comment]
Hi @KartikSareen18, you can take a look at the [Billing API](https://cloud.google.com/billing/docs/resources) which provides estimated costs.

Kindly click on `Send feedback` on the API page directly and ask the product team if there's a way to fetch actual daily costs.

**Comment by parthea** [comment]
I'm going to close this issue as it was recommended to reach out via the [Cloud Billing API support page](https://cloud.google.com/support/billing) for API specific questions.
