### ISSUE TITLE
A module not found error in a python-selenium project

### ISSUE THREAD

**Issue by spoorthy24** [googleapis/google-cloud-python#12234]
### Discussed in https://github.com/googleapis/google-cloud-python/discussions/12233

<div type='discussions-op-text'>

<sup>Originally posted by **spoorthy24** January 31, 2024</sup>
I am actually new to this, I was assigned to do a selenium project where there's already a bunch of code written i need to run and test it out. But when i run i keep getting this error. I have given the code and the error below! can any one help me with it.

```
import unittest
from common.common import minutes_seconds, cleanup_screenshots
from common.selenium_wrappers import *
import HTMLTestRunner
from Email import *
from Email import send_email
import common.global_vars
from common.common import *
import sys
import common.common`
```
```
Error ::
from common.common import minutes_seconds, cleanup_screenshots
  File "c:\Users\admin\OneDrive\Documents\Insights\common\common.py", line 16, in <module>
    import global_vars
ModuleNotFoundError: No module named 'global_vars'
```

directory:
![image](https://github.com/googleapis/google-cloud-python/assets/54950730/220a72ee-a4d7-4099-be0d-a64390a687b8)

</div>

**Comment by parthea** [comment]
Hi @spoorthy24,

This issue tracker is for questions or help related to the packages in [this directory ](https://github.com/googleapis/google-cloud-python/tree/main/packages). For other packages, you'll need to locate the corresponding issue tracker or post the question on [stackoverflow](https://stackoverflow.com/questions/tagged/python).

If you still have a question about one of the packages in this repository, please feel free to open a new issue.

**Comment by spoorthy24** [comment]
I'll post if I have different issue related to the package in the directory. Thanks
