### ISSUE TITLE
SecretManagerServiceClient: missing staticmethod decorators on two methods

### ISSUE THREAD

**Issue by Salvo-kun** [googleapis/google-cloud-python#12255]
The methods are:

- _get_client_cert_source
- _get_api_endpoint

It is mainly a matter of consistency but also to avoid eventual accesses through self.

**Comment by parthea** [comment]
Thanks for reporting this issue. It was included in https://github.com/googleapis/gapic-generator-python/pull/1923 and the fix was added to this repository via https://github.com/googleapis/google-cloud-python/pull/12266.
