### ISSUE TITLE
Cyclical bug report guidance on secrets-manager client

### ISSUE THREAD

**Issue by kojiromike** [googleapis/google-cloud-python#12363]
The template says:

> **NOTE**: [Google Cloud Python](https://cloud.google.com/python/docs/reference) client libraries are no longer maintained inside this repository. Please visit the python-API repository (e.g., https://github.com/googleapis/python-pubsub/issues) for faster response times.

But https://github.com/googleapis/python-secret-manager is archived and points back here.

Also
> See all published libraries in the [README](https://github.com/googleapis/google-cloud-python/blob/main/README.rst).

but google-cloud-secret-manager is not listed in that readme at all.

Yet, it's [here](https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-secret-manager).

So, what is the correct way to report an issue on the python client for google-cloud-secret-manager?

**Comment by parthea** [comment]
Closing as obsolete as the issue templates have been updated.
