### ISSUE TITLE
ImportError: No module named oauth2client

### ISSUE THREAD

**Issue by cnbuff410** [googleapis/google-cloud-python#124]
Do we have to install "google-api-python-client" library to use this or it will be self-contained library in the future? Currently I have to manually download oauth2client python library from "https://code.google.com/p/google-api-python-client/" in order to properly use gcloud-python.

**Comment by andreadale** [comment]
TRY THIS:
pip install --upgrade oauth2client

**Comment by gennopp** [comment]
In virtual environment it will not work, unfortunately it is working outside of it. Try installing through 
pip install --upgrade oauth2client.

**Comment by naeemakram** [comment]
updating the oauth2client worked for me...

**Comment by rahulbhat44** [comment]
Run this 

sudo python -m pip install oauth2client

**Comment by sirius0503** [comment]
> In virtual environment it will not work, unfortunately it is working outside of it. Try installing through
> pip install --upgrade oauth2client.

Can somebody explain why it doesn't work with the virtualenvironments? It should work right, since I am installing oauth2client from pip in the virtualenvs packages and it shows in pip list , when I have the virtual environment activated.
