### ISSUE TITLE
discoveryenginev1: error on request above 100 gcsSource.inputUris

### ISSUE THREAD

**Issue by Sponge96** [googleapis/google-cloud-python#12458]
Not familiar enough with the codebase to report this as a bug. I'm trying to batch import documents to a dataset using the following code.
```
            request = discoveryengine_v1.ImportDocumentsRequest(
                parent=parent,
                gcs_source=discoveryengine_v1.GcsSource(
                    data_schema="content",
                    input_uris=batch,
                ),
                reconciliation_mode=discoveryengine_v1.ImportDocumentsRequest.ReconciliationMode.INCREMENTAL,
            )
            operation = client.import_documents(request=request)
            operation_status = operation.result()

```
I'm getting the following error:

> 400 At most 100 values are allowed in "gcsSource.inputUris", but 100000 values found.

Although in the documentation it states the following about the `GcsSource` class: 

> A request can contain at most 100 files (or 100,000 files if data_schema is content).

I'm able to use this code to upload only if I split the `batch` into 100 path chunks (which for the amount of data is rather slow).
I'm using the following endpoint: `discoveryengine.googleapis.com/v1/` and the `DocumentServiceClient`. 

Any help/guidance is appreciated.

**Comment by ohmayr** [comment]
@Sponge96  thanks for reporting this issue.

As per the [documentation](https://cloud.google.com/generative-ai-app-builder/docs/reference/rest/v1beta/GcsSource):

```
InputUris[]: A request can contain at most 100 files (or 100,000 files if dataSchema is content). 
             Each file can be up to 2 GB (or 100 MB if dataSchema is content).
```

Please ensure that if `data_schema="content"`, then files <= 100,000 and file_size <= 100MB.

If the above is true and you're able to reproduce this issue via a `REST` call / curl command, then please directly report this to the Vertex AI Search team by submitting feedback here: https://cloud.google.com/generative-ai-app-builder/docs/reference/rest/v1beta/GcsSource.

**Comment by ohmayr** [comment]
Closing this issue as per the previous comment directing the user to report it directly to the Vertex AI Search team.

**Comment by SaymV** [comment]
Still hitting this 100 vs 100,000 error in 2025. with `data_schema` set to `content` the API still rejects requests with more than 100 URIs
