### ISSUE TITLE
How to get the credits information from google apis which is available in the Billing page native google cloud console?

### ISSUE THREAD

**Issue by Venkatesh-Heeddata** [googleapis/google-cloud-python#12623]
@parthea 
I am requesting you to provide the information to get the credits information of that billing GCP account. 
please provide the google APIs classes or any public API to get that data accurately by using python as a programming language.

**Comment by ohmayr** [comment]
@Venkatesh-Heeddata Kindly reach out to the Cloud Billing API support team by clicking on submit feedback [here](https://cloud.google.com/billing/docs/reference/rest). They should be able to assist you with whether this is supported by the Billing API.
