### ISSUE TITLE
IAM Documentation Typo/Feature Request

### ISSUE THREAD

**Issue by WebbinRoot** [googleapis/google-cloud-python#12662]
Greetings. It looks like some of the markdown might be malformed here for "parent": https://cloud.google.com/python/docs/reference/iam/latest/google.cloud.iam_admin_v1.types.ListRolesRequest
![image](https://github.com/googleapis/google-cloud-python/assets/74038921/5882f460-da4c-47ce-b065-f3aadb753914)

Is there a way to filter the list of roles returned to just custom roles? Because all the official predefined roles already have documentation/are documented, it make sense to only list the custom roles to review the IAM permissions, but there did not seem to be that type of filter in the documentation? Would that be a feature request?

**Comment by ohmayr** [comment]
Hey @WebbinRoot, For any API-specific questions or feature requests, please file an new issue by clicking on `Create new IAM issue` in [here](https://cloud.google.com/support/docs/issue-trackers).

Feel free to file a new ticket if you have any questions related to the client libraries.

**Comment by ohmayr** [comment]
Closing this issue as per previous comment. Please file a new issue if needed.
