### ISSUE TITLE
update dependencies to protobuf=">=4.21.0"

### ISSUE THREAD

**Issue by eljalalpour** [googleapis/google-cloud-python#12690]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**NOTE**: [Google Cloud Python](https://cloud.google.com/python/docs/reference) client libraries are no longer maintained inside this repository. Please visit the python-API repository (e.g., https://github.com/googleapis/python-pubsub/issues) for faster response times.

See all published libraries in the [README](https://github.com/googleapis/google-cloud-python/blob/main/README.rst).

**Comment by vchudnov-g** [comment]
We are working on supporting newer versions of protobuf.

In the meantime, could you help us understand the problem you're facing? Is it a matter of the client libraries being the only blocker to you updating?

**Comment by parthea** [comment]
Closing as duplicates of https://github.com/googleapis/google-cloud-python/issues/11437 and https://github.com/googleapis/google-cloud-python/issues/12621. If these are not duplicates, please open a new issue with more information.
