### ISSUE TITLE
How to use GA4 "Audience Export Dimensions"

### ISSUE THREAD

**Issue by AkshatSoni26** [googleapis/google-cloud-python#12802]
### Determine this is the right repository

- [X] I determined this is the correct repository in which to report this feature request.

### Summary of the feature request

How to use GA4 `Audience Export Dimensions`. So take a data for a particular user by giving userId.

### Desired code experience

file: main.py
```python
from google.analytics.data_v1beta import BetaAnalyticsDataClient
from google.analytics.data_v1beta.types import (
    DateRange,
    Dimension,
    Metric,
    RunReportRequest,
    AudienceDimension,
    AudienceExport
)
import pandas as pd


def sample_run_report(property_id=GA4_PROPERTY_ID):
    property_id = GA4_PROPERTY_ID

    client = BetaAnalyticsDataClient()

    request = RunReportRequest(
        property=f"properties/{property_id}",
        dimensions=[Dimension(name='city'), Dimension(name='country'), AudienceDimension(name="userId")],
        metrics=[Metric(name="activeUsers"), Metric(name='userKeyEventRate'), Metric(name='screenPageViews')],
        date_ranges=[DateRange(start_date="2020-03-31", end_date="today")],
    )
    
    response = client.run_report(request)

    data = {'city': [], 'country': [], 'activeUsers': [], 'userKeyEventRate': [], 'screenPageViews':[]}

    for row in response.rows:
        data['city'].append(row.dimension_values[0].value)
        data['country'].append(row.dimension_values[1].value)
        data['activeUsers'].append(row.metric_values[0].value)
        data['userKeyEventRate'].append(row.metric_values[1].value)
        data['screenPageViews'].append(row.metric_values[2].value)


    df = pd.DataFrame(data=data)

    print(df.head(30))

```

<any additional py files>

### Expected results

got the user data.

### API client name and version

google-analytics-data

**Comment by parthea** [comment]
As mentioned in the [Audience Export Dimensions](https://developers.google.com/analytics/devguides/reporting/data/v1/audience-export-api-schema), use the [Audience Export methods](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties.audienceExports/create). Specifically [these methods](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties.audienceExports). You can use the `Try this method` on [this page](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties.audienceExports/create) to experiment with the API. 

You can find similar methods in the python client library here:
https://github.com/googleapis/google-cloud-python/blob/9d1c3e78e56b04a838494bbaea703500ff1e8438/packages/google-analytics-data/google/analytics/data_v1beta/services/beta_analytics_data/client.py#L1363


I'm going to close this issue but please feel free to open a new issue with more information.

**Comment by jamvaz123** [comment]
Hello Guys,
I tried your code as is (passing in my own property_id) I get error with AudienceDimension(name="userId")  Error: ValueError unknown field for AudienceDimension: name

Am I missing something? 
The code works without AudienceDimension , however for my project it would be very interesting to include AudienceDimension(name="userId").
Any insight for me.
Cheers
James

**Comment by AkshatSoni26** [comment]
hey  @jamvaz123 , in this first of all you need to create  audience_export which make audience and give ids

> 
`def create_audience_export(property_id=GA4_PROPERTY_ID, audience_id=None):

    client = AnalyticsAdminServiceClient(credentials=credentials)
    parent = f"properties/{property_id}"

    audience_exports = client.list_audiences(parent=parent)

    for export in audience_exports:
        print(f"Name: {export.name}")
        print(f"Audience Export ID: {export.name.split('/')[-1]}")
        print(f"Display Name: {export.display_name}")
        print("---")

    return audience_exports
`

then after getting **audience_export_id** you need to give audience_dimensions in this way.
`def get_user_data():
    # Create a client
    client = BetaAnalyticsDataClient(credentials=credentials)

    # Initialize request argument(s)
    audience_export = AudienceExport(
        dimensions=[AudienceDimension(dimension_name="userId")],
        # metrics=[Metric(name="activeUsers")],
        # date_ranges=[DateRange(start_date="2020-09-01", end_date="2020-09-15")],
    )
    audience_export.audience = f"properties/{GA4_PROPERTY_ID}/audiences/{audiences_id}"

    request = CreateAudienceExportRequest(
            parent=f"properties/{GA4_PROPERTY_ID}",
            audience_export=audience_export,
        )

    # Make the request
    operation = client.create_audience_export(request=request)

    print("Waiting for operation to complete...")`


it returns the result to you.

**Comment by jamvaz123** [comment]
Hello Sir
Thank you for your reply, I did try your code here are my results:
•	The **def create_audience_export(property_id=GA4_PROPERTY_ID, audience_id=None)**: functions work well, I can loop through all of my audiences and get Audience Export ID, thank you for this part.
•	When I give this value (Audience Export ID) to the **def get_user_data():** I am assuming the line operation = client.create_audience_export(request=request), the “operation” is the response, correct?
•	How do I use the “operation” object to list for me the UserId contained inside. Or did I miss something in your example.
Any help would be greatly appreciated.

Cheers
James
