### ISSUE TITLE
Add location parameters to TagBindingsClient. 

### ISSUE THREAD

**Issue by matheuslima-google** [googleapis/google-cloud-python#12849]
https://github.com/googleapis/google-cloud-python/blob/74154b11d201cb1bfa4874f6a90debd7fe931e53/packages/google-cloud-resource-manager/google/cloud/resourcemanager_v3/services/tag_bindings/client.py#L137

Hi team -

im trying to use the TagBindingsClient method to link a Tag for some GCE instance. The resource is zonal. Is there a way to set the location as a parameter? I see variable DEFAULT_ENDPOINT is hardcoded.

Done a simple workaround like this on line 134 to temporarily fix this:

From
    DEFAULT_ENDPOINT = "loudresourcemanager.googleapis.com"
Change to
    DEFAULT_ENDPOINT = "southamerica-east1-b-cloudresourcemanager.googleapis.com"

Reading the API doc, LOCATION should be an variable:

https://cloud.google.com/compute/docs/tag-resources#api

This is the error message before the workaround:

google.api_core.exceptions.InvalidArgument: 400 field [binding.resource] has issue [Must be a valid One Platform resource name of a tag-compatible global resource. Did you forget to specify the correct location?] [field_violations {
  field: "binding.resource"
  description: "Must be a valid One Platform resource name of a tag-compatible global resource. Did you forget to specify the correct location?"
}

I can submit a PR but want to check if my understand of the situation is correct.

Thank you
Regards

**Comment by ohmayr** [comment]
Hi @matheuslima-google, thanks for reaching out! You can override the api endpoint by configuring `client_options.api_endpoint` parameter and passing it to the client in the following way:


```python3

from google.api_core import client_options

opts = client_options.ClientOptions(api_endpoint="southamerica-east1-b-cloudresourcemanager.googleapis.com")
client = TagBindingsClient(client_options=opts)

```

Feel free to reach out if you have any further questions!

**Comment by parthea** [comment]
I'm going to close this issue as a response was provided but please feel free to open a new issue with more information.
