### ISSUE TITLE
A

### ISSUE THREAD

**Issue by AtufaShireen** [googleapis/google-cloud-python#12899]
### Determine this is the right repository

- [X] I determined this is the correct repository in which to report this feature request.

### Summary of the feature request

I would like to easily be able to create the default event handlers like sys.no-match1, webhook.error by simply using an abstract class.

### API client name and version

google-cloud-dialogflow-cx

**Comment by parthea** [comment]
Hi @AtufaShireen,

Would you be willing to fill out the entire template at https://github.com/googleapis/google-cloud-python/issues/new?assignees=&labels=type%3A+feature+request%2Ctriage+me&projects=&template=feature_request.yaml ? For example, please share the code that you're currently using, and what the desired experience would be.

**Comment by parthea** [comment]
I'm going to close this issue as I don't have sufficient information to create the feature request. Please file a new feature request with more information.
