### ISSUE TITLE
call_function method for Functions V2

### ISSUE THREAD

**Issue by WebbinRoot** [googleapis/google-cloud-python#12980]
### Determine this is the right repository

- [X] I determined this is the correct repository in which to report this feature request.

### Summary of the feature request

call_function only exists for functions V1 (https://cloud.google.com/python/docs/reference/cloudfunctions/latest/google.cloud.functions_v1.services.cloud_functions_service.CloudFunctionsServiceClient#google_cloud_functions_v1_services_cloud_functions_service_CloudFunctionsServiceClient_call_function). It would be nice if the SDK supported functions v2 calls. At the moment i have to do this manually via REST API calls, so seems like it could be encapsulated in an API call. Not sure on the progress for this but just filing this feature request

### Desired code experience

```
try:
            grant_type = "refresh_token"
            if "token_uri" in auth_json.keys():
                token_uri = auth_json["token_uri"]
            if "client_id" in auth_json.keys():
                client_id = auth_json["client_id"]
            if "client_secret" in auth_json.keys():
                client_secret = auth_json["client_secret"]
            if "refresh_token" in auth_json.keys():
                refresh_token = auth_json["refresh_token"]

            if not (token_uri and client_id and client_secret and refresh_token):
                print(fail_string)
                return -1

            else:

                arguments = {
                    "grant_type":grant_type,
                    "client_id":client_id,
                    "client_secret":client_secret,
                    "refresh_token":refresh_token
                }

                headers = {
                    "Content-Type": "application/x-www-form-urlencoded"
                }
                
                response = requests.post(token_uri, data=arguments, headers=headers)

                if response.status_code == 200:

                    response_json = json.loads(response.text)
                    if "id_token" in response_json.keys():
                        identity_token = response_json["id_token"]
                    else:
                        print(fail_string)
                        return -1
                
                    simple_name = function_name.split("/")[5]
                    region = function_name.split("/")[3]
                    project = function_name.split("/")[1]


                    url = f"https://{region}-{project}.cloudfunctions.net/{simple_name}"
                    
                    headers = {
                        'Authorization': f'bearer {identity_token}',
                        'Content-Type': 'application/json'
                    }

                    data = {
                        "name": "Hello World"
                    }

                    response = requests.post(url, headers=headers, data=json.dumps(data), timeout=70)
                    response_data = response.text
```

### Expected results

Like the V1 function, it would be nice to be able to just do
```
            request = functions_v1.CallFunctionRequest(
                name=function_name,
                data="test"
            )
            response = function_client_v1.call_function(request=request)
            # Handle the response
            response_data = response.result
```

### API client name and version

google-cloud-functions

**Comment by parthea** [comment]
Hi @WebbinRoot ,

Please see https://issuetracker.google.com/issues/278353662#comment4 where the feature request was closed in the API specific issue tracker with the following comment:

> The CallFunction rpc will not be added to the V2 API anytime soon, users can follow https://cloud.google.com/functions/docs/create-deploy-gcloud#triggering_the_function to test their 2nd gen functions after deployment.

If you have additional questions about the missing rpc or would like to follow up on the feature request, please create a new issue in the API specific issue tracker for the Cloud Functions API [here](https://issuetracker.google.com/issues/new?component=187195&template=0)
