### ISSUE TITLE
notebook version 2 instance state change has no STOPPING being reported based on expected behaviour

### ISSUE THREAD

**Issue by NithinMathewJosephAston** [googleapis/google-cloud-python#13164]
### Determine this is the right repository

- [X] I determined this is the correct repository in which to report this bug.

### Summary of the issue

**Context**
_The expected behaviour for state changes observed in Google Notebook version 1 should be replicated when running an instance in version 2. But that isn't being mimicked. The API version 1 was used previously for the setup and I see that the documentation still states that this behaviour will be prevalent in version 2 as well:_ https://cloud.google.com/python/docs/reference/notebooks/latest/google.cloud.notebooks_v2.types.State?hl=en

_Since the version 1 is getting depreciated the code is getting transitioned to version 2. But the behaviour change has caused a portion of our tool to break._

**Expected Behaviour:**
_State change expected for the instance is in this sequence:_ STARTING --> PROVISIONING --> ACTIVE --> STOPPING --> STOPPED

**Actual Behavior:**
_State change observed for the instance is in this sequence:_ STARTING --> PROVISIONING --> ACTIVE --> STOPPED

### API client name and version

google-cloud-notebooks 1.10.5

### Reproduction steps: code

**Assumption:** The instance is already running. The state print happens in a different process that polls the status of the instance every 10 seconds.

This portion is to **stop the running instance**
```python
NOTEBOOK_NAME =  f"projects/{project}/locations/{location}/instances/{name}"
credentials = service_account.Credentials.from_service_account_file(SERVICE_ACCOUNT_JSON)
client = notebook_v2.NotebookServiceAsyncClient(credentials=credentials)
request = notebook_v2.StopInstanceRequest(name=NOTEBOOK_NAME)
operation = client.stop_instance(request=request)
response = (await operation)
result = await response.result()
```

This portion of the code is used to **get the state of the instance** and is run at intervals while waiting for the instance to fully stop.
```python
NOTEBOOK_NAME =  f"projects/{project}/locations/{location}/instances/{name}"
credentials = service_account.Credentials.from_service_account_file(SERVICE_ACCOUNT_JSON)
client = notebook_v2.NotebookServiceClient(credentials=credentials)
request = notebook_v2.GetInstanceRequest(name=NOTEBOOK_NAME)
instance = client.get_instance(request=request)
print(instance.state.name)
```

Provided crumbs for debugging purposes.

### Reproduction steps: supporting files

file: mydata.csv
```
alpha,1,3
beta,2,5
```

<any additional supporting files>

### Reproduction steps: actual results

Output:
```
ACTIVE
ACTIVE
ACTIVE
ACTIVE
ACTIVE
STOPPED
```

### Reproduction steps: expected results

Output:
```
ACTIVE
STOPPING
STOPPING
STOPPING
STOPPING
STOPPED
```

### OS & version + platform

macOS Sonoma 14.7  + VScode

### Python environment

3.12.6

### Python dependencies

Package                  Version
------------------------ ---------
annotated-types          0.7.0
anyio                    4.6.0
cachetools               5.5.0
certifi                  2024.8.30
cffi                     1.17.1
charset-normalizer       3.3.2
click                    8.1.7
cryptography             43.0.1
ecdsa                    0.19.0
fastapi                  0.115.0
google-api-core          2.20.0
google-auth              2.35.0
google-cloud-compute     1.19.2
google-cloud-notebooks   1.10.5
googleapis-common-protos 1.65.0
grpc-google-iam-v1       0.13.1
grpcio                   1.66.1
grpcio-status            1.66.1
h11                      0.14.0
httptools                0.6.1
idna                     3.10
ldap3                    2.9.1
pip                      24.2
proto-plus               1.24.0
protobuf                 5.28.2
pyasn1                   0.6.1
pyasn1_modules           0.4.1
pycparser                2.22
pydantic                 2.9.2
pydantic_core            2.23.4
python-dotenv            1.0.1
python-jose              3.3.0
python-multipart         0.0.10
PyYAML                   6.0.2
requests                 2.32.3
rsa                      4.9
six                      1.16.0
sniffio                  1.3.1
starlette                0.38.6
typing_extensions        4.12.2
urllib3                  2.2.3
uvicorn                  0.30.6
uvloop                   0.20.0
watchfiles               0.24.0
websockets               13.1

**Comment by vchudnov-g** [comment]
Thanks for reporting this!

It sounds like this might be more of a server issue than a client library issue. I see we don't have the service team contact info listed on the [README](https://github.com/googleapis/google-cloud-python/blob/main/README.rst) (something else we're working on), so we'll locate and contact the service team.

**Comment by parthea** [comment]
Hi @NithinMathewJosephAston,

Regrettably for questions/bugs specific to the behavior of the API (i.e. responses from the API) rather than the client library, I need to redirect you to the API support channel so you can get better quality answers.

Please use the [public issue tracker here](https://issuetracker.google.com/issues/new?component=1392625) to communicate directly with the Notebooks API team.   The link to the public documentation for the `Notebooks` API lives here: https://cloud.google.com/vertex-ai/docs/workbench/instances/introduction . On this page, there are additional resources to get API specific support. For support, see https://cloud.google.com/vertex-ai/docs/support/getting-support.

I'm going to close this issue but please feel free to open a new issue if you encounter any bugs specific to the client library, rather than the API, or if you would like to request features for the client library.
