### ISSUE TITLE
Add Documentation of google-ai-generativelanguage in its pypi release

### ISSUE THREAD

**Issue by EiPiFun** [googleapis/google-cloud-python#13168]
### Determine this is the right repository

- [X] I determined this is the correct repository in which to report this feature request.

### Summary of the feature request

Add Documentation of google-ai-generativelanguage in its pypi release

When I try to package google-ai-generativelanguage, one reviewer told me that your pypi release lacks docs.
And its GitHub release lacks setup.py or pyproject.toml.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1085071

I suggest you to add docs for it and add a link in README, thanks.

### Desired code experience

Add Documentation of google-ai-generativelanguage in its pypi release

### Expected results

Add Documentation of google-ai-generativelanguage in its pypi release

### API client name and version

google-ai-generativelanguage v0.6.10

**Comment by parthea** [comment]
There is a link to the public documentation in the README. The link is titled `Client Library Documentation` and points to https://googleapis.dev/python/generativelanguage/latest . Alternatively, `nox -s docs` can be used to generate the html docs locally which is mentioned [here](https://github.com/googleapis/google-cloud-python/blob/main/packages/google-ai-generativelanguage/CONTRIBUTING.rst#id8). 

The `setup.py` file exists in the release under `packages/google-ai-generativelanguage/setup.py`. I'm going to close this issue but please feel free to open a new issue if you have additional questions.
