### ISSUE TITLE
How to store BigQuery schemas for later use.

### ISSUE THREAD

**Issue by tweeter0830** [googleapis/google-cloud-python#3419]
Is there an easy way to get the schema from a BigQuery table and save it to disk for later use?

For example, say that I wanted to get the schema of a table that currently exists, save it to disk and later create a table with the same schema.

I see that there is such a thing as a SchemaField in the api, but there doesn't seem to be a clean way to serialize it.

**Comment by tseaver** [comment]
@tweeter0830 There is no built-in support for serializing `SchemaField` instances.  The non-public `table._build_schema_resource` and `table._parse_schema_resource` functions could be used as the basis for serializing them to JSON.

**Comment by tweeter0830** [comment]
Thanks.

**Comment by tseaver** [comment]
I'll leave the issue open, as making those two functions public / better documented seems like a reasonable enhancement.

**Comment by tseaver** [comment]
E.g., I could see adding a `schema.SchemaField.from_api_repr` classmethod and a corresponding `schema.SchemaField.to_api_repr` instance method to support your usecase.

**Comment by tseaver** [comment]
#3796 doesn't fix this issue.

**Comment by lukesneeringer** [comment]
Why? As soon as it is a dictionary, saving it to disk is trivial (`json.dump`).

**Comment by tseaver** [comment]
The goal of this issue is to store the *entire* schema for a table (not a single field) and in a format which is "good" for people (i.e., with the appropriate top-level mapping / key holding that list).

**Comment by yiga2** [comment]
Similar use case. I have the JSON schema files in GCS already for all tables. `bq load` CLI supports JSON schema but Python Client lib not (0.29).
Next to a getter method,  `LoadJobConfig.schema.save`, there should be a `LoadJobConfig.schema.load` method too that takes a URL has parameter (gs:// or local).
That would be consistent with CLI and other languages - Java lib has a `setSchema`

**Comment by chemelnucfin** [comment]
Hello, feature requests will now be tracked in the project [Feature Requests](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/5#card-6867160).  I will close this issue now, please feel free to continue to address any issues/concerns here.

**Comment by tswast** [comment]
*Background*

With the BigQuery command-line tool, it's possible to specify a schema via a JSON file. See: https://cloud.google.com/bigquery/docs/schemas#using_a_json_schema_file

Schema format:

```
[
  {
    "description": "quarter",
    "mode": "REQUIRED",
    "name": "qtr",
    "type": "STRING"
  },
  {
    "description": "sales representative",
    "mode": "NULLABLE",
    "name": "rep",
    "type": "STRING"
  },
  {
    "description": "total sales",
    "mode": "NULLABLE",
    "name": "sales",
    "type": "FLOAT"
  }
]
```

*Phase 1*

This feature request is to add a helper function that can load such files and return a list of [SchemaField](https://googleapis.github.io/google-cloud-python/latest/bigquery/generated/google.cloud.bigquery.schema.SchemaField.html#google.cloud.bigquery.schema.SchemaField) objects.

```
# file_or_path = "path/to/schema.json"
# OR
# file_or_path = open("path/to/schema.json")

schema_fields = client.schema_from_json(file_or_path)

# Now the value of schema_fields is
# schema_fields = [
#      schema.SchemaField(...),
#      schema.SchemaField(...),
#      schema.SchemaField(...),
# ]
```

*Phase 2*

Blocked by https://github.com/googleapis/google-cloud-python/issues/7693

`client.schema_from_json` should accept GCS paths like `file_or_path = "gs://bucket_name/path/to/schema.json"`.

This (optional) feature only works if a `storage_client` argument is passed in as an additional argument.

```
schema_fields = client.schema_from_json(file_or_path, storage_client=storage_client)
```

**Comment by tswast** [comment]
cc @lbristol88

**Comment by yiga2** [comment]
@tswast  could you make `schema_from_json` accept a string too ? 

We have the schema in gcs but need to touch it a bit before using in bigquery.
This would avoid saving it locally just to use that new function.

FYI, we do this today: `  job_config._properties['load']['schema'] = schema_json`

**Comment by tswast** [comment]
In the case of in-memory JSON, I'd prefer you pass in a file-like object, i.e.

```
json.load(io.BytesIO(b'[{"name": "col1", "type": "INTEGER"}]'))
```

Otherwise it gets a little tricky to disambiguate a path from file contents.

**Comment by yiga2** [comment]
Makes sense.

**Comment by tswast** [comment]
Fixed by https://github.com/googleapis/google-cloud-python/pull/9550 (allow passing JSON version of schema directly to schema setters) and https://github.com/googleapis/google-cloud-python/pull/7761 (adds `schema_from_json` and `schema_to_json` helpers).

Closing despite missing GCS integration, as that wasn't in the original request.
