### ISSUE TITLE
Missing system tests after pubsub redesign

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python#4031]
The redesign effort (#3859) left behind only very minimal system tests.  The older implementation had much broader system test coverage:

- Listing topics and subscriptions in the client's project.
- Creating subscriptions with non-default settings.
- Listing subscriptions bound to a topic.
- Setting / getting IAM policy for topics and subscriptions
- Creating / seeking snapshots.

I noticed the missing tests today when I went looking for examples of updating a topic's IAM policy.

**Comment by danoscarmike** [comment]
@tseaver could you please update the status of this?  Have new tests been added?  What is current coverage of the tests you enumerated here?

**Comment by jonparrott** [comment]
The [samples](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/pubsub/cloud-client) are likely a good starting place for system tests.

I mean, if anyone wants to take on moving the samples wholesale here I'd be cool with that.

**Comment by dhermes** [comment]
@danoscarmike No new tests have been added or are planned to be added.

As I identified bugs I made reproducible cases at https://github.com/dhermes/google-cloud-pubsub-performance and some of them may be worth turning into tests, but they run for too long to make that feasible.

> What is current coverage of the tests you enumerated here?

Can you be more specific? Do you mean line coverage?

**Comment by danoscarmike** [comment]
> Can you be more specific? Do you mean line coverage?

I meant which of the following points (per original issue post) have tests?

> Listing topics and subscriptions in the client's project.
> Creating subscriptions with non-default settings.
> Listing subscriptions bound to a topic.
> Setting / getting IAM policy for topics and subscriptions
> Creating / seeking snapshot

If we are satisfied that behavior and performance are tested (one way or another) can we close this issue?

**Comment by tseaver** [comment]
I would say we should *not* close the issue until we have added those system tests:  we can mark it as non-release-blocking, but the fact that we are missing tests which exercise what should be important use cases against the back-end should not be swept under the carpet.

**Comment by danoscarmike** [comment]
Fair.  Thanks Tres.

**Comment by lukesneeringer** [comment]
Reverting this to P2 (in a triage meeting) on the basis that:

  * These are auto-generated methods.
  * We have sample tests (unfortunately in a different repo).

**Comment by tseaver** [comment]
If the `triaged for GA` label means that we judge this issue not a blocker for the GA release, I'd like to re-litigate that choice.  ISTM that releasing this library as GA *without* good system test coverage would be a mistake.

The notion that "generated methods, no worries" is clearly wrong:  the generator has bugs, too.

Having the snippets maintained elsewhere give *us* no visibility to any regressions which occur.  If they are our canaries in the mine for the broader surface, then they should be maintained here, and run as part of our CI.
