### ISSUE TITLE
Exception: Request failed. Error was: Backend Error

### ISSUE THREAD

**Issue by pdknsk** [googleapis/google-cloud-python#470]
I'm getting this error for every request, get or put. I don't know why. The API console only knows this.

| Methods | Error codes |
| --- | --- |
| datastore.datasets.commit | 500 |
| datastore.datasets.lookup | 500 |

**Comment by pdknsk** [comment]
What adds to the confusion is yet another [gcloud](https://github.com/GoogleCloudPlatform/gcloud), which is really gcloud-cli-go from what I can tell.

To reproduce this bug, disable a project in Application Settings in the old [Appengine Dashboard](https://appengine.google.com). This function does not seem to be available in the new Cloud Console. Run the [steps] (https://cloud.google.com/datastore/docs/activate#accessing_an_existing_app_engine_datastore_from_another_platform) to access a Datastore tied to an Appengine project, in particular the Wizard to enable the API.

```Python
from gcloud import datastore
a = datastore.get_dataset('app-id', '@developer.gserviceaccount.com', 'path/key')

a.entity('item').save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python2.7/site-packages/gcloud/datastore/entity.py", line 244, in save
    exclude_from_indexes=self.exclude_from_indexes())
  File "/home/user/.local/lib/python2.7/site-packages/gcloud/datastore/connection.py", line 425, in save_entity
    result = self.commit(dataset_id, mutation)
  File "/home/user/.local/lib/python2.7/site-packages/gcloud/datastore/connection.py", line 329, in commit
    datastore_pb.CommitResponse)
  File "/home/user/.local/lib/python2.7/site-packages/gcloud/datastore/connection.py", line 81, in _rpc
    data=request_pb.SerializeToString())
  File "/home/user/.local/lib/python2.7/site-packages/gcloud/datastore/connection.py", line 59, in _request
    raise Exception('Request failed. Error was: %s' % content)
Exception: Request failed. Error was: Backend Error

# project re-enabled
a.entity('item').save()
<Entity[{'kind': u'item', 'id': 5649391675244544L}] {}>
```

**Comment by dhermes** [comment]
Thanks for giving me a way to replicate @pdknsk.

I added a debug statement before the error is [raised][1] and actually printed the body and headers of the response.

------

With writes disabled, but the app still enabled I got
```
('The API call datastore_v4.Commit() is temporarily unavailable: Datastore '
 'writes have been disabled by an application administrator. Writes can be '
 're-enabled in the admin console.')
# Word-wrapping by me

{
  "status": "403",
  "alternate-protocol": "443:quic,p=0.02",
  "content-length": "178",
  "x-xss-protection": "1; mode=block",
  "x-content-type-options": "nosniff",
  "transfer-encoding": "chunked",
  "expires": "Fri, 02 Jan 2015 18:28:40 GMT",
  "vary": "Origin, X-Origin",
  "server": "GSE",
  "-content-encoding": "gzip",
  "cache-control": "private, max-age=0",
  "date": "Fri, 02 Jan 2015 18:28:40 GMT",
  "x-frame-options": "SAMEORIGIN",
  "content-type": "text/html; charset=UTF-8"
}
```

------

With the app disabled (as @pdknsk suggests) I got
```
'Backend Error'

{
  "status": "503",
  "alternate-protocol": "443:quic,p=0.02",
  "content-length": "13",
  "x-xss-protection": "1; mode=block",
  "x-content-type-options": "nosniff",
  "transfer-encoding": "chunked",
  "expires": "Fri, 02 Jan 2015 18:31:42 GMT",
  "vary": "Origin, X-Origin",
  "server": "GSE",
  "-content-encoding": "gzip",
  "cache-control": "private, max-age=0",
  "date": "Fri, 02 Jan 2015 18:31:42 GMT",
  "x-frame-options": "SAMEORIGIN",
  "content-type": "text/html; charset=UTF-8"
}
```

------

Do you think we should also print the status code? Here the information was `403 Forbidden` when writes aren't allowed vs. `503 Service Unavailable` when the app is turned off.

Do you think the backend should return more than just `Backend Error` if the app is turned off? FWIW I also tried this on apps that don't exist and apps that my credentials can't see and in both cases got a non-descript error and a 503. This may indicate that the error is a security protection.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/b79d8624950b3b205de20f527488dde7aa8c8cd8/gcloud/datastore/connection.py#L73

**Comment by pdknsk** [comment]
I don't know how this works behind the scenes, but I've been thinking that the Datastore should perhaps be able to operate separately from App Engine. Storage does. Every App Engine project also gets a default bucket named `app-id.appspot.com` which can be accessed with this API even when the app is disabled. I just tried.

**Comment by dhermes** [comment]
@pdknsk Thanks for the feedback.

@silvolu What's the right channel for this?
