### ISSUE TITLE
Update unit tests to use 'api_core.grpc_helpers.ChannelStub' vs. custom mocks

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python#4772]
See GoogleCloudPlatform/google-cloud-python#4705

Likely other APIs as well.

/cc @jonparrott

**Comment by tseaver** [comment]
Just did a quick check.  The following spanner unit test modules are still using custom stubs (although none seem a candidate for `ChannelStub`, which is used in the generated tests for the gapic-layer clients).

- [ ] `tests/unit/test_batch.py`
- [ ] `tests/unit/test_database.py`
- [ ] `tests/unit/test_instance.py`
- [ ] `tests/unit/test_snapshot.py`
- [ ] `tests/unit/test_streamed.py`
- [ ] `tests/unit/test_transaction.py`

**Comment by mf2199** [comment]
If this particular request is not applicable to Spanner, which seems to be the case, should we not re-label it to include relevant products instead?

**Comment by tseaver** [comment]
None of those modules are using mocks relevant to the `ChannelStub` helper.
