### ISSUE TITLE
Pubsub API should provide a way to synchronize a set of operations

### ISSUE THREAD

**Issue by gcbirzan** [googleapis/google-cloud-python#4913]
The pubsub API provides no easy way to make sure a bunch of publishes finish before continuing. You have to either deal with batches yourself or wait on every Future returned. A context manager would do the job, or even a wait method on the client.

**Comment by jonparrott** [comment]
@lukesneeringer what do you think?

**Comment by lukesneeringer** [comment]
Seems reasonable to me. asyncio does have a mechanism to wait on multiple futures but that does not help anyone on earlier versions of Python.

**Comment by sduskis** [comment]
@theacodes, do you think this is still a GA blocking issue?
