### ISSUE TITLE
Speech: measure time between end of user speech and final results

### ISSUE THREAD

**Issue by akmalhakimi1991** [googleapis/google-cloud-python#5086]
Is there a way to measure the time taken between the end of user speech and the time to get the final results? Right now what I'm doing is, I take the latest interim result timestamp as the "start time" and final result timestamp as the "end time". This works ok-ish if the interim result comes immediately after user speaks. However, the interim result might come a bit later. This made the result inaccurate.  
  
Is there any better way to do this?

**Comment by tseaver** [comment]
I do not believe that there is anything emitted from the backend which signals "start of processing."  @beccasaurus, can you confirm?

**Comment by sduskis** [comment]
This seems like a question better answered by the speech team.  You can reach them here: https://cloud.google.com/speech-to-text/docs/support
