### ISSUE TITLE
BigQuery: add destinationTableProperties to LoadJobConfig

### ISSUE THREAD

**Issue by yiga2** [googleapis/google-cloud-python#5093]
To catch up with https://issuetracker.google.com/issues/70117381

**Comment by tseaver** [comment]
@tswast while working on this, I am adding unit tests for each of the `LoadJobConfig` properties.  I notice that `skipLeadingRows` is mangled to a string in the resource, while `maxBadRows` is not.  Which is correct?  Given that we are using JSON, and the numbers expected wouldn't be huge, I would think that leaving them both as integers would be correct.  The [docs](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs) show them both as integers.

**Comment by tswast** [comment]
Per the discovery document (https://www.googleapis.com/discovery/v1/apis/bigquery/v2/rest)

`maxBadRows` is an int32 and can safely be represented as an integer in Google's JSON parser.

`skipLeadingRows` is an int64, so needs to be encoded as a string for Google's JSON parser.

I asked the BigQuery team this same question (why the inconsistency in types) and they didn't have a satisfactory answer.
