### ISSUE TITLE
Speech: long transcription times for non-English segments

### ISSUE THREAD

**Issue by akmalhakimi1991** [googleapis/google-cloud-python#5094]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_streaming_mic.py

## pip freeze output
altgraph==0.15
asn1crypto==0.23.0
aspy.yaml==1.0.0
backports-abc==0.5
backports.ssl-match-hostname==3.5.0.1
cached-property==1.3.1
cachetools==2.0.1
certifi==2018.1.18
cffi==1.11.2
chardet==3.0.4
cheroot==6.0.0
CherryPy==11.2.0
click==6.7
cryptography==2.1.4
dill==0.2.7.1
dis3==0.1.2
enum34==1.1.6
future==0.16.0
futures==3.2.0
google-api-core==1.0.0
google-auth==1.4.1
google-cloud-core==0.27.1
google-cloud-speech==0.29.0
google-cloud-translate==1.3.0
google-gax==0.15.16
googleapis-common-protos==1.5.3
grpcio==1.10.0rc2
gTTS==1.2.2
gTTS-token==1.1.1
identify==1.0.7
idna==2.6
ipaddress==1.0.18
jaraco.classes==1.4.3
lxml==4.1.1
macholib==1.9
monotonic==1.4
more-itertools==4.1.0
nodeenv==1.2.0
pefile==2017.11.5
pluggy==0.6.0
ply==3.8
portend==2.2
pre-commit==1.4.5
protobuf==3.5.2
py==1.5.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
PyAudio==0.2.11
pycparser==2.18
pyenchant==2.0.0
PyInstaller==3.3.1
pyOpenSSL==17.5.0
pyttsx==1.1
pytz==2018.3
PyYAML==3.12
requests==2.18.4
rsa==3.4.2
singledispatch==3.4.0.3
six==1.11.0
SpeechRecognition==3.8.1
tempora==1.10
tenacity==4.7.1
tornado==4.5.2
tox==2.9.1
translate==3.5.0
urllib3==1.22
virtualenv==15.1.0
ws4py==0.4.2

## Describe the issue

Is it normal for non-English language to have longer transcription time? When I run the script with `en-US`, it will take only 1 sec max to get the final transcription. However, when I changed it to `ms-MY` or `cmn-Hans-CN`, it took at least 5 seconds to get the final transcription. I can see the interim result is there but the final transcription didn't come immediately.  The issue seems to be a lot worse since last few weeks where sometime I didn't get the final transcription at all until it time out. Not sure if it related to when I updated `google-cloud-speech` library to 0.31.0 and 0.32.0.
  
Note that I tried iOS speech SDK and it doesn't have this problem.

**Comment by akmalhakimi1991** [comment]
But it didn't happen with iOS SDK

**Comment by tianxiongh** [comment]
I encounter the same problem that the property 'is_final' is working fine with English recognition. However for other languages it takes too much time to get 'is_final=True', even more than 1 minute. Meanwhile the interim results keeps coming and the responses are quick. It just does not return 'is_final'.

**Comment by sduskis** [comment]
This seems like a question for the speech team.  You can reach out to them here: https://cloud.google.com/speech-to-text/docs/support
