### ISSUE TITLE
BigQuery: add support for full job-level and config-level properties e.g. labels

### ISSUE THREAD

**Issue by yiga2** [googleapis/google-cloud-python#5110]
`client.load_table_from_uri` takes some job properties and `job.configuration.load` but none at `job.configuration` level like labels.
Request to either provide additional arguments to set any job or configuration properties.

This is valid for other `load` helper methods and other job type - extraction, copy, query

**Comment by yiga2** [comment]
Workaround for anyone on `1.0.0` is to use private `_properties` e.g.

`job_config._properties['labels']['mylabel'] = 'myvalue'`

**Comment by tseaver** [comment]
#5694 added a `labels` property to the job config classes.
