### ISSUE TITLE
Speech:  exception raised, "Too many audio buffers being processed."

### ISSUE THREAD

**Issue by akmalhakimi1991** [googleapis/google-cloud-python#5135]
Code used: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_streaming_mic.py

Been getting this error message since few hours ago. No changes made to the code. Is this server problem?

**Comment by chemelnucfin** [comment]
@akmalhakimi1991 I think it is a server problem as it suggests to wait.  Perhaps you can adjust the retry settings?  If not, let's keep an eye on it and let us know if it's still a problem.

Thanks.

**Comment by akmalhakimi1991** [comment]
Hi @chemelnucfin . It happened again today. If it matters, I'm using speech version 0.30.0 since my program has issues with 0.31.0 and 0.32.0. BTW, do you mind elaborating on the "retry settings"?

**Comment by chemelnucfin** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/speech/google/cloud/speech_v1/gapic/speech_client_config.py

Here. You can adjust the timeout to be larger.  You might still have to
wait for your results, but it might not throw an error.

Seems like the function you are calling does retry on unavailable.

Please let us know if you encounter any more problems.

**Comment by gmramaswamy** [comment]
this is happening again, now. seems like a server issue. but status page says all services are running fine. really concerning.

**Comment by RitwikGopi** [comment]
It indeed seems like a server issue. Today before some 30 minutes we were also facing the issue. Even four days before we had faced the same issue. Both the times we checked with 2 different accounts and still, the same error was happening.

**Comment by sduskis** [comment]
This seems like a question for the speech team.  You can reach out to them here: https://cloud.google.com/speech-to-text/docs/support
