### ISSUE TITLE
BigQuery: Partitioned tables: type and field

### ISSUE THREAD

**Issue by VikramTiwari** [googleapis/google-cloud-python#5162]
Doesn't seem like I have a way to set partition field using 0.31 SDK for BigQuery. I am trying to recreate the following scenario.

![screen shot 2018-04-05 at 23 25 43](https://user-images.githubusercontent.com/1330677/38406293-29bd1eb8-3929-11e8-8588-36df4b6f7915.png)

@tswast @jonparrott Could this be part of 1.0.0 release, if not already?

**Comment by tswast** [comment]
P.S. @alixhami and I recently refactored the Table and JobConfig classes, so it should be relatively easy to contribute a fix if you wanted to contribute a fix before we get to it.

The classes have a private `_properties` dictionary which correspond to the API resource representation. Fields are exposed via properties: each field has a:
- setter that converts the input into API representation and sticks it in the `_properties` dictionary,
- getter that takes the API representation from `_properties` and constructs the friendly Python object for it.

**Comment by VikramTiwari** [comment]
With this job config:
```
        job_config = bigquery.LoadJobConfig()
        job_config.source_format = 'CSV'
        job_config.skip_leading_rows = 1
        job_config.allow_jagged_rows = True
        job_config.write_disposition = 'WRITE_TRUNCATE'
        job_config._properties['load']['timePartitioning'] = {'type': 'DAY', 'field': 'date'}
```

I get:
```
{'error': '400 POST https://www.googleapis.com/upload/bigquery/v2/projects/omni-ds/jobs?uploadType=resumable: Required parameter is missing'}
```

The file is present and is not zero bytes.

**Comment by tswast** [comment]
@VikramTiwari Are you able to load this file without using the `'timePartitioning'` property?

**Comment by tswast** [comment]
Oh, you are using `0.31.0`. My workaround was for `0.32.0`. Drop the `['load']` to workaround the missing field in version `0.31.0`.

**Comment by VikramTiwari** [comment]
@tswast I created a new virtualenv and now using 0.32.0
```
        table_ref = client.dataset(dataset_id, project=project_id).table(table_id)
        job_config = bigquery.LoadJobConfig()
        job_config.source_format = 'CSV'
        job_config.skip_leading_rows = 1
        job_config.allow_jagged_rows = True
        job_config.write_disposition = 'WRITE_TRUNCATE'
        job_config._properties['load']['timePartitioning'] = {'type': 'DAY', 'field': 'date'}

        with open(BQ_FILE.name, 'rb') as csv_file:
            job = client.load_table_from_file(
                csv_file, table_ref, job_config=job_config)
            job.result()
            BQ_FILE.close()
```

Gives me an error:
```
{'error': '400 POST https://www.googleapis.com/upload/bigquery/v2/projects/omni-ds/jobs?uploadType=resumable: Table with field based partitioning must have a schema.'}
```

Table is already present (empty). I have tried passing schema to table_ref which seems useless.

**Comment by tswast** [comment]
I don't think you can make a table into a partitioned table after it is already created.

**Comment by VikramTiwari** [comment]
@tswast I have also tried with empty table.

The error seems to be in the `client.load_table_from_file` where it requires `table_ref`.

`table_ref` is `TableReference('project, 'dataset', 'table')`
but while pushing data in with `timePartitioning`, I have to also pass `schema` which can be done by passing `table` object `<google.cloud.bigquery.table.Table object at 0x105a83950>`

A fix would be `load_table_from_file` should use passed `table_ref` to get the schema is job properties have `timePartitioning` enabled. @tswast Thoughts?

**Comment by tswast** [comment]
Why aren't you setting the `LoadJobConfig.schema` property?

**Comment by VikramTiwari** [comment]
Ah! My bad. Fixed. Thanks, @tswast. 👍
