### ISSUE TITLE
BigQuery: to_arrow() method similar to to_dataframe()

### ISSUE THREAD

**Issue by cpcloud** [googleapis/google-cloud-python#5204]
Current there's a `to_dataframe()` method that returns a pandas `DataFrame` from a query. `DataFrame`s don't efficiently support array and struct values, but `pyarrow` provides efficient support for them:

```python
In [11]: import pyarrow as pa

In [13]: a = pa.array(
    ...:     [
    ...:         {'a': [1, 2, 3]}
    ...:     ],
    ...:     pa.struct([pa.field('a', pa.list_(pa.int64()))])
    ...: )

In [14]: a
Out[14]: 
<pyarrow.lib.StructArray object at 0x7f55f8764b88>
[
  {'a': [1, 2, 3]}
]
```

A `to_arrow()` method will make it easier to efficiently support more complex types going forward in downstream libraries like [ibis](https://github.com/ibis-project/ibis).

**Comment by maxim-lian** [comment]
I realize out of scope for this library, but it would awesome to have this as an export rather than JSON -> python -> arrow. 

quasi-ref https://github.com/pydata/pandas-gbq/issues/133

**Comment by tswast** [comment]
Fixed in #8609 

To be released in `google-cloud-bigquery` 1.17.0 (https://github.com/googleapis/google-cloud-python/pull/8663).

**Comment by tswast** [comment]
FYI: `results.to_arrow(bqstorage_client=bqstorage_client).to_pandas()` is currently the fastest way to get a pandas DataFrame from your query results. About 4 seconds from results to DataFrame for a 125 MB table.

**Comment by tswast** [comment]
Looks like I added the `bqstorage_client` arg to `RowIterator`, but I missed adding it to `QueryResults`. It can still be used by calling `QueryResults.results().to_arrow(bqstorage_client=bqstorage_client)`, but we should add it to `QueryJob` for consistency.

**Comment by tseaver** [comment]
@tswast Did you mean to reopen here?

**Comment by tswast** [comment]
@tseaver Yep. I missed one parameter update in the PR that added this feature.

**Comment by tswast** [comment]
@plamut Remaining task to close out this FR is to add the `bqstorage_client` argument to `QueryJob.to_arrow()`

https://github.com/googleapis/google-cloud-python/blob/e4cf3f4458d13ce5b0203060dc4249d3e34e80a7/bigquery/google/cloud/bigquery/job.py#L2899

See `RowIterator.to_arrow()`:

https://github.com/googleapis/google-cloud-python/blob/e4cf3f4458d13ce5b0203060dc4249d3e34e80a7/bigquery/google/cloud/bigquery/table.py#L1452

Also, we should add comments before `to_arrow` and `to_dataframe` in both `QueryJob` and `RowIterator` reminding us to add any additional arguments in the other class.
