### ISSUE TITLE
BigQuery: Should retry on 502 like Go client does

### ISSUE THREAD

**Issue by esprehn** [googleapis/google-cloud-python#5291]
See https://code-review.googlesource.com/c/gocloud/+/22490 ans associated bug.

This is the python equivalent function here:
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/_helpers.py#L372

but it doesn't check for StatusBadGateway

**Comment by tseaver** [comment]
Via #5930 and #6011.
