### ISSUE TITLE
BigQuery: 'pyarrow' support cannot be used with Python 3.7

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#5294]
Pandas/Cython doesn't currently support 3.7. Once it does we need to enable 3.7 testing on BigQuery.

Collecting pandas>=0.17.1 (from google-cloud-monitoring==0.29.0)
Using cached https://files.pythonhosted.org/packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz
Could not find a version that satisfies the requirement Cython (from versions: )
No matching distribution found for Cython

**Comment by crwilcox** [comment]
I came across a bunch of closed issues for Cython (which works for 3.7 but doesn't seem to ship a wheel at this time). I couldn't find much at all regarding Pandas.

**Comment by tswast** [comment]
I think we need to keep open to drop removal of Pandas from 3.7 tests once Pandas adds a package for 3.7.

Upstream issues:

- Cython: per https://github.com/cython/cython/issues/1978 it should work with HEAD, but possibly not packaged to support 3.7 on PyPI
- Numpy: https://github.com/numpy/numpy/issues/10500
- Pandas: https://github.com/pandas-dev/pandas/issues/20552

**Comment by tseaver** [comment]
Pandas 0.23.3 [claims (working) support for Python 3.7](http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#v0-23-3-july-7-2018).

The release page also notes Pandas will be [dropping Python 2.7 support](http://pandas.pydata.org/pandas-docs/stable/install.html#install-dropping-27) for new feature releases as of 2019-01-01.

**Comment by tseaver** [comment]
However, `pyarrow` does **not** yet support Python 3.7 in its [latest release](https://pypi.org/project/pyarrow/0.10.0/#files).

**Comment by tseaver** [comment]
The forthcoming Pyarrow 0.11.0 release is [supposed to have wheels for Python 3.7](https://issues.apache.org/jira/browse/ARROW-3468).

**Comment by tswast** [comment]
Fixed by https://github.com/googleapis/google-cloud-python/pull/7610.

Removing outdated comment in https://github.com/googleapis/google-cloud-python/pull/8785.
