### ISSUE TITLE
Speech: prevent returning English words when user is speaking non-English

### ISSUE THREAD

**Issue by akmalhakimi1991** [googleapis/google-cloud-python#5308]
Is there a way to prevent speech to return English words when user is speaking non-English?

**Comment by jerjou** [comment]
Have you set the language code to non-english?

**Comment by akmalhakimi1991** [comment]
Yes I did

**Comment by jerjou** [comment]
Can you provide more detail as to what you're doing, what you expect to happen, and what actually happens? Code snippets and copy/pasted example output is always helpful.

**Comment by akmalhakimi1991** [comment]
So I'm trying to do a language detection/validation by comparing the confidence levels of multiple STT results from different language code based on single audio streaming.   

For example, I want to know whether a user is speaking Chinese or English. I will send his speech audio to the API with the first one configured to "cmn-Hans-CN" and the other configured to "en-US". I will then compare the confidence level returned by both API call and the higher one indicates that it's the spoken language.   

The idea is, most of the time, when user are not speaking the language that's the API call configured with, it will return lower confidence level. This works fine most of the time. But there are certain time when a user is speaking English, the "cmn-Hans-CN" call returns English transcription with higher confidence than the "en-US" call.   
  
My expectation is, if non-English API call did not return English transcription, it will improve the accuracy of the language detection program.

**Comment by sduskis** [comment]
This seems like a question for the speech team.  You can reach out to them here: https://cloud.google.com/speech-to-text/docs/support
