### ISSUE TITLE
Spanner: timeout for streaming reads is 60 seconds

### ISSUE THREAD

**Issue by ji-han** [googleapis/google-cloud-python#5389]
It seems that the timeout for streaming read operations from Spanner is set to 60 seconds by the Python client. It wasn't clear to me if this was intentional, since the configuration here has `timeout_millis` for `StreamingRead` set to `3600000`: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/26f1a97ec06b5c48df7a3c9eec00ae3985657164/spanner/google/cloud/spanner_v1/gapic/spanner_client_config.py#L66

However, that value is superseded by `initial_rpc_timeout_millis` here: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/26f1a97ec06b5c48df7a3c9eec00ae3985657164/api_core/google/api_core/gapic_v1/config.py#L105

Which for the `default` retry param is `60000`:
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/26f1a97ec06b5c48df7a3c9eec00ae3985657164/spanner/google/cloud/spanner_v1/gapic/spanner_client_config.py#L14

If this is intentional, what's the appropriate way to perform a large-size read out of Spanner using this client?

**Comment by theacodes** [comment]
It would be up to @snehashah16 to update the artman/gapic config next to the protos

**Comment by tseaver** [comment]
@snehashah16 can you look at tweaking the `googleapis/google/spanner/` configuration?

**Comment by tseaver** [comment]
f7c008af73349fe74f5ddd7110255282fd0f7c2c picked up changes to the GAPIC configuration:  `ExecuteStreamingSql` and `StreamingRead` now have extended timeouts (1200 seconds).
