### ISSUE TITLE
Regen / release vision, texttospeech, iot

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python#5520]
Now that the gapic-generator [fix for shared modules is merged](https://github.com/googleapis/gapic-generator/pull/2063).  The recent releases of those API libraries all contain the re-introduced module overwrites for shared modules (#5473).

**Comment by tseaver** [comment]
As of right now:

- `vision-0.33.0` has the fix in place (#5530)
- `texttospeech` does not yet have it.
- `iot` does not yet have it.

**Comment by busunkim96** [comment]
I assume this is now out of date, closing.
