### ISSUE TITLE
Monitoring: where is CallOptions on monitoring API example?

### ISSUE THREAD

**Issue by miyatin0212** [googleapis/google-cloud-python#5560]
[OS] macOS Sierra 10.12.6
[Versions]

- Python 3.6.1

```
google-api-core==1.2.1
google-api-python-client==1.7.3
google-auth==1.5.0
google-auth-httplib2==0.0.3
google-cloud-monitoring==0.30.0
googleapis-common-protos==1.5.3
```

----

## CallOptions class was not found!

Hi. I'm new to GCP and Stackdriver. I wanted to use Google Kubernetes Engine and its auto scaling by custom metrics. Then, it is required to export the metrics to Stackdriver Monitoring, so I am trying to do it.

But, After installing above-mentioned libraries, the example code on monitoring API README document failed. The pit hole is that `CallOptions` was not found, thus I've searched it in this repository and some other repositories.

And finally, I couldn't find it...

`CallOptions` is defined in gax.python, but the package is currently deprecated and moved to google-api-core. So I guess that also the dependency is currently corrupted or the some examples are out-of-date.

Please tell me how handle this problem.

_Thank you for the great package and platform._

**Comment by tseaver** [comment]
@miyatin0212 Thanks very much for the report!  The examples you are seeing are outdated.  You should be able to use the `pages` attribute of the response iterator without needing to pass a token, e.g.:

```python
for page in client.list_monitored_resource_descriptors(name).pages:
    for element in page:
        # process element
        pass
```

**Comment by tseaver** [comment]
I have opened https://github.com/googleapis/gapic-generator/issues/2388 to track the issue for examples in generated code.
