### ISSUE TITLE
Logging: Expose receiveTimestamp field in LogEntry

### ISSUE THREAD

**Issue by qingling128** [googleapis/google-cloud-python#5601]
The [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) proto has the following two fields:
1. `receiveTimestamp` - The time the log entry was received by Stackdriver Logging.
2. `timestamp` - The time the event described by the log entry occurred.

We can potentially use the delta between these two to measure the latency at the client side.

However `receiveTimestamp` is not exposed in the Python client lib: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging/entries.py#L155.

**Comment by qingling128** [comment]
Friendly ping. Any update on this one?

**Comment by tseaver** [comment]
I'm closing this in favor for #6094, which includes its commits, adds other `LogEntry` fields, and refactors the `google.cloud.logging.entries` module to use named tuples.
