### ISSUE TITLE
Bigtable: reads are much slower in latest release than previous release.

### ISSUE THREAD

**Issue by sduskis** [googleapis/google-cloud-python#5725]
Users describe a dramatic slowdown (300x) in reads in google-cloud-bigtable==0.29.0 potentially due to to `deepcopy`.  ([Here's the stackOverflow post](https://stackoverflow.com/questions/51593612/python-bigtable-client-spends-ages-on-deepcopy?noredirect=1#comment90170224_51593612)).

We have new methods that have not been released yet that improve performance.  We should probably release soon.  

This was previously discussed in #4468, but I'd like to raise the question again given the customer issue.  Can we remove the deepcopy for performance consideration?

**Comment by tseaver** [comment]
@sduskis I believe the work done since `google-cloud-bigtable 0.29.0` has addressed this issued.  Can you please confirm and close?

**Comment by tseaver** [comment]
Please reopen if my assumption was incorrect.
