### ISSUE TITLE
Container: documentation is deficient, links aren't helpful, page has bug

### ISSUE THREAD

**Issue by DazWilkin** [googleapis/google-cloud-python#5777]
https://googlecloudplatform.github.io/google-cloud-python/latest/container/gapic/v1/api.html

![image](https://user-images.githubusercontent.com/1022400/43903089-7d536c4c-9ba0-11e8-95e2-c66a033162b8.png)

Page's "Client Library Documentation" is a self-referential, expect it to take me to the list of methods.

References to e.g. "API Documentation" go to the Kubernetes Engine product page (not the API docs)
https://cloud.google.com/kubernetes-engine/

It's not obvious to me how to get from the documentation pages to the correct sources of the documentation to try to correct them directly.

**Comment by tseaver** [comment]
- The [page from which that image was made](https://googleapis.github.io/google-cloud-python/latest/container/gapic/v1/api.html) looks a bunch better to me today:

![screenshot from 2018-12-05 16-36-15](https://user-images.githubusercontent.com/242750/49545526-ed5a1500-f8ab-11e8-8c73-865665e98e83.png)

- The [main page](https://googleapis.github.io/google-cloud-python/latest/container/index.html) has a "Product Documentation" link, pointing (appropriately) to the cloud.google.com product page.

- Re:  the circular link.  I will update it to land on the `api.html` page.
