### ISSUE TITLE
[Documentation] Add a nice search experience in the website

### ISSUE THREAD

**Issue by s-pace** [googleapis/google-cloud-python#5869]
👋  Google team,

In our project, we need to use your awesome tool. But without search within your documentation, browsing it might be painful. In order to help me learn your tool, I have build a quick search experience that provide me a learn-as-you-type experience. I feel like I must share it to you

I'm working at Algolia on the a project called [DocSearch](https://community.algolia.com/docsearch/) which goal is to enhance documentation websites with exhaustive, fast and relevant search. You might have seen DocSearch live already on websites like [Bootstrap](https://getbootstrap.com/), [ESLint](https://eslint.org/) or [Babel](https://babeljs.io/).

We put together [a demo](https://docsearch-google-cloud-python.netlify.com/) of what DocSearch on the google-cloud-python website could look like here. Feel free to try it and let us know what you think.

[![demo of DocSearch + google-cloud-python](https://cl.ly/41f739a1ccb8/Screen%20Recording%202018-08-30%20at%2011.41%20AM.gif)](https://docsearch-google-cloud-python.netlify.com/)

The way DocSearch works is by crawling your content, pushing the results into an Algolia index, and then requesting this index directly from the website front-end through JavaScript.

We'll take care of crawling your website and populating the Algolia index with the latest changes every 24h for you. You don't need to change anything to your deployment process. The only thing you need to add are the following CSS and JS snippets that will bind the dropdown to your searchbox.

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '783cae1144e2bc58975f4eead301c9b2',
  indexName: 'google_cloud_python',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

The `inputSelector` option should be set to a CSS selector that target your search input. Feel free to update it if this one is not specific enough.

We built DocSearch with the idea of giving back to the Open-Source community. This is why your [crawling configuration](https://github.com/algolia/docsearch-configs/blob/master/configs/google-cloud-python.json) is available on GitHub if you want to change it. We also have our own [documentation](https://community.algolia.com/docsearch/documentation/) to help you tweak the dropdown to your needs. You'll also have access to analytics on the most searched terms or those with no results. All of this is of course entirely free.

Would that be something you'd be interested in? If so, we'd be happy to work on integrating it through a PR.

**Comment by tseaver** [comment]
@JustinBeckwith, @theacodes I'll leave it to you guys to think about this integration with our docs.

**Comment by grant** [comment]
(Bug bashing/fixit)
I don't think an integration with Algolia can be supported at this time, at least with our team.
What do you think @JustinBeckwith?

**Comment by JustinBeckwith** [comment]
This is googleapis.dev territory, which means it's all @theacodes :)

**Comment by s-pace** [comment]
Why do you think we can't help you with the search on the documentation? @grant

**Comment by grant** [comment]
Up to Thea, but I think there are other priorities that must be resolved first.

**Comment by theacodes** [comment]
Universal search and navigation are on our roadmap but lower down the list than other things. I'll keep this solution in mind when we get there.

Closing this for now.
