### ISSUE TITLE
Missing Machine Learning API support

### ISSUE THREAD

**Issue by saalaa** [googleapis/google-cloud-python#5872]
Unless I'm greatly mistaken, support for the Machine Learning (`ml`) API is missing from the project which means that I am personally using `requests` to extract prediction from models on GCP.

This, in my opinion, is a bug because unlike AutoML, ML is not in beta and should therefore receive greater attention but you may decide it's a feature request instead.

To reproduce the issue:

```
$ pip install google-cloud-datastore
$ python
Python 3.7.0 (default, Jul 15 2018, 10:44:58) 
[GCC 8.1.1 20180531] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import ml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ml' from 'google.cloud' (unknown location)
```

**Comment by tseaver** [comment]
Adding support for an API is definitely feature-ish:  the priorities for such efforts are juggled by the stakeholders (typically *not* here).  That doesn't mean we would turn down reviewing a PR which added support for `ml`, of course. :)

**Comment by tseaver** [comment]
@saalaa I am an external contractor, paid by Google for my work on `google-cloud-python`.

**Comment by tseaver** [comment]
@danoscarmike is the Googler who juggles the feature priority list.

**Comment by danoscarmike** [comment]
Looking into this today...standby...

**Comment by mivdnber** [comment]
@danoscarmike Did you look into this? It's kind of a shame that we have to pull in another client library in maintenance mode with a much less powerful level of abstraction and its own authentication machinery to run a simple classifier.

**Comment by busunkim96** [comment]
@czahedi Would you know anything about plans for a library for the `ml` API?

**Comment by czahedi** [comment]
Actually @puneith would know better. My understanding is there's no plan for a library on that API in the near-term.

**Comment by czahedi** [comment]
Hey Steve, here's a quite old issue to take a look at. If we have a library planned near-term we should mention that, otherwise we should probably file this as a feature request against the product team's public issue tracker and close this.
