### ISSUE TITLE
Cloud Functions & Storage: fails intermittently with ProtocolError + ConnectionResetError

### ISSUE THREAD

**Issue by brianmhunt** [googleapis/google-cloud-python#5879]
This is a cross post originally detailed at https://issuetracker.google.com/issues/113672049 

Essentially the problem is that in a Google Cloud Functions python endpoint the `google-cloud-storage` API is intermittently throwing a `ProtocolError` and `ConnectionResetError` when getting a blob.

**Comment by brianmhunt** [comment]
Linking possibly relevant Golang issue: GoogleCloudPlatform/google-cloud-go#108

**Comment by frankyn** [comment]
I'm not sure what's happening here, acking for now in GCS library weekly.

**Comment by frankyn** [comment]
I did not get additional input in the weekly meeting.

@brianmhunt could you tell me more about your use-case so I can try to reproduce? 
Also what is the size of a file you're trying to read?

**Comment by brianmhunt** [comment]
@frankyn Of course, thanks for the follow-up.

Our function is given an array of slices of PDFs and converts that to a single PDF.  An oversimplified version is something like this:

```python
def consolidatePdf(pdfSlices):
    """Create a PDF from the given slices.

    pdfSlices is an iterable of dicts of this form: { url: "gs://", range: [start, end] }
    """
    newPdf = PdfWriter()
    for slice in pdfSlices:
        reader = PdfReader(getPdfFromGS(slice['url']))
        start, end = slice['range']
        pdfWriter.append(reader.getPages(start, end))
    return newPdf.getBytes()
```

Where the `getPdfFromGS` performs the blob storage read.  If you think it'll help I'm happy to share the code if you email me at `brianmhunt at gmail.com`.

I've only seen the failure occur on the very first file being read (but that doesn't mean that the problem is limited to the first file being read).

The files failing are fairly small, in the 150k range.

**Comment by frankyn** [comment]
Thanks, I'd like to keep this discussion as much as possible through Github.  So if someone else hits a similar issue they can find it later.

Is PdfReader wrapping around the google-cloud-storage package? Could you share a portion of that code?

**Comment by brianmhunt** [comment]
Thanks, here's the salient bit of code that's throwing.

```python
def generateUrlPdfBytesMap():
    upm = dict()
    for url in urls:
        bucket, path = urlToBucketPath(url)
        account = path.split('/')[1]
        blob = storage.bucket(bucket).get_blob(path) # 🔥
        upm[url] = blob.download_as_string()
    return upm
```

Where `urlToBucketPath` converts a `gs://` or `https://` Firebase url to the `bucket, path` pair per https://stackoverflow.com/questions/52064868.

It really is as simple as one could possibly imagine;  I was going to put the PDF reader code in but it looks like it never gets called because the slurp (`generateUrlPdfBytesMap`) occurs before.

Related, according to [am...@google.com](https://issuetracker.google.com/issues/113672049#comment2), it appears that a newer version of `google-cloud-storage` is available (i.e. I was using `1.10.0`; version `1.11.0` is out).

I will switch to the new version and report any occurrences.

**Comment by brianmhunt** [comment]
This continues to occur with google-cloud-storage version 1.11.0.

**Comment by arvindnrbt** [comment]
This issue occurs to me as well. But in my case, it throws connection error when I'm trying to get a bucket before signing a url.
Code:
```
bucket = storage.get_bucket(bucket)
```
Traceback:
```
File "/code/xxx/yyy/models.py", line 106, in generate_signed_url
    storage_bucket = STORAGE_CLIENT.get_bucket(GCS_BUCKET)
  File "/usr/lib/python3.6/site-packages/google/cloud/storage/client.py", line 225, in get_bucket
    bucket.reload(client=self)
  File "/usr/lib/python3.6/site-packages/google/cloud/storage/_helpers.py", line 108, in reload
    _target_object=self)
  File "/usr/lib/python3.6/site-packages/google/cloud/_http.py", line 290, in api_request
    headers=headers, target_object=_target_object)
  File "/usr/lib/python3.6/site-packages/google/cloud/_http.py", line 183, in _make_request
    return self._do_request(method, url, headers, data, target_object)
  File "/usr/lib/python3.6/site-packages/google/cloud/_http.py", line 212, in _do_request
    url=url, method=method, headers=headers, data=data)
  File "/usr/lib/python3.6/site-packages/google/auth/transport/requests.py", line 201, in request
    method, url, data=data, headers=request_headers, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by rasputnik** [comment]
Same here, my context is I'm in a pubsub worker and am retrieving a URL to download and store into a bucket. I've spent an ungodly amount of time trying to debug the retrieval method I was running only to realise it's actually the cloud stores https machinery that is failing.

**Comment by cmey** [comment]
I get the same error as OP @brianmhunt and @ arvindnrbt.
`Connection reset by peer`

It happens during:

 - `storage.bucket(bucket).get_blob(path)`
and `bigquery_client.insert_rows(table, rows_to_insert)`.
This is running Google Cloud Functions with Python 3.7 and google-cloud-storage==1.11.0.

Not all the time, about 10% failure rate. Function deployed to `us-east1` (I also tried `us-central1`, about the same).

**Comment by yiga2** [comment]
@anyone-watching, is this still occurring ? We were considering migrating from AWS Lambda but this may hold us up.

**Comment by frankyn** [comment]
I'm heads down on another issue. @tseaver could you take a look?

**Comment by tseaver** [comment]
@frankyn This is  a request for the same feature as `[Python] Storage: automatic retry behavior for transient server failures (exponential backoff + jitter)` in our feature backlog (we would just need to ensure that `ProtocolError` and `ConnectionError` are tracked as transient errors for that feature).

**Comment by parthmishra** [comment]
Would like to add that I'm experiencing same error in GCF environment using google-cloud-storage==1.12.0 

I see that 1.13.0 has been released and I may try that to see if problem persists.

**Comment by frossigneux** [comment]
[trace.txt](https://github.com/googleapis/google-cloud-python/files/2476954/trace.txt)
I get the same error:
- google-cloud-storage==1.13.0
- runtime: python37
- python_version: 3

**Comment by stephenk289** [comment]
Hi,
I'm also having this issue.  There is a scenario for which this occurs for me every time.

I send a dataset to a non-google ML provider.  We then wait for the prediction to finish.  When the ML prediction does finish, I take the .CSV file and then I wish to deposit it on the Google Storage.  The wait can be up to 10mins (normally 6mins).  I get the ConnectionResetError.  If this is useful I'm happy to share more details.

g-c-s==1.13.0
runtime python37

**Comment by yiga2** [comment]
Remember CF times out after 9min so the error could be "normal". 
I would check the Stackdriver log to see what exact http code is returned and raise the issue on issuetracker. Not here as it sounds like related to the core API.

**Comment by tseaver** [comment]
If, as @yiga2 suggests, the CF run is being terminated due to a [time limit](https://cloud.google.com/functions/quotas#time_limits), there is nothing we can do in `google-cloud-storage` to address it:  the Python process itself is being killed in that case.

**Comment by rasputnik** [comment]
Not to disregard @stephenk289 s issue, but lots of us are having issues when GCS throws 50x errors that are not related to timeouts.

Some retry semantics built-in would be really useful.

**Comment by stephenk289** [comment]
Thanks very much for the answers / feedback @tseaver and @yiga2.  

If you'll forgive me a follow-up  - 

I tried to respond to the error by recreating my client object [client = storage.Client()] as this was the closest I could find to re-establishing a connection so that I could interact afresh with Google Storage with a decaying re-try logic - it didn't seem to work.  Given the advice that there is a time limit on any connection to GS (~9mins), I will, therefore, risk losing said connections during long-wait times.    Any steer most welcome.

**Comment by ilons** [comment]
I'm also hitting this error from Cloud Function trying to read from Cloud Storage.
The majority of invocations works, but I get this every so often, and it makes a lot of noise even if I retry.

My CF are finishing in under 2 seconds in most cases, and I've followed the recommendations on https://cloud.google.com/functions/docs/bestpractices/networking to avoid re-establishing connections, which I suspect is also the culprit of the problem.

Could it be that the same connection are (as intended) re-used for multiple invocations of the CF, and eventually the remote server (GCS) drops it when I try to use it?

**Comment by yiga2** [comment]
After a lot of research and interactions with G support, it turns out that indeed, connection may either timeout (our case, resumable upload) or just disconnect sporadically - happens at other cloud storage providers. 
No big deal as ConnectionResetError (104) is a retriable error but this must be handled on the client side. 

Unfortunately `google-client-python` - and may others - is delegating exponential backup to lower-level dependencies - signaled by deprecated `num_retries` - which means less control on when retries should trigger. And these dependencies do not catch 104 as retriable.

If you search out there, you will see there is a lot of debate (resistance ?) on where and how best to address this, in googleapi's, requests or urllib3 (as I read this may be Py3 specifc),... 
For me, this is as simple as adding 104 to the list of transient errors (500-505 range or so) but I may be oversimplify.
Despite the numerous posts - many recent ones -, no real resolution.

If you can't wait for resolution or patch your own fork, you can look at `gcsfs` which we use for streaming from/to GCS (from GCF). The ConnectionResetError is retriable there - it does log an exception (looks like an Error in SD logging) but the retries do happen and function does not end abruptly.

**Comment by dustinfarris** [comment]
@yiga2 Can you elaborate on how "ConnectionResetError" is retriable in gcsfs?  Is there an argument I need to pass to the constructor to enable this?  My Cloud Function is crashing right after the error is thrown.

**Comment by jbugbee126** [comment]
I had found that that exception is simply a generic unhandled exception. Be sure to wrap all of your connections . I.e Api calls,  GCS file transfers etc..  with try except error handling. You will see that one of your connections maybe failing. But it could be for any number of reasons.





-------- Original message --------

**Comment by gururajasekhar** [comment]
CHEERS!  
Lots of stuff to learn from the comments itself.
So, I was trying to do a similar thing, like accessing a file from GCS and then updating it. Same error still exists, so other than adding a 'try except' statement and trying to retrieve the file again, is there any other solution? Because this also might be unreliable.

**Comment by busunkim96** [comment]
@crwilcox @frankyn @jkwlui @tseaver (Is there a storage team alias?)

Would you mind looking into the internal issue? It's been closed as 'Won't fix - not reproducible', but folks have commented here and over on the issue since then.

**Comment by frankyn** [comment]
@busunkim96 what's the internal tracking issue?

**Comment by tseaver** [comment]
@brianmhunt `ConnectionResetError` seems like the kind of error one might see when the VM is being torn down.  Can you tell whether your function is failing due to a [time limit](https://cloud.google.com/functions/quotas#time_limits)?  If so, there isn't really much we can do in `google-cloud-storage` to mitigate the issue.

**Comment by brianmhunt** [comment]
@tseaver Thanks. The problem was not the time limit.  i.e. it can fail in the first ~5 seconds.

**Comment by tseaver** [comment]
@brianmhunt OK, good to know.  Here is a workaround:

```python
from urllib3.exceptions import ProtocolError
from google.api_core import retry

predicate = retry.if_exception_type(
    ConnectionResetError, ProtocolError)
reset_retry = retry.Retry(predicate)

def generateUrlPdfBytesMap(urls):
    upm = dict()
    for url in urls:
        bucket_name, path = urlToBucketPath(url)
        account = path.split('/')[1]
        bucket = storage.bucket(bucket_name)
        blob = bucket.get_blob(path)  # Note: makes API call
        upm[url] = retry(blob.download_as_string)()
    return upm
```

**Comment by rasputnik** [comment]
@tseaver awesome, have passed this on to our devs. Some GCP client libraries seem to expose a retry option, some don't. This will be very handy, thanks!

**Comment by frankyn** [comment]
Thanks @tseaver, IIUC, updating retry strategy for download and upload blob can help with GCF time limits when the VM is unscheduled. 

How are retry defaults defined in the GCS Python library? Do they mainly come from api_core and do you have examples of best practices with modifying retry strategy in other Python manual libraries?

@tritone is a new GCS DPE who will be taking a look at fixing it.


team alias: @googleapis/storage

**Comment by frankyn** [comment]
We are working to correct the issues with Python libraries retry strategy and will continue to update on-going work in https://github.com/googleapis/google-cloud-python/issues/9298.

As stated by @tseaver, the workaround is the following:
```python
from urllib3.exceptions import ProtocolError
from google.api_core import retry

predicate = retry.if_exception_type(
    ConnectionResetError, ProtocolError)
reset_retry = retry.Retry(predicate)

def generateUrlPdfBytesMap(urls):
    upm = dict()
    for url in urls:
        bucket_name, path = urlToBucketPath(url)
        account = path.split('/')[1]
        bucket = storage.bucket(bucket_name)
        blob = bucket.get_blob(path)  # Note: makes API call
        upm[url] = retry_reset(blob.download_as_string)()
    return upm
```

Thank you for your patience.

**Comment by pablopla** [comment]
Two weeks ago I've started getting ConnectionResetError 10% of the calls to blob.download_to_filename() from a GCE instance.
I've tried wrapping download_to_filename with Retry but still getting the same error.

Is there something wrong with my code?
How can I verify that ConnectionResetError was caught and the download failed several times?
```python
from google.api_core import retry
from google.api_core.exceptions import InternalServerError
from google.api_core.exceptions import TooManyRequests

predicate = retry.if_exception_type(ConnectionResetError, InternalServerError, TooManyRequests)
r = retry.Retry(predicate=predicate)
r(blob.download_to_filename)(filename)
```

**Comment by pablopla** [comment]
I've wrapped the call to blob.download_to_filename with try/catch and the exception e.__class__.__name__ gives me ChunkedEncodingError. Shouldn't be added to google.api_core.retry.if_transient_error?

**Comment by asgasw** [comment]
```
22:42:12 [I 201228 22:42:12 preprocess_step_1:56] downloading files from gs://aitd-train-data/prd/generator/raw/70/Generator_ad*.tsv
22:42:14 Traceback (most recent call last):
22:42:14   File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 436, in _error_catcher
22:42:14     yield
22:42:14   File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 518, in read
22:42:14     data = self._fp.read(amt) if not fp_closed else b""
22:42:14   File "/usr/local/lib/python3.6/http/client.py", line 459, in read
22:42:14     n = self.readinto(b)
22:42:14   File "/usr/local/lib/python3.6/http/client.py", line 503, in readinto
22:42:14     n = self.fp.readinto(b)
22:42:14   File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
22:42:14     return self._sock.recv_into(b)
22:42:14   File "/usr/local/lib/python3.6/ssl.py", line 1012, in recv_into
22:42:14     return self.read(nbytes, buffer)
22:42:14   File "/usr/local/lib/python3.6/ssl.py", line 874, in read
22:42:14     return self._sslobj.read(len, buffer)
22:42:14   File "/usr/local/lib/python3.6/ssl.py", line 631, in read
22:42:14     v = self._sslobj.read(len, buffer)
22:42:14 ConnectionResetError: [Errno 104] Connection reset by peer
22:42:14 
22:42:14 During handling of the above exception, another exception occurred:
22:42:14 
22:42:14 Traceback (most recent call last):
22:42:14   File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 751, in generate
22:42:14     for chunk in self.raw.stream(chunk_size, decode_content=True):
22:42:14   File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 575, in stream
22:42:14     data = self.read(amt=amt, decode_content=decode_content)
22:42:14   File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 540, in read
22:42:14     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
22:42:14   File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
22:42:14     self.gen.throw(type, value, traceback)
22:42:14   File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 454, in _error_catcher
22:42:14     raise ProtocolError("Connection broken: %r" % e, e)
22:42:14 urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
22:42:14 
22:42:14 During handling of the above exception, another exception occurred:
22:42:14 
22:42:14 Traceback (most recent call last):
22:42:14   File "preprocess_step_1.py", line 126, in <module>
22:42:14     main()
22:42:14   File "preprocess_step_1.py", line 57, in main
22:42:14     adfiles = gsa.download_all(adwc, modeldir)
22:42:14   File "/app/googlestorage.py", line 109, in download_all
22:42:14     self.download(gspath, localpath)
22:42:14   File "/app/googlestorage.py", line 101, in download
22:42:14     blob.download_to_filename(localpath)
22:42:14   File "/usr/local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 1145, in download_to_filename
22:42:14     checksum=checksum,
22:42:14   File "/usr/local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 1049, in download_to_file
22:42:14     checksum=checksum,
22:42:14   File "/usr/local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 899, in _do_download
22:42:14     response = download.consume(transport, timeout=timeout)
22:42:14   File "/usr/local/lib/python3.6/site-packages/google/resumable_media/requests/download.py", line 171, in consume
22:42:14     self._write_to_stream(result)
22:42:14   File "/usr/local/lib/python3.6/site-packages/google/resumable_media/requests/download.py", line 105, in _write_to_stream
22:42:14     for chunk in body_iter:
22:42:14   File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 754, in generate
22:42:14     raise ChunkedEncodingError(e)
22:42:14 requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```
