### ISSUE TITLE
Pub/Sub MergeFrom error publish message

### ISSUE THREAD

**Issue by paulorcf** [googleapis/google-cloud-python#5903]
🏷 pub/sub
SO: Linux/Ubuntu 16.04
api_core_version = 1.3.0
client_library_version = None
gapic_version = 0.37.2
grpc_version = 1.14.2
python_version = 3.6.4

```
client = pubsub.PublisherClient.from_service_account_json('account.json')
topic_path = client.topic_path('project_name', 'topic_name')
data = b'The rain in Wales falls mainly on the snails.'
response = client.publish(topic, data)
```

Version: google-cloud-pubsub==0.37.2

## Error:
` response = client.publish(topic_path, data)
  File "venvpy/lib/python3.6/site-packages/google/cloud/pubsub_v1/gapic/publisher_client.py", line 393, in publish
    messages=messages,
TypeError: Parameter to MergeFrom() must be instance of same class: expected google.pubsub.v1.PubsubMessage got int.`

**Comment by tseaver** [comment]
I don't think there can be any connection between the `Client.from_service_account_json` factory and the traceback you are reporting.  What version of `google-cloud-pubsub` do you have installed?  E.g.:

```bash
$ pip show google-cloud-pubsub
```

**Comment by paulorcf** [comment]
Version: google-cloud-pubsub==0.37.2

**Comment by ericgj** [comment]
I just got the same error, `google-cloud-pubsub==0.38.0`.  And the same workaround worked for me too (thanks Paulo).  [Possibly related StackOverflow question](https://stackoverflow.com/questions/31843088/isinstance-doesnt-work-when-use-reflection-of-python-protobuf-v2-6-1) ?

**Comment by tseaver** [comment]
@paulorcf It looks as though you are bypassing the "main" API for publishing messages ([`pubsub_v1.PublisherClient.publish`](https://googlecloudplatform.github.io/google-cloud-python/latest/pubsub/publisher/api/client.html#google.cloud.pubsub_v1.publisher.client.Client.publish)), and instead calling the lower-level, GAPIC-generated helper (`pubsub_v1.gapic.publisher_client.PublisherClient.publish`]), which is definitely not recommended.

 The error message you report indicates that one of the items you are passing in `data` is an int, rather than an instance of `google.pubsub.v1.PubsubMessage`.    Can you show the code in your application which triggers the error?

The recommended path would be:

```python
from google.cloud import pubsub_v1

client = pubsub_v1.PublisherClient()
topic_path = client.topic_path('my-project-123'. 'my-topic-name')
data = b'BYTES OF MESSAGE DATA'

client.publish(topic_path, data, attr='ATTR VALUE')
```

Please feel free to reopen / follow up if you can show the reproduction case where your app passes values using this pattern.

**Comment by ericgj** [comment]
I believe they showed their code in the original post, re-pasting it here, it's the same I used.  It's the `from_service_account_json` constructor. 

```python
client = pubsub.PublisherClient.from_service_account_json('account.json')
topic_path = client.topic_path('project_name', 'topic_name')
data = b'The rain in Wales falls mainly on the snails.'
response = client.publish(topic, data)
```

**Comment by tseaver** [comment]
@ericgj we have [passing system test for `PublisherClient.publish`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/db2019aab45775ca8955cbc67b5df1c2be5870b8/pubsub/tests/system.py#L69).

Can you provide the complete traceback, along with the value you are passing to `publish`?

**Comment by paxsonsa** [comment]
Working:
```
from google.cloud import pubsub_v1
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file('auth.json')
client = pubsub_v1.PublisherClient(credentials=credentials)
topic = client.topic_path('project, 'topic')
client.publish(topic, b'hello')

```

Not Working:
```
from google.cloud import pubsub_v1

client = pubsub_v1.PublisherClient.from_service_account_json('auth.json')
topic = client.topic_path('project, 'topic')
client.publish(topic, b'hello')
```

TRACEBACK:
```
...
  File ".../python3.6/site-packages/google/cloud/pubsub_v1/gapic/publisher_client.py", line 395, in publish
    messages=messages,
TypeError: Parameter to MergeFrom() must be instance of same class: expected google.pubsub.v1.PubsubMessage got int.
```

**Comment by tseaver** [comment]
OK, I can reproduce here.  The issue is that `pubsub_v1.PublisherClient.from_service_account` is returning an instance of the low-level `pubsub_v1.gapic.publisher_client.PublisherClient`:  that class has a different signature for `publish`.

**Comment by tseaver** [comment]
@theacodes I believe this is the issue you tried to fix in #5826.  Can you shed any light here?

**Comment by tseaver** [comment]
Looks like #5826 returns a `staticmethod`, rather than a `classmethod`, for things that started life as `classmethod`s.  That would explain seeing the wrong `cls`.

**Comment by paxsonsa** [comment]
Thanks for looking into that and getting that fixed
