### ISSUE TITLE
Problems with firestore (DX is no good)

### ISSUE THREAD

**Issue by nodkrot** [googleapis/google-cloud-python#5907]
Firestore is great, but I just want to be able to have pagination easily, chat with new messages and infinite scroll easily. But it is not so easy. I cannot find an example and may be I am missing something. End solution ends up looking ugly with many boolean flags. Here are some of the main constrains:

- On the website (in browser), how am I supposed to persist current page (cursor) if user refreshes the page? `startAt` and `startAfter` seem to only take doc as an argument? 
  - May be store it in localStorage? But then how would SSR work?
  - How can I get a collection count to know how to render the pagination? ([1, 2] or [1, 2...59])
  - How do I know if I fetched the last set of docs so that I dont show loading extra one time?
- In chat app, in order to get real time messages in a group chat, I have to use this:
```
    .onSnapshot(function(snapshot) {
        snapshot.docChanges().forEach(function(change) {
            const newChats = []
            if (change.type === "added") {
                chats.push(change.doc)
                // or chats.push(change.doc.data()) but now its a different type of array
            }
            // now i need to figure out what to do with `chats` :(
        });
    });
```
  - Here are the problems with this
    - On first execution this will bring in all messages (assuming filters and limit), now I need to know if this is first call or subsequent ones to know if I should track the cursor or not
    - Do I use this to fetch first set of chats? If not, how do I make it only return only the **actually** added docs and not existing ones

I don't believe these are very specific use cases. I used firebase in the past and now there is firestore which didn't solve anything :(. I really want firebase to be a solution for backend but with these simple problems its easier to use meteor, mongodb/express or something. All of the above is solvable but from my experience it makes code look ugly, confusing, and requires extra setup to have solutions be performant on large collections. So please consider this as a feature request :) (If I encounter more DX issues I will be adding them on this thread). The only reason why I am writing this is because firebase is very close to what it is trying to be.

**Comment by nodkrot** [comment]
Following up on this.

**Comment by wilhuff** [comment]
I'm not sure what you're expecting here. This is a forum for solving issues specific to cloud python SDKs. This isn't a great forum for discussing general Firestore product features or misfeatures--it's not regularly reviewed from that point of view and indeed I only just stumbled onto this while looking for something else.

I'd suggest the best venue for this kind of discussion would be on the [mailing list](https://groups.google.com/forum/#!forum/google-cloud-firestore-discuss).

As a general note I'd suggest that while Firestore doesn't make this super easy it's also hard to do so in a universal way that interacts well with all the different frameworks that impose their own constraints on how pagination or infinite scrolling works.

At the same time, this is a solved problem and the best way to get this is use one of the UI framework adapters we or the community have already built. For example, if you're building your app with Angular, all the plumbing has already been done to plug this into general infinite scroll/pagination support in that library: https://angularfirebase.com/lessons/infinite-scroll-firestore-angular/.
