### ISSUE TITLE
Suppress 'PendingDeprecationWarnings' in GAPIC-based clients

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python#5967]
Clients which pass through `channel` rather than `transport` to their low-level `api` constructors trigger `PendingDeprecationWarnings`:

```python
<filename>:<lineno>: PendingDeprecationWarning: The `channel` argument is deprecated; use `transport` instead.
```

Tests for those packages routinely trigger those warnings (repeatedly).

**Comment by sduskis** [comment]
Is it possible to clean up the generator?

**Comment by samtstern** [comment]
This applies to Cloud Firestore as well.

**Comment by tseaver** [comment]
The vast majority of those warnings come from generated tests!  See: https://github.com/googleapis/gapic-generator/issues/2389

**Comment by tseaver** [comment]
I have a PR to fix the generator issue: https://github.com/googleapis/gapic-generator/pull/2407

It should merge today, which means that this issue should be resolved in the next autosynth round.
