### ISSUE TITLE
Vision: is global 'text confidence' available?

### ISSUE THREAD

**Issue by stankovicsrdjo** [googleapis/google-cloud-python#5992]
Hello,

Is there possibility to implement 'overall' confidence of text extracted scanned using Google Vision Text Detection ?

I know there is confidence for each label, letter and etc. but I can't find confidence for the last 'text' block.

For example adding 'confidence' tag bellow text tag. Currently JSON body looks like this: 

` }
}
text: "Lorem Ipsum\n\342\200\242 Lorem ipsum dolor sit amet, consectetuer\nadipiscing elit. Maecenas porttitor congue\nmassa. Fusce posuere, magna sed pulvinar\nultricies, purus lectus malesuada libero, sit\namet commodo magna eros quis urna.\n\342\200\242 Nunc viverra imperdiet enim. Fusce est.\nVivamus a tellus.\n"
`

But it would be great if it cloud look like this:

` }
}
detected_text: {
text: "Lorem Ipsum\n\342\200\242 Lorem ipsum dolor sit amet, consectetuer\nadipiscing elit. Maecenas porttitor congue\nmassa. Fusce posuere, magna sed pulvinar\nultricies, purus lectus malesuada libero, sit\namet commodo magna eros quis urna.\n\342\200\242 Nunc viverra imperdiet enim. Fusce est.\nVivamus a tellus.\n",
confidence: 0.9999999999000
}
`

If there is already way of getting that 'global' confidence rate let me know.

Sincerely,

Srdjan Stankovic.

**Comment by stankovicsrdjo** [comment]
Hello,

Is there possibility for this feature to be implemented ?

**Comment by tseaver** [comment]
@stankovicsrdjo There isn't anything we can do in the `google-cloud-vision` library to implement such a feature:  that would need to happen in the Vision API itself..  You need to request it via one of the [Vision API support page](https://cloud.google.com/vision/docs/support) links.
