### ISSUE TITLE
Storage: `download_to_file()` decompresses gzip'd object even when passed "Accept-Encoding: gzip"

### ISSUE THREAD

**Issue by houglum** [googleapis/google-cloud-python#6035]
1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
   - Storage
2. OS type and version
   - Only tested on Linux (Debian), but I assume this happens regardless of OS
3. Python version and virtual environment information `python --version`
   - Python 2.7.13
4. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
   - `pip freeze | grep storage` gives 1.12.0
5. Stacktrace if available
   - N/A
6. Steps to reproduce
   - See https://github.com/GoogleCloudPlatform/google-resumable-media-python/issues/49.
7. Code example
    - See https://github.com/GoogleCloudPlatform/google-resumable-media-python/issues/49.

<hr>

Once the issue mentioned above is resolved and a new version of google-resumable-media-python is released, this library should:
-  Require a version of it >= the new version
-  Figure out what to do about the `download_to_file()` and `download_to_filename()` methods in blob.py [1] [2].  They currently look like they're **supposed** to download gzipped objects (those with Content-Encoding set to "gzip") in their compressed state, given that they add the "Accept-Encoding: gzip" header to the request.  However, due to the issue mentioned above, they do not; they actually result in the decompressed bytes being written to the desired stream/file.  Once this gets fixed and we pull in a new version with that fix, we'll probably want to allow users to specify whether or not the downloaded gzip'd file should be decompressed (this is the behavior today, so it should probably be the default), or if the downloaded file should contain the compressed bytes.

[1]https://github.com/GoogleCloudPlatform/google-cloud-python/blob/e4a24d30283ce42ae58051dfd7f6267f2939d115/storage/google/cloud/storage/blob.py#L542
[2] https://github.com/GoogleCloudPlatform/google-cloud-python/blob/e4a24d30283ce42ae58051dfd7f6267f2939d115/storage/google/cloud/storage/blob.py#L489

**Comment by tseaver** [comment]
Fix blocked on a non-b0rken release of the "raw downloads" feature for `google-resumable-media` (see https://github.com/googleapis/google-resumable-media-python/pull/109).

At that point, we will need to surface options to the `Blob.download_*` methods which enable "raw" streaming:  iniially, that option will need to default to `False` for backward-compatibility.

**Comment by tseaver** [comment]
As of PR #9565 (being released today in `google-cloud-storage 1.23.0` release, PR #9778), the `Blob.download_*` methods take an optional `raw_download` argument:  if `True`, then the decompression will not happen.  Unfortunately, we have to leave it defaulted to False for backward-compatibility.
