### ISSUE TITLE
Firestore: Improve docs for 'Query.get' / 'Collection.get'

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6043]
`Query.get` (which underlies `Collection.get`) could have better documentation strings. Particularly there is no mention that iteration must be completed in the `max_rpc_timeout_millis` as specificed when creating the firestore_client. If iteration is not completed in that time, the iteration will stop at the timeout.

This is in response to a customer question on StackOverflow:

https://stackoverflow.com/questions/52395736/loop-over-cloud-firestore-docs-ends-unexpectedly-after-20-seconds-when-iterating

**Comment by tseaver** [comment]
#6033 was the previous report of that same SO issue here.  I wasn't aware of the timeout:  I assumed that it was a problem with non-transactional write-during-read.
