### ISSUE TITLE
Speech: Memory leak when creating SpeechClient instance for each request

### ISSUE THREAD

**Issue by todom-tivo** [googleapis/google-cloud-python#6077]
**OS**: Linux Debian and Mint 19

**Python version**: Python 2.7.15rc1

**Python package versions**:
```
grpcio==1.15.0
google-api-core==1.4.0
google-auth==1.5.1
google-cloud==0.34.0
google-cloud-speech==0.36.0
googleapis-common-protos==1.5.3
```

**Description**:
gRPC channels are not closed when a `SpeechClient` goes out of scope.  The obvious answer may be that we shouldn't construct a `SpeechClient` for every request, we found that we were running into issues trying to re-use a `SpeechClient` instance across multiple simultaneous requests (perhaps due to forking limitations of gRPC).  Ideally, garbage collection of the `SpeechClient` instance would clean up any transports it created and any transports could clean up any channels.  

**Steps to Reproduce**:
Run the attached speech_leak.py script on Linux and you'll see the RSS steadily increase for each request..

**Workaround**:
The leak can be avoided if we manually construct a channel and `Transport` and pass that to the `SpeechClient` and then explicitly close the channel after the request is complete using `with`.  See speech_workaround.py for the modified version.

**Code Samples**:
[leak_examples.zip](https://github.com/GoogleCloudPlatform/google-cloud-python/files/2412082/leak_examples.zip)

**Comment by tseaver** [comment]
You are correct that we don't provide a `close` method (or similar) on `SpeechClient`.  Creating a new client per request is not part of our expected usage pattern.

It should be safe to share a single `SpeechClient` across threads in a single process.  If you are forking, then best practice is to create a single `SpeechClient` in each forked process.

**Comment by tseaver** [comment]
Related to #5523 for pubsub, which led me to open https://github.com/googleapis/gapic-generator/issues/2337 to support explicitly closing the client->transport->channel.
