### ISSUE TITLE
Logging: '_BaseEntry' missing fields added to 'LogEntry' in API 

### ISSUE THREAD

**Issue by salrashid123** [googleapis/google-cloud-python#6094]
[LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) defines several additional fields which are dropped by  [_BaseEntry](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging/entries.py#L51)  

- [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry)  shows
```
  "receiveTimestamp": string,
  "traceSampled": boolean,
  "sourceLocation": {
    object(LogEntrySourceLocation)
  },
```
but those are not set on init of [entries.py](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging/entries.py#L87)

**Comment by tseaver** [comment]
`receiveTimestamp` is output-only:  it likely shouldn't be settable by the normal `LogEntry` constructor, but should be captured in `LogEntry.from_api_repr`.  The other two should be settable.

**Comment by hjed** [comment]
It's also missing `operation`

**Comment by tseaver** [comment]
`receiveTimestamp` (reported in #5601), added in PR #6143.
