### ISSUE TITLE
PubSub: double base64 encode *sometimes*

### ISSUE THREAD

**Issue by ericgj** [googleapis/google-cloud-python#6127]
**OS:** Windows 7 client (see below) and GAE 2nd generation standard
**Python:**  3.6.4 (Windows)  and 3.7 (GAE)
**google-cloud-pubsub:** 0.38.0 (both Windows and GAE)

I have a Windows command-line client that publishes data from local files to pubsub. These messages are consumed by a push subscription (handler within a GAE app).  This part works great. The encoding and decoding of messages looks like this:

```python
# encoding  (publisher_client is a google.cloud.pubsub.PublisherClient)
publisher_client.publish( some_topic, json.dumps(some_dict).encode('utf-8') )

# decoding from an HTTP body (using WebOb request.body):
envelope = json.loads( request.body )
data = json.loads( base64.b64decode( envelope['message']['data'] ) )
```

In the same application, messages are published internally within the GAE app to other push subscriptions. **The messages in this case end up double base64-encoded in the HTTP body**, despite the encoding and decoding being indistinguishable -- the _same_ code is run on the subscriber side, and _identical_ code to the above on the publisher side.

I did see #2771, but was an old and closed issue, so I assume something different is happening here.

**UPDATE 28 Sep**:  
I don't think it's Windows related. I built the command-line client to run from a linux box and it also ran fine. So I think it's something to do with the encoding of messages published from within the Google App Engine app, as distinguished from published from the outside. Though this doesn't make much sense to me why it would be different.

**Comment by tseaver** [comment]
@ericgj Can you debug the GAE app and dump the "raw" message before it is passed to `publisher_client.publish`?  I'm wondering if somehow it is being base64-encoded before then.

**Comment by ericgj** [comment]
OK. When I get a moment I'll make a minimal example.

**Comment by tseaver** [comment]
@theacodes Can you suggest anything which would explain the double encoding?

**Comment by tseaver** [comment]
@ericgj Please feel free to reopen with the additional information.
