### ISSUE TITLE
Trace: docs have bad url for "Library Documentation"

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6140]
https://googlecloudplatform.github.io/google-cloud-python/latest/trace/starting.html is linked to from the root of the latest trace docs. This page doesn't seem to exist.

**Comment by tseaver** [comment]
It looks like the content is now subsumed into `trace/README.rst` / `docs/index.html`.  Needs a static redirect, like `bigquery/docs/usage.html`.
