### ISSUE TITLE
PubSub module object has no attribute 'SubscriberClient'

### ISSUE THREAD

**Issue by mikeymezher** [googleapis/google-cloud-python#6149]
Exactly what the title says. Tried downgrading to 0.37.0 didn't work either. Full trace:
Traceback (most recent call last):
  File "t2t_pubsub_server.py", line 27, in <module>
    main()
  File "t2t_pubsub_server.py", line 12, in main
    subscriber = pubsub.SubscriberClient()
AttributeError: 'module' object has no attribute 'SubscriberClient'

Debian 

Env: 
absl-py==0.5.0
apache-beam==2.6.0
appdirs==1.4.3
arrow==0.12.1
asn1crypto==0.22.0
astor==0.7.1
atomicwrites==1.1.5
attrs==18.1.0
avro==1.8.2
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
backports.weakref==1.0.post1
beautifulsoup4==4.6.3
bf==1.8.3
bl==2.0.0
bleach==1.5.0
boto==2.44.0
bq==0.7.0
bz2file==0.98
cachetools==2.1.0
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
click==6.7
cloud-tpu-profiler==1.9.0
configparser==3.5.0
crcmod==1.7
cryptography==1.7.1
cssselect==1.0.3
cssutils==1.0.2
cycler==0.10.0
decorator==4.3.0
defusedxml==0.5.0
dill==0.2.8.2
docopt==0.6.2
docutils==0.14
entrypoints==0.2.3
enum34==1.1.6
fastavro==0.19.7
fasteners==0.14.1
Flask==1.0.2
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.2.0
gapic-google-cloud-datastore-v1==0.15.3
gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
gapic-google-cloud-pubsub-v1==0.15.4
gast==0.2.0
gax-google-logging-v2==0.8.3
gax-google-pubsub-v1==0.8.3
gcloud==0.18.3
Geohash==1.0
get==1.0.3
gevent==1.3.6
google==2.0.1
google-api-core==1.4.1
google-api-python-client==1.7.4
google-apitools==0.5.20
google-auth==1.5.1
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.2.0
google-cloud==0.34.0
google-cloud-bigquery==1.5.0
google-cloud-bigquery-datatransfer==0.1.1
google-cloud-bigtable==0.28.1
google-cloud-container==0.1.1
google-cloud-core==0.25.0
google-cloud-dataflow==2.5.0
google-cloud-datastore==1.4.0
google-cloud-dns==0.28.0
google-cloud-error-reporting==0.28.0
google-cloud-firestore==0.28.0
google-cloud-language==1.0.2
google-cloud-logging==1.4.0
google-cloud-monitoring==0.28.1
google-cloud-pubsub==0.38.0
google-cloud-resource-manager==0.28.1
google-cloud-runtimeconfig==0.28.1
google-cloud-spanner==0.29.0
google-cloud-speech==0.30.0
google-cloud-storage==1.6.0
google-cloud-trace==0.17.0
google-cloud-translate==1.3.1
google-cloud-videointelligence==1.0.1
google-cloud-vision==0.29.0
google-compute-engine==2.7.5
google-gax==0.15.16
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
googledatastore==7.0.1
greenlet==0.4.15
grpc-google-iam-v1==0.11.4
grpc-google-logging-v2==0.8.1
grpc-google-pubsub-v1==0.8.1
grpcio==1.15.0
gunicorn==19.9.0
gym==0.10.5
h5py==2.8.0
hdfs==2.1.0
html5lib==0.9999999
httplib2==0.11.3
idna==2.7
ipaddress==1.0.17
ipykernel==4.9.0
ipython==5.8.0
ipython-genutils==0.2.0
ipywidgets==7.4.1
itsdangerous==0.24
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
keyring==10.4.0
keyrings.alt==2.2
kiwisolver==1.0.1
libsass==0.14.5
Mako==1.0.7
Markdown==3.0.1
MarkupSafe==1.0
matplotlib==2.2.2
mistune==0.8.3
mock==2.0.0
monotonic==1.5
more-itertools==4.3.0
mpmath==1.0.0
nbconvert==5.4.0
nbformat==4.4.0
networkx==2.1
notebook==5.6.0
numpy==1.15.2
oauth2client==3.0.0
oauthlib==2.1.0
pandas==0.23.4
pandas-gbq==0.5.0
pandocfilters==1.4.2
pathlib2==2.3.2
pbr==4.2.0
pexpect==4.6.0
pickleshare==0.7.4
pluggy==0.7.1
ply==3.8
post==1.0.2
prometheus-client==0.3.1
prompt-toolkit==1.0.15
proto-google-cloud-datastore-v1==0.90.4
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
proto-google-cloud-pubsub-v1==0.15.4
protobuf==3.6.1
protorpc==0.12.0
psutil==5.4.5
psycopg2==2.7.4
ptyprocess==0.6.0
public==1.0.3
py==1.5.4
pyasn1==0.4.4
pyasn1-modules==0.2.2
pycparser==2.18
pycrypto==2.6.1
pydot==1.2.4
pyglet==1.3.2
Pygments==2.2.0
pygobject==3.22.0
pyparsing==2.2.0
pytest==3.7.0
python-dateutil==2.7.3
python-geohash==0.8.5
python-gflags==3.1.2
pytools==2018.5.2
pytz==2018.5
PyVCF==0.6.8
pyxdg==0.25
PyYAML==3.13
pyzmq==17.1.2
qtconsole==4.4.1
query-string==1.0.2
redis==2.10.6
request==1.0.2
requests==2.19.1
requests-oauthlib==1.0.0
rsa==4.0
scandir==1.7
scikit-learn==0.19.2
scipy==1.1.0
SecretStorage==2.3.1
Send2Trash==1.5.0
Shapely==1.6.4.post1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sklearn==0.0
style==1.1.0
subprocess32==3.5.2
sympy==1.2
tensor2tensor==1.9.0
tensorboard==1.11.0
tensorflow==1.11.0
tensorflow-metadata==0.9.0
tensorflow-serving-api==1.10.1
tensorflow-transform==0.9.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.3.1
tornado==5.1
tqdm==4.25.0
traitlets==4.3.2
typing==3.6.6
tzwhere==3.0.3
Unum==4.1.4
update==0.0.1
uritemplate==3.0.0
urllib3==1.23
virtualenv==16.0.0
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.4.1
xgboost==0.72.1

**Comment by tseaver** [comment]
Trying to reproduce in a fresh virtual environment:

```bash
$ python3.6 -m venv /tmp/gcp/6149
$ /tmp/gcp/6149/bin/pip install --upgrade setuptools pip wheel
...
Successfully installed pip-18.0 setuptools-40.4.3 wheel-0.32.0
 /tmp/gcp/6149/bin/pip install google-cloud-pubsub
...
Successfully installed cachetools-2.1.0 certifi-2018.8.24 chardet-3.0.4 google-api-core-1.4.1 google-auth-1.5.1 google-cloud-pubsub-0.38.0 googleapis-common-protos-1.5.3 grpc-google-iam-v1-0.11.4 grpcio-1.15.0 idna-2.7 protobuf-3.6.1 pyasn1-0.4.4 pyasn1-modules-0.2.2 pytz-2018.5 requests-2.19.1 rsa-4.0 six-1.11.0 urllib3-1.23
$ /tmp/gcp/6149/bin/python -c "from google.cloud import pubsub; print(pubsub.SubscriberClient.__name__)"
SubscriberClient
$ /tmp/gcp/6149/bin/pip freeze google-cloud-pubsub-f file:///home/tseaver/.pip/wheels
cachetools==2.1.0
certifi==2018.8.24
chardet==3.0.4
google-api-core==1.4.1
google-auth==1.5.1
google-cloud-pubsub==0.38.0
googleapis-common-protos==1.5.3
grpc-google-iam-v1==0.11.4
grpcio==1.15.0
idna==2.7
protobuf==3.6.1
pyasn1==0.4.4
pyasn1-modules==0.2.2
pytz==2018.5
requests==2.19.1
rsa==4.0
six==1.11.0
urllib3==1.23
```

My guess is that you have one or more old packages installed which are interfering:  in this case, the `gapic-google-cloud-pubsub-v1` is the likely culprit.  It was a dependency of older versions of `google-cloud-pubsub`, but is no longer needed.
