### ISSUE TITLE
Translate: 'Client.from_service_account_json' function problem

### ISSUE THREAD

**Issue by sdsy888** [googleapis/google-cloud-python#6152]
# Some specs in advance:
- OS type and version: ubuntu 16.04
- Python version: 3.6 in anaconda
- google-cloud-python version: latest (03/10/2018)
- Steps to reproduce: using the function `explicit()` given in [Passing the path to the service account key in code](https://cloud.google.com/docs/authentication/production#auth-cloud-explicit-python)
- code example: using the given code of [`Using the client library`](https://cloud.google.com/translate/docs/reference/libraries#client-libraries-install-python)

# Problem description
As indicated in [Passing the path to the service account key in code](https://cloud.google.com/docs/authentication/production#auth-cloud-explicit-python), we can either provide authentication credentials to your application code `by setting the environment variable ` or `by passing the path to the service account key in code`.

The first method works fine ( by setting the environment variable), but the second don't.

When I try to explicitly spicify the `json` file in code, the code `buckets = list(storage_client.list_buckets())` gets nothing. Thus, I got this error:

```
raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://developers.google.com/accounts/docs/application-default-credentials.
```

I've also found that some of issues mentioned this problem, but seems like no solutions right now. So, will this problem be fixed in future?

# Related issues
https://github.com/googleapis/google-cloud-python/issues/5449
https://github.com/googleapis/google-cloud-python/issues/1883
https://stackoverflow.com/questions/45501082/set-google-application-credentials-in-python-project-to-use-google-api

**Comment by sdsy888** [comment]
Or there might be a way of providing credentials that isn't mentioned by the official cloud API webpage: https://google-auth.readthedocs.io/en/latest/user-guide.html#service-account-private-key-files

**Comment by tseaver** [comment]
@sdsy888 a couple of questions:

- The "Using the client library" docs you link above are for the Translate API, not Cloud Storage.
- Please provide the complete traceback for your exception (so that we can see the code path.

Note that the following works for me:

```bash
$ python3.6 -m venv /tmp/gcp/6152
$ /tmp/gcp/6152/bin/pip install --upgrade setuptools pip wheel
...
Successfully installed pip-18.0 setuptools-40.4.3 wheel-0.32.0
$ /tmp/gcp/6152/bin/pip install google-cloud-storage
...
Successfully installed cachetools-2.1.0 certifi-2018.8.24 chardet-3.0.4 google-api-core-1.4.1 google-auth-1.5.1 google-cloud-core-0.28.1 google-cloud-storage-1.13.0 google-resumable-media-0.3.1 googleapis-common-protos-1.5.3 idna-2.7 protobuf-3.6.1 pyasn1-0.4.4 pyasn1-modules-0.2.2 pytz-2018.5 requests-2.19.1 rsa-4.0 six-1.11.0 urllib3-1.23
$ /tmp/gcp/6152/bin/python
```

```python
>>> from google.cloud.storage import Client
>>> creds_file = '<path-to-my-service-account.json>`
>>> client = Client.from_service_account_json(creds_file)
>>> list(client.list_buckets())
[<Bucket: ...>]
```

**Comment by sdsy888** [comment]
@tseaver Thank you for your reply!

Sorry I didn't make myself clear enough. I guess either I  `set the environment variable` in the wrong way, or there is something wrong with the code with the code.

I  try to use `Translate API`. And as  [`Translation API Client Libraries`](https://cloud.google.com/translate/docs/reference/libraries#client-libraries-install-python) says, I need to use the methods in [this link](https://cloud.google.com/docs/authentication/production#auth-cloud-explicit-python)  to set up the ` service account key`  or `the environment variable` implicitly or explicitly, am I right?

But, the `explicit` way of `Setting the environment variable` did not work. Here's the traceback:
```
Traceback (most recent call last):
  File "trans.py", line 25, in <module>
    translate.Client(target_language='en')
  File "/home/neo/anaconda3/lib/python3.6/site-packages/google/cloud/translate_v2/client.py", line 65, in __init__
    super(Client, self).__init__(credentials=credentials, _http=_http)
  File "/home/neo/anaconda3/lib/python3.6/site-packages/google/cloud/client.py", line 129, in __init__
    credentials, _ = google.auth.default()
  File "/home/neo/anaconda3/lib/python3.6/site-packages/google/auth/_default.py", line 306, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://developers.google.com/accounts/docs/application-default-credentials.
```
Also, I tried your code above, I still get a blank list `[]` using `list(client.list_buckets())`:
```python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud.storage import Client
>>> creds_file ='/home/neo/dataset/report_english/report-translation-7c37b6b50ce3.json'
>>> client = Client.from_service_account_json(creds_file)
>>> list(client.list_buckets())
[]

```

**Comment by tseaver** [comment]
Can you try the following to set up the translate client?

```python
from google.cloud import translate_v2

translate_client = translate_v2.Client.from_service_account_json(
    creds_file, target_language='en')
```

For the storage client:  getting an empty list back from `list(client.list_buckets()` just means that you haven't actually created any buckets for the project bound to your credentials file:  the credentials themselves are valid, or the call to `Client.from_service_account_json` would have raised an exception.

**Comment by tseaver** [comment]
Setting the environment variable should be (for bash):

```bash
$ export GOOGLE_APPLICATION_CREDENTIALS=/home/neo/dataset/report_english/report-translation-7c37b6b50ce3.json
```

**Comment by tseaver** [comment]
@sdsy888 Please reopen if you can add more information to this report.
