### ISSUE TITLE
IAM: Improve Policy docs

### ISSUE THREAD

**Issue by alexcwatt** [googleapis/google-cloud-python#6161]
It would help the Policy docs if there were an example of how to set bindings. The dunder methods don't have docstrings and so, without looking at the source, it's not very obvious how to assign roles and members to a policy.

```
policy = iam.Policy()
policy[role] = [iam.Policy.user(user_email)]
```

This will help people reading the docs for methods that take an `iam.Policy` who follow the link to the class definition and then can't figure out how to build the policy they want--for instance, for a new storage bucket. (I was helping a friend today who also found this confusing.)

I'm happy to contribute an example here but not sure how you all would like that done.

Edit: [Link to current Policy docs](https://googleapis.github.io/google-cloud-python/latest/core/iam.html#google.cloud.iam.Policy)

**Comment by tseaver** [comment]
@alexcwatt A PR adding a docstring with examples to the `Policy` class would do the trick, I think.

Also, in your example you can invoke the various static factories via the instance, e.g.:

```python
policy = iam.Policy()
policy[role] = [policy.user(user_email)]
```
