### ISSUE TITLE
Language: Unknown entity type 11

### ISSUE THREAD

**Issue by Sytten** [googleapis/google-cloud-python#6165]
Hi!
I faced this bug in production September 27th when using the language api to extract entities from text. Multiple requests got an entity type 11 which triggered an exception when I tried to match it with `Entity.Type`. Not sure what caused this to happen? What is a glitch on your side?

* OS: Linux (Latest Python 3.6 docker image)
* Python version: 3.6.6
* google-cloud-language==1.0.2

I can try to dig deeper to see which texts caused it to happen.

**Comment by tseaver** [comment]
The [`Entity.Type` enum](https://github.com/googleapis/googleapis/blob/cd17066d792649f1f089bad6fed4d10eda2be68d/google/cloud/language/v1/language_service.proto#L127-L151) does not have a value for `11`.  Can you please provide the full traceback produced by your code?

**Comment by Sytten** [comment]
I know that, the traceback is not very informative. Basically I do:
```python
self.entity_types = {
            value: key for key, value in vars(language.enums.Entity.Type).items()
            if not key.startswith('__')}
```
And then:
```python
 for row in query_result.entities:
    entity_category = self.entity_types[row.type]
```
Which on the 27 September resulted in a number of `KeyError: 11`

**Comment by Sytten** [comment]
An example of text that was submitted is:
```
Today's TMJ4 Latest Headlines | September 27, 6pm
Watch the latest headlines from Today’s TMJ4 any time.
```

**Comment by Sytten** [comment]
My current guesses:
1. A glitch on google server side
2. The field `type` gets overridden by another value on some edge case

**Comment by tseaver** [comment]
Can you show how you invoked the query?  Can you show the entire `query_result` protobuf message?

**Comment by Sytten** [comment]
Sadly I didn't log it and I am not sure how to reproduce it. We had some DNS issues around hat time, maybe that could have been the problem?

**Comment by tseaver** [comment]
I cannot reproduce now:

```python
>>> from google.cloud.language import LanguageServiceClient
>>> from google.cloud.language import types
>>> client = LanguageServiceClient()
>>> text = """\
... Today's TMJ4 Latest Headlines | September 27, 6pm
... Watch the latest headlines from Today’s TMJ4 any time."""
>>> 
>>> document = types.Document(content=text, language='en', type='PLAIN_TEXT')
>>> response = client.analyze_entities(document)
>>> response
entities {
  name: "TMJ4 Latest Headlines"
  type: OTHER
  salience: 0.5040660500526428
  mentions {
    text {
      content: "TMJ4 Latest Headlines"
      begin_offset: -1
    }
    type: PROPER
  }
}
entities {
  name: "headlines"
  type: WORK_OF_ART
  salience: 0.3171876072883606
  mentions {
    text {
      content: "headlines"
      begin_offset: -1
    }
    type: COMMON
  }
}
entities {
  name: "TMJ4"
  type: ORGANIZATION
  salience: 0.12375497072935104
  mentions {
    text {
      content: "TMJ4"
      begin_offset: -1
    }
    type: PROPER
  }
}
entities {
  name: "Today"
  type: WORK_OF_ART
  salience: 0.05499136075377464
  mentions {
    text {
      content: "Today"
      begin_offset: -1
    }
    type: PROPER
  }
}
language: "en"

```

Please reopen if you can provide more information.

**Comment by Sytten** [comment]
If I see it again, I will try to enable full logs.

**Comment by yurijmikhalevich** [comment]
@tseaver it's an issue happening with the `google-cloud-language` < 1.2.0 because the enum is missing recently added types (https://cloud.google.com/natural-language/docs/reference/rest/v1/Entity#Type — PHONE_NUMBER and following), but the query can return them anyway.

Example:
```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import language
>>> client = language.LanguageServiceClient()
>>> doc = language.types.Document(content='Hello on 12th of May!', type=language.enums.Document.Type.PLAIN_TEXT)
>>> client.analyze_entities(doc)
entities {
  name: "12th of May"
  type: 11
  metadata {
    key: "day"
    value: "12"
  }
  metadata {
    key: "month"
    value: "5"
  }
  mentions {
    text {
      content: "12th of May"
      begin_offset: -1
    }
  }
}
entities {
  name: "12"
  type: 12
  metadata {
    key: "value"
    value: "12"
  }
  mentions {
    text {
      content: "12"
      begin_offset: -1
    }
  }
}
language: "en"

>>> {int(value): key for key, value in vars(language.enums.Entity.Type).items() if not key.startswith('_')}
{0: 'UNKNOWN', 1: 'PERSON', 2: 'LOCATION', 3: 'ORGANIZATION', 4: 'EVENT', 5: 'WORK_OF_ART', 6: 'CONSUMER_GOOD', 7: 'OTHER'}
>>>
```
