### ISSUE TITLE
Vision: Intermittent failure on OCR, Successful on retrying the same file

### ISSUE THREAD

**Issue by arvindnrbt** [googleapis/google-cloud-python#6172]
```
"responses": [
        {
            "error": {
                "code": 4,
                "message": "Error reading file: gs://vision-temp-storage-us-global-cloud-ml-vision-prod/prod/0000009c0ad7cdc4-915b2471a343bacf/async-doc-page-30-id-0-cd5f7ae4467dee1f.png."
            },
            "fullTextAnnotation": {},
            "context": {
                "uri": "gs://xbucket/zzz/yyy.pdf",
                "pageNumber": 30
            }
        }
    ]
```
I have been getting this error randomly for the last two weeks when trying to perform OCR on some pdf files. Strangely, this has no recurrence when I retry the process with the same file. This has been generated in the output file with no error on the api call. This is hard to handle on production because when we try to parse a page from the file in runtime (after downloading the output json) we would be surprised with an error message and would have to process the entire document again to get the appropriate results for the pages that failed. One other thing to notice is, this doesn't happen frequently but when it happens, there are at least 3 - 4 failures like this. If this is not the appropriate repository to file this issue, please direct me to the right place. Thanks.

**Comment by tseaver** [comment]
@beccasaurus can you loop in the correct back-end team member for this issue?

**Comment by zinjiggle** [comment]
Captured, will take a look

**Comment by sduskis** [comment]
This seems like something that ought to be asked of the Vision support team should handle, not something that the clients can fix. You can find various support avenues here: https://cloud.google.com/vision/docs/support and here: https://cloud.google.com/support/docs/issue-trackers
