### ISSUE TITLE
Storage:  list_blobs does not populate prefixes without iterating results

### ISSUE THREAD

**Issue by rconnaug** [googleapis/google-cloud-python#6178]
When using the `Bucket.list_blobs` method, I noticed that the `prefixes` attribute does not get populated unless you first iterate over the resulting blobs:

I had a bucket whose contents look like:
```
/a/1
/a/2
/b/1
/c/1
```

Then in python:
```
>>> storage_client = storage.Client()
>>> bucket = storage_client.get_bucket('my bucket name')
>>> blobs = bucket.list_blobs(delimiter = '/')
>>> blobs.prefixes
set([])
>>> list(blobs)
[]
>>> blobs.prefixes
set([u'a/', u'b/', u'c/'])
```

This seems unintuitive and probably unintentional.

Using python 2.7.10, google-cloud-storage version 1.13.0

**Comment by tseaver** [comment]
@rconnaug The prefixes can only be discovered via iteration:  the results of the [`objects.list` API call](https://cloud.google.com/storage/docs/json_api/v1/objects/list) are paged, and the prefixes are accumulated from each page of the response.

**Comment by rconnaug** [comment]
Hi, thanks for the quick response.

That makes sense, but is there a way to iterate through the prefixes page by page?   Seems like I need to iterate through alllll of the blobs first, before the entire list of prefixes are available, rather than page by page.

I'm just comparing the python client to the `objects.list` API.  Using the API on the example bucket up above, if I set `delimiter` to `/` and `maxResults` to 1, then the result will return just the first prefix along with the nextPageToken to allow iteration through the prefixes page by page.  

ie,
```
{
 "kind": "storage#objects",
 "nextPageToken": "CgdzdHVkeTAv",
 "prefixes": [
  "a/"
 ]
}
```

Using the python client, if I do:
```
resp = bucket.list_blobs(delimiter ='/', max_results = 1)
```

The only way i can see to get `resp.prefixes` populated is to iterate over the entire `resp` iterator, which could be many pages of responses.

**Comment by rconnaug** [comment]
Ah, perfect, thanks!
