### ISSUE TITLE
GCP Project Label creation Error : "field [Project.parent] has issue [Project parent cannot be empty.]"

### ISSUE THREAD

**Issue by mrmahesh106** [googleapis/google-cloud-python#6188]
Hi Team ,

 I am trying to create labels for a project with Python but receiving below error. Please help on the same.
Error : - "field [Project.parent] has issue [Project parent cannot be empty.]"

Thanks
Mahesh

code snippet: 

```python
 project_body = {
            "projectId": "test1233",
            "labels": {
             "name": "auto-test"
             }
           }
           request = service.projects().update(projectId=project_Id, body=project_body)
           try:
             response = request.execute()
           except Exception as e:
            print(e)
```

**Comment by tseaver** [comment]
@mrmahesh106 It looks as though you are using the `google-api-python-client` library, which isn't supported in this repository.  Please report issues with it in its [own repository](https://github.com/googleapis/google-api-python-client/issues/).

We do maintain the `google-cloud-resource_manager` library here.  Using it to do the task would look like:

```python
from google.cloud import resource_manager

client = resource_manager.Client()
project = client.fetch_project('test1233')
project.labels['name'] = 'auto-test'
project.update()
```
