### ISSUE TITLE
Speech: speaker_tag has value 0

### ISSUE THREAD

**Issue by codeAshu** [googleapis/google-cloud-python#6192]
### Api

speech_v1p1beta1
---
### os

macOS 10.13.5

### python version

Python 2.7 
---
api version
Name: google-cloud-speech
Version:0.36.0
Summary: Google Cloud Speech API client library
----
If I set the config with diarization enabled, I get speaker_tag as `0` and then result repeat for speaker_tag as` 1` or other value. Sometimes it is only `0` . The [documentation](https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1p1beta1) says it should be any value between `1` and `diarization_speaker_count`.

**Comment by tseaver** [comment]
I'm sorry you are having this issue, but I'm afraid there is nothing in the `google-cloud-speech` library itself which could cause it.  The ["speaker diarization" feature](https://cloud.google.com/speech-to-text/docs/multiple-voices#speech-diarization-python) is marked as "beta" in the docs, and is still under development.

I would suggest reporting the issue to the back-end folks using one of the links on the [Cloud Speech support page](https://cloud.google.com/speech-to-text/docs/support).
