### ISSUE TITLE
Using autoML libraries

### ISSUE THREAD

**Issue by OrielResearchCure** [googleapis/google-cloud-python#6200]
Hello,

I am new to autoML and would like to run a simple example on Google datalab notebook.

I started with https://googleapis.github.io/google-cloud-python/latest/automl/index.html which works with google.cloud.automl_v1beta1 import PredictionServiceClient
I tried to install automl_v1beta1 which is not available 

-  pip install automl works but I could not find an example for using it.

Could you please refer me to an updated resource.

Thank you, 
eilalan

**Comment by tseaver** [comment]
`pip install google-cloud-automl` installs the latest distribution from [PyPI](https://pypi.org/project/google-cloud-automl/).  Once installed, you can either import `google.cloud.automl_v1beta1` (to use a specific version of the API):

```python
from google.cloud import automl_v1beta1

client = automl_v1beta1.AutoMlClient()
```

or import `google.cloud.automl` (to use the latest version of the API):

```python
from google.cloud import automl

client = automl.AutoMlClient()
```
