### ISSUE TITLE
Pub/Sub: return type`future` is not `concurrent.futures.Future` 

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/google-cloud-python#6201]
https://github.com/googleapis/google-cloud-python/blob/8f63393a151a22018a3d03c7a35576da25ee17b3/pubsub/google/cloud/pubsub_v1/publisher/client.py#L170

Contrary to what's in the [reference](https://gcloud-python.readthedocs.io/en/latest/pubsub/publisher/api/client.html#google.cloud.pubsub_v1.publisher.client.Client.publish), the correct return type for `publish()` should be `google.cloud.pubsub_v1.publisher.futures.Future`. I didn't find a reference for it but only some reference for [`google.cloud.pubsub_v1.subscriber.futures.StreamingPullFuture`](https://google-cloud.readthedocs.io/en/latest/pubsub/subscriber/api/futures.html). 

People won't be able to use of Python's concurrent library's `wait()` method on `google.cloud.pubsub_v1.publisher.futures.Future`. But our doc implies they can because we say the return type is `concurrent.futures.Future`.  

```Python
from concurrent.futures import wait
from google.cloud import pubsub_v1

publisher = pubsub_v1.PublisherClient()
# future has type `google.cloud.pubsub_v1.publisher.futures.Future`
future = publisher.publish('projects/{PROJECT_ID}/topics/{TOPIC_NAME}', data=b'rain')

# wait(fs, timeout=None, return_when='ALL_COMPLETED') expects a sequence of `concurrent.futures.Future`.  
wait([future])
```
Here is the error: 
```Python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 257, in wait
    with _AcquireFutures(fs):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 146, in __enter__
    future._condition.acquire()
AttributeError: 'Future' object has no attribute '_condition'
```
I tried in both Python 2 and 3.

**Comment by tseaver** [comment]
@theacodes can you comment?

**Comment by theacodes** [comment]
Yeah we should update it. It should additionally say that it conforms to the `concurrent.futures.Future` interface and can be used in similar ways, but it not completely compatible with `concurrent.futures` tools such as `wait()`.

**Comment by anguillanneuf** [comment]
Thanks! Listing a couple of places in the doc where we need it changed: 

1. https://google-cloud.readthedocs.io/en/latest/pubsub/publisher/api/client.html#google.cloud.pubsub_v1.publisher.client.Client.publish

2. https://google-cloud.readthedocs.io/en/latest/pubsub/publisher/index.html#futures

3. Could we expose this page in the API Reference and link 1&2 to it? https://github.com/googleapis/google-cloud-python/blob/master/pubsub/google/cloud/pubsub_v1/publisher/futures.py

**Comment by sam-qordoba** [comment]
If you end up here trying to figure out how to make a PubSub future _act_ like a concurrent Future, hopefully this code snippet will help

```python
if __name__ == "__main__":
    asyncio.set_event_loop(uvloop.new_event_loop())
    s1 = app.create_server(host="0.0.0.0", port=8090)
    task = asyncio.ensure_future(s1)

    print('creating subscription to pubsub')
    pubsub_future = subscriber.subscribe(subscription_path, callback=callback)
    # this is not really a future
    # so monkey patch
    pubsub_future._asyncio_future_blocking = True
    pubsub_future.__class__._asyncio_future_blocking = True
    s2 = asyncio.wrap_future(pubsub_future)

    task2 = asyncio.ensure_future(s2)
    try:
        loop.run_forever()
    except:
        loop.stop()
```

**Comment by ChameleonTartu** [comment]
> If you end up here trying to figure out how to make a PubSub future _act_ like a concurrent Future, hopefully this code snippet will help
> 
> ```python
> if __name__ == "__main__":
>     asyncio.set_event_loop(uvloop.new_event_loop())
>     s1 = app.create_server(host="0.0.0.0", port=8090)
>     task = asyncio.ensure_future(s1)
> 
>     print('creating subscription to pubsub')
>     pubsub_future = subscriber.subscribe(subscription_path, callback=callback)
>     # this is not really a future
>     # so monkey patch
>     pubsub_future._asyncio_future_blocking = True
>     pubsub_future.__class__._asyncio_future_blocking = True
>     s2 = asyncio.wrap_future(pubsub_future)
> 
>     task2 = asyncio.ensure_future(s2)
>     try:
>         loop.run_forever()
>     except:
>         loop.stop()
> ```

@sam-qordoba What is a `loop` in your example?

**Comment by sam-qordoba** [comment]
Ahh sorry, that was some code I had for using asyncio to run a Sanic web server and pubsub listener in the same process. The main part is

```python
        pubsub_future = subscriber.subscribe(
            subscription_path,
            callback=callback)

        # Google implemented a custom, psuedo-future
        # need monkey patch for it to work with asyncio
        pubsub_future._asyncio_future_blocking = True
        pubsub_future.__class__._asyncio_future_blocking = True
        real_pubsub_future = asyncio.wrap_future(pubsub_future)
```

**Comment by mar2194** [comment]
> Ahh sorry, that was some code I had for using asyncio to run a Sanic web server and pubsub listener in the same process. The main part is
> 
> ```python
>         pubsub_future = subscriber.subscribe(
>             subscription_path,
>             callback=callback)
> 
>         # Google implemented a custom, psuedo-future
>         # need monkey patch for it to work with asyncio
>         pubsub_future._asyncio_future_blocking = True
>         pubsub_future.__class__._asyncio_future_blocking = True
>         real_pubsub_future = asyncio.wrap_future(pubsub_future)
> ```

This saved me a lot of work/headache. Thank you!
