### ISSUE TITLE
Firestore: surprising DocumentReference.get behavior for non-iterable field_path argument

### ISSUE THREAD

**Issue by wsh** [googleapis/google-cloud-python#6203]
Hi there! :smile:

I've been trying to get a specific field on a document efficiently by specifying a field path in `get`, but I encountered some surprising behavior. The docs point out that `field_paths` is an optional _iterable_, but if you pass a single field argument like this:

```doc.get('foo')```

no fields are returned (`to_dict` on the resulting snapshot produces `{}`). If, however, you pass an invalid field path:

```doc.get('.foo')```

you'll get a validation error, which makes it seem like passing a _valid_ single field path would work. Only ```doc.get(['foo'])``` produces the expected result (a snapshot with only field `foo` present). This is an easy mistake to make! Maybe we could validate that users pass in an iterable?

This is from `google-cloud-firestore` version 0.29.0.

**Comment by tseaver** [comment]
The underlying issue here is that Python's `str` type *is* iterable.  In effect, `doc.get(`foo`)` is the same as `doc.get(['f', 'o', 'o'}`, which is why the snapshot is empty (none of the requested field paths are in it).

**Comment by tseaver** [comment]
@schmidt-sebastian, @jadekler Should `google-cloud-firestore` be adding special-case handling for the case that the user passes a single field name to `doc.get`?

**Comment by schmidt-sebastian** [comment]
`DocumentSnapshot.get()` should accept a single field path, and not an array of field paths. 

https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L693

**Comment by tseaver** [comment]
At least in [Python](https://github.com/googleapis/google-cloud-python/blob/d6bfb08ed3c5332d4bc91139c544c30d86019602/firestore/google/cloud/firestore_v1beta1/document.py#L395), `DocumentReference.get` takes an optional list of `field_paths` (not names, that was my mistake) and returns a snapshot.  If `field_paths` is passed, only the matching fields are included in the snapshot, via the `mask` argument of [`BatchGetDocumentsRequest`](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1beta1#google.firestore.v1beta1.BatchGetDocumentsRequest).

**Comment by schmidt-sebastian** [comment]
We are currently trying to figure out how to expose Field Mask in the Server SDKs in a consistent way for all SDKs. The expected state for these masks is that they are not exposed right now outside of Query API. As such, I cannot provide any guidance on how this API should behave.
