### ISSUE TITLE
Trouble importing from Google Cloud?

### ISSUE THREAD

**Issue by echan00** [googleapis/google-cloud-python#6228]
I have the Google Cloud SDK installed. I also have the translate client library in python installed:
`pip install --upgrade google-cloud-translate`

What else can possibly be wrong to not be able to import translate?
```
Python 2.7.10 (default, Oct  6 2017, 22:29:07)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> # Imports the Google Cloud client library
... from google.cloud import translate
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ImportError: cannot import name translate
```

**Comment by tseaver** [comment]
You likely have one of the following scenarios:

- The Python you are running is not the one where `google-cloud-translate` is installed (e.g., if you left a different virtualenv activated).  In the same command prompt where you launch `python`, try typing `pip freeze` and past the output here.  I recommend *never* activating a virtualenv for just this reason:  instead, I just type-and-tab the path to its `bin` directory and add the command I want.
- Some other package is installed in the environment which does not play nice in the `google` namespace.  Again, the output from `pip freeze` would provide useful clues.
- You have a really old pip or setuptools, which could also foul up the `google` namespace package.

Try creating a fresh virtualenv, and then install `google-cloud-translate` there.  E.g.:

```bash
$ python2.7 -m virtualenv /tmp/test_gcp_6228
New python executable in /tmp/test_gcp_6228/bin/python2.7
Also creating executable in /tmp/test_gcp_6228/bin/python
Installing setuptools, pip, wheel...done.
$ /tmp/test_gcp_6228/bin/pip install --upgrade setuptools pip
...
Looking in links: file:///home/tseaver/.pip/wheels
Requirement already up-to-date: setuptools in /tmp/test_gcp_6228/lib/python2.7/site-packages (40.4.3)
Requirement already up-to-date: pip in /tmp/test_gcp_6228/lib/python2.7/site-packages (18.1)
$ /tmp/test_gcp_6228/bin/pip install google-cloud-translate
...
Successfully installed cachetools-2.1.0 certifi-2018.10.15 chardet-3.0.4 futures-3.2.0 google-api-core-1.5.0 google-auth-1.5.1 google-cloud-core-0.28.1 google-cloud-translate-1.3.1 googleapis-common-protos-1.5.3 idna-2.7 protobuf-3.6.1 pyasn1-0.4.4 pyasn1-modules-0.2.2 pytz-2018.5 requests-2.19.1 rsa-4.0 six-1.11.0 urllib3-1.23
$ /tmp/test_gcp_6228/bin/python -c "from google.cloud import translate; print(translate.__file__)"
/tmp/test_gcp_6228/lib/python2.7/site-packages/google/cloud/translate.pyc
```

If that doesn't clarify your issue, please feel free to reopen with more information (e.g., the output from `pip freeze`).
