### ISSUE TITLE
Generated noxfiles missing 'cover' session

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python#6234]
They are also missing the `lint` session.

While the argument might be made, "they are autogen-only", the fact is that a) the `gapic-generator`, `synthtool`, etc. are software, and have bugs too; b) the local `synth.py` is perfectly capable of injecting its *own* bugs.

`videointelligence` is notable in this list because it is at "beta" support level, so we should expect higher code quality for it.

**Comment by busunkim96** [comment]
This has been resolved.
