### ISSUE TITLE
There are two distinct docs labels

### ISSUE THREAD

**Issue by dhermes** [googleapis/google-cloud-python#6266]
Currently [`documentation`][1] (798 total issues/PRs) and [`type: docs`][2] (31 total issues/PRs) are active labels

[1]: https://github.com/googleapis/google-cloud-python/issues?utf8=%E2%9C%93&q=label%3Adocumentation+
[2]: https://github.com/googleapis/google-cloud-python/issues?utf8=%E2%9C%93&q=label%3A%22type%3A+docs%22+

**Comment by JustinBeckwith** [comment]
Fixed! I went ahead and updated the open issues to use `type: docs`, and removed the previous label.

**Comment by dhermes** [comment]
@JustinBeckwith but now the 798 `documentation` issues have no label fulfilling the previous role?

**Comment by dhermes** [comment]
It depends on what you want to do with the labels. One might want to use them to say "what have we been spending on our time on", in which case labels on closed issues / merged PRs are meaningful.

**Comment by tseaver** [comment]
Removing labels is bad for institutional memory.  I'd have actually preferred to go the other way, and make the issues with `type: docs` have another type, but keep the old `documentation` label.
