### ISSUE TITLE
Speech: inconsistent behaviour (breaking changes)

### ISSUE THREAD

**Issue by abdelrahman-t** [googleapis/google-cloud-python#6276]
Provided is a test file in Turkish that was used as part of our tests. last time we have run the tests was SEPT 4 2018, Speech API was able to transcribe the file **correctly**, this is **suddenly no longer the case however.**

Case 1. (used to work correctly) ([test1.zip](https://github.com/googleapis/google-cloud-python/files/2495509/test1.zip))

Speech API (previous behavior - correct)
Mürat Öztürk

Current transcription:
Mürat Boz

other files that was working now returns empty responses, we use speech API as part of our pipeline and this had a massive impact on our services.

1. Google Speech API.

2.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

3. Python 3.6.3

4. google-cloud-speech==0.35.0

6. attached is a test file in Turkish

**Comment by chrisrossi** [comment]
It looks like this isn't a problem with the Python client, but with the API it's consuming.  How do we refer to this to the team responsible for the upstream API?

**Comment by tseaver** [comment]
@abdelrahman-t Just in case, I looked at the [Best Practices](https://cloud.google.com/speech-to-text/docs/best-practices) for the Speech API.  The doc says about sampling rate:

> Capture audio with a sampling rate of 16,000 Hz or higher.

and then later:

> if possible, set the sampling rate of the audio source to 16000 Hz. Otherwise, set the [`sample_rate_hertz`](https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#recognitionconfig) to match the native sample rate of the audio source (instead of re-sampling).

Your file is a WAV encoded at 44.1 KHz.  Is your application passing the `sample_rate_hertz` value in the `config` argument to `client.recognize`?

**Comment by abdelrahman-t** [comment]
I have tried explicitly passing the sample rate but it made no difference, I will experiment with different sample rates, but I am worried that these changes in API behaviour is due to changes to the underlying model.

thanks,

**Comment by tseaver** [comment]
@abdelrahman-t Thanks for clarifying.  The only other thing I noticed in your example file was the metallic click / slap sound shortly after the speaker finished:  I wouldn't expect that to have mattered to the API model, but perhaps it had some effect.

**Comment by abdelrahman-t** [comment]
@beccasaurus @tseaver what do you think is the problem?  what can i do if there are some change done to the Speech API?
