### ISSUE TITLE
Tasks has Client/Types API links under API Reference double listed

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6303]
https://googleapis.github.io/google-cloud-python/latest/tasks/index.html

Displayed at the bottom is the following, but shouldn't be duplicated
```
Api Reference
Client for Cloud Tasks API
Types for Cloud Tasks API Client
Client for Cloud Tasks API
Types for Cloud Tasks API Client
```

**Comment by tseaver** [comment]
The *text* of the links is duplicated, but they links themselves are different (`v2beta2` vs `v2beta3`).

**Comment by crwilcox** [comment]
Good point. We do need to differentiate these in the index.
