### ISSUE TITLE
Firestore: implement set such that it passes conformance testing

### ISSUE THREAD

**Issue by mcdonc** [googleapis/google-cloud-python#6307]
No master branch version of firestore has ever passed the class of conformance tests for the "set" command, which means someone (me) needs to deeply understand the Firestore spec and either make changes to the current impl to make those conformance tests pass or reimplement.

https://github.com/googleapis/google-cloud-python/issues/6290#issuecomment-433178371

**Comment by mcdonc** [comment]
We'll merge the https://github.com/mcdonc/google-cloud-python/tree/6307-implement-set-conformance branch back into Tres' 6290-firestore-refactor_conformance_tests branch represented by https://github.com/googleapis/google-cloud-python/pull/6291 once it has a positive review.

**Comment by mcdonc** [comment]
We decided to blacklist the tests that are related to ArrayRemove, ArrayUnion and Delete transforms.  We will reenable once we have a plan for implementing those features.

After the blacklisting, the branch currently has 6 failures.  These fall into three classes:

1) update-st-nested.textproto, update-st-multi.textproto

pbs_for_update doesn't populate update_mask properly when a ServerTimestamp is nested (not at the top level).  This appears to be a problem with the way process_server_timestamp returns field paths.

2) create-st-alone.textproto, update-st-alone.textproto

stray update field in write protobuf.  trying to make it do something different here breaks other tests, just haven't been able to pin the right juke down, probably should look more closely at the go and node impls.

3) set-st-merge-nonleaf-alone.textproto, update-st-dot.textproto

stray update field and update_mask field in write protobuf. similar to #2.

**Comment by mcdonc** [comment]
This clowny diff fixes set-st-merge-nonleaf-alone.textproto but it's clearly just working around the problem and there is some more fundamental way to fix it.
```
diff --git a/firestore/google/cloud/firestore_v1beta1/_helpers.py b/firestore/google/cloud/firestore_v1beta1/_helpers.py
index 59110aeb16..135dd5f2a1 100644
@@ -1153,7 +1153,18 @@ def _pbs_for_set_with_merge(document_path, document_data, merge, exists):
     write_pbs = []
     update_pb = write_pb2.Write()
 
-    if actual_data or create_empty:
+    update_paths = data_merge[:]
+
+    # for whatever reason, the conformance tests want to see the parent
+    # of nested transform paths in the update mask
+    # (see set-st-merge-nonleaf-alone.textproto)
+    for transform_path in transform_paths:
+        if len(transform_path.parts) > 1:
+            parent_fp = FieldPath(*transform_path.parts[:-1])
+            if not parent_fp in update_paths:
+                update_paths.append(parent_fp)
+    
+    if actual_data or create_empty or update_paths:
         update = document_pb2.Document(
             name=document_path,
             fields=encode_dict(actual_data),
@@ -1161,7 +1172,9 @@ def _pbs_for_set_with_merge(document_path, document_data, merge, exists):
         update_pb.update.CopyFrom(update)
 
         mask_paths = [
-            fp.to_api_repr() for fp in merge if fp not in transform_merge
+            fp.to_api_repr() for fp in merge if (
+                (fp not in transform_merge) or (fp in update_paths)
+                )
         ]
 
         if mask_paths or create_empty:
@@ -1218,6 +1231,7 @@ def pbs_for_update(client, document_path, field_updates, option):
 
     # for whatever reason, the conformance tests want to see the parent
     # of nested transform paths in the update mask
+    # (see update-st-nested.textproto)
     for transform_path in transform_paths:
         if len(transform_path.parts) > 1:
             parent_fp = FieldPath(*transform_path.parts[:-1])
```

**Comment by chemelnucfin** [comment]
@schmidt-sebastian, @jba, @mcdonc  I have converted the `merge` from an Option class to the `merge` and `exists` parameters passing all the tests that were there before.  In effect [this](https://github.com/chemelnucfin/google-cloud-python/tree/firestore_fix_before_rebase) is about the place I should have at least left the code at (before cleanup).

After rebasing to [master](https://github.com/chemelnucfin/google-cloud-python/tree/firestore_fix_rebase_master) it seems that there are more tests that need to be done to pass the conformance tests than before and it seems like I'm about 15 tests behind @mconc even after taking away the `ArrayUnion/ArrayRemove/Delete` tests.  Some of which seem easy to fix, and I will try to clean up the code a bit and perhaps there will be some commonality to compare and contrast to fix the remaining bugs.

**Comment by mcdonc** [comment]
@chemelnucfin the recent comments above refer to https://github.com/mcdonc/google-cloud-python/tree/6307-implement-set-conformance which evolved to not have a MergeOption class, instead using the master pattern of merge= to set. Its unclear where you branched from but you may want to base your work on that branch as it has all but 4 tests passing. I received some of your code for apirepr parsing in there too.

**Comment by tseaver** [comment]
Via #6291.
