### ISSUE TITLE
Quick start steps enable Datastore API instead of Cloud Spanner API

### ISSUE THREAD

**Issue by dsrivast80** [googleapis/google-cloud-python#6321]
The "Quick Start" Steps on https://googleapis.github.io/google-cloud-python/latest/spanner/index.html, Step #3, says (and links to) " Enable the Google Cloud Datastore API".

This should clearly be fixed to point to Cloud Spanner API enablement.

**Comment by crwilcox** [comment]
It seems a few of our libs have this: https://github.com/googleapis/google-cloud-python/search?q=%22Enable+the+Google+Cloud+Datastore+API.%22&unscoped_q=%22Enable+the+Google+Cloud+Datastore+API.%22
