### ISSUE TITLE
DLP: 'inspect_content' raisies 'urllib3.exceptions.SSLError: [Errno 24] Too many open files'

### ISSUE THREAD

**Issue by fimafurman** [googleapis/google-cloud-python#6330]
1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types

Google DLP

2. OS type and version

CentOS 7

3. Python version and virtual environment information: `python --version`

3.6

4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`

Google DLP 0.9

5. Stacktrace if available

```python
urllib3.exceptions.SSLError: [Errno 24] Too many open files exception is thrown
2018-10-29 11:55:05 ERROR    AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f00a37556a0>" raised exception!
Traceback (most recent call last):
  File "/home/ffurman/stg/ai-services/aiservice/tools/venv/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 309, in ssl_wrap_socket
```

Could be similar to issue #5523 

6. Steps to reproduce

Call dlp.inspect_content(parent, inspect_config, item) a 500 times or more.

7. Code example

**Comment by fimafurman** [comment]
That did it, thank you! The Google Cloud Python sample code has dlp_client = dlp_v2.DlpServiceClient() within inspect_file() function. It might be useful to move it out or provide comments in that sample to instruct people to re-use the client to prevent these leaks.

https://cloud.google.com/dlp/docs/inspecting-images

**Comment by tseaver** [comment]
Thanks for linking that example:  I will try to get your report forwarded to the docs team.
