### ISSUE TITLE
Pub/Sub: mistake in publisher client example

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/google-cloud-python#6334]
It should have been `from google.cloud.pubsub_v1 import PublisherClient` in this line: https://github.com/googleapis/google-cloud-python/blob/23a3204770f68a56dba12d1a37058398773f3daf/pubsub/google/cloud/pubsub_v1/publisher/client.py#L156

**Comment by tseaver** [comment]
@anguillanneuf Is the example a mistake, or is it just a question of style?  The next line uses the module-qualified name: https://github.com/googleapis/google-cloud-python/blob/23a3204770f68a56dba12d1a37058398773f3daf/pubsub/google/cloud/pubsub_v1/publisher/client.py#L156-L157

Some folks prefer "import only modules" as a practice (I'm not one of them, but the usage doesn't bother me, either).

**Comment by anguillanneuf** [comment]
There is no `publisher_client` in google.cloud.pubsub_v1 in `google-cloud-pubsub==0.38.0`. 

```
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud.pubsub_v1 import publisher_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'publisher_client'
>>> from google.cloud.pubsub_v1 import PublisherClient
>>> 
```

**Comment by tseaver** [comment]
OK, the docstrings in the generated code all use this pattern:

```python
>>> from google.cloud import pubsub_v1
>>> publisher_client = pubsub_v1.PublisherClient()
```

I will fix in the hand-written docstrings for `pubsub_v1.publisher.client.Client.publish`, as well as in `pubsub_v1.subcriber.client.Client.subscribe`, which has a similar problem.
