### ISSUE TITLE
A library should not mess around with logging configuration of the app

### ISSUE THREAD

**Issue by nikhilk** [googleapis/google-cloud-python#6342]
The line in question is this:
https://github.com/googleapis/google-cloud-python/blob/e0130f52947c6af6576bc187efb58ea890bc80bf/logging/google/cloud/logging/handlers/handlers.py#L153

The code is adding a StreamHandler to the default/root logger.
An application owns the configuration of how logs are formatted, where they are written to etc. A library that got loaded in the transitive closure of dependencies should not be affecting the app's logging behavior.

**Comment by tseaver** [comment]
The `setup_logging` method is a convenience wrapper for app developers who wish to have all their logging pushed to the Google Cloud Logging API.  The library does not invoke it anywhere:  it will only be run if explicitly called.  See the [Integration with the Python logging module page](https://googleapis.github.io/google-cloud-python/latest/logging/stdlib-usage.html) in the docs for how / why developers might want this convenience.

**Comment by nikhilk** [comment]
I hadn't done an in-depth analysis of everywhere logging might be showing up... but it turns out google cloud libraries do bring in grpc which does have this: https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/framework/foundation/logging_pool.py#L20

(there might be other places, but at least that's where the first handler that gets added from is coming, based on detecting all callers of addHandler)

So I guess the place to move this bug is there! :)

**Comment by tseaver** [comment]
@nikhilk Thanks for following up with the grpc issue!
