### ISSUE TITLE
Firestore: add support for admin interface

### ISSUE THREAD

**Issue by cobookman** [googleapis/google-cloud-python#6344]
Missing RPC call of projects.databases.exportDocuments in Firestore Client library:
https://cloud.google.com/firestore/docs/reference/rest/v1beta1/projects.databases/exportDocuments

**Comment by tseaver** [comment]
Thanks for the report!  As the URL you link shows, the `exportDocuments` API (and the related `importDocuments` API) are exposed through the REST endpoint for the Cloud Firestore service.  In the gRPC endpoint, the equivalent functionality is part of the [Firestore Admin interface](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.admin.v1beta1), for which we do not currently have any support (including the CRUD methods for indexes).

**Comment by cobookman** [comment]
Ah didn't realize the RPC & Rest APIs differed like that && Makes sense.

thnx

**Comment by tchiotludo** [comment]
Any update on support for admin interface ? 

When doing integration test, [create index api](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.admin.v1#google.firestore.admin.v1.CreateIndexRequest) is mandatory in order to create index use by integration test.

**Comment by tseaver** [comment]
@BenWhitehead AFAIK this feature is not prioritized for Firestore.

**Comment by tseaver** [comment]
Superseded by #8664.
