### ISSUE TITLE
NDB: Consider making `ndb.eventloop` private.

### ISSUE THREAD

**Issue by chrisrossi** [googleapis/google-cloud-python#6376]
As near as I can tell, `ndb.eventloop`, in the current legacy usage, is already a *de facto* private module—I can't find any code outside of the `ndb` package calling it directly, and nothing in [the documentation](https://cloud.google.com/appengine/docs/standard/python/ndb/async) leads me to think it was ever part of the published API for `ndb`.

So, my suggestion is to, effectively, make explicit what already seems to be implicitly true by renaming `ndb.eventloop` to `ndb._eventloop`.  By making it explicitly private, we can be sure, going forward, that nothing in that module is part of the public,user facing API.

**Comment by dhermes** [comment]
I am big :+1: on this
