### ISSUE TITLE
[BigQuery] table schema update is misordening the fields

### ISSUE THREAD

**Issue by bgbraga** [googleapis/google-cloud-python#6383]
python 3.7.1
google-cloud-bigquery 1.6.0
tested os: mac and windows

Steps to reproduce:
1) insert or load data1.json and data1_schema.json
2) it will create a table like data1_schema.jpg
3) insert or load data2.json with schema update data2_schema.json
4) it will update the table like data2_schema.jpg
5) compare data2_schema.json and data2_schema.jpg. They should be equal but are different. Table update misorder the fields. Phone field should be appear after last_name.

I used google-cloud-bigquery 1.6.0 for table update. Tested with method update_table or load_table_from_uri + jobconfig. Same problem in both.

![data1_schema](https://user-images.githubusercontent.com/4409701/47970283-7c37ff80-e06a-11e8-822c-06b4d607ad79.jpg)
![data2_schema](https://user-images.githubusercontent.com/4409701/47970284-7cd09600-e06a-11e8-9a9d-aef833027c38.jpg)
[data1.json.txt](https://github.com/googleapis/google-cloud-python/files/2546353/data1.json.txt)
[data2.json.txt](https://github.com/googleapis/google-cloud-python/files/2546354/data2.json.txt)
[data1_schema.json.txt](https://github.com/googleapis/google-cloud-python/files/2546355/data1_schema.json.txt)
[data2_schema.json.txt](https://github.com/googleapis/google-cloud-python/files/2546356/data2_schema.json.txt)

**Comment by tseaver** [comment]
@bgbraga Can you please show how you are doing the "insert or load" steps you describe above in Python?

**Comment by bgbraga** [comment]
@tseaver 

**Table creation to use with insertAll:**
        table = bigquery.Table(table_ref, schema=schema)
        table = bigquery_client.create_table(table)

**Table update to use with insertAll:**
        table.schema = schema
        bigquery_client.update_table(table, ['schema'])

**Table create and update using Load:**
        job_config = bigquery.job.LoadJobConfig()
        job_config.source_format = bigquery.job.SourceFormat.NEWLINE_DELIMITED_JSON
        job_config.schema = schema
        job = bigquery_client.load_table_from_uri(uri, table_ref, job_config=job_config)


**Schema converted from JSON to SchemaField to be filled at table creation time:**
`[SchemaField('id', 'INTEGER', 'NULLABLE', None, ()), SchemaField('first_name', 'STRING', 'NULLABLE', None, ()), SchemaField('last_name', 'STRING', 'NULLABLE', None, ()), SchemaField('dob', 'DATE', 'NULLABLE', None, ()), SchemaField('addresses', 'RECORD', 'REPEATED', None, (SchemaField('status', 'STRING', 'NULLABLE', None, ()), SchemaField('address', 'STRING', 'NULLABLE', None, ()), SchemaField('city', 'STRING', 'NULLABLE', None, ()), SchemaField('state', 'STRING', 'NULLABLE', None, ()), SchemaField('zip', 'INTEGER', 'NULLABLE', None, ()), SchemaField('numberOfYears', 'INTEGER', 'NULLABLE', None, ())))]`

**Schema converted from JSON to SchemaField to be filled at table update time:**
`[SchemaField('id', 'INTEGER', 'NULLABLE', None, ()), SchemaField('first_name', 'STRING', 'NULLABLE', None, ()), SchemaField('last_name', 'STRING', 'NULLABLE', None, ()), SchemaField('phone', 'INTEGER', 'NULLABLE', None, ()), SchemaField('dob', 'DATE', 'NULLABLE', None, ()), SchemaField('addresses', 'RECORD', 'REPEATED', None, (SchemaField('status', 'STRING', 'NULLABLE', None, ()), SchemaField('address', 'STRING', 'NULLABLE', None, ()), SchemaField('city', 'STRING', 'NULLABLE', None, ()), SchemaField('state', 'STRING', 'NULLABLE', None, ()), SchemaField('zip', 'INTEGER', 'NULLABLE', None, ()), SchemaField('numberOfYears', 'INTEGER', 'NULLABLE', None, ())))]`

**Comment by bgbraga** [comment]
@tseaver these info are ok?
Please, could you remove tag "awaiting information" ?

**Comment by tseaver** [comment]
@tswast Can you please review?

**Comment by tswast** [comment]
`data1_schema.json.txt` doesn't contain a `phone` column. `data2_schema.json.txt` does.

I believe when you [add a column to a BigQuery table](https://cloud.google.com/bigquery/docs/managing-table-schemas), it is always appended to the end of the list of columns, and columns cannot be reordered. I'm not seeing this explicitly documented anywhere, though. I'll double check with the product team about this limitation and see if we can explicitly document it.

**Comment by tswast** [comment]
Got confirmation from the BigQuery team that adding a column always adds it to the end of the schema. I have CL 222091725 pending internally to document this.

**Comment by bgbraga** [comment]
Hi guys,

I opened that as a 'Feature Request', not a bug.
So I know that is not supported today. But it is nice if the new field are created in right order.
It is just a nice to have, not critical. So feel free to decide if that enhancement could be considered in the future of if it is not important.

**Comment by tswast** [comment]
@bgbraga Since this is an issue with the service, not the Python client, please file your feature request at https://issuetracker.google.com/issues/new?component=187149&template=1162659
