### ISSUE TITLE
bigtable 0.31.1 release on pypi

### ISSUE THREAD

**Issue by wuttem** [googleapis/google-cloud-python#6478]
Hi,
Could you please release the 0.31.1 version of the bigtable client to pypi ? This would make it much easier for us to upgrade.

**Comment by tseaver** [comment]
Release tagged on github:  https://github.com/googleapis/google-cloud-python/releases/tag/bigtable-0.31.1

**Comment by tseaver** [comment]
And available on PyPI: https://pypi.org/project/google-cloud-bigtable/0.31.1/
