### ISSUE TITLE
Please support array_contains in queries

### ISSUE THREAD

**Issue by RohanTalip** [googleapis/google-cloud-python#6479]
`array_contains` is supported in most other languages (Python and Ruby are holdouts) :
https://firebase.google.com/docs/firestore/query-data/queries#array_membership

Is there a timeframe for when this might become available for Python?

**Comment by RohanTalip** [comment]
@tseaver, thanks!  I'm assuming that you or someone else will create an internal bug or ticket to update https://firebase.google.com/docs/firestore/query-data/queries once this change is released?

**Comment by tseaver** [comment]
@RohanTalip I don't have access to the internal ticket system.

@crwilcox Can you bridge to the team that manages those snippets?

**Comment by RohanTalip** [comment]
@tseaver and @crwilcox, roughly when do you think this change will be released?

I see that [firestore-0.30.0](https://github.com/googleapis/google-cloud-python/releases/tag/firestore-0.30.0) was released on 2018-10-15.

Are there other changes that need to be rolled up into firestore-0.31.0 ?

**Comment by tseaver** [comment]
@RohanTalip There are a bunch of things pending.  Maybe by the beginning of December we will be in a place to make a release.

**Comment by RohanTalip** [comment]
@tseaver, OK, I'll monkey-patch this change until then.

**Comment by Emsu** [comment]
@tseaver I know you mentioned maybe at the beginning of December this would be released. Any updates?

**Comment by RohanTalip** [comment]
@Emsu, it looks like it was released 3 days ago: https://github.com/googleapis/google-cloud-python/releases/tag/firestore-0.31.0

**Comment by RohanTalip** [comment]
FYI, I just sent some feedback on https://firebase.google.com/docs/firestore/query-data/queries#array_membership via the "SEND FEEDBACK" button, that this is now supported in Python.  I linked to this issue in the feedback.
