### ISSUE TITLE
[Firestore] Add mergeFields option to set

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6544]
This may be related to https://github.com/googleapis/google-cloud-python/issues/6307

set(..., merge:true) exists, but set(..., mergeFields:[..]) does not.  
We originally only added mergeFields in clients that supported POJO mapping, but have since added this option to all SDKs.

**Comment by tseaver** [comment]
At this point, `merge` can be [one of `True`, `False`, or a list of field paths](https://github.com/googleapis/google-cloud-python/blob/50080450b6ff397fe7663bebad86de045601d639/firestore/google/cloud/firestore_v1beta1/batch.py#L77).  If they insist on having 'mergePaths' as a separate argument, we can accomodate it.

**Comment by crwilcox** [comment]
Closing as by design.
