### ISSUE TITLE
[Firestore] Add ARRAY_UNION, ARRAY_REMOVE ARRAY_CONTAINS FieldValues

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6546]
There is no support for FieldValue.arrayUnion()/FieldValue.arrayRemove() and no support for array-contains Queries.

**Comment by tseaver** [comment]
#6481 added support for the `array_contains` query operator.

We don't really have a `FieldValue` concept in Python:  rather, we will have wrappers (like `constants.DELETE_FIELD` or `constants.SERVER_TIMESTAMP`) which will be used to signal those transforms by embedding the in the native Python dict.  E.g.:

```python
from google.cloud.firestore_v1beta1 import ArrayUnion, ArrayRemove

document_data = {
    'a': {
        'b': ArrayUnion([3, 4, 5]),
        'c': ArrayRemove([2, 7]), 
    },
}
```
