### ISSUE TITLE
[Firestore] higher precision timestamps

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6547]
The Python SDK timestamps are lossy. The SDK doesn’t expose a way to retrieve timestamps with higher precision.

**Comment by tseaver** [comment]
I'm not sure what this item addresses.  We [expose the `timestamp_pb2.Timestamp` fields](https://github.com/googleapis/google-cloud-python/blob/9033bb72ab4b76f7bf629d25da2fd91d3d486305/firestore/google/cloud/firestore_v1beta1/document.py#L500-L521), which are full nanosecond precision.

For user-set values (versus the `DocumentSnapshot` attributes I linked), we have the `google.api_core.datetime_helpers.DateTimeWithNanos` subclass of the stdlib's `datetime.datetime`, but no conversion utilities between it and `timestamp_pb2.Timestamp`.
