### ISSUE TITLE
[Firestore] WriteBatch doesn't return instance so you cannot chain.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6548]
The WriteBatch methods don’t return the WriteBatch instances for chaining.

**Comment by tseaver** [comment]
We pretty much *never* do chaining in Python libs.

**Comment by tseaver** [comment]
I would suggest that the "Pythonic" way to provide multiple operations would be to make `WriteBatch` a context manager, invoking `commit` from within its `__exit__`.  E.g.:

```python
with client.batch() as batch:
    batch.create(client.document('documents', 'foo'), {...})
    batch.set(client.document('documents, 'bar'), {...}, merge=True)
    batch.delete(client.document('documents, 'baz'))
```

I'm surprised that it doesn't already operate this way.
