### ISSUE TITLE
[Firestore] Field Path escaping in python doesn't match other languages

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6549]
There are no FieldPath overloads in the SDK. Instead, there is a field_path() method that returns an encoded string. While the Python SDK expects fully escaped field paths, 
other SDKS escape user-provided field paths by default and split on dots for this escaping.

**Comment by tseaver** [comment]
There is a bunch of work landed around field paths in #6291.  This issue need more clarity on the delta between that work and the desired outcome.

**Comment by tseaver** [comment]
#6770 landed a new [`split_field_path` helper](https://github.com/googleapis/google-cloud-python/blob/33eb5b5894427c839bd091d1af39a54186acc410/firestore/google/cloud/firestore_v1beta1/_helpers.py#L502-L534), which tokenizes / splits a string path "correctly" (as far as the conformance tests go, anyway).

I plan to split the `FieldPath` class and related helpers out into their own module, and try to normalize how path strings are handled everywhere.
