### ISSUE TITLE
[Firestore] un-constant server timestamp and delete values to support ARRAY_UNION, etc

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6551]
FieldValue.serverTimestamp() and FieldValue.delete() are exposed as constants, which will become problematic as we add arrayUnion()/arrayRemove()/numericAdd().

**Comment by tseaver** [comment]
There is no `FieldValue` in Python.  I am working now to refactor how the various transforms are handled, and do not expect to need a non-constant value for deleted fields or server timestamp-valued fields.

`ArrayUnion` and `ArrayRemove` will not be constants, but rather helper classes (see my comment in #6546).

We have no conformance tests for any `numeric_add` transform, and I do not see any corresponding element in the [`FieldTransform` docs](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1beta1#google.firestore.v1beta1.DocumentTransform.FieldTransform).

**Comment by crwilcox** [comment]
Closing as #6546 is the work item. This will be fixed if necessary via that issue.
