### ISSUE TITLE
[Firestore] FirestoreClient.list_collections() is missing, but is in DocumentReference.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6553]
FirestoreClient.list_collections() is missing, but it does exist as part of DocumentReference.

**Comment by tseaver** [comment]
The [`ListCollectionIds` API reference](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1beta1#google.firestore.v1beta1.Firestore.ListCollectionIds) describes the method:

> Lists all the collection IDs underneath a document.

I can see no reason to add such a method to the client:  it is pointless without first having a `DocuementReference`, at which point you just use its method.

**Comment by tseaver** [comment]
By hacking around, Firestore apparently accepts the database path as `parent` passed to the `ListCollectionIds` API:

```python
>>> from google.cloud.firestore_v1beta1 import Client
>>> client = Client()
>>> api = client._firestore_api
>>> list(api.list_collection_ids(parent=client._database_string))
['users']
```

So, we could reasonable expose `Client.collections()` returning that iterator.
