### ISSUE TITLE
[Firestore] Query start/end at/after accepts snapshots, doesn't properly apply implicit ordering.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6555]
Query.start_at()/start_after()/end_at()/end_after() accepts DocumentSnapshots, but doesn’t properly apply the implicit ordering.

**Comment by tseaver** [comment]
We have conformance tests for this one, but as I noted in #6533, we don't actually run them (and never have).

**Comment by tseaver** [comment]
Actual semantics are documented in #6665, including links to the conformance tests.  Closing this one in its favor.
