### ISSUE TITLE
[Firestore] Query.get returns incorrect type

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6558]
Query.get returns an Array of DocumentSnapshots, not a QuerySnapshot. QuerySnapshot are a requirement for Watch.

**Comment by crwilcox** [comment]
@mcdonc what is the status of this?

**Comment by crwilcox** [comment]
https://github.com/googleapis/google-cloud-python/blob/master/firestore/google/cloud/firestore_v1beta1/query.py#L698

This is currently returning an iterable of DocumentSnapshot. The request from the firestore team is that, to match node, this would return a QuerySnapshot. QuerySnapshots contain a list of 'docs', list of 'changes', and a 'readTime'.

Here is the corresponding class in node. https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L995

If were to take this change, I think it would make sense to enumerate the QueryDocumentSnapshots (docs). Query document snapshot is an extended class of DocumentSnapshot, though I am not 100% sure we need this as it doesn't seem to add additional data. We can likely just use DocumentSnapshot.

**Comment by tseaver** [comment]
In Python, `Query.get` is a parallel for Node's `Query.stream`.  Should we rename it to match (breaking existing users?)  Nobody needs the equivalent of Node's `Query.get`, AFAICT, exept the listen / watch implementation, which already works around its absence.

**Comment by tseaver** [comment]
@crwilcox As discussed in chat, I propose resolving this issue by:

- Renaming `Query.get` -> `Query.stream` (for conformance with Node's semantics).
- Leaving a docs-deprecated `Query.get` wrapper for `Query.stream`.

Later, if needed, we can add a `Query.get_snapshot` method with Node's `Query.get` semantics.
