### ISSUE TITLE
[BigQuery] provide a way to get all error messages from client libraries

### ISSUE THREAD

**Issue by bgbraga** [googleapis/google-cloud-python#6573]
Python Client Library: 1.7.0

**Limitation**
At code below, the error / exception from load job is a String with a high level overview of error. 
It is not give a clear message of what kind of error is happening.
```
        try:
            job = bigquery_client.load_table_from_uri(uri, table_ref, job_config=job_config)
            job.result(500)
        except Exception as e:
            print(e)
```
Example - Real error message: 
> Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 50435; errors: 1. Please look into the error stream for more details.

**Issue** 
It is not easy to fix the load error only reading that message.
If I didn't missed anything there is no way to get "bigquery error stream" using python client libraries.
For my point of view, is not possible to fix load issue only looking at information provided by client libraries.

**Workaround**
I found a way to get all messages using api-client-library.
The problem is: that library is not recommended and maybe it will be deprecated in future.
[https://developers.google.com/api-client-library/python/apis/bigquery/v2](https://developers.google.com/api-client-library/python/apis/bigquery/v2)

> While this library is still supported, we suggest trying the newer Cloud Client Library for BigQuery, especially for new projects. See BigQuery Libraries for installation and usage details.

`bigquery_discovery.jobs().get(projectId=project_id, jobId=job.job_id).execute()`

That api-client-library method provide some job data, including it:
```
    "errors": [
      {
        "reason": "invalid",
        "location": "gs://......",
        "message": "Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 50435; errors: 1. Please look into the error stream for more details."
      },
      {
        "reason": "invalid",
        "location": "gs://......",
        "message": "Error while reading data, error message: JSON parsing error in row starting at position 20236581: **No such field: Last Name**."
      }
    ]
```

In that case, the second message in array is clear and explain the problem better (**No such field: Last Name**).
Apparently we can't access that from python client libraries or bigquery job history ui 
_(note: it out of scope of that issue, but could be a good idea show all messages at job history ui to provide a better usability and understanding of problem instead of request user to filter stackdrive logging messages to find what is happening)._

**Request**
**The workaround to use api-client-library is working fine.** But please, don't deprecate api-client-library before implement a job description method contain all error messages that could be accessed from  python client libraries, ok?

**Comment by tseaver** [comment]
The [`LoadJob.errors`](https://googleapis.github.io/google-cloud-python/latest/bigquery/generated/google.cloud.bigquery.job.LoadJob.html#google.cloud.bigquery.job.LoadJob) attribute exposes that same list of error mappings.

**Comment by bgbraga** [comment]
Ok. Sorry. I just looking at exception object.
LoadJob have other attributes that are set even if the Job is surprised with an Exception.
Nice. Thanks.
