### ISSUE TITLE
[BigQuery] insertAll from client libraries

### ISSUE THREAD

**Issue by bgbraga** [googleapis/google-cloud-python#6574]
Python Client Library: 1.7.0

**Limitation**
Apparently there is not method insertAll at client library.
I'm using load for some cases:

`bigquery_client.load_table_from_uri(uri, table_ref, job_config=job_config)`

But for other cases I need to use streaming as a workaround to limit of 1000 load jobs by day to a table.

**Workaround**
I'm using api-client-library as workaround:

```
        response = bigquery_discovery.tabledata().insertAll(
            projectId=self.project_id,
            datasetId=self.dataset_id,
            tableId=self.table_id,
            body=body).execute()
```

The problem is: that library is not recommended and maybe it will be deprecated in future.
[https://developers.google.com/api-client-library/python/apis/bigquery/v2](https://developers.google.com/api-client-library/python/apis/bigquery/v2)

> While this library is still supported, we suggest trying the newer Cloud Client Library for BigQuery, especially for new projects. See BigQuery Libraries for installation and usage details.

**Request**
**The workaround to use api-client-library is working fine.** But please, don't deprecate api-client-library before implement insertAll method at python client libraries, ok?

**Comment by tseaver** [comment]
[`Client.insert_rows`](https://googleapis.github.io/google-cloud-python/latest/bigquery/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client.insert_rows) and [`Client.insert_rows_json`](https://googleapis.github.io/google-cloud-python/latest/bigquery/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client.insert_rows_json) provide access to the `tabledata.insertAll` API.
