### ISSUE TITLE
BigTable Row Data cells property not copy

### ISSUE THREAD

**Issue by zaccharieramzi** [googleapis/google-cloud-python#6643]
**Is your feature request related to a problem? Please describe.**
I was profiling the code I wrote that makes use of the BigTable client python API. I realised that it made a lot of calls to `deepcopy` and that these calls were very costly. It's actually because the `cells` property of a [row data](https://googleapis.github.io/google-cloud-python/latest/bigtable/row-data.html#cells) is actually returning a deep copy of the actual private `_cells` property. The fact is that I don't need all the cells information and I am only using it once so I don't really need the copy.

 **Describe the solution you'd like**
I think it would be nice to have the possibility to return the `_cells` property directly without copying. I imagine there are reasons why it has been coded like that, not offering the alternative, but I don't see them.

 **Describe alternatives you've considered**
Of course a hacky solution is to access directly the private property but it doesn't look like the right way to do it (i.e. `row._cells`).

**Comment by sduskis** [comment]
@zaccharieramzi: You can use the `find_cells` and `cell_value` methods to reduce the deepcopy.

@tseaver: the `deepcopy` issue continues to be a source of consternation.  We've been through this before (#4468).  This will continue to be a source of performance issues for users.  Can we remove the `deepcopy`?

**Comment by zaccharieramzi** [comment]
Thanks for the tip, it will indeed fix some of my use cases.

However when I want to access all columns (whose names I don't necessarily know in advance) it won't work. 

I think the `deepcopy` was introduced because of the [`clear`](https://github.com/googleapis/google-cloud-python/commit/163e98b52cc45ad3b819169b57c7072a3bc53089), but I don't think it's here anymore.

**Comment by tseaver** [comment]
@sduskis I thought y'all had already removed the `deepcopy` bits.
