### ISSUE TITLE
Datastore: Can't use next() on Datastore query

### ISSUE THREAD

**Issue by retnikt** [googleapis/google-cloud-python#6649]
You can use it in a for loop (it provides `__iter__`), but not with `next()` (it does not provide `__next__`, which makes it *not an iterator*). This should be fixed, or at very least renamed to something other than `Iterator`.
#### Environment details

1. Datastore
2. Windows 10, KDE Neon
3. Python 3.7.0 64-Bit
4. Google Cloud Datastore 1.7.1

#### Steps to reproduce

  1. Create a query and fetch it
  2. Use `next()` on it

#### Code example

```python
result = client.query().fetch()
next(result)
```

#### Stack trace
```
  File "<stdin>", line 1, in <module>
    item = next(result)
TypeError: 'Iterator' object is not an iterator
```

**Comment by tseaver** [comment]
The [language spec](https://docs.python.org/3/library/stdtypes.html#iterator.__next__) distinguishes between iterable containers and iterators.

Frankly, I don't see the need for it:  if you really want something you can call `next()` on, then use `iter()`, e.g.:

```python
result = client.query().fetch()
real_iterator = iter(result)
next(real_iterator)
```

**Comment by retnikt** [comment]
Well then it shouldn't be called 'Iterator' because that's very confusing

**Comment by tseaver** [comment]
@retnikt Maybe so, but it is a public API, and we cannot change it.
