### ISSUE TITLE
AutoML: Can payload image be stored in Cloud Storage?

### ISSUE THREAD

**Issue by JustusWest** [googleapis/google-cloud-python#6702]
I have a trained model with AutoML. I plan to use this model on a set of images that are stored in Google Cloud Storage. I was looking through the documentation for prediction [here](https://cloud.google.com/vision/automl/docs/reference/rest/v1beta1/projects.locations.models/predict#image). 
It's not entirely clear to me. Under Image the documentation says:
>Union field data. Input only. The data representing the image. For Predict calls [image_bytes][] must be set, as other options are not currently supported by prediction API. You can read the contents of an uploaded image by using the [content_uri][] field. data can be only one of the following:

inputConfig(a gcs location if I understand it correctly) is one of the following. So is inputConfig supported or does the payload have to be imageBytes (like it seems to say above).

**Comment by tseaver** [comment]
@beccasaurus Can you address the question?

**Comment by JustusWest** [comment]
It seems as though input_config is not supported. In my attempts to use it there was no way to make the request without setting image_bytes. I did find a work around if anyone else is trying to use cloud storage objects. Cloud Storage blobs have a method [download_as_string()](https://googleapis.github.io/google-cloud-python/latest/_modules/google/cloud/storage/blob.html#Blob.download_as_string). This returns the bytes of the object, which you can put right into image_bytes for a predict call.

**Comment by tseaver** [comment]
@JustusWest From the [protobuf description of `ExamplePayload`](https://github.com/googleapis/googleapis/blob/6f6505a69b2b0a1260c93e890d636eefb859e76e/google/cloud/automl/v1beta1/data_items.proto#L64-L72), it appears that you can pass *either* `image_bytes` (bytes) *or* an `input_config` mesage (of type [`InputConfig`](https://github.com/googleapis/googleapis/blob/6f6505a69b2b0a1260c93e890d636eefb859e76e/google/cloud/automl/v1beta1/io.proto#L27-L33)) as the `image` attribute.  E.g.:

```python
from google.cloud.automl_v1beta1.proto import data_items_pb2
from google.cloud.automl_v1beta1.proto import io_pb2
from google.cloud.automl_v1beta1 import PredictionServiceClient

client = PredictionServiceClient()
input_config = io_pb2.InputConfig(gcs_source="gs:<bucket-name>/<object-name>")
image = data_items_pb2.Image(input_config=input_config)
example_payload = data_items_pb2.ExamplePayload(image_image)
model_path = client.model_path('<project-id>', '<location>', '<model-name>')
response = client.predict(model_path, example_payload, ...)

```

```
