### ISSUE TITLE
Spanner: Operation_id missing in Spanner's Database.update_ddl method

### ISSUE THREAD

**Issue by potiuk** [googleapis/google-cloud-python#6737]
Library: google_cloud_spanner v. 1.6.1

We seem to miss operation_id in spanner_v1 of database.update_ddl(). 

It looks like the Spanner HTTP API supports operation_id: https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances.databases/updateDdl
GoogleAPI docs mention that Spanner's database.update_ddl() supports operation_id:
https://googleapis.github.io/google-cloud-python/latest/spanner/database-usage.html#update-an-existing-database.

Wy use (from pypi) google_cloud_spanner v. 1.6.1: This seems to be the latest released version (Released 10 Nov 2018). In the code of the library's Database object - contrary to the documentation there is no operation_id parameter in update_ddl statement and the operation_id seems to be hard-coded to “” in the actual API call:

https://github.com/googleapis/google-cloud-python/blob/master/spanner/google/cloud/spanner_v1/database.py#L257 

Is it intended? How else can we use operation_id

**Comment by tseaver** [comment]
Having that parameter missing from `Database.update_ddl()` looks like an oversight to me.
