### ISSUE TITLE
Logging: google.cloud libraries shouldn't create handlers on root logger by default

### ISSUE THREAD

**Issue by Hexcles** [googleapis/google-cloud-python#6742]
#### Environment details

1. This applies to the general logging mechanism of various `google.cloud.*` libraries (using `datastore` as an example in this issue).
2. OS type and version: gLinux
3. Python version and virtual environment information: `python --version`: Python 3.5.3
4. google-cloud-datastore version: 1.7.1

#### Steps to reproduce

Simply importing a `google.cloud` library would add a default handler to the root logger. This is a surprising behaviour and goes against the [best practices of logging in Python](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library): libraries shouldn't add handlers (other than a `NullHanlder`, if needed) by default, as users should be the ones to control logging.

Adding a handler to the **root** logger simply by importing the library is particularly bad, because it breaks the commonly used `logging.basicConfig(...)` pattern, which is usually executed in the main entry point *after* all the imports. Because of this behaviour of `google.cloud` libraries, `logging.basicConfig` would [become a no-op as there is already a handler on the root logger](https://docs.python.org/3/library/logging.html#logging.basicConfig).

#### Code example

```python
import logging

# No default handlers on root, as expected.
print(logging.getLogger().handlers)

from google.cloud import datastore

# A handler is created on root by the import.
print(logging.getLogger().handlers)

# This will hence be a no-op.
logging.basicConfig(level=logging.INFO)
```

**Comment by tseaver** [comment]
This is not an issue with `google.cloud-*`, but with `grpc`:  /grpc/grpc/issues/17017.  The fix for that bug was released in [`grpcio 1.16.1`](https://pypi.org/project/grpcio/1.16.1/).
