### ISSUE TITLE
Container: Regional Cluster support for GKE clusters

### ISSUE THREAD

**Issue by dbkegley** [googleapis/google-cloud-python#6838]
I'm unable to get or create regional clusters using the container_v1 client APIs. The [documentation](https://googleapis.github.io/google-cloud-python/latest/container/gapic/v1/api.html#google.cloud.container_v1.ClusterManagerClient.create_cluster) suggests that this is possible by using the `parent` parameter to describe the project/region to launch the cluster but I get the following errors:

```bash
(env) david@ ~ $ which python
~/dev/env/bin/python 

(env) david@ ~ $ pip freeze
...
google-api-core==1.6.0
google-auth==1.6.1
google-cloud==0.34.0
google-cloud-container==0.1.1
googleapis-common-protos==1.5.5
grpcio==1.16.1
...

(env) david@ ~ $ python --version
Python 2.7.10

(env) david@ ~ $ python ./get_cluster.py
Traceback (most recent call last):
  File "./get_cluster.py", line 6, in <module>
    cluster = client.get_cluster(project_id=credentials.project_id, parent='projects/<project_id>/locations/us-east1', cluster_id='ha-cluster-1')
TypeError: get_cluster() got an unexpected keyword argument 'parent'
```
 
Is it possible that the API documentation has been updated before the feature was merged or is it more likely an environment issue on my end? Any insight into this would be appreciated

I have also looked at using the [google-api-python-client](https://github.com/googleapis/google-api-python-client#google-api-client) to launch regional clusters but I would prefer to use this library if the feature is supported.  Are there any known workarounds for this?

**Comment by dazuma** [comment]
The source protos were [updated](https://github.com/googleapis/googleapis/commit/27aa9a664e8d94560c18dfae1e12f277036d9e33#diff-c8b4ce812f4fcba12ec4d26438c2b919) around Nov 6, and it looks like the documentation reflects that, and it looks like the [code](https://github.com/googleapis/google-cloud-python/tree/master/container/google/cloud/container_v1/gapic) has been generated in the repo itself as well. But https://pypi.org/project/google-cloud-container says the library itself was last released in February. @theacodes @tseaver Can we release an update to google-cloud-container?

**Comment by tseaver** [comment]
@dazuma I can make a release, if we're satisfied that the library is in good shape (given the weird codegen issues from earlier).

**Comment by dazuma** [comment]
@tseaver Yes we were able to update the gapic configs conservatively to avoid breaking changes in the library.
