### ISSUE TITLE
Datastore: 'test_empty_array_put' systest flakes with 503 Deadline Exceeded

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python#6859]
See: https://source.cloud.google.com/results/invocations/d630b05c-174f-49aa-97be-630fa44bd814/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-python%2Fpresubmit%2Fdatastore/log

```python
________________ TestDatastoreTransaction.test_empty_array_put _________________
self = <tests.system.test_system.TestDatastoreTransaction testMethod=test_empty_array_put>
    def test_empty_array_put(self):
        local_client = clone_client(Config.CLIENT)
        key = local_client.key("EmptyArray", 1234)
        local_client = datastore.Client()
        entity = datastore.Entity(key=key)
        entity["children"] = []
>       local_client.put(entity)
tests/system/test_system.py:551:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
google/cloud/datastore/client.py:421: in put
    self.put_multi(entities=[entity])
google/cloud/datastore/client.py:448: in put_multi
    current.commit()
google/cloud/datastore/batch.py:273: in commit
    self._commit()
google/cloud/datastore/batch.py:249: in _commit
    self.project, mode, self._mutations, transaction=self._id
google/cloud/datastore_v1/gapic/datastore_client.py:501: in commit
    request, retry=retry, timeout=timeout, metadata=metadata
../api_core/google/api_core/gapic_v1/method.py:143: in __call__
    return wrapped_func(*args, **kwargs)
../api_core/google/api_core/retry.py:270: in retry_wrapped_func
    on_error=on_error,
../api_core/google/api_core/retry.py:179: in retry_target
    return target()
../api_core/google/api_core/timeout.py:214: in func_with_timeout
    return func(*args, **kwargs)
../api_core/google/api_core/grpc_helpers.py:59: in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
value = ServiceUnavailable(u'Deadline Exceeded',)
from_value = <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	de...re/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":14}"
>
    def raise_from(value, from_value):
>       raise value
E ServiceUnavailable: 503 Deadline Exceeded

.nox/system-2-7/lib/python2.7/site-packages/six.py:737: ServiceUnavailable
```

**Comment by tseaver** [comment]
@IlyaFaer The "flaky" label indicates that the test failure is intermittent.  We would normally close such reports when we have made some change which we expect to address the failure (e.g., in this case, increasing the timeout in the gRPC configuration).  Unfortunately, we often have to reopen them. :(

**Comment by IlyaFaer** [comment]
@tseaver thanks for the explanation, I'll think about it

**Comment by tseaver** [comment]
There is something odd about that error response:  "Deadline Exceeded" should normally be a client-side exception (no HTTP response status code), while '503' should be "Service Unavailable" (returned from the Google front-end gateway during an outage).

We do have some history of having the backend APIs returning "odd" response codes.  @andrewsg Do you know if this is one such case for the Datastore API?

**Comment by andrewsg** [comment]
I haven't heard of this one from Datastore before, sorry.

**Comment by daaain** [comment]
I got this same error persistently when trying to use Datastore outside Flask context. I'm not really sure what does it have to do with Flask (could be a race condition fixed by waiting for Flask to boot up?), but thought I should share as it took a few hours to find the workaround...

**Comment by tseaver** [comment]
We haven't seen this error in our CI for ten months.
