### ISSUE TITLE
BigQuery: Magic cell should not displace DataFrame output when assigning a variable

### ISSUE THREAD

**Issue by brianquinlan** [googleapis/google-cloud-python#6907]
For example:

```
In [1]:  %%bigquery myvar
           SELECT badname
           FROM mytable
```

Since the output of the query is being assigned to 'myvar', it should not be output in the notebook. This would be consistent with how other cells work i.e.

```
In [1]: 5 + 5 # Result shown
```

```
In [1]: x = 5 + 5 # Result not shown
```

If backwards compatibility is an issue - and I don't think that it would be - you could make this a flag.

**Comment by tseaver** [comment]
@tswast, @alixhami Can you please comment?

**Comment by alixhami** [comment]
Are there other magics that assign variables and show no output? Magics tend to be inconsistent with code anyway, so I'd want to follow the example of other magics rather than how python cells behave.

I recognize that the user might want a way to suppress displaying all the results, though. Maybe a flag to suppress output or a flag to specify that you only want to display the head of the dataframe?

**Comment by tswast** [comment]
> the user might want a way to suppress displaying all the results

IMO, assigning it to a variable could actually be a good way to indicate this desire. If someone is assigning it explicitly to `myvariable`, then they clearly know that the next cell could be just `myvariable` (or `myvariable.head()`) to display it.

**Comment by brianquinlan** [comment]
@tswast Exactly! It would be my preference to not have any output if there is a successful variable assignment.

**Comment by alixhami** [comment]
I wanted to make sure this was a consistent behavior of magics, not just a preference. I looked through the Jupyter magics to see if I could find a precedent for this and found the following:

![image](https://user-images.githubusercontent.com/19769177/50242453-41bac580-037f-11e9-8bdc-323ce81d4b17.png)

Sending a PR to Tim now for the update.
