### ISSUE TITLE
BigQuery: magic cell `params` flag not documented

### ISSUE THREAD

**Issue by brianquinlan** [googleapis/google-cloud-python#6909]
The other params are documented at https://google-cloud.readthedocs.io/en/latest/bigquery/generated/google.cloud.bigquery.magics.html but not `params`.

**Comment by alixhami** [comment]
The documentation has been moved from readthedocs.io to github.io. Here is the current [Magics documentation](https://googleapis.github.io/google-cloud-python/latest/bigquery/generated/google.cloud.bigquery.magics.html#module-google.cloud.bigquery.magics).

@crwilcox It looks like the google-cloud.readthedocs.io page is stuck at v 1.5.0 for BigQuery. This is misleading to have an old snapshot of docs up. Can we get this to redirect?

**Comment by plamut** [comment]
It appears that `--params` is now documented, or am I missing something?
Seems like we can close this issue...

cc: @tswast

**Comment by plamut** [comment]
It appears that `--params` is now documented, and that this issue can be closed.

cc :@tswast

(if I'm missing something, please re-open the issue)

**Comment by tswast** [comment]
Yes. It's documented at https://googleapis.dev/python/bigquery/latest/magics.html It appears that redirects are working as expected.
