### ISSUE TITLE
documentation incorrectly claiming that the default is not to retry requests

### ISSUE THREAD

**Issue by bmenasha** [googleapis/google-cloud-python#6914]
This effects nearly every  APIs  but am looking at google-cloud-asset in particular. 
Name: google-cloud-asset
Version: 0.1.1

We document in nearly every client  that when retry is not  supplied then no retries are peformed:

retry (Optional[google.api_core.retry.Retry]):  A retry object used
                to retry requests. If ``None`` is specified, requests will not
                be retried.

This isn't true. We will retry according to gapic's  xxx_client_config.py  for the service which defines the default retry policy for the service. 

For example have this text for asset_export:  https://googleapis.github.io/google-cloud-python/latest/asset/gapic/v1beta1/api.html   yet I empirically verified that we do retry the request upon failure. 

It's a nice feature of the new python client libraries that some sane retries are enabled by default, we should document our  behavior correctly. 

thanks

**Comment by tseaver** [comment]
FWIW, the docstrings are generated from the corresponding comments in the `.proto` files (e.g., see the [`ExportAssets` RPC comment](https://github.com/googleapis/googleapis/blob/a207551d5190d2dc915ea261f19ce83eeee000d3/google/cloud/asset/v1beta1/asset_service.proto#L35-L39), with additional examples and additional parameter documentation added via the GAPIC generator: [parameter declaration](https://github.com/googleapis/gapic-generator/blob/e9cc7b716338a294e56b7fa76d6449d843ecbdd2/src/main/resources/com/google/api/codegen/py/main.snip#L304-L306), [parameter docstring generation](https://github.com/googleapis/gapic-generator/blob/e9cc7b716338a294e56b7fa76d6449d843ecbdd2/src/main/java/com/google/api/codegen/transformer/py/PythonApiMethodParamTransformer.java#L168-L194).

Fixing the retry docstrings involves changing the GAPIC generator and re-generating the library code.

**Comment by tseaver** [comment]
https://github.com/googleapis/gapic-generator/pull/2890 updates the generator to state that a default retry config will be used.  That change will roll out in an autogen bot scream one of these days.
