### ISSUE TITLE
IAM Gone?

### ISSUE THREAD

**Issue by gturetsky** [googleapis/google-cloud-python#6918]
`from google.cloud import iam`

^^^ No longer works after updating **google-cloud-api-core** and **google-cloud-python**.

This link is also a 404 now: https://github.com/googleapis/google-cloud-python/blob/master/core/google/cloud/iam.py

Thanks!

**Comment by gturetsky** [comment]
**Update:** Looks like this was moved to:

`from google.api_core import iam`

**Comment by tseaver** [comment]
@gturetsky You are correct.  We had to move the module to avoid expected conflicts with the new `google-cloud-iam` library.
