### ISSUE TITLE
Firestore: Using offset greater than 1000 on a query doesn't work

### ISSUE THREAD

**Issue by KiwiPolarBear** [googleapis/google-cloud-python#6924]
#### Environment details

macOS Mojave 10.14.1
Python 3.6
google-cloud-firestore==0.30.0

#### Steps to reproduce

  1. Create a query to get a large collection (over 1000 documents)
  2. Add an offset greater than 1000 to the query
  3. Get the query and iterate over the documents
  4. You should get an exception about having no documents

#### Code example

```python
from google.cloud import firestore

client = firestore.Client()

documents = client.collection('Collection').order_by('field').offset(1001).get()

for document in documents:
    pass
```

#### Stack trace
```
ValueError: Unexpected server response. All responses other than the first must contain a document. The response at index 1 was
read_time {
  seconds: 1544736718
  nanos: 109409000
}
skipped_results: 1
.
```

**Comment by tseaver** [comment]
Can you please show the whole traceback?  Also, are you sure there are at least 1000 documents in the collection?

**Comment by KiwiPolarBear** [comment]
Sure.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Source/....../scripts/.......py", line 21, in <module>
    for document in documents:
  File "/Source/......../venv/lib/python3.6/site-packages/google/cloud/firestore_v1beta1/query.py", line 599, in get
    raise ValueError(msg)
ValueError: Unexpected server response. All responses other than the first must contain a document. The response at index 1 was
read_time {
  seconds: 1544741917
  nanos: 761441000
}
skipped_results: 1
.
```

I am certain there are more than 1000 documents as making the same query with an offset of 1000, returns more documents.

**Comment by tseaver** [comment]
There is no indication in the [`StructuredQuery` API docs](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1beta1#google.firestore.v1beta1.StructuredQuery) of any upper bound on `limit`, and the `google-cloud-firestore` code doesn't do anything particular with the value beyond copying it into that message.

@shollyman Can you shed light on why the server would be returning a `RunQueryResponse` here with no `document` set?  If it is expected, what is the expected behavior within the client library?

**Comment by hishnash** [comment]
To verify I am also getting this bug with `.offset` in 0.31.0.

**Comment by tseaver** [comment]
Hmm, looking at the [API docs for `RunQueryResponse`](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1beta1#runqueryresponse), I note that the `document` field description says:

> A query result. Not set when reporting partial progress.

Response fields:

- The `transaction` field can only be set on the first response in the stream.
- `read_time` doesn't seem sensible if there is no document.
- `skipped_results`: I *guess* the back end could send a document-less response with this field set as a "still skipping" notification?

**Comment by tseaver** [comment]
Looking at `Query.get`, which [loops over the stream of `RunQueryResponse` messages](https://github.com/googleapis/google-cloud-python/blob/4ccf5682e5674a09a52e5fbe1e4035b005d4b92c/firestore/google/cloud/firestore_v1beta1/query.py#L744-L761), ISTM that we could just *not* raise the error for the empty document.  In fact, the whole thing could be simplified to the following, given that we don't return the `skipped_results` anywhere:

```python
        for response_pb in response_iterator:
            snapshot, _ = _query_response_to_snapshot(
                response_pb, self._parent, expected_prefix
            )
            if snapshot is not None:
                yield snapshot
```

I don't think raising exceptions about potential error cases from the back-end (non-empty response after empty first response, empty response after non-empty response) is useful here, given that we *know* the back end can return the empty response beyond the first one.

**Comment by tseaver** [comment]
@KiwiPolarBear I'm sorry this issue has been frustrating.  Could you try the patch in PR #7206 and see if it resolves your issue?

**Comment by hishnash** [comment]
@tseaver I have been able to test that branch I can confirm the bug seems fixed

for at least offset sizes of 8500 (with limit = 100) (that is the largest single collection I have in my current data set)

it also appears to return the same set of items as using the `start_after` with a `DocumentSnapshot` 

```
    try:
        first = next(collection.order_by(field).limit(1).get())
    except StopIteration:
        return
    yield first

    document = first

    while document is not None:
        documents = collection.order_by(field)

        chunk = documents.start_after(
            document
        ).limit(limit).get()

        document = None

        for document in chunk:
            yield document
```
