### ISSUE TITLE
BigQuery: 'Client.list_rows' returns more than 'max_results'

### ISSUE THREAD

**Issue by chrischan9008** [googleapis/google-cloud-python#6926]
Python 2.7
bigquery.__version__ , '1.8.0'
Issue: bigquery client list_rows returns results more than the max_results

**Codes**
from google.cloud import bigquery
import re
bq_client = bigquery.Client()
table_name = "bigquery-public-data.austin_crime.crime"
max_results=109999
start_index=0
chunk_size=109999
table = bq_client.get_table(table_name)
iterrows = bq_client.list_rows("bigquery-public-data.austin_crime.crime", selected_fields=table.schema,
                    max_results=109999, start_index=0, page_size=109999)
print iterrows.num_results

**the number of returned rows is 116675 > 109999.**

**Comment by tseaver** [comment]
@chrischan9008 The `max_results` value is used only to determine whether to fetch another page.  You have set the `page_size` really large, which causes extra values to be fetched  Try not passing it at all, e.g.:

```python
from google.cloud import bigquery

table_name = "bigquery-public-data.austin_crime.crime"
max_results=109999
start_index=0

bq_client = bigquery.Client()
table = bq_client.get_table(table_name)
iterrows = bq_client.list_rows(
    table,
    max_results=max_results,
    start_index=start_index,
)

list(iterrows)

print(iterrows.num_results)
```

Which yields `10999`.
