### ISSUE TITLE
result %%bigquery magic still shown when specifying destination_var

### ISSUE THREAD

**Issue by dkapitan** [googleapis/google-cloud-python#7011]
The documentation says:

> <destination_var> (optional, line argument):
> variable to store the query results. The results are not displayed if this parameter is used.

I have tried this with the example from the documentation, and the resulting dataframe is still shown

Environment:
  * OSX 10.14.2 (Mojave)
  * Python 3.6.5
  * IPython 6.5.0
  * Notebook server 5.6.0
  * pandas 0.23.4

**Comment by alixhami** [comment]
The library has not been released since this change was made. Please try again after the next release.

**Comment by tswast** [comment]
This has been released as of `1.9.0`.
