### ISSUE TITLE
Cloud billing: Manage budgets, BigQuery export via python

### ISSUE THREAD

**Issue by IrribarraC** [googleapis/google-cloud-python#7012]
One feature I consider important is being able to monitorize my projects billing. As for now, it is possible to do that by accessing the Cloud console first and set up budgets and their corresponding notifications following [this tutorial](https://cloud.google.com/billing/docs/how-to/notify). But when working on a corporation level, where hopefully projects will be generated in big numbers, it is needed to automatize this process entirely. I think every startup working on GCP would love a set_budget() feature in the cloud billing API, where one could both setup a money amount and turn on/off notifications for it. So it can after be handled with the Pub/Sub API. Other method for this would be an enable_bigquery_exports() option, and check the billing data there. (Of course, if both were possible would be even better)

**Comment by tseaver** [comment]
This repository is for the Python libraries which wrap the various Google Cloud APIs.  To request a feature like this, which would essentially be a new feature for the [Cloud Billing API](https://cloud.google.com/billing/) (not yet wrapped here), please use one of the [support resources](https://cloud.google.com/support-hub/).
