### ISSUE TITLE
Pyhton external_dependencies: 'google-cloud-pubsub' not working

### ISSUE THREAD

**Issue by girishghoda** [googleapis/google-cloud-python#7029]
#### Environment details

1. Google cloud pubsub
2. window 10
3. Python version: 3.6.3
4. google-cloud-pubsub version: 0.39.1

#### Steps to reproduce
I used google-cloud-pubsub in Odoo module. I tried to explain issue in step by step.
  1. Added 'google-cloud-pubsub' in external_dependencies in python manifest file:
     `"external_dependencies": {
        'python': ['google-cloud-pubsub']
    },`
2. When i published python module to Odoo server its threw below error:
`odoo.exceptions.UserError: ('Unable to install module "caliva_wsp" because an external dependency is not met: No module named google-cloud-pubsub', '')`

How to solved this issue?I already stuck at this point around 3 days.
Thanks!

**Comment by tseaver** [comment]
@girishghoda I'm afraid I don't have any experience with Odoo.  Installing `google-cloud-python` into a fresh virtual environment using `pip` works fine:

```bash
$ python3.6 -m venv /tmp/gcp/7029
$ /tmp/gcp/7029/bin/pip install --upgrade setuptools pip
...
Successfully installed pip-18.1 setuptools-40.6.3
$ /tmp/gcp/7029/bin/pip install google-cloud-pubsub
...
Successfully installed cachetools-3.0.0 certifi-2018.11.29 chardet-3.0.4 google-api-core-1.7.0 google-auth-1.6.2 google-cloud-pubsub-0.39.1 googleapis-common-protos-1.5.5 grpc-google-iam-v1-0.11.4 grpcio-1.17.1 idna-2.8 protobuf-3.6.1 pyasn1-0.4.5 pyasn1-modules-0.2.3 pytz-2018.7 requests-2.21.0 rsa-4.0 six-1.12.0 urllib3-1.24.1
```

Please feel free to reopen if you can identify a specific issue with how we are packaging `google-cloud-pubsub`.
