### ISSUE TITLE
Language:  502 Bad Gateway after processing few files

### ISSUE THREAD

**Issue by arycloud** [googleapis/google-cloud-python#7034]
I'm trying to implement Natural Language API using Python(3.6) where I need to process thousands of files from a directory, at the moment I'm reading the files one by one from the files directory then perform sentiment-analysis using NLP-API and then upload the results to the Cloud Storage Bucket.

Here's my code for performing sentiment-analysis:
```
def nlp_text_manager(text_path, name):
    text = text_path
    txt = Path(text_path).read_text(encoding='utf8')
    service = discovery.build('language', 'v1', credentials=credentials)
    service_request = service.documents().analyzeSentiment(
        body={
            'document': {
                'type': 'PLAIN_TEXT',
                'content': txt
            }
        }
    )
    response = service_request.execute()
    return response
```

But after processing ~200-300  files it returns an error as:

> raise HttpError(resp, content, uri=self.uri)
> 
> googleapiclient.errors.HttpError: https://language.googleapis.com/v1beta2/documents:analyzeSentiment?alt=json returned "Bad Gateway">
> 
> [30/Dec/2018 05:10:03] "POST / HTTP/1.1" 500 15162

**Comment by tseaver** [comment]
I suspect one of two things:  either the back-end API is / was experiencing transient issues, or else the 502 is being returned (wrongly, I think) due to quota or rate limiting issues.

Looking at the [Google Cloud Status page](https://status.cloud.google.com/), where Natural Language would be covered by the "Cloud Machine Learning" entry (I think), there don't seem to have been any recent service disruptions.

@beccasaurus, @lukasr, can you comment, please?

**Comment by arycloud** [comment]
Hi @tseaver,The status for Machine Learning api at [Google Cloud Status page](https://status.cloud.google.com/) is available.

**Comment by tseaver** [comment]
@arycloud I was looking at that page, and don't see any disruptions / outages for the ML APIs.

**Comment by beccasaurus** [comment]
Reached out to the team for more info incase they have more information about why the API might be 502'ing

**Comment by beccasaurus** [comment]
Likely network error, recommendation is to be sure to use retry logic in your code.

I noticed from the code sample that the Python Natural Language API client library isn't being used, you might want to try using the [`google-cloud-language`](https://pypi.org/project/google-cloud-language/) package. Getting started instructions available at [Cloud Natural Language API : Using Client Libraries](https://cloud.google.com/natural-language/docs/quickstart-client-libraries#client-libraries-usage-python)

Recommend: close this issue

**Comment by tseaver** [comment]
Thanks, @beccasaurus:  I didn't notice that the OP was using the `googleapiclient` library, rather than `google-cloud-language`.
