### ISSUE TITLE
Datastore: Entity KeyProperty losing id, returns ''

### ISSUE THREAD

**Issue by fish-bytes** [googleapis/google-cloud-python#7037]
After migrating NDB Python27 to python37 google-cloud-datastore Entities that store a Key value of a different entity (KeyProperty from NDB) and no long working.

Python returns that the object is a Key, it has a kind value, however name is returned as '' and the numeric id value comes back as None.

entity.path is returning "path[{'kind': 'UserAccount', 'name': ''}]" - all values are stored with auto-generated ids.  UserAccount "key literal" from the console shows as Key(UserAccount, 57xxxxx60) (obfuscated for security concerns)

It would appear that an incomplete path is being retrieved at query time.

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version
3. GAE Python37 (upgraded from Python27)
4. google-cloud-datastore version: 1.7.3

#### Steps to reproduce

Data Structure
Entity (Notebook )
Entity (UserAccount)
Notebook.creator = UserAccount.key
Notebook.creator._path[0].get("id")None #tried this to see if library

  1. nbquery = client.query(kind='Notebook')
  2. nbquery.fetch()
  3. nbrecord = list(nbquery)[0] #get just one record
  4. creatorid = nbrecord.creator.id #will return as None

flat_path will return ('UserAccount','')
kind will return 'UserAccount'
id_or_name will return ''

Thanks for the help, this is blocking issue for me right now.

**Comment by tseaver** [comment]
@fish-bytes Can you show a minimal example which actually creates the two entities and saves them, etc., before fetching them?

**Comment by tseaver** [comment]
The following example works as expected for me:

```python
from google.cloud import datastore


def main():
    client = datastore.Client()

    user_key = client.key('UserAccount', 'phred')
    user_account = datastore.Entity(key=user_key)
    user_account.update({'foo': 'bar'})
    client.put(user_account)

    notebook_key = client.key('Notebook', 'gcp-7037')
    notebook = datastore.Entity(key=notebook_key)
    notebook.update({'creator': user_key})
    client.put(notebook)

    nbquery = client.query(kind='Notebook')
    found = list(nbquery.fetch())[0]

    assert found['creator'] == user_key

    client.delete(user_key)
    client.delete(notebook_key)


if __name__ == '__main__':
    main()
```

Please feel free to reopen if you can provide more information.

**Comment by fish-bytes** [comment]
This is still an issue, my guess is that it is in the python client (I'm using 1.7.3) - if the id is a number rather than a string, the query returns incomplete key values

Modified Code:
user_key = client.key('UserAccount', 'phred')
        user_account = datastore.Entity(key=user_key)
        user_account.update({'foo': 'bar'})
        client.put(user_account)
        
        #existing user
        numUserKey = client.key('UserAccount',5760325647335424)
    
        notebook_key = client.key('Notebook', 'gcp-7037')
        notebook = datastore.Entity(key=notebook_key)
        notebook.update({'creator': user_key})
        client.put(notebook)
        
        notebook_key_byid = client.key('Notebook', 'gcp-7037_byid')
        notebookbyid = datastore.Entity(key=notebook_key_byid)
        notebookbyid.update({'creator': numUserKey})
        client.put(notebookbyid)
    
        found = client.get(notebook_key)
        logging.info('notebook_string:'+str(found))
        self.response.write('found:'+str(found))
        self.response.write('\n')
        foundid = client.get(notebook_key_byid)
        logging.info('notebook_id:'+str(foundid))
        self.response.write("found by id:"+str(foundid))

Returns
found:Notebook(key=<Key('Notebook', 'gcp-7037'), project=classroom-xinc>, creator=<Key('UserAccount', 'phred'), project=classroom-xinc>)
found by id:Notebook(key=<Key('Notebook', 'gcp-7037_byid'), project=classroom-xinc>, creator=<Key('UserAccount', ''), project=classroom-xinc>) <-----Notice the empty string for key value, I can't find a way for this to resolve properly.  

This was run in my project, not in the console - the console python3 continues to work correctly.

**Comment by fish-bytes** [comment]
> Please feel free to reopen if you can provide more information.

I don't think I can re-open, but I added more example in a later post to hopefully give you a reproduceable.

**Comment by tseaver** [comment]
I just checked:  the example I posted above works whether I use a string name or and integer ID for `user_key`.  Can you check your example to verify that you don't have a stray `Notebook` entity coming back in your `client.query()` results, with different values than you expect?
