### ISSUE TITLE
Pub/Sub doc: missing definition for `max_lease_duration` in FlowControl

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/google-cloud-python#7043]
The ref doc for [`max_lease_duration`](https://googleapis.github.io/google-cloud-python/latest/pubsub/types.html#google.cloud.pubsub_v1.types.FlowControl.max_lease_duration) does not describe what it is or how it is used, especially about how it interacts with ack deadlines. 

Given that this is an important config setting for long-running tasks, we may want to provide more documentation here by showing its default value (is it 2 hours), and explaining whether max lease duration restrains ack deadline modification or ack deadline modification overwrites max lease duration when one configures both flow control settings and ack deadlines.

**Comment by anguillanneuf** [comment]
@tseaver How can we bring the default values (mentioned [here](https://github.com/googleapis/google-cloud-python/blob/414f0261d74b38756ff5300112915b537bf2b8dd/pubsub/google/cloud/pubsub_v1/types.py#L64)) into the documentation?

**Comment by tseaver** [comment]
@anguillanneuf `FlowControl` is a [Python `namedtuple`](https://docs.python.org/2/library/collections.html#collections.namedtuple), which provides no way to inject any additional semantic information into its docstring, or those of its members.  We could generate a class derived from the named tuple, and put proto-a comment-based docstring, but we would still not be able to tweak docstrings for the members.

**Comment by anguillanneuf** [comment]
@crwilcox Surfacing this for your attention.

**Comment by plamut** [comment]
In Python 3.5+ the docstrings of namedtuples [can be updated](https://docs.python.org/3/whatsnew/3.5.html#collections):

```py
from collections import namedtuple

FlowControl = namedtuple("FlowControl", ["foo", "bar"])                                                                                                                                                                                                                  
FlowControl.__doc__ = "These are the flow control settings."                                                                                                                                                                                                                 
FlowControl.foo.__doc__ = "The foo setting does X"                                                                                                                                                                                                                       
FlowControl.bar.__doc__ = "The bar setting does Y"  
```

With the modifications, invoking `help(FlowControl)` displays the following (abbreviated):
```
Help on class FlowControl in module __main__:

class FlowControl(builtins.tuple)
 |  FlowControl(foo, bar)
 |  
 |  These are the flow control settings.
 |  
 |  Method resolution order:
 |      ...
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  foo
 |      The foo setting does X
 |  
 |  bar
 |      The bar setting does Y
 |  
 | ...
```
No more default _"Alias for field number X"_ descriptions of the members that end up in the linked docs.

In the code, we could optionally modify the namedtuples' docstrings if Python version >= 3.5, and [generate the docs](https://github.com/googleapis/google-cloud-python/blob/master/CONTRIBUTING.rst#documentation-coverage-and-building-html-documentation) using one of the officially supported Python versions (which are, in fact, Python 3.5+).

Would that solve the issue, or am i missing something?

**Comment by sduskis** [comment]
@plamut, It sounds like your solution would work.  Please do it.

**Comment by plamut** [comment]
@sduskis The `FlowControl` settings class is auto-generated, thus the change needs to be done in the code generator (the ticket that Tres linked above).

If Luke (the current assignee) is too occupied with other work, I can help, although I would first have to familiarize myself with the `gapic-generator` lib.

**Comment by sduskis** [comment]
oh.  Thanks for the info @plamut.   That sounds like a time intensive change, so I don't think that the effort is advisable in the near term. @anguillanneuf, I'm ok keeping this open, but this will be a very low priority.
