### ISSUE TITLE
IoT: segfault in list_devices

### ISSUE THREAD

**Issue by rvandegrift** [googleapis/google-cloud-python#7050]
The `list_devices` method segfaults when the `metadata` parameter is supplied.

#### Environment details
google-cloud-iot version: 0.2.0
OS: Debian buster
Python version: 3.7.2rc1

#### Code example
```python
from google.cloud import iot_v1
client = iot_v1.DeviceManagerClient()
list(client.list_devices('projects/asdf/locations/us-central1/registries/asdf', metadata=[{'k1': 'v1'}]))
```

**Comment by tseaver** [comment]
Trying to reproduce:

```bash
$ python3.7 -m venv /tmp/gcp/7050
$ /tmp/gcp/7050/bin/pip install --upgrade setuptools pip
...
Successfully installed pip-18.1 setuptools-40.6.3
$ /tmp/gcp/7050/bin/pip install google-cloud-iot
...
Successfully installed cachetools-3.0.0 certifi-2018.11.29 chardet-3.0.4 google-api-core-1.7.0 google-auth-1.6.2 google-cloud-iot-0.2.0 googleapis-common-protos-1.5.5 grpc-google-iam-v1-0.11.4 grpcio-1.17.1 idna-2.8 protobuf-3.6.1 pyasn1-0.4.5 pyasn1-modules-0.2.3 pytz-2018.7 requests-2.21.0 rsa-4.0 six-1.12.0 urllib3-1.24.1
$ gvim /tmp/gcp/7050/repro_gcp_7050.py  # add your code, tweak project
$ /tmp/gcp/7050/bin/python /tmp/gcp/7050/repro_gcp_7050.py
```
That raises an error (not a segfault):

```python
ValueError: metadata was invalid: [{'k1': 'v1'}, ('x-goog-request-params', 'parent=projects/XXX/locations/us-central1/registries/XXX'), ('x-goog-api-client', 'gl-python/3.7.1 grpc/1.17.1 gax/1.7.0 gapic/0.2.0')]
```

Note that the [docs for `DeviceManagerClient.list_devices`](https://googleapis.github.io/google-cloud-python/latest/iot/gapic/v1/api.html#google.cloud.iot_v1.DeviceManagerClient.list_devices) show that `metadata` is a sequence of tuples of the form, `(HEADER_NAME, HEADER_VALUE)`, not a dict.

Can you check the installed package versions in your environment against the following?

```bash
$ /tmp/gcp/7050/bin/pip freeze
-f file:///XXX/.pip/wheels
cachetools==3.0.0
certifi==2018.11.29
chardet==3.0.4
google-api-core==1.7.0
google-auth==1.6.2
google-cloud-iot==0.2.0
googleapis-common-protos==1.5.5
grpc-google-iam-v1==0.11.4
grpcio==1.17.1
idna==2.8
protobuf==3.6.1
pyasn1==0.4.5
pyasn1-modules==0.2.3
pytz==2018.7
requests==2.21.0
rsa==4.0
six==1.12.0
urllib3==1.24.1
```

**Comment by rvandegrift** [comment]
I discovered the segfault is inconsistent - try running it a few times in a row.  Both errors go away if I change the `dict` to a `tuple`.

My pip freeze is:
```$ /tmp/gcp/7050/bin/pip freeze
cachetools==3.0.0
certifi==2018.11.29
chardet==3.0.4
google-api-core==1.7.0
google-auth==1.6.2
google-cloud-iot==0.2.0
googleapis-common-protos==1.5.5
grpc-google-iam-v1==0.11.4
grpcio==1.17.1
idna==2.8
pkg-resources==0.0.0
protobuf==3.6.1
pyasn1==0.4.5
pyasn1-modules==0.2.3
pytz==2018.9
requests==2.21.0
rsa==4.0
six==1.12.0
urllib3==1.24.1
```

Perhaps related: the IoT API docs do not mention a `metadata` parameter - https://cloud.google.com/iot/docs/reference/cloudiot/rest/v1/projects.locations.registries.devices/list

What should `metadata` do?  I was hoping it'd provide a workaround for https://issuetracker.google.com/issues/122333181 but it doesn't appear to do anything.

**Comment by tseaver** [comment]
The `metadata` argument is used to pass metadata headers along with the gRPC request (e.g., user agent / library version info for analysis):  it isn't really intended for use at the application level.
