### ISSUE TITLE
Firestore: `document.set` always fails when running in python-rq

### ISSUE THREAD

**Issue by Kcrong** [googleapis/google-cloud-python#7110]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-python/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version
3. Python version and virtual environment information: `python --version`
4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`

#### Python version
3.6.6

#### Module version: 
**OS X Mojave 10.14.2**
- rq==0.13.0
- rq-dashboard==0.3.12
- rq-scheduler==0.9
- firebase-admin==2.14.0
- google-cloud-firestore==0.31.0

##### worker.py
```python
#!/usr/bin/env python
import random
import string
import sys
import logging

from redis import Redis
from rq import Connection, Worker

def randomkey(length):
    return ''.join(random.choice(string.ascii_lowercase) for _ in range(length))

logging.getLogger('rq.worker').propagate = False

logger = logging.getLogger("matching.queue")
logger.setLevel(logging.INFO)

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

stream_handler = logging.StreamHandler()
stream_handler.setFormatter(formatter)

file_handler = logging.FileHandler('worker-{}.log'.format(sys.argv[1] or randomkey(10)), encoding='utf8')
file_handler.setFormatter(formatter)

logger.addHandler(stream_handler)
logger.addHandler(file_handler)

with Connection(connection=Redis(host=current_config.REDIS_HOST, port=current_config.REDIS_PORT)):
    Worker(['default']).work()
```

##### rq_queue.py
```python
from firebase_admin import firestore

def queue():
    firestore.client().collection('collection_name').document('1').set({'id': 1})
```

##### rq_firebase.py
```python
from rq_queue import queue


def main():
    from app.config import current_config
    from datetime import datetime
    from rq_scheduler import Scheduler
    from redis import Redis
    import firebase_admin
    from firebase_admin import credentials

    config = current_config

    cred = credentials.Certificate(config.FIREBASE_KEY_FILE)
    firebase_admin.initialize_app(cred)

    scheduler = Scheduler(connection=Redis(host=config.REDIS_HOST, port=config.REDIS_PORT))

    # Start matching
    scheduler.enqueue_job(scheduler.schedule(
        scheduled_time=datetime.utcnow(),  # Time for first execution, in UTC timezone
        func=queue,  # Function to be queued
        args=[],  # Arguments passed into function when executed
        kwargs={},  # Keyword arguments passed into function when executed
        interval=10,  # Time before the function is called again, in seconds
        repeat=None  # Repeat this number of times (None means repeat forever)
    ))


if __name__ == '__main__':
    main()
```

##### Terminal 1
```bash
$ python worker.py
```
And open a new terminal. Let's call it `Terminal 2`
##### Terminal 2
```bash
$ python rq_firebase.py
// ERROR!!
```

#### Stack trace
```
15:12:50 RQ worker 'rq:worker:Kcrong-MacBook-Pro.77452' started, version 0.13.0
15:12:50 *** Listening on default...
15:12:50 Cleaning registries for queue: default
15:13:01 default: rq_queue.queue() (dc63be8d-42f6-4d02-ae06-72559ada54fb)
15:13:02 Moving job to 'failed' queue (work-horse terminated unexpectedly; waitpid returned 11)
15:13:04 Warm shut down requested
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by mcdonc** [comment]
Thanks for the report.

The waitpid status returned is 11 which means a segfault.  Note that the thing you called a stack trace isn't exactly a stacktrace, it's just output from rq.  It's unclear whether the code you enqueued actually ran or not, or whether the error has anything to do with firestore.  Do you see a document named 1 in the collection collection with the data you passed from the firestore web UI?

**Comment by Kcrong** [comment]
I wanted to write a real "stack trace" logs, but it didn't print any stack trace logs at all.
I think it just killed by segfault issue.

Also, I checked several stuff and figured out:
1. It works with a single process.
2. When it execute `commit` function inside gRPC module, it just be killed.
3. No changes at the firestore.

Ps.
A. I made the document named '1'. (You may know at 1 above)
B. The queue was actually enqueued, and ran other stuff (db, http requests, etc). But the firestore code.

**Comment by mcdonc** [comment]
Thanks for the info!  I'll see if I can reproduce it.

**Comment by tseaver** [comment]
Given the segfault, it seems likely that this is actually an issue with gRPC and forking, e.g. see https://github.com/grpc/grpc/issues/13873.  Please reopen if you can provide more information linking it to `google-cloud-firestore`.
