### ISSUE TITLE
Speech: 'long_running_recognize' fails for files shorter than 1 second

### ISSUE THREAD

**Issue by Zhdanovich** [googleapis/google-cloud-python#7120]
1. Speech to text
2. MacOS
3. Python 3.6
4. google-cloud-speech 0.36.0

#### Steps to reproduce

  1. Send an audio file that is shorter than 1 second
     I can observe similar behavior here: https://cloud.google.com/speech-to-text/ When I upload a short file, it doesn't give me any results
     The same code works well with files longer than 1s

#### Code example

```python
gaudio = types.RecognitionAudio(content=audio_buffer)
gconfig = types.RecognitionConfig(
    encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16,
    sample_rate_hertz=16000,
    language_code='en-US')
operation = gspeech_client.long_running_recognize(gconfig, gaudio)
response = operation.result(timeout=5.0)
```

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/main.py", line 127, in predict
    response = operation.result(timeout=5.0)  # timeout in seconds
  File "/usr/local/lib/python3.5/dist-packages/google/api_core/future/polling.py", line 127, in result
    raise self._exception
google.api_core.exceptions.GoogleAPICallError: None Unexpected state: Long-running operation had neither response nor error set.
```

Thanks!

**Comment by Zhdanovich** [comment]
I guess it probably an issue with the backend, then with API library itself.

**Comment by tseaver** [comment]
@beccasaurus Can you please confirm that this is a back-end issue?

**Comment by beccasaurus** [comment]
Huh, we just had another _"Unexpected state: Long-running operation had neither response nor error set."_ the other day (where the Operation had neither an error nor a response when marked as done)

https://github.com/googleapis/google-cloud-python/issues/7024

In that case, it was reproducible via `gcloud ml speech recognize-long-running`

@Zhdanovich can you reproduce this 1s audio files using the `gcloud` command?

```
gcloud ml speech recognize-long-running gs://BUCKET/foo.wav --language-code=en-US --sample-rate=44100 --async

gcloud ml speech operations describe <operation ID which previous command printed out>

# command will wait for the operation to finish
gcloud ml speech operations wait <operation ID which previous command printed out>

# the printed out operation should now be "done": true
# ideally an "error" or "response" field should also be present
# if not, this is a problem with the long-running operations
gcloud ml speech operations describe <operation ID which previous command printed out>
```

@tseaver Based on the message, it's fair to assume that this issue and #7024 are backend issues & not issues y'all need open on google-cloud-python

I filed a bug on the external Speech bug tracker (visible to all):
https://issuetracker.google.com/issues/122732566

@Zhdanovich feel free to add reproduction steps / information to that external ticket
