### ISSUE TITLE
Bigtable: Unable to use UTF8 encoding while setting a cell value using set_cell()

### ISSUE THREAD

**Issue by naveenwashere** [googleapis/google-cloud-python#7131]
The BigTable SDK does not seem to provide an option to explicitly specify an encoding type while writing to Big Table, using the [set_cell()](https://github.com/googleapis/google-cloud-python/blob/master/bigtable/google/cloud/bigtable/row.py#L292) method of the bigtable/row.py module (in-turn forcing ASCII encoding). This causes issues when the string that I'm trying to store in bigtable has special characters.

Upon investigating the SDK source code, we can see that though the `_to_bytes()` method [called internally by the `set_cell()` method of `bigtable/row.py` module] accepts encoding as a function argument, the `set_cell()` method does not allow us to supply the encoding.

So, this prevents us from being able to save any string that has UTF8 characters in them.

#### Environment details

1. API: BigTable
2. MacOS Mojave, while the production pipeline is deployed in GCP
3. Python 2.7
4. google-cloud-bigtable: 0.26.0, while this issue still exists in the latest version.

#### Steps to reproduce

Try to set a cell in the table with a string value that contains UTF8 characters, for example: `Café`, and you'll see the error similar to the one mentioned below.

#### Stack trace
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 6: ordinal not in range(128)
```
A fix along [these](https://github.com/naveenwashere/google-cloud-python/commit/454d2666099312147c5b8784b92345acb90617e7) lines should solve the problem. I don't have tests for my changes yet.

This issue has been raised with GCP support, and they requested that I raise the bug here as well.

Thanks!

**Comment by tseaver** [comment]
> So, this prevents us from being able to save any string that has UTF8 characters in them.

Bigtable's columns are designed explicitly to hold bytes, not text.  Your application needs to be aware of this fact, and manage converting any textual data to / from bytes (note that your suggested implementation still doesn't handle getting textual data *back* from the cell).

For instance, rather than:

```python
row = table.row(row_key)
row.set_cell(column_family_id, column, text_value, encoding='UTF8')
```

prefer:

```python
row = table.row(row_key)
row.set_cell(column_family_id, column, text_value.encode('UTF8'))
```

which is equally as clear, and even shorter!  On retrieving the cell value, the application can decode it because it knows the encoding:

```python
row = table.read_row(row_key)
text_value = row.cells[column_family_id][column][index].value.decode('UTF-8')
```

I'm therefore inclined not to add an `encoding` argument to the various `set_cell` implementations.  @sduskis, feel free to reopen if you disagree.

**Comment by naveenwashere** [comment]
Thanks for the quick response 🙏 

> Bigtable's columns are designed explicitly to hold bytes, not text.

Yes, I'm aware of this. 

The above solution works perfectly, when I'm only dealing with strings. In order to use the above solution, I would have to first add an `if` conditional, in my code to check for `unicode` type, and then explicitly apply UTF8 encoding. 

Somehow, it does not look like an elegant solution. The [to_bytes()](https://github.com/googleapis/google-cloud-python/blob/master/core/google/cloud/_helpers.py#L366) method in the `_helpers.py` module, already seems to do it for me (and more!), and also accepts an encoding type as an argument.

Also, if I may ask, when UTF8 seems to be general standard these days while working with strings, is there any reason why the Python SDK is enforcing `ASCII`? Shouldn't it be the other way around? This is where I feel that accepting encoding type as an argument to `set_cell` or any other related methods would be beneficial. I find this approach to be much cleaner, and also helps to take advantage of helper methods that the SDK already has (which seem to have been actually built for giving this choice, to the developers). Please correct me if I'm wrong.

> note that your suggested implementation still doesn't handle getting textual data back from the cell

My apologies, I haven't yet had a chance to complete the PR. But, there's already another helper method present in the same `_helpers.py` module, [_bytes_to_unicode()](https://github.com/googleapis/google-cloud-python/blob/master/core/google/cloud/_helpers.py#L373), that handles this conversion.

Thanks!
