### ISSUE TITLE
Bigtable: memory leak somewhere?

### ISSUE THREAD

**Issue by mxlei01** [googleapis/google-cloud-python#7207]
I have a python function that basically that appends a dictionary into BigTable.

```
@log_func
@google_clients(bigtable_enable=True)
def insert_row(client_bigtable, table, row_key, column_family_id, data):
    """Insert a row of data into BigTable.

    Args:
        client_bigtable (google.cloud.bigtable.Client): BigTable client.
        table (str): Table of google BigTable.
        row_key (str): Row key for BigTable.
        column_family_id (str): Column family the data is on.
        data (dict): A dictionary that stores data we want to keep in BigTable.

    Returns:
        None

    """
    # Generate an instance so that we can put our features into BigTable
    instance = client_bigtable.instance(config.BIGTABLE_INSTANCE)
    table = instance.table(table)

    # We need to keep a list of table changes into a list, then perform a mutation to update all changes.
    rows = []

    # Create a timestamp, this is required to set a cell
    time = datetime.datetime.utcnow()

    for key, value in data.items():
        row = table.row(row_key)
        # If we cannot convert to string, and this happens with unicode values, we need to encode the string
        # into unicode first
        row.set_cell(
            column_family_id=column_family_id.encode(),
            column=key.encode(),
            value=str(value).encode("unicode-escape"),
            timestamp=time
        )
        rows.append(row)
    table_mutation = table.mutate_rows(rows, retry=Retry(deadline=1200))

    # If the code is not 0, then there is an issue
    if any([True if i.code != 0 else False for i in table_mutation]):
        logging.error(f"Function Name: {insert_row.__qualname__}, Function Locals: {locals()}")
        raise RuntimeError("BigTable table mutation error")

```

I placed this function in Google Cloud Functions, and whenever I start writing, my memory consumption goes sky high until it reaches the maximum allowable memory.

![image](https://user-images.githubusercontent.com/7399324/51669849-8dfeb400-1f82-11e9-8538-fb9b63120a82.png)

Once I removed the BigTable writes, I now have constant memory consumption (At the end of the graph).

Is there another way to add data in BigTable that doesn't cause this?

Edit 1:

Removed bulk write `table.mutate_rows(rows)`, and used `row.commit()` instead, and the problem still persists.

Edit 2:

Tried updating `grpcio` package, tried to delete BigTable objects, and gc garbage collection:
```
    del instance
    del table
    del rows
    del table_mutation
    import gc
    gc.collect()
```

Problem still persists.

**Comment by mxlei01** [comment]
@sduskis @tseaver 

I've added a minimum code to test:

`cbt createtable test
cbt createfamily test data`

`os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "google_auth.json"`

`import datetime
import random
import sys
import os
import string

from google.cloud import bigtable
from google.api_core.retry import Retry

from mem_top import mem_top

def insert_row(project_id, instance, table, row_key, column_family_id, data):
    client_bigtable = bigtable.Client(project=project_id, admin=True)
    
    # Generate an instance so that we can put our features into BigTable
    instance = client_bigtable.instance(instance)
    table = instance.table(table)

    # We need to keep a list of table changes into a list, then perform a mutation to update all changes.
    rows = []

    # Create a timestamp, this is required to set a cell
    time = datetime.datetime.utcnow()

    for key, value in data.items():
        row = table.row(row_key)
        # If we cannot convert to string, and this happens with unicode values, we need to encode the string
        # into unicode first
        row.set_cell(
            column_family_id=column_family_id.encode(),
            column=key.encode(),
            value=str(value).encode("unicode-escape"),
            timestamp=time
        )
        rows.append(row)
    table_mutation = table.mutate_rows(rows, retry=Retry(deadline=1200))

    # If the code is not 0, then there is an issue
    if any([True if i.code != 0 else False for i in table_mutation]):
        logging.error(f"Function Name: {insert_row.__qualname__}, Function Locals: {locals()}")
        raise RuntimeError("BigTable table mutation error")`

`data = {
    ''.join(random.choices(string.ascii_uppercase + string.digits, k=15)):''.join(random.choices(string.ascii_uppercase + string.digits, k=15)) for _ in range(100)
}

while True:
    insert_row(
        project_id="user-tracking-228117",
        instance="analytics",
        table="test",
        row_key=f"{random.randint(0, sys.maxsize)}_{datetime.datetime.utcnow().strftime('%Y_%m_%d_%H_%M_%S_%f')}",
        column_family_id="data",
        data=data
    )`

Memory Consumption:

`34755 ubuntu    20   0 1118552 128968  21952 S   2.3  0.4   0:04.99 python3.6
34755 ubuntu    20   0 1118552 129844  21952 S   2.0  0.4   0:05.05 python3.6
34755 ubuntu    20   0 1118552 129968  21952 S   1.0  0.4   0:05.08 python3.6
34755 ubuntu    20   0 1118552 130780  21952 S   1.6  0.4   0:05.13 python3.6
34755 ubuntu    20   0 1119116 132212  21952 S   9.2  0.4   0:05.41 python3.6
34755 ubuntu    20   0 1119116 134008  21952 S   4.3  0.4   0:05.54 python3.6
34755 ubuntu    20   0 1119116 134944  21952 S   2.6  0.4   0:05.62 python3.6
34755 ubuntu    20   0 1119116 137924  21952 S   6.6  0.4   0:05.82 python3.6
34755 ubuntu    20   0 1119116 138536  21952 S   1.7  0.4   0:05.87 python3.6
34755 ubuntu    20   0 1119116 139988  21952 S   3.0  0.4   0:05.96 python3.6
34755 ubuntu    20   0 1119096 141768  21952 S  11.2  0.4   0:06.30 python3.6
34755 ubuntu    20   0 1119096 144140  21952 S   4.6  0.4   0:06.44 python3.6
34755 ubuntu    20   0 1119096 145140  21952 S   2.6  0.4   0:06.52 python3.6
34755 ubuntu    20   0 1119096 148648  21952 S   7.6  0.5   0:06.75 python3.6
34755 ubuntu    20   0 1119096 148920  21952 S   0.7  0.5   0:06.77 python3.6
34755 ubuntu    20   0 1119096 149828  21952 S   2.3  0.5   0:06.84 python3.6
34755 ubuntu    20   0 1119608 152796  21952 S  12.2  0.5   0:07.21 python3.6
34755 ubuntu    20   0 1119608 154692  21952 S   4.6  0.5   0:07.35 python3.6
34755 ubuntu    20   0 1119608 155448  21952 S   1.6  0.5   0:07.40 python3.6
34755 ubuntu    20   0 1119608 156656  21952 S   2.6  0.5   0:07.48 python3.6
34755 ubuntu    20   0 1119608 157724  21952 S   2.6  0.5   0:07.56 python3.6
34755 ubuntu    20   0 1119608 160796  21952 S   6.9  0.5   0:07.77 python3.6
34755 ubuntu    20   0 1119608 161616  21952 S   1.7  0.5   0:07.82 python3.6
34755 ubuntu    20   0 1185468 163896  21952 S  12.8  0.5   0:08.21 python3.6
34755 ubuntu    20   0 1185476 167612  21952 S   7.6  0.5   0:08.44 python3.6
34755 ubuntu    20   0 1185476 170552  21952 S   6.6  0.5   0:08.64 python3.6
34755 ubuntu    20   0 1185804 173848  21952 S  13.5  0.5   0:09.05 python3.6
34755 ubuntu    20   0 1185804 173848  21952 S   0.3  0.5   0:09.06 python3.6
34755 ubuntu    20   0 1185804 176724  21952 S   6.6  0.5   0:09.26 python3.6
34755 ubuntu    20   0 1185804 180588  21952 S   8.5  0.6   0:09.52 python3.6
34755 ubuntu    20   0 1185804 181524  21952 S   2.3  0.6   0:09.59 python3.6
34755 ubuntu    20   0 1186116 183228  21952 S  12.5  0.6   0:09.97 python3.6
34755 ubuntu    20   0 1186116 183228  21952 S   0.7  0.6   0:09.99 python3.6
34755 ubuntu    20   0 1186116 183276  21952 S   0.3  0.6   0:10.00 python3.6
34755 ubuntu    20   0 1186116 183296  21952 S   0.3  0.6   0:10.01 python3.6
34755 ubuntu    20   0 1186116 183332  21952 S   0.3  0.6   0:10.02 python3.6
34755 ubuntu    20   0 1186116 183436  21952 S   0.7  0.6   0:10.04 python3.6
34755 ubuntu    20   0 1186116 183516  21952 S   0.7  0.6   0:10.06 python3.6
34755 ubuntu    20   0 1186116 183616  21952 S   0.3  0.6   0:10.07 python3.6
34755 ubuntu    20   0 1186116 183656  21952 S   0.3  0.6   0:10.08 python3.6
34755 ubuntu    20   0 1186116 183656  21952 S   0.3  0.6   0:10.09 python3.6
34755 ubuntu    20   0 1186116 183680  21952 S   0.3  0.6   0:10.10 python3.6
34755 ubuntu    20   0 1186116 183708  21952 S   0.3  0.6   0:10.11 python3.6
34755 ubuntu    20   0 1186116 183728  21952 S   0.3  0.6   0:10.12 python3.6`

**Comment by patrickvalle** [comment]
@mxlei01 What version of this library are you running? And are you closing your gRPC channel when you're done with it? Version `0.31.1` exposes the gRPC channel so you can close it like what's mentioned @ https://github.com/googleapis/google-cloud-python/issues/7208#issuecomment-458653087.

**Comment by sduskis** [comment]
I would suggest creating a single `client_bigtable = bigtable.Client(project=project_id)`.  I agree with @patrickvalle.  Creating it over and over again, and not closing it is likely the problem.  I would also suggest not having `admin=True` which creates another connection the the Cloud Bigtable admin service.

**Comment by tseaver** [comment]
Closing, as the suggested best practice is to create a shared client instance (passing it into your `insert_row` function in the example).  If you *must* create the instance inside your `insert_row` for some reason, then you need to clean it up as well, e.g.:

```python
def insert_row(project_id, instance, table, row_key, column_family_id, data):
    client_bigtable = bigtable.Client(project=project_id, admin=True)
    try:
        ...  # your code here
    finally:
        client_bigtable.table_data_client.transport.channel.close()
```
