### ISSUE TITLE
Pubsub: No module named 'iam.v1',

### ISSUE THREAD

**Issue by ShaunWang965475263** [googleapis/google-cloud-python#7289]
2. Running on Datalab
3. 2.7 version

#### Steps to reproduce

 Simply trying to do:
from google.cloud import pubsub_v1 doesn't work

#### Code example

!pip install google-cloud-pubsub
from google.cloud import pubsub_v1

Thanks!

**Comment by tseaver** [comment]
@ShaunWang965475263 Can you please show the following:

- Output from `pip freeze`;
- The full traceback?

**Comment by ShaunWang965475263** [comment]
Hello,

I restarted the datalab VM and somehow it worked. Apache Beam seems very unstable, sometimes a module can be found, sometimes that module decides itself is not in the package..

Thanks

**Comment by tseaver** [comment]
@ShaunWang965475263 Please feel free to follow up if you can provide us with more information.

**Comment by mlotstein** [comment]
Same issue.
Traceback:
ImportErrorTraceback (most recent call last)
<ipython-input-14-d79141cec78b> in <module>()
      1 import time
      2 import datetime
----> 3 from google.cloud import pubsub
      4 import json
      5 import apache_beam as beam

/usr/local/envs/py2env/lib/python2.7/site-packages/google/cloud/pubsub.py in <module>()
     17 from __future__ import absolute_import
     18 
---> 19 from google.cloud.pubsub_v1 import PublisherClient
     20 from google.cloud.pubsub_v1 import SubscriberClient
     21 from google.cloud.pubsub_v1 import types

/usr/local/envs/py2env/lib/python2.7/site-packages/google/cloud/pubsub_v1/__init__.py in <module>()
     15 from __future__ import absolute_import
     16 
---> 17 from google.cloud.pubsub_v1 import types
     18 from google.cloud.pubsub_v1 import publisher
     19 from google.cloud.pubsub_v1 import subscriber

/usr/local/envs/py2env/lib/python2.7/site-packages/google/cloud/pubsub_v1/types.py in <module>()
     18 
     19 from google.api import http_pb2
---> 20 from google.iam.v1 import iam_policy_pb2
     21 from google.iam.v1 import policy_pb2
     22 from google.iam.v1.logging import audit_data_pb2

ImportError: No module named iam.v1

pip freeze:
absl-py==0.6.1
alembic==0.8.10
apache-airflow==1.9.0
asn1crypto==0.24.0
astor==0.7.1
avro==1.8.2
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
backports.weakref==1.0.post1
beautifulsoup4==4.7.1
bleach==2.1.2
blinker==1.4
bokeh==1.0.3
brewer2mpl==1.4.1
bs4==0.0.1
cachetools==2.1.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
Click==7.0
cloudpickle==0.6.1
configparser==3.5.0
crcmod==1.7
croniter==0.3.26
cryptography==2.3.1
cycler==0.10.0
cytoolz==0.9.0.1
dask==0.17.1
datalab==1.1.3
decorator==4.3.0
dill==0.2.6
distributed==1.21.8
docutils==0.14
entrypoints==0.2.3
enum34==1.1.6
fastcache==1.0.2
Flask==0.11.1
Flask-Admin==1.4.1
Flask-Cache==0.13.1
Flask-Login==0.2.11
flask-swagger==0.2.13
Flask-WTF==0.14
funcsigs==1.0.0
functools32==3.2.3.post2
future==0.16.0
futures==3.2.0
gast==0.2.2
ggplot==0.6.8
gitdb2==2.0.5
GitPython==2.1.11
google-api-core==1.8.2
google-api-python-client==1.6.2
google-apitools==0.5.10
google-auth==1.6.2
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.1.0
google-cloud==0.34.0
google-cloud-bigquery==0.23.0
google-cloud-core==0.28.1
google-cloud-dataflow==2.0.0
google-cloud-monitoring==0.28.0
google-cloud-pubsub==0.40.0
google-resumable-media==0.3.2
googleapis-common-protos==1.5.5
googledatastore==7.0.1
grpc-google-iam-v1==0.11.4
grpcio==1.17.1
gunicorn==19.9.0
h5py==2.7.1
heapdict==1.0.0
html5lib==1.0.1
httplib2==0.12.0
idna==2.6
imageio==2.4.1
ipaddress==1.0.22
ipykernel==4.8.2
ipython==5.8.0
ipython-genutils==0.2.0
ipywidgets==7.2.1
itsdangerous==1.1.0
Jinja2==2.8
jsonschema==2.6.0
jupyter-client==5.2.4
jupyter-core==4.4.0
lime==0.1.1.23
locket==0.2.0
lockfile==0.12.2
lxml==3.8.0
Mako==1.0.7
Markdown==2.6.11
MarkupSafe==1.1.0
matplotlib==2.1.2
mistune==0.8.4
mltoolbox-datalab-classification-and-regression==1.0.1
mltoolbox-datalab-image-classification==0.2
mock==2.0.0
msgpack==0.5.6
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.2
nltk==3.2.1
notebook==5.7.4
numpy==1.14.0
oauth2client==2.2.0
oauthlib==2.1.0
olefile==0.46
ordereddict==1.1
packaging==18.0
pandas==0.22.0
pandas-gbq==0.3.0
pandas-profiling==1.4.1
pandocfilters==1.4.2
partd==0.3.9
pathlib2==2.3.3
patsy==0.5.1
pbr==5.1.1
pexpect==4.6.0
pickleshare==0.7.5
Pillow==3.4.1
plotly==1.12.5
prometheus-client==0.5.0
prompt-toolkit==1.0.15
proto-google-cloud-datastore-v1==0.90.0
protobuf==3.6.1
psutil==4.3.0
ptyprocess==0.6.0
pyasn1==0.4.4
pyasn1-modules==0.2.2
pycparser==2.19
pydot==1.2.4
Pygments==2.1.3
PyJWT==1.7.1
pyOpenSSL==18.0.0
pyparsing==2.3.0
PySocks==1.6.8
python-daemon==2.1.2
python-dateutil==2.5.0
python-editor==1.0.3
python-nvd3==0.14.2
python-slugify==1.1.4
python-snappy==0.5.1
pytz==2018.4
PyVCF==0.6.8
PyWavelets==1.0.1
PyYAML==3.13
pyzmq==17.1.0
requests==2.18.4
requests-oauthlib==0.8.0
rsa==3.4.2
scandir==1.9.0
scikit-image==0.13.0
scikit-learn==0.19.1
scipy==1.0.0
seaborn==0.7.0
Send2Trash==1.5.0
setproctitle==1.1.10
simplegeneric==0.8.1
simplejson==3.16.0
singledispatch==3.4.0.3
six==1.10.0
smmap2==2.0.5
sortedcontainers==2.1.0
soupsieve==1.7.1
SQLAlchemy==1.2.16
statsmodels==0.8.0
subprocess32==3.5.3
sympy==0.7.6.1
tabulate==0.7.7
tblib==1.3.2
tensorboard==1.8.0
tensorflow==1.8.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.4.2
thrift==0.11.0
toolz==0.9.0
tornado==4.5.1
traitlets==4.3.2
Unidecode==1.0.23
uritemplate==3.0.0
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.2.1
WTForms==2.2.1
xgboost==0.6a2
zict==0.1.3
zope.deprecation==4.4.0
