### ISSUE TITLE
All doc links are broken

### ISSUE THREAD

**Issue by wsh** [googleapis/google-cloud-python#7290]
https://googleapis.github.io/google-cloud-python/ 404s. (read-the-docs redirects to it and also 404s.)

**Comment by crwilcox** [comment]
@wsh thanks for bringing this to our attention. In the process of cleaning up stale branches, this one got deleted. Turns out we didn't have branch protection enabled. I have republished the branch and added the appropriate safeguards to prevent this in the future.
