### ISSUE TITLE
Document using JSON string to create credentials from service account.

### ISSUE THREAD

**Issue by tab1293** [googleapis/google-cloud-python#7291]
It would be beneficial to be able to create a client instance using a service account file whose JSON contents have already been loaded in to memory. Currently `from_service_account_json` only supports loading a service account file from disk. This makes it difficult to create a client in scenarios where you are loading service account JSON contents from some external service and don't necessarily want to store the contents in a file where your application is running.

**Comment by tseaver** [comment]
As a workaround, you can use a tempfile:

```python
import tempfile
from google.cloud.<apilib> import Client

with tempfile.NamedTemporaryFile() as temp:
    temp.write(json_service_account_bytes)
    temp.flush()
    client = Client.from_service_account_json(temp.name)
```

The file will be closed / deleted when the `with` block exits.

**Comment by tab1293** [comment]
Yeah, a tempfile can be used (that's actually what I'm currently doing) but avoiding storing the key on disk is better. You should be able to pass the JSON string directly to the client constructor.

**Comment by mik-laj** [comment]
@tab1293 you could use a code similar to:
```python
credentials = google.oauth2.service_account.Credentials.from_service_account_info(keyfile_dict, scopes=scopes)
client = VideoIntelligenceServiceClient(credentials)
```
Real use case: https://github.com/apache/airflow/blob/master/airflow/contrib/hooks/gcp_api_base_hook.py

**Comment by tswast** [comment]
+1 to https://github.com/googleapis/google-cloud-python/issues/7291#issuecomment-471982254

I never really liked those factory functions. It's better to explicitly create a credentials object with the google-auth library.

**Comment by tseaver** [comment]
Rather than adding a `from_service_account_json` classmethod factory to each of the 95 or so clients which currently have `from_service_account_file` factories, let's instead just document how to construct credentials from JSON.

**Comment by simonobe** [comment]
are you kidding me that this is not supported?:D or is this just not updated as of yet?

**Comment by mik-laj** [comment]
@busunkim96  Is it done?

**Comment by iennae** [comment]
The PR was merged on December 14, and the details look up to date now with a working example. Please reopen if the update is insufficient. Thank you.
