### ISSUE TITLE
Segmentation Fault on types

### ISSUE THREAD

**Issue by dwagon** [googleapis/google-cloud-python#7298]
#### Environment details

1. google-cloud-monitoring==0.31.1
2. Python 3.7.2
3. Darwin 10.13.6 (High Sierra)

#### Steps to reproduce

  1. Do help() on anything in types.

#### Code example

```python
from google.cloud.monitoring import types
help(types)
```

**Comment by dwagon** [comment]
I can still access the docstring:
```
print(types.Group.__doc__)
The description of a dynamic collection of monitored resources. Each
...
```

**Comment by tseaver** [comment]
@dwagon Thanks for the report.  The bug is actually a [well-known issue for Python protobufs](https://github.com/protocolbuffers/protobuf/issues/2974), which we can't do anything to fix in this repository.
