### ISSUE TITLE
Needed URL endpoints to whitelist for pub-sub (publish)

### ISSUE THREAD

**Issue by optimistanoop** [googleapis/google-cloud-python#7305]
Hello, 
I am using pub/sub python client. 
Our organization's firewall is stopping us to publish.
Hence API endpoint URLs used by pub/sub client is needed to whitelist them from the firewall.

Any help will be much appreciated.
Thanks in advance.

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by tseaver** [comment]
The APIs for both publisher / subscriber methods are all under https://pubsub.googleapis.com .
