### ISSUE TITLE
Where is the official documentation for python storage package?

### ISSUE THREAD

**Issue by leberknecht** [googleapis/google-cloud-python#7333]
Ahoi!

Im trying to find the official documentation for google.cloud.storage python package. If i search for `download_as_string` on https://cloud.google.com/storage/docs/reference/libraries i dont find anything. And https://cloud.google.com/storage/docs/downloading-objects is only talking about download-to-file.

**Comment by tseaver** [comment]
The [API documentation is hosted on Github](https://googleapis.github.io/google-cloud-python/latest/storage/), which is linked from the [Cloud docs site](https://cloud.google.com/storage/docs/reference/libraries#client-libraries-resources-python).
