### ISSUE TITLE
Support for defining a different "endpoint" for clients for local testing?

### ISSUE THREAD

**Issue by simonvanderveldt** [googleapis/google-cloud-python#7336]
:wave: It could be I've missed something but I'd like to run some tests for our code using a locally running storage service (minio in this case, from what I could gather it's supposed to work) but I've been unable to determine how to override the endpoint/URL that's being used by the storage client.

For [S3 on AWS there's an `endpoint_url`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.client) argument that allows one to set this endpoint so it can just reference `localhost:<someport>` for example. I'm looking for something similar.

If this doesn't exist would it be possible to add it? It seems like a pretty common thing to do to validate one's code without depending on the network/external services.

**Comment by tseaver** [comment]
This is essentially a storage-specific variant of #4840.

The fastest way to make it happen in your code is to pass in an instance of your own HTTP connection object to the client constructor, e.g., something like the following (untested):

```python
from google.cloud.storage import _http
from google.cloud.storage import Client

class LocalConnection(_http.Connection):
    API_BASE+URL = 'http://localhost:2345'

client = Client(_http=LocalConnection())   # may need other args
```

**Comment by simonvanderveldt** [comment]
@tseaver Thanks for the link to the other issue. You're right, this is indeed a storage specific variant of that issue.

Also thanks for the code example. I'll give it a try and update in #4840 if it works or not using minio, might be relevant to others.

**Comment by simonvanderveldt** [comment]
@tseaver Tried this but can't get it to work, assuming the `_http` argument to `Client()` is a `Connection` it seems like there's a circular dependency with `_http.Connection` needing a `Client` https://github.com/googleapis/google-cloud-python/blob/8b3559a9c3c51555ef8be777d779f42c172352d8/core/google/cloud/_http.py#L52, exemplified here https://github.com/googleapis/google-cloud-python/blob/8b3559a9c3c51555ef8be777d779f42c172352d8/storage/google/cloud/storage/client.py#L77 and `Client` needing a `_http.Connection` which doesn't really make sense, so maybe I'm missing something.

[`google.cloud.storage._http.Connection`](https://github.com/googleapis/google-cloud-python/blob/8b3559a9c3c51555ef8be777d779f42c172352d8/storage/google/cloud/storage/_http.py#L25) does seem to be the right place to set the endpoint (`API_BASE_URL`) but it seems like there's no way to create a `Connection` first and then use it in the `Client`

Is the `_http` argument really supposed to be a `Connection`? Is seems like it shouldn't (it's supposed to be a `requests.Session` according to the docstring), but then there's no way to manually create a `Connection` and use that. So if it's supposed to already be possible to use custom/overridden `Connection`s it seems like it isn't working.

**Comment by simonvanderveldt** [comment]
> The fastest way to make it happen in your code is to pass in an instance of your own HTTP connection object to the client constructor, e.g., something like the following (untested):

@tseaver Does this actually work for you or was your proposal purely a theoretical one? We've not been able to get it to work so far (see my comment above) and it's preventing us from running a quiet important part of our testsuite.

**Comment by tseaver** [comment]
@simonvanderveldt I'm not sure if the advice I gave earlier *used* to work, but now it is obviously incorrect.  Rather, you need to replace the `client._connection` attribute with an instance of the `LocalConnection`, e.g.:

```python
from google.cloud.storage import _http
from google.cloud.storage import Client

class LocalConnection(_http.Connection):
    API_BASE_URL = 'http://localhost:2345'

client = Client(...)  # whatever args needed
client._connection = LocalConnection(client._http)
```
