### ISSUE TITLE
BigQuery: Make `RowIterator._to_dataframe_iterable` public

### ISSUE THREAD

**Issue by tswast** [googleapis/google-cloud-python#7339]
Follow-up to https://github.com/googleapis/google-cloud-python/issues/7293

There are use cases where it's not ideal to download a whole table at once, but a pandas DataFrame is still desired.

Potential solution:

Make the `pages` member of `RowIterator` return a generator of a subclass of `google.api_core.page_iterator.Page` with a `to_dataframe()` method.

**Comment by agsha** [comment]
Any updates on this?

**Comment by tswast** [comment]
We have a private method `RowIterator._to_dataframe_iterable` that we could make public.

https://github.com/googleapis/google-cloud-python/blob/13bd849797be6f8ec076782d12413f75de56bff2/bigquery/google/cloud/bigquery/table.py#L1557

When I originally filed this FR, I thought a per-page `to_dataframe` would be more appropriate, but it's actually quite difficult to override the page class with how the superclasses are structured. Plus, it wouldn't be able to take advantage of the BQ Storage API if we used the `pages` property.

**Comment by tswast** [comment]
@HemangChothani I think this is a good task you all. https://github.com/googleapis/google-cloud-python/issues/7339#issuecomment-567564457

In addition to making it public, let's make sure we have some unit tests for using the function directly.
