### ISSUE TITLE
Bigquery: Avro file insert to Bigquery

### ISSUE THREAD

**Issue by ShaunWang965475263** [googleapis/google-cloud-python#7371]
Hello,

I am trying to streaming avro format data from our kafka cluster to pubsub - dataflow - bigquery. 
I am able to get the avro to dataflow however, I can't seem to be able to load avro streaming into Bigquery

Is json the only format that bigquery takes in? 

Thanks,
Shaun

**Comment by tseaver** [comment]
@ShaunWang965475263 BigQuery supports AVRO for batch inserts and external tables (both for files stored in a GCS bucket), but not for streaming inserts:  `Client.insert_rows` takes either a sequence of tuples (in schema order) or a sequence of dicts.  This behavior follows that of the [back-end `insertAll` API](https://cloud.google.com/bigquery/docs/reference/rest/v2/tabledata/insertAll), which wants JSON data.
