### ISSUE TITLE
BigQuery:  Retrieving BigQuery data as a Pandas DataFrame is taking forever

### ISSUE THREAD

**Issue by carlobailey** [googleapis/google-cloud-python#7380]
What is the best way to query large amounts to data with Python? Currently, retrieving data from the server is very fast (less than a second for 7 million rows) but converting that to a DataFrame takes 12 minutes? Am I doing something wrong?

#### Environment details

2. OS type and version
OSX 10.14.3

3. Python version and virtual environment information:
3.7.2

4. google-cloud-<service> version:
Name: google-cloud-bigquery
Version: 1.9.0

#### Code example

```python
# example
from google.cloud import bigquery
client = bigquery.Client()

sql = '''
        SELECT table.id, table.name
        from `my_project.dataset.some_table' table
        '''

query_job = client.query(
    sql,
    location="US",
) 
df = client.query(sql).to_dataframe()
```

#### Stack trace
N/A

Thanks!

**Comment by tseaver** [comment]
@carlobailey The call to the query does not fetch the results:  it only returns a cursor into them.  So, the time you are seeing converting to a dataframe is mostly network bound, making calls to page through the cursor.  It would be similar if you just iterated over the rows in a loop, e.g.:

```python
from google.cloud import bigquery
client = bigquery.Client()

sql = '''
        SELECT table.id, table.name
        from `my_project.dataset.some_table' table
        '''

query_job = client.query(
    sql,
    location="US",
) 
count = 0
for row in query_job:
    count += 1
print("Fetched %d rows.".format(count))
```

Please reopen / follow-up if this doesn't answer your question.
