### ISSUE TITLE
Vision: 503 ServiceUnavailable returned from 'Client.face_detection'

### ISSUE THREAD

**Issue by denka0711** [googleapis/google-cloud-python#7381]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hi google

Our company using the google vision api to detect the face with python as mentioned in https://cloud.google.com/vision/docs/detecting-faces
There are about 155 images which I want to detect, but there is error when I detect the 93rd image, and there is error as following, I have restart my jumper several times, and still have the same errors, could you guys know how to solve this.

[---------------------------------------------------------------------------
_Rendezvous                               Traceback (most recent call last)
/anaconda3/lib/python3.6/site-packages/google/api_core/grpc_helpers.py in error_remapped_callable(*args, **kwargs)
     58         try:
---> 59             return callable_(*args, **kwargs)
     60         except grpc.RpcError as exc:

/anaconda3/lib/python3.6/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials)
    532         state, call, = self._blocking(request, timeout, metadata, credentials)
--> 533         return _end_unary_response_blocking(state, call, False, None)
    534 

/anaconda3/lib/python3.6/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    466     else:
--> 467         raise _Rendezvous(state, None, None, deadline)
    468 

_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Getting metadata from plugin failed with error: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1c28b17fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))"
	debug_error_string = "{"created":"@1550570160.024993000","description":"Getting metadata from plugin failed with error: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1c28b17fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))","file":"src/core/lib/security/credentials/plugin/plugin_credentials.cc","file_line":82,"grpc_status":14}"
>

The above exception was the direct cause of the following exception:

ServiceUnavailable                        Traceback (most recent call last)
<ipython-input-12-f2620def71ac> in <module>()
      3 i = 1
      4 for f in file_names_10:
----> 5     lst_emotion.append(detect_faces(f))
      6     print(i)
      7     i = i + 1

<ipython-input-11-99fa65d216a3> in detect_faces(path)
      9     image = vision.types.Image(content=content)
     10 
---> 11     response = client.face_detection(image=image)
     12     faces = response.face_annotations
     13 

/anaconda3/lib/python3.6/site-packages/google/cloud/vision_helpers/decorators.py in inner(self, image, max_results, retry, timeout, **kwargs)
    109             **kwargs
    110         )
--> 111         response = self.annotate_image(request, retry=retry, timeout=timeout)
    112         return response
    113 

/anaconda3/lib/python3.6/site-packages/google/cloud/vision_helpers/__init__.py in annotate_image(self, request, retry, timeout)
     65         # of them.
     66         protobuf.setdefault(request, 'features', self._get_all_features())
---> 67         r = self.batch_annotate_images([request], retry=retry, timeout=timeout)
     68         return r.responses[0]
     69 

/anaconda3/lib/python3.6/site-packages/google/cloud/vision_v1/gapic/image_annotator_client.py in batch_annotate_images(self, requests, retry, timeout, metadata)
    218             requests=requests, )
    219         return self._inner_api_calls['batch_annotate_images'](
--> 220             request, retry=retry, timeout=timeout, metadata=metadata)
    221 
    222     def async_batch_annotate_files(

/anaconda3/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py in __call__(self, *args, **kwargs)
    137             kwargs['metadata'] = metadata
    138 
--> 139         return wrapped_func(*args, **kwargs)
    140 
    141 

/anaconda3/lib/python3.6/site-packages/google/api_core/grpc_helpers.py in error_remapped_callable(*args, **kwargs)
     59             return callable_(*args, **kwargs)
     60         except grpc.RpcError as exc:
---> 61             six.raise_from(exceptions.from_grpc_error(exc), exc)
     62 
     63     return error_remapped_callable

/anaconda3/lib/python3.6/site-packages/six.py in raise_from(value, from_value)

ServiceUnavailable: 503 Getting metadata from plugin failed with error: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1c28b17fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))](url)

**Comment by tseaver** [comment]
Similar error with the NodeJS vision client: https://github.com/googleapis/google-cloud-node/issues/2658.

The max retries error from within the OAuth token URL makes me think that you might be creating a new client for each request, rather than reusing the same instance.  Looking at the traceback, your top-level function looks like:

```python
for f in file_names_10:
    lst_emotion.append(detect_faces(f))
print(i)
```

Instead, create the `ImageAnnotatorClient` at the outer scope and pass it into your `detect_faces` function, e.g.:

```python
from google.cloud.vision_v1 import ImageAnnotatorClient

def main():
    client = ImageAnnotatorClient()
    for f in file_names_10:
        lst_emotion.append(detect_faces(client, f))
```

(removing the client instantiation from inside your `detect_faces` function).
