### ISSUE TITLE
Firestore: Add docs regarding Client threadsafety

### ISSUE THREAD

**Issue by danielx** [googleapis/google-cloud-python#7421]
**Is your feature request related to a problem? Please describe.**
There is no mention in the current docs if a `google.cloud.firestore.Client()` can safely be shared among threads.

 **Describe the solution you'd like**
Some docs explaining if a `Client` can safely be reused among threads.

**Comment by tseaver** [comment]
For example, see `storage/docs/index.rst`.  We should do likewise for all clients.
