### ISSUE TITLE
Logging: write_log_entries insufficient documentation

### ISSUE THREAD

**Issue by vkhazin** [googleapis/google-cloud-python#7457]
I am trying to figure out the data structure to use for the following example from google documentation: https://github.com/googleapis/google-cloud-python/tree/master/logging#using-the-api
and
https://googleapis.github.io/google-cloud-python/latest/logging/index.html?highlight=write_log_entries
and
https://github.com/googleapis/google-cloud-python/blob/9e804dfb2fa1ca4a29e861d88600f924906776d6/logging/google/cloud/logging/_gapic.py
```
from google.cloud import logging_v2

client = logging_v2.LoggingServiceV2Client()
entries = []
response = client.write_log_entries(entries)
```
How do I format the content of the `entries` array?
And how to include a specific timestamp element, instead of a default time-of-collection timestamp?

**Comment by tseaver** [comment]
I would normally use a `Logger` instance, e.g.:

```python
import datetime
from google.cloud import logging

logging_client = logging.Client()
logger = logging_client.logger('my-log')

now = datetime.datetime.utcnow()
stamp = now.isoformat()
logger.log_text('A text string!, timestamp=stamp)
logger.log_struct({'foo': 'bar'})
```

See the ["Python Client Library" section of the API docs](https://cloud.google.com/logging/docs/reference/libraries#client-libraries-usage-python).

**Comment by vkhazin** [comment]
@tseaver 
Thank you for the suggestion!
It is, however, a one log entry at the time, while I am interested in a bulk ingest that write_log_entires seems to be tailored to.

**Comment by tseaver** [comment]
Updated example (the `timestamp` argument is expected to be a `datetime.datetime` instance):

```python
import datetime
from google.cloud import logging

logging_client = logging.Client()
logger = logging_client.logger('my-log')

now = datetime.datetime.utcnow()
logger.log_text('A text string!, timestamp=now)
logger.log_struct({'foo': 'bar'})
```

**Comment by tseaver** [comment]
You can use the logger's `batch` method to get an instance used for making multiple logging calls in a single request:

```python
with logger.batch() as batch:
    batch.log_text('Issue #7457', timestamp=now)
    batch.log_struct({'issue': 7457})
```

**Comment by tseaver** [comment]
We don't really expect / encourage direct use of the lower-level `logging_v2.LoggingServiceV2Client`.  If you want to use it yourself, you could look at [how the `Batch` class uses it](https://github.com/googleapis/google-cloud-python/blob/3a1bed32f62db4425925a26894b8fde6bcb80d85/logging/google/cloud/logging/logger.py#L362-L384) (you'll also need to the `to_api_repr` methods of the various log entry types, e.g. [`TextEntry.to_api_repr`](https://github.com/googleapis/google-cloud-python/blob/3a1bed32f62db4425925a26894b8fde6bcb80d85/logging/google/cloud/logging/entries.py#L287-L292).

**Comment by immohsin** [comment]
Hi @tseaver, 
I'm new to the stackdriver. Sending a nested dict in `log_struct` method throws `Unexpected type for Value message.` exception.

Is there a way to send a nested dictionary in log_struct method?

**Comment by tseaver** [comment]
@immohsin Trying to reproduce:

```python
>>> from google.cloud.logging import Client
>>> client = Client()
>>> logger = client.logger('gcp-7457')
>>> struct = {
...     'nested': {
...         'value': 'foo',
...     },
... }
>>> logger.log_struct(struct)
>>>
```

Can you provide sample code and the full traceback?

**Comment by immohsin** [comment]
```
format = {'app_id': '00000000000000000000000000000000', 'app_name': 'UNKNOWN', 'request_id': '00000000000000000000000000000000', 'message': "{'method': 'POST', 'uri': '/v1/testapi', 'code': 500, 'message': 'Internal Server Error'}", 'service_name': 'test_api', 'json_payload': {'method': 'POST', 'uri': '/v1/testapi', 'code': 500, 'message': 'Internal Server Error'}}
client = google.cloud.logging.Client()
logger = client.logger(service_name)
self.logger = google.cloud.logging.logger.Batch(logger, client)
 self.logger.log_struct(format, severity='ERROR')
```

This is code i'm using and trying to json_payload as nested dict.

**Comment by iamtodor** [comment]
The documentation is incredibly poor.
As a topic author, I also need to send a bunch of logs at the time.
For example, I have the list of the dicts and want to send them. I haven't found proper documentation of this feature. The only I found is the following answer https://stackoverflow.com/a/54894785/5151861
I'm not sure if I use conversion dict -> protobuf.Structure correctly, where can I proper example?
My current solution is the following:
```
        entries = []
        for message in messages:
            struct = Struct()
            struct['field1'] = message['field1']
            struct['field2] = message['field2']
            -!-
            struct['fieldN'] = message['fieldN']

            entry = {
                'json_payload': struct,
            }

            entries.append(entry)

        res = {"type": "-",
               "labels": {
                   "zone": "-",
                   "instance_id": "-"}}
        
        self.client.write_log_entries(entries,
                                      log_name=f'projects/-/logs/-',
                                      resource=res)
```
