### ISSUE TITLE
Dataflow SDK Support and Deprecation

### ISSUE THREAD

**Issue by ShaunWang965475263** [googleapis/google-cloud-python#7481]
Hello,

I am seeing on this page that most of the versions are going to be deprecated for python and java working with apache beam.
https://cloud.google.com/dataflow/docs/support/sdk-version-support-status#apache-beam-2x-sdks

Is Dataflow a dead project? Thanks,

Also quick question on maintaining order with Dataflow... python sdk doesnt support windowed write, and I want to be able to partition based on both early and late data for financial transactions, how can that be done?

Thanks,
Shaun

**Comment by tseaver** [comment]
The Cloud Dataflow SDK is not maintained in this repository.  Please use one of the [support links](https://cloud.google.com/dataflow/docs/support/getting-support) to get answers to your questions.
