### ISSUE TITLE
Readme links to example applications are broken

### ISSUE THREAD

**Issue by brystmar** [googleapis/google-cloud-python#7488]
Links to both [Example Application](https://github.com/googleapis/google-cloud-python#example-applications) repos in the Readme are broken.
### getting-started-python
- Current link (broken): https://github.com/googleapis/getting-started-python
- Proper link: https://github.com/GoogleCloudPlatform/getting-started-python

### google-cloud-python-expenses-demo
- Current link (broken): https://github.com/googleapis/google-cloud-python-expenses-demo
- Proper link: https://github.com/GoogleCloudPlatform/google-cloud-python-expenses-demo

I'm not yet comfortable submitting actual changes to large, open repos like this one, so I'll post this as an issue for now :)

**Comment by tseaver** [comment]
#7492 fixed the link for the expenses demo.

**Comment by tseaver** [comment]
@brystmar Thanks for the report!
