### ISSUE TITLE
Firestore: add emulator support

### ISSUE THREAD

**Issue by lkollar** [googleapis/google-cloud-python#7500]
**Is your feature request related to a problem? Please describe.**
The library does not respect the `FIRESTORE_EMULATOR_HOST` environment variable thus it cannot be used with the emulator.
 **Describe the solution you'd like**
Respect the `FIRESTORE_EMULATOR_HOST` environment variable and connect to the emulator when set.
 **Describe alternatives you've considered**
None. If there are other ways to use the emulator with the library they are not documented.

**Comment by tseaver** [comment]
See #4840.

**Comment by mnoseworthy** [comment]
Preamble: I haven't looked at much of the source code for the project at all and have just been happily using it straight from pip. But now we're looking to handle a local test stack for our application, and want to use the beta Firestore Emulator from a Python runtime

As a hack, could we instantiate a [transport object](https://github.com/googleapis/google-cloud-python/blob/master/firestore/google/cloud/firestore_v1beta1/gapic/transports/firestore_grpc_transport.py) pointing to the local endpoint of the simulator and bind that to a Client object?

I'm assuming that if it was this easy the `FIRESTORE_EMULATOR_HOST` envar would already be supported. I'll give this a shot and update.

**Comment by therefromhere** [comment]
@mnoseworthy I think this works: https://gist.github.com/therefromhere/5acc827ec7a27db9edcb24fe2ece7d37

**Comment by mf2199** [comment]
With live Firestore, all the system tests pass. With the emulator, out of the 24 tests in total, 17 pass and 7 fail. The reasons are yet to be determined, for the following error messages:

4 tests showing error "Few assertion failed with emulator, but works with real one."
	test_update_document(client, cleanup),
	test_query_stream(client, cleanup),
	test_get_all(client, cleanup),
	test_batch(client, cleanup):

2 tests failing with "PermissionDenied: 403 Metadata operations require admin authentication. which received in two test":
	test_create_document_w_subcollection(client, cleanup)
	test_collection_add(client, cleanup)

1 test showing "entity already exists: so DID NOT RAISE <class 'google.api_core.exceptions.InvalidArgument'>":
	assert_timestamp_less(timestamp_pb1, timestamp_pb2)
