### ISSUE TITLE
GoogleCloudStorage: Unable to download metadata

### ISSUE THREAD

**Issue by jrmlhermitte** [googleapis/google-cloud-python#7537]
I checked both of these for `google storage metadata` and found nothing relevant:
- https://github.com/googleapis/google-cloud-python/issues
- http://stackoverflow.com/questions/tagged/google-cloud-python

I'm unable to get metadata from blobs I have saved to buckets. Am I doing something wrong?

#### Environment details
1. Mac OSX
2. Google cloud storage version:
```
In [31]: import google.cloud.storage

In [32]: google.cloud.storage.__version__
Out[32]: '1.13.0'
```
3. python version:
```
python --version                                                                                                                       ✹ ✭
Python 3.6.7 :: Anaconda, Inc.
```

#### Steps to reproduce
Here, I upload a file to a blob called "test.txt" with metadata `{'test': 'test}`. I can upload it but I cannot retrieve it via the python API:

```py3
from google.cloud import storage
bucket = storage_client.get_bucket(BUCKET_NAME)
blob = bucket.blob('test.txt')
blob.metadata = {'test': 'test'}
blob.upload_from_file('foo')  # from some file named foo

# now review
blob = bucket.blob('test.txt')
# This is None so this runs
assert blob.metadata is None
```

However, in looking at the file uploaded to google cloud storage, I can clearly see that there is metadata:
<img width="468" alt="Screen Shot 2019-03-19 at 4 14 09 PM" src="https://user-images.githubusercontent.com/705366/54638873-65ff6e80-4a62-11e9-841a-c2758ae1ec93.png">

**Comment by tseaver** [comment]
@jrmlhermitte `bucket.blob()` does not perform an API request to load properties from GCS.  You can do one of the following:
- Call `blob.reload()` on the instance (which *does* perform the API request).
- Use `bucket.get_blob()`, which calls `reload` for you.

**Comment by jrmlhermitte** [comment]
Tested it out and it works, thanks! Should the documentation be elaborarated a bit to help out?
Either way thanks!

**Comment by tseaver** [comment]
@jrmlhermitte We do document that [`Bucket.blob` does not make an API request](https://googleapis.github.io/google-cloud-python/latest/storage/buckets.html#google.cloud.storage.bucket.Bucket.blob).  Can you suggest updated wording for that note which would make it clearer?

**Comment by jrmlhermitte** [comment]
I think that is actually fine then. Maybe what would help are some documented examples. But otherwise, as a reference, I think that is clear enough. Do you think examples would help and would you like me to list some I find useful?
