### ISSUE TITLE
Storage: read image files locally from google collaboratory without "blob"?

### ISSUE THREAD

**Issue by Sawatdatta** [googleapis/google-cloud-python#7542]
I am trying to use GPU instance provided by Google collaboratoy. The python project will fetch data from google cloud storage and process in batches, But as per APIs provided by google cloud we need to use blob methods to read and write to GCS. Is there any alternative that we can treat GCS files in google collaboratory as local files without need to change existing python code to read and write image files.

**Comment by mik-laj** [comment]
@Sawatdatta look at: https://pypi.org/project/fs-gcsfs/

**Comment by tseaver** [comment]
I'm closing here, as there is nothing to be done within `google-cloud-storage`.
