### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in C:\Users\User\AppData\Local\Temp\pip-install-cxjooigk\tesseract-sip\

### ISSUE THREAD

**Issue by Ma3aXaKeP** [googleapis/google-cloud-python#7555]
Help Help Help. Error Command "python setup.py egg_info" failed with error code 1 in C:\Users\User\AppData\Local\Temp\pip-install-cxjooigk\tesseract-sip\ 
Install python

**Comment by tseaver** [comment]
Unrelated to the `google-cloud-python` repo, AFAICT.
