### ISSUE TITLE
BigQuery: writing bytes with insert_rows does not write correctly

### ISSUE THREAD

**Issue by Juta** [googleapis/google-cloud-python#7606]
Hi all,

I am working on porting apache beam to python 3. In the future we want to migrate the BigQuery IO to use this library. I was testing writing bytes to bigquery with the following code on google-cloud-bigquery==1.10.0 (writing data to an existing table with schema bytes:BYTES):

```python
from google.cloud import bigquery
client = bigquery.Client('<project-id>')
dataset = client.dataset('<dataset-id>')
table = dataset.table('<table-id>')
table = client.get_table(table)
client.insert_rows(table, [(b'\xab')])
client.insert_rows(table, [(b'\xab\xac\xad')])
```

In python 2.7.12 this writes `[b'\xab', b'\xab']` to bigquery.
In python 3.5.2 this writes `[b'\xd7\xbd', b'\xd7\xbd']`

So I think there is a bug when writing bytes to BigQuery this way.

Note: when I use
```python
client.insert_rows(table, [{'bytes':b'\xab\xac\xad'}])
```
the bytes are written correctly .

**Comment by tseaver** [comment]
I can't see any difference in how the [`_bytes_to_json` helper]() behaves under Python 2.7:

```python
ython 2.7.14 (default, Oct  4 2017, 16:09:27) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud.bigquery._helpers import _bytes_to_json
>>> print(_bytes_to_json(b"\xab"))
qw==
>>> print(_bytes_to_json(b"\xab\xac\xad"))
q6yt
```

versus 3.x:

```python
Python 3.5.3 (default, Jan 17 2017, 17:53:57) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud.bigquery._helpers import _bytes_to_json
>>> print(_bytes_to_json(b"\xab"))
qw==
>>> print(_bytes_to_json(b"\xab\xac\xad"))
q6yt
```

Can you show the schema of your table?

**Comment by tseaver** [comment]
Hmm, I think I see the issue here:  in your example above:

```
client.insert_rows(table, [(b'\xab')])
client.insert_rows(table, [(b'\xab\xac\xad')])
```

you pass the bytes values directly, rather than as tuples, which causes only the first byte to be sent.  You need to add the trailing comma to ensure that each row passed is a tuple:

```python
client.insert_rows(table, [(b'\xab',)])
#                                  ^
client.insert_rows(table, [(b'\xab\xac\xad',)])
#                                          ^
```

**Comment by Juta** [comment]
I can confirm that this issue was indeed related to the missing trailing comma. Thanks!
