### ISSUE TITLE
Empty API page in "Python Client for Cloud Text-to-Speech API"

### ISSUE THREAD

**Issue by mik-laj** [googleapis/google-cloud-python#7629]
Hello,

I readed a document for "Python Client for Cloud Text-to-Speech API" and found a links "APIs" and "API Reference"
<img width="546" alt="Screenshot 2019-04-01 at 12 42 51" src="https://user-images.githubusercontent.com/12058428/55322186-ed45dc80-547b-11e9-896a-5e9d5fcd0b4d.png">

They point to 
https://googleapis.github.io/google-cloud-python/latest/texttospeech/api.html
but it's not have content.
<img width="682" alt="Screenshot 2019-04-01 at 12 45 49" src="https://user-images.githubusercontent.com/12058428/55322258-22eac580-547c-11e9-8bd5-04f0d4730118.png">

I think that this page should be deleted.
.
Greetings

**Comment by bbookman** [comment]
This is still open, yet was taken care of and did not close as mentioned on April 2
