### ISSUE TITLE
Firestore: reference type does not read in readable form.

### ISSUE THREAD

**Issue by klausmyrseth** [googleapis/google-cloud-python#7630]
OSType: ubuntu 18
Python: 3.7.1
Version: google-cloud-firestore: 0.31.0

when using the reference type I keep getting the base reference type which I cant convert to path, or I haven't found a good reliable way doing this yet. I use normal path when I initialize the field.

#### Code example
```python
users_ref = firestore.collection(u'user_profile')
users = users_ref.get()
map( lambda x: print( x.get('employee_link') ), users )
```
output is then:
```json
{
            "id": "Zh99aeho7PcEq6DaeZzU",
            "parent": {
                "id": "employees",
                "parent": {
                    "id": "pBvqyNbSOeJbUaGZTugC",
                    "parent": {
                        "id": "company",
                        "parent": null
                    }
                }
            }
        }
```
instead of: /company/pBvqyNbSOeJbUaGZTugC/employee/Zh99aeho7PcEq6DaeZzU

Which is readable and convertable to send to web and back and still reference the correct database links.

#### Bad workaround:
use string instead of reference

**Comment by tseaver** [comment]
Trying to reproduce:

```python
from google.cloud.firestore_v1beta1 import Client
client = Client.from_service_account_json('/path/to/service_account.json')
coll = client.collection('gcp-7630')
target = coll.document('target')
target.set({'name': 'Target'})
dependent = coll.document('dependent')
dependent.set({'name': 'Dependent', 'ref': target})
snapshot = dependent.get()
assert snapshot.get('ref') == target
assert snapshot.get('ref').get().to_dict()['name'] == 'Target'
```

Reference values get loaded as `DocumentRef` instances.

@klausmyrseth Can you please show how you are populating the reference in your code?

**Comment by tseaver** [comment]
Please feel free to reopen if you can provide more information.
