### ISSUE TITLE
How can I activate the incremental processing feature?

### ISSUE THREAD

**Issue by malihealikhani** [googleapis/google-cloud-python#7644]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

**Comment by busunkim96** [comment]
@malihealikhani Hi, thank you for filing an issue! We'll need a bit more detail to be able to help you. 

Can you please fill out the questions above?

**Comment by malihealikhani** [comment]
I like to have the output of my speech like this:

first 100 ms: Hi
Second 100 ms: How a
Third 100 ms: re you?

How can i get such output?

Thank you!

**Comment by busunkim96** [comment]
To clarify, you are working with the Speech to Text API? We have good guides on that at cloud.google.com. I've listed a few below. If you haven't worked with the API yet, I highly recommend starting with the quickstart to familiarize yourself. If you have any specific issues with the client library, please feel free to file another issue. 

* [Quickstart: Using Client Libraries](https://cloud.google.com/speech-to-text/docs/quickstart-client-libraries)
* [Performing streaming speech recognition on a local file](https://cloud.google.com/speech-to-text/docs/streaming-recognize#performing_streaming_speech_recognition_on_a_local_file)
