### ISSUE TITLE
Firestore: Exception on watch.py after update libraries firebase-admin

### ISSUE THREAD

**Issue by gbonline** [googleapis/google-cloud-python#7652]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-python/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types

2. OS type and version
ubuntu 18.04
3. Python version and virtual environment information: `python --version`
I use python2.7 in virtual env, updated to the last version of firebase-admin with the command
pip install --upgrade firebase-admin
4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`
firebase-admin==2.16.0
funcsigs==1.0.2
future==0.16.0
futures==3.2.0
gax-google-logging-v2==0.8.3
gax-google-pubsub-v1==0.8.3
gcloud==0.18.3
gdata==2.0.18
google-api-core==1.8.2
google-auth==1.6.3
google-cloud==0.34.0
google-cloud-core==0.29.1
google-cloud-firestore==0.32.0
google-cloud-storage==1.14.0
google-gax==0.16.0
google-resumable-media==0.3.2
googleapis-common-protos==1.6.0b9
grpc-google-logging-v2==0.11.1
grpc-google-pubsub-v1==0.11.1

#### Steps to reproduce

  1. ?

#### Code example
in file watch.py in the __init__()
```python
# example
        self._rpc = ResumableBidiRpc(
            self._api.transport.listen,
            initial_request=initial_request,
            should_recover=should_recover,
            metadata=self._firestore._rpc_metadata,
        )
```

#### Stack trace
```
# example
  File "/home/nemesix/Sviluppo/odoo/extra-addons-7.0/addons-sviluppo/scm_booking_app_backend/nx_booking_app_firestore/nx_booking_app_firestore.py", line 45, in _initialize
    BookingAppFirestore.users_ref = BookingAppFirestore.uniqdb.collection('users').where('newuser','==',True).on_snapshot(self.new_users_on_snapshot)
  File "/home/nemesix/Sviluppo/venvs/odoo-dev/local/lib/python2.7/site-packages/google/cloud/firestore_v1/query.py", line 775, in on_snapshot
    self, callback, document.DocumentSnapshot, document.DocumentReference
  File "/home/nemesix/Sviluppo/venvs/odoo-dev/local/lib/python2.7/site-packages/google/cloud/firestore_v1/watch.py", line 366, in for_query
    reference_class_instance,
  File "/home/nemesix/Sviluppo/venvs/odoo-dev/local/lib/python2.7/site-packages/google/cloud/firestore_v1/watch.py", line 219, in __init__
    metadata=self._firestore._rpc_metadata,
TypeError: __init__() got an unexpected keyword argument 'metadata'
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by crwilcox** [comment]
Hi @gbonline. My apologies for this. I have released a new version that will address this. `google-api-core` had an update that needed to ship first which is out as v1.9.0. `Firestore` has released v0.32.1 which now depends on that version, resolving this issue. Thank you for bringing this to our attention.
