### ISSUE TITLE
ImportError: No module named moves

### ISSUE THREAD

**Issue by jimmyromanticdevil** [googleapis/google-cloud-python#7699]
I'm frustrated with this bug. I use flask and already deeply investigate. I don't know what happens. Error every time I run dev_appserver.py app.yaml but if I run it manually by python main.py it smoothly running. 

> $ dev_appserver.py app.yaml
> ERROR    2019-04-12 00:31:55,491 wsgi.py:263]
> Traceback (most recent call last):
>   File "/Users/xx/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
>     handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
>   File "/Users/xx/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
>     handler, path, err = LoadObject(self._handler)
>   File "/Users/xx/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
>     obj = __import__(path[0])
>   File "/Users/xx/ggcloud/project/ai-chatbot/main.py", line 4, in <module>
>     from six.moves import _thread
> ImportError: No module named moves

**Comment by jimmyromanticdevil** [comment]
However, I fixed this issue by 

import six
from six import moves 

and change all of the libs that include six.moves to moves.urrlib and moves httpclient and etc

is there any way to fix it without changing the script manually

**Comment by tswast** [comment]
cc @googleapis/serverless-team

**Comment by tseaver** [comment]
@jimmyromanticdevil I can't see that this issue is related to the `google-cloud-python` libraries at all:  it seems to be related to GAE, which isn't supported here.

Please follow up with more information if I am wrong.

**Comment by andrewsg** [comment]
@jimmyromanticdevil It looks like you're using six directly in your application; does this problem still happen even if you just use the Cloud Client libraries in GAE without using six in your app? Are you following any particular sample or tutorial? Also, does the problem occur in production or only with dev_appserver.py?
