### ISSUE TITLE
Getting all calendars of organisation users

### ISSUE THREAD

**Issue by shilomagen** [googleapis/google-cloud-python#7723]
Hi,
I'm trying to figure out if as an organisation admin I can get all my users calendar and meeting.
Is it possible? Could not find any documentation for it.

Thanks!

**Comment by Zaffer** [comment]
Hi @shilomagen how did you get this to start working? I am only seeing a way to do it via the old https://github.com/googleapis/google-api-python-client method.

Please share the way to use Google Calendar with this new package.
