### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by riensWinoto** [googleapis/google-cloud-python#7748]
Hi all.
I'm brand new with open source world.
I'm on progress to share my code that using google cloud storage library.
I only use the google cloud storage library to upload my file content and the rest is make it infinity looping so the code allow infinity input the content

If I license my code, can i be sued by Google and the contributors?
if it's no problem, then what license I must use?

My code not for commercial, just for share for who need it

**Comment by tseaver** [comment]
The `google-cloud-storage` library, like all those released from this repository, is licensed under the [Apache license v 2.0](https://github.com/googleapis/google-cloud-python/blob/master/LICENSE), which spells out the requirements for your use of the library, including redistribution, creation of derived works, etc.
