### ISSUE TITLE
automl vision 

### ISSUE THREAD

**Issue by denfromufa** [googleapis/google-cloud-python#7751]
Not sure where to report AutoML Vision issues, but I'm not observing the confusion matrix in the "EVALUATE" tab of the web UI when following the basic quickstart:

https://cloud.google.com/vision/automl/docs/quickstart?refresh=1

![image](https://user-images.githubusercontent.com/7870949/56386502-919f8100-61e7-11e9-9011-6b54661da514.png)

The confusion matrix should be displayed according to this documentation:

https://cloud.google.com/vision/automl/docs/evaluate

**Comment by tseaver** [comment]
@denfromufa This repository supports the `google-cloud-*` API client libraries, including `google-cloud-automl`.  For support of issues related to the back-end AutoML Vision service, please use one of the resources linked from its [support page](https://cloud.google.com/vision/automl/getting-support).

**Comment by denfromufa** [comment]
@tseaver done: https://stackoverflow.com/questions/55753086/confusion-matrix-not-displayed-in-google-cloud-automl-vision
