### ISSUE TITLE
Outdated info in CONTRIBUTING.rst

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/google-cloud-python#7807]
Where is this mysterious `system_tests/` directory referenced several times in the[ guide](https://github.com/googleapis/google-cloud-python/blob/1f08ba5f568313aab62cf5c9b281e421eb6cc432/CONTRIBUTING.rst)? What could possibly be `$ source system_tests/local_test_setup`?

**Comment by tswast** [comment]
Looks like a few of those scripts moved to https://github.com/googleapis/google-cloud-python/tree/1f08ba5f568313aab62cf5c9b281e421eb6cc432/datastore/tests/system/utils

A lot of that section reads very specific to Cloud Datastore to me. In general, our system tests set up any required resources as part of the nox session. There are a few exceptions to this, such as with Datastore, but IMO those setup steps should be documented in the product directory and definitely as nicer error messages about what to run to set up any needed resources.

**Comment by mf2199** [comment]
The above mentioned directory and the associated files can be found in the [Happybase](https://github.com/googleapis/google-cloud-python-happybase) repository. It is true that the `CONTRIBUTING.rst` file can be updated, to clarify these refrences as being particular examples, or rephrased, to provide a more accurate, generalized system testing guidance.

**Comment by paul1319** [comment]
Everything seems like up-to-date already, and you can close this issue.
