### ISSUE TITLE
clodshell usage quota

### ISSUE THREAD

**Issue by Zibri** [googleapis/google-cloud-python#7811]
In cloudshell (not compute) it seems is possible to know the usage quota only from the web interface at https://console.cloud.google.com/cloudshell/editor?shellonly=true

I have noticed that the page makes a request to https://ssh.cloud.google.com/devshell/quota?authuser=0&token=****

How can we get that token so we can be able to know the usage quota from inside the shell itself or from an external authenticated client?

I tried with the access token but it does not work obviously.

**Comment by tseaver** [comment]
@Zibri This repository is used to maintain the Python client libraries for Google Cloud APIs.  The Cloud Shell API is not supported here:  please use one of the links on its [support page](https://cloud.google.com/shell/docs/getting-support) to report issues / request support.
