### ISSUE TITLE
Vision: celery task hangs during 'annotate_image' on Ubuntu 16 server.

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [googleapis/google-cloud-python#7821]
Hello. I have been fighting against this bug for three days and couldn't find any solution.

I create my client like this:

    client = vision.ImageAnnotatorClient.from_service_account_json('/path/to/json/file.json')

then I read my local image file:

     with io.open('/path/to/image.jpg', 'rb') as image_file:
        content = image_file.read()
    image = types.Image(content=content)

After that I'm trying to annotate this image by using Cloud Vision:

    response = client.annotate_image({'image': image, 'features': [
        {'type': vision.enums.Feature.Type.TEXT_DETECTION},
    ]})

These lines of code are inside Celery task. When I launch this task it **hangs forever at annotate_image**. It hangs so bad that I needed to kill and restart whole supervisor that runs this celery.

However, there is one interesting thing. If I launch this code directly from my console, it works.

    Python version -- 3.7.1
    Ubuntu 16

My dependencies:
    
     google-api-core==1.9.0
     google-auth==1.6.3
     google-cloud-vision==0.36.0
     googleapis-common-protos==1.5.9
     greenlet==0.4.15
     grpcio==1.19.0
     celery==4.2.1

I have even added  `GOOGLE_CLOUD_DISABLE_GRPC=True` as env variable and it still not working

**Comment by tseaver** [comment]
There are a number of known issues with `grpc` and forking, e.g. see https://github.com/grpc/grpc/issues/18075.

As a workaround, avoid creating the `ImageAnnotatorClient` until *after* the child process is forked, e.g.:

```python
_vision_client = None

def vision_client():
    global _vision_client
    if _vision_client is None:
        _vision_client = = vision.ImageAnnotatorClient.from_service_account_json('/path/to/json/file.json')
    return _vision_client
```

And then in your task function:

```python
response = vision_client().annotate_image({'image': image, 'features': [
    {'type': vision.enums.Feature.Type.TEXT_DETECTION},
]})
````

**Comment by SuperMasterBlasterLaser** [comment]
@tseaver I have replaced my task with your code and it still hangs

**Comment by SuperMasterBlasterLaser** [comment]
I just gave up and started to use REST API requests to call directly vision annotation from vision service.

**Comment by tseaver** [comment]
@SuperMasterBlasterLaser I'm sorry you weren't able to resolve the issue.  Could you double-check that your last efforts do *not* instantiate an `ImageAnnotatorClient` anywhere before celery forks the child process?

**Comment by SuperMasterBlasterLaser** [comment]
@tseaver It only instantiates only in this task. One of the strange things is that in my local Windows PC with launched celery it works as it needed.
