### ISSUE TITLE
BigQuery: Table.from_string() doesn't support GCP project ID with org prefix

### ISSUE THREAD

**Issue by salvador-bynd** [googleapis/google-cloud-python#7827]
#### Environment details

1. BigQuery
2. Google App-Engine standard (Python 2.7)
3. Python 2.7
4. google-cloud-bigquery==1.10.0

#### Code example

```python

from google.cloud import bigquery
from google.cloud.bigquery import Table

# Standard SQL (works fine)
# SELECT * FROM `google.com:my-project.mydataset.mytable` LIMIT 1

# Works fine
table = Table.from_string('my-project.mydataset.mytable')

# Fails
table = Table.from_string('google.com:my-project.mydataset.mytable')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/vv/local/lib/python2.7/site-packages/google/cloud/bigquery/table.py", line 815, in from_string
    return cls(TableReference.from_string(full_table_id))
  File "/tmp/vv/local/lib/python2.7/site-packages/google/cloud/bigquery/table.py", line 246, in from_string
    "got {}".format(table_id)
ValueError: Too many parts in table_id. Must be a fully-qualified table ID in standard SQL format. e.g. "project.dataset.table", got google.com:my-project.mydataset.mytable
```

**Comment by joncass** [comment]
I am having this same issue. It looks to me like the fix would be to change line https://github.com/googleapis/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/_helpers.py#L590 from `parts = full_id.split(".")` to `parts = full_id.rsplit(".", 2)`. Any objections to that change?

**Comment by Emar-Kar** [comment]
@tswast yeah, sure. I’ll take a look tomorrow.

**Comment by plamut** [comment]
@Emar-Kar Are you currently working on this? Asking to not unnecessarily duplicate the effort.

**Comment by Emar-Kar** [comment]
@plamut Yeah, thank you for asking. I’m working on it.

**Comment by plamut** [comment]
@Emar-Kar Great, thanks. I updated the assignee for better visibility.
