### ISSUE TITLE
Pub/Sub: Add subscriber unit tests

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/google-cloud-python#7833]
The test here doesn't check if `max_bytes` is abided by the subscriber client. A better test would do that and also check if `max_messages` is adhered to. What we observe now is that FlowControl doesn't work properly (#7677).

```python
def test_subscribe_options(manager_open):
    creds = mock.Mock(spec=credentials.Credentials)
    client = subscriber.Client(credentials=creds)
    flow_control = types.FlowControl(max_bytes=42)
    scheduler = mock.sentinel.scheduler

    future = client.subscribe(
        "sub_name_a",
        callback=mock.sentinel.callback,
        flow_control=flow_control,
        scheduler=scheduler,
    )
    assert isinstance(future, futures.StreamingPullFuture)

    assert future._manager._subscription == "sub_name_a"
    assert future._manager.flow_control == flow_control
    assert future._manager._scheduler == scheduler
    manager_open.assert_called_once_with(mock.ANY, mock.sentinel.callback)
```

**Comment by plamut** [comment]
A thorough [system test](https://github.com/googleapis/google-cloud-python/blob/master/pubsub/tests/system.py#L213-L265) for `max_messages` now exists, was added in the [PR](https://github.com/googleapis/google-cloud-python/pull/7948) that fixed that bug. Among other things it verifies that the big-picture logic for pausing / resuming the consumer based on the current leaser load is sound.

One bit of the pause / resume logic is also considering the `max_bytes` value when computing the current load, and that bit is covered by several existing [unit tests](https://github.com/googleapis/google-cloud-python/blob/master/pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py#L158-L212).

Based on this, I think we can close the issue.
