### ISSUE TITLE
Ability to customize blob._DEFAULT_CHUNKSIZE

### ISSUE THREAD

**Issue by oliverchang** [googleapis/google-cloud-python#7834]
On App Engine standard, URLFetch has a request limit size of 10MiB. The value of blob._DEFAULT_CHUNKSIZE is [100MiB](https://github.com/googleapis/google-cloud-python/blob/75277847ea68d228be4c3e91bb228236489f19f5/storage/google/cloud/storage/blob.py#L101)

This means that uploads larger than this will fail on App Engine with the exception `Request exceeds 10 MiB limit for URL`.

Currently we are working around this by doing:

```python
+  from google.cloud.storage import blob
+  blob._DEFAULT_CHUNKSIZE = 10 * 1024 * 1024  # 10MiB.
```
Could we get a proper way to customize this value?

**Comment by tseaver** [comment]
You can pass `chunk_size` as an argument to the `Blob` constructor, e.g.:

```python
TEN_MIB = 10 * 1024 * 1024

blob = bucket.blob('file.name', chunk_size=TEN_MIB)
```

Or assign to an existing blob's `chunk_size` property:

```python
blob.chunk_size = TEN_MIB
```
The blob's own value, if not set to `None`, overrides the module-scope default.
