### ISSUE TITLE
Pub/Sub: System test failures on Python 2.7 (invalid syntax)

### ISSUE THREAD

**Issue by tswast** [googleapis/google-cloud-python#7841]
https://source.cloud.google.com/results/invocations/e8706e96-9a37-40d5-8411-7cd62206b4aa/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-python%2Fpresubmit%2Fpubsub/log

```
tests/unit/pubsub_v1/subscriber/test_subscriber_client.py:18: in <module>
    from google.cloud.pubsub_v1 import subscriber
google/cloud/pubsub_v1/__init__.py:19: in <module>
    from google.cloud.pubsub_v1 import subscriber
google/cloud/pubsub_v1/subscriber/__init__.py:17: in <module>
    from google.cloud.pubsub_v1.subscriber.client import Client
google/cloud/pubsub_v1/subscriber/client.py:30: in <module>
    from google.cloud.pubsub_v1.subscriber._protocol import streaming_pull_manager
E     File "/tmpfs/src/github/google-cloud-python/pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 198
E       print(f"{messages_percent}, {bytes_percent}")
E                                                  ^
E   SyntaxError: invalid syntax
```

Looks like `streaming_pull_manager.py` is using a format string, which isn't valid Python 2.7 syntax. Needs to use `"{}, {}".format(...)`, instead.

**Comment by plamut** [comment]
How did that end up in the codebase, didn't the tests catch this before merging?

Anyhow, will have a look at it tomorrow, should be an easy fix. Thanks for bringing it up!

**Comment by plamut** [comment]
Found the [commit](https://github.com/googleapis/google-cloud-python/pull/7758/commits/b606d889f673b077fb43373c856c14e144d13991) that brought this in.

What are all those `print()` calls in `streaming_pull_manager.py` for anyway? They seem like some debugging leftovers to me...

**Comment by anguillanneuf** [comment]
I confirm those are bebugging leftover. They are safe to remove/reverted to what's there before.

**Comment by sduskis** [comment]
Thanks for taking care of this, @tswast, @anguillanneuf and @plamut
