### ISSUE TITLE
Allow transfring files from GCS to SFTP

### ISSUE THREAD

**Issue by OmerJog** [googleapis/google-cloud-python#7844]
The lib supports downloading files from GCS to local host.
However it doesn't support transferring the files directly to FTP server.
It would be nice if this would be possible directly.

**Comment by tseaver** [comment]
We're unlikely to add a dependency to `google-cloud-storage` to support this usecase.  However, `Blob.download_to_file` takes a file-like *object*, not a filename, which means you should be able to do the copy using [`paramiko`](http://docs.paramiko.org/en/2.4/), via something like (untested):

```python
import paramiko

ssh_client = paramiko.SSHClient()
ssh_client.connect(hostname)
sftp_client = ssh_client.open_sftp()
with sftp_client.file('blob_copy.txt', 'w') as target:
    blob.download_to_file(target)
sftp_client.close()
ssh_client.close()
```

**Comment by northtree** [comment]
> We're unlikely to add a dependency to `google-cloud-storage` to support this usecase. However, `Blob.download_to_file` takes a file-like _object_, not a filename, which means you should be able to do the copy using [`paramiko`](http://docs.paramiko.org/en/2.4/), via something like (untested):
> 
> ```python
> import paramiko
> 
> ssh_client = paramiko.SSHClient()
> ssh_client.connect(hostname)
> sftp_client = ssh_client.open_sftp()
> with sftp_client.file('blob_copy.txt', 'w') as target:
>     blob.download_to_file(target)
> sftp_client.close()
> ssh_client.close()
> ```

@tseaver Is this solution supported **streaming**, which means I could use it to download and upload one file exceeded max memory of GCF?
