### ISSUE TITLE
ImportError: cannot import name 'logging' from 'google.cloud' (unknown location)

### ISSUE THREAD

**Issue by iamtodor** [googleapis/google-cloud-python#7866]
If you are still having issues, please be sure to include as much information as possible:

#### Environment details
1. google-cloud-logging==1.10.0
2. Google Cloud Platform, Cloud Functions
3. python37
4. google-cloud-logging==1.10.0

#### Steps to reproduce

  1. Add google-cloud-logging to requirements
  2. Import logging to .py file as `from google.cloud import logging`
  3. Create cloudbuild.yaml, describe the build
  4. Create Google Cloud Platform Trigger to some repository
  5. Push code to reposirory
  6. Check the output (stack trace) from Google Cloud Platform Cloud Build

#### Code example

```python
from google.cloud import logging
request_arguments = request.args.to_dict()
logging_client = logging.Client(project='my_project')
logger = logging_client.logger('my_logs')
logger.log_struct(request_arguments)
```

#### Stack trace
```
starting build "c960d62e-9f4a-473c-9034-0d20cb312687"

FETCHSOURCE
Initialized empty Git repository in /workspace/.git/
From https://source.developers.google.com/p/my_project/r/build
* branch e1760f02032b0418bff27d3204f27f01b1a70d5f -> FETCH_HEAD
HEAD is now at e1760f0 trying to fix logging
BUILD
Already have image (with digest): gcr.io/cloud-builders/gcloud
Created .gcloudignore file. See `gcloud topic gcloudignore` for details.
Deploying function (may take a while - up to 2 minutes)...
.................failed.
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Function failed on loading user code. Error message: Code in file main.py can't be loaded.
Detailed stack trace: Traceback (most recent call last):
File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 305, in check_or_load_user_function
_function_handler.load_user_function()
File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 184, in load_user_function
spec.loader.exec_module(main)
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/user_code/main.py", line 3, in <module>
from google.cloud import logging
ImportError: cannot import name 'logging' from 'google.cloud' (unknown location)

ERROR
ERROR: build step 0 "gcr.io/cloud-builders/gcloud" failed: exit status 1
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by tseaver** [comment]
@iamtodor Your installation of `google-cloud-logging` is broken:  can you please show the output of `pip freeze` in the environment which produces the traceback?

**Comment by iamtodor** [comment]
@tseaver could you please give me a hint of how to reach this? I am using it with Google Cloud Platform and don't know how to do this. Here is the output from my `requirements.txt`:
```
requests==2.19.1
pymssql==2.1.4
elasticsearch==6.3.1
python-dateutil==2.8.0
google-cloud-logging
Flask==1.0.2
```

**Comment by tseaver** [comment]
Trying to reproduce in a virtualenv:

```bash
$ python3.7 -m venv /tmp/gcp/7866
$ /tmp/gcp/7866/bin/pip install --upgrade setuptools pip
...
Successfully installed pip-19.1.1 setuptools-41.0.1
$ gvim /tmp/gcp/7866/requirements.txt  # add your requirements
$ /tmp/gcp/7866/bin/pip install -r /tmp/gcp/7866/requirements.txt 
...
Successfully installed Flask-1.0.2 Jinja2-2.10.1 MarkupSafe-1.1.1 Werkzeug-0.15.2 cachetools-3.1.0 certifi-2019.3.9 chardet-3.0.4 click-7.0 elasticsearch-6.3.1 google-api-core-1.10.0 google-auth-1.6.3 google-cloud-core-0.29.1 google-cloud-logging-1.10.0 googleapis-common-protos-1.5.10 grpcio-1.20.1 idna-2.7 itsdangerous-1.1.0 protobuf-3.7.1 pyasn1-0.4.5 pyasn1-modules-0.2.5 pymssql-2.1.4 python-dateutil-2.8.0 pytz-2019.1 requests-2.19.1 rsa-4.0 six-1.12.0 urllib3-1.23
$ /tmp/gcp/7866/bin/python
Python 3.7.1 (default, Oct 22 2018, 11:31:38) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import logging
>>> logging.__version__
'1.10.0'
>>> ^D
```

So, I'm pretty sure that something in your cloudbuild environment is installing a broken package in the `google` namespace.  Can you get the output of the following?

```python
import google
print(google.__path__)
```

And also (similar to `pip freeze`):

```python
import pkg_resources
for dist in pkg_resources.working_set:
    print(dist)
```

**Comment by iamtodor** [comment]
@tseaver could you please tell me how can I connect to the "container" not sure if I called it right to execute `python3.7 -m venv /tmp/gcp/7866`?

**Comment by iamtodor** [comment]
@tseaver We had holiday yersterday. Here is the output from
```
import google
print(google.__path__)
```
`_NamespacePath(['/env/local/lib/python3.7/site-packages/google', '/env/lib/python3.7/site-packages/google'])`. According to this payload it seems google package successfully installed.

**Comment by tseaver** [comment]
@iamtodor 
> UPD: Fortunately sometime later I have figured out what was the reason for the issue. Thank you for the help, I highly appreciate it!

I'm glad you resolved the problem.  Could you post a description of the resolution here, for the benefit of those who find this issue via search in the future?  My suspicion from looking at the packages you listed is that the `google-cloud-functions-worker` project (which I can't find on PyPI??) might be the culprit.

**Comment by iamtodor** [comment]
Well, the problem was really easy but not obvious at first look. My `.gitignore` contains `.txt` files that mean I don't install any additional package that was provided within requirements.txt

**Comment by shubhamchaukro** [comment]
> Well, the problem was really easy but not obvious at first look. My `.gitignore` contains `.txt` files that mean I don't install any additional package that was provided within requirements.txt

I am facing the same issue could you please mention how you solved it

**Comment by iamtodor** [comment]
@shubhamchaukro remove `.txt` from `.gitignore` and let GCP install all the packages that you are providing in `req.txt`
