### ISSUE TITLE
Symbol instances of OCR on PDF missing boundingBox attributes.

### ISSUE THREAD

**Issue by fishLogic25** [googleapis/google-cloud-python#7905]
Hi,

I have been doing some testing of the Google Cloud API OCR service on some PDF files. I have noticed that the proto definition of a symbol here: https://github.com/googleapis/google-cloud-python/blob/master/vision/google/cloud/vision_v1/proto/text_annotation.proto indicates that a Symbol proto may have a bounding_box member. However, none of the symbols in my test output contain bounding boxes. Higher level attributes like Words, Paragraphs ... do have bounding boxes. I wonder if there is some configuration I am missing or if this is intentional?

Thanks,

Ryan

**Comment by tseaver** [comment]
@beccasaurus Can you help figure this one out?

**Comment by beccasaurus** [comment]
@dizcology /cc @googleapis/ml-apis

**Comment by sduskis** [comment]
This seems like something that ought to be asked of the Vision support team should handle, not something that the clients can fix. You can find various support avenues here: https://cloud.google.com/vision/docs/support and here: https://cloud.google.com/support/docs/issue-trackers

**Comment by nnegrey** [comment]
@fishLogic25, if you want to pipe this over to the https://github.com/GoogleCloudPlatform/python-docs-samples repo. I'd be happy to try to take a look and figure out which Feature you are using with the Vision API. In the end it may still be that you'll have to file an issue on https://cloud.google.com/support/docs/issue-trackers for product feedback, but maybe we can find the answer. :)

**Comment by MaxRepin** [comment]
Dear all,

This issue is relevant, I've opened the discussion in Google Groups: https://groups.google.com/forum/#!topic/cloud-vision-discuss/xaYH9xTPBYk

Regards,
Max

**Comment by redvedev** [comment]
This still occurs, and nobody says about solution (especially in the discussion on google groups)
