### ISSUE TITLE
PubSub: Bad error message when message attribute is too long

### ISSUE THREAD

**Issue by mlucy** [googleapis/google-cloud-python#7906]
#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types

PubSub

2. OS type and version

Ubuntu 16.04.6 LTS (Xenial Xerus)

3. Python version and virtual environment information: `python --version`

Python 2.7.12

4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`

google-cloud-pubsub==0.40.0

#### Steps to reproduce

  1. Send a message with an attribute that is too long.
  2. The error message will be bad.  It will say "One of the attributes in the request has a 2000 that is too long. The length is 1024 characters, but the maximum allowed is value. Refer to https://cloud.google.com/pubsub/quotas for more information." instead of "One of the attributes in the request has a value that is too long. The length is 2000 characters, but the maximum allowed is 1024. Refer to https://cloud.google.com/pubsub/quotas for more information."

#### Code example

```python
from google.cloud import pubsub_v1

publisher = pubsub_v1.PublisherClient()
path = publisher.topic_path(PROJECT_ID, TOPIC_PATH)
future = publisher.publish(path, '', foo=('a'*2000))
raise future.exception()
```

#### Stack trace
```
>>> Traceback (most recent call last):                                                               
  File "<stdin>", line 1, in <module>                                                                
  File "/tmp/repro.py", line 9, in <module>                                                          
    raise future.exception()                                                                         
google.api_core.exceptions.InvalidArgument: 400 One of the attributes in the request has a 2000 that is too long. The length is 1024 characters, but the maximum allowed is value. Refer to https://cloud.google.com/pubsub/quotas for more information.                                                     
```

**Comment by tseaver** [comment]
Thanks for the report!  That error message is generated by the back-end API, not by the `google-cloud-pubsub` client library.  @sduskis, can you suggest where this report should be directed?

**Comment by sduskis** [comment]
@kamalaboulhosn, do you have any insight into this issue?  Would it make sense to add some additional information about which attribute caused the validation issue?

**Comment by kamalaboulhosn** [comment]
Yes, this is an error message generated on the server side. I will make a fix there and will also add the name of the attribute that is incorrect.

**Comment by sduskis** [comment]
There was a back-end fix for this, which will be deployed at some point in the near future.  Thanks @kamalaboulhosn!  I'm going to close this issue, since there's nothing more we can do here.
