### ISSUE TITLE
logging usage docs for list_entries method incorrect for both v1 and v2 library

### ISSUE THREAD

**Issue by rsalmond** [googleapis/google-cloud-python#7916]
#### Environment details

1. Logging API
2. OSX Mojave
3. Python version: 3.7.3
4. google-cloud-logging version:  
```
pip show google-cloud-logging
Name: google-cloud-logging
Version: 1.10.0
```

#### Steps to reproduce

  1. Navigate to the [usage start docs](https://googleapis.github.io/google-cloud-python/latest/logging/usage.html#retrieving-log-entries).
  2. Check out the example code `client.list_entries(project_ids=PROJECT_IDS)`
  3. Confirm that this is the [method name of the V1 library](https://github.com/googleapis/google-cloud-python/blob/master/logging/google/cloud/logging/client.py#L184-L186) mixed with the [renamed parameter of the v2 library](https://github.com/googleapis/google-cloud-python/blob/master/logging/google/cloud/logging_v2/gapic/logging_service_v2_client.py#L416-L419). 

I would have just cut a PR to fix it but it is unclear from that page whether the examples are for the v1 or v2 library.

**Comment by tseaver** [comment]
@rsalmond For clarity, the method name you link to is not "the V1 library":  it is the high-level client object, which supports both GAPIC and HTTP/JSON requests to the V2 back-end API.

You are correct that the parameter name for the high-level client's `list_entries` method should be `projects`, rather than `project_ids`.

**Comment by tseaver** [comment]
Here is the offending snippet:.
https://github.com/googleapis/google-cloud-python/blob/8581f6a118f13f1f4ce3131ea96fde7425c7bd4f/logging/docs/snippets.py#L104-L113

I need to figure out why those snippets aren't being tested under CI.
