### ISSUE TITLE
Core: Retry.__init__ add on_error

### ISSUE THREAD

**Issue by xmedeko** [googleapis/google-cloud-python#7951]
`Retry.__call__` has `on_error` argument. I would like to have it in the `Retry.__init__`, too. I use it for own logging of retry.

**Comment by Emar-Kar** [comment]
@xmedeko Could you explain some details, please. As I understand you would like to add `on_error` argument into the `Retry.__init__` method, but I really can not get how are you going to use it? Do you want it to be the class attribute, or you want it to be called in `__init__`?

**Comment by tseaver** [comment]
@Emar-Kar I read the request that the `on_error` passed to the constructor would be saved as an attribute on the `Retry` instance, and used in every invocation as a fall-back if no `on_error` is passed.  E.g.:

```python
from google.api_core.retry import Retry

def error_callback(exception):
    psas

retry = Retry(on_error=error_callback)

# callback invoked for retryable exceptions
retry(some_object.delete)()
```
