### ISSUE TITLE
Does not install on Linux

### ISSUE THREAD

**Issue by ttfreeman** [googleapis/google-cloud-python#7952]
I am trying to install Google Cloud SDK on Linux (in a Chrome OS). I have followed all the steps from https://cloud.google.com/sdk/docs/#linux , which means, I have downloaded and unpacked it on my file system and have attempted running the command ./google-cloud-sdk/install.sh or ./google-cloud-sdk/bin/gcloud init (with and without sudo). However, all I get is an error ./google-cloud-sdk/bin/gcloud: command not found or ./google-cloud-sdk/install.sh: No such file or directory or sudo: ./install.bat: command not found. I have tried different paths and anything else I could think of and nothing seem to work.

**Comment by ttfreeman** [comment]
@JustinBeckwith thanks for assigning this, and I would love to help, but I no longer own a Chrome OS laptop to test.

**Comment by JustinBeckwith** [comment]
No worries - just a robot run amok.  Feel free to ignore!  🤖
