### ISSUE TITLE
Problem with 'httplib2' when installing gsutil on linux

### ISSUE THREAD

**Issue by ajwitty** [googleapis/google-cloud-python#7957]
I am trying to download some dataset using gsutil, but when trying to install, i get the following  error with regards to the package httplib2: 

Collecting gsutil
  Downloading https://files.pythonhosted.org/packages/60/22/c421f4bcf4ebdc4516211e79afac1c0af4df6d8e0f478682a08c02a4dd0b/gsutil-4.34.tar.gz (866kB)
    100% |████████████████████████████████| 870kB 9.7MB/s 
Requirement already satisfied: argcomplete>=1.9.4 in /usr/local/lib/python3.5/dist-packages (from gsutil) (1.10.0)
Requirement already satisfied: boto==2.48.0 in /usr/local/lib/python3.5/dist-packages (from gsutil) (2.48.0)
Requirement already satisfied: crcmod>=1.7 in /usr/local/lib/python3.5/dist-packages (from gsutil) (1.7)
Requirement already satisfied: fasteners>=0.14.1 in /usr/local/lib/python3.5/dist-packages (from gsutil) (0.14.1)
Collecting gcs-oauth2-boto-plugin>=2.2 (from gsutil)
  Downloading https://files.pythonhosted.org/packages/53/ef/ac13239328b5d0727079b5298265f7fec272d4fe2ee0c145d341944611f8/gcs-oauth2-boto-plugin-2.3.tar.gz
Collecting google-apitools>=0.5.24 (from gsutil)
  Downloading https://files.pythonhosted.org/packages/7f/32/df3e36fd705a00092f1ffa9f41ce1df8dcb594ae313d239b87861a41fc2e/google-apitools-0.5.28.tar.gz (172kB)
    100% |████████████████████████████████| 174kB 11.1MB/s 
Collecting httplib2>=0.11.3 (from gsutil)
  Downloading https://files.pythonhosted.org/packages/e8/b3/b34037575d6d75ff8dcfcf75315f56befbe409952be9f95c9b8cc9ee0499/httplib2-0.12.3-py3-none-any.whl (94kB)
    100% |████████████████████████████████| 102kB 14.8MB/s 
Requirement already satisfied: google-reauth>=0.1.0 in /usr/local/lib/python3.5/dist-packages (from gsutil) (0.1.0)
Collecting mock==2.0.0 (from gsutil)
  Downloading https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 17.7MB/s 
Requirement already satisfied: monotonic>=1.4 in /usr/local/lib/python3.5/dist-packages (from gsutil) (1.5)
Collecting oauth2client==4.1.3 (from gsutil)
  Downloading https://files.pythonhosted.org/packages/95/a9/4f25a14d23f0786b64875b91784607c2277eff25d48f915e39ff0cff505a/oauth2client-4.1.3-py2.py3-none-any.whl (98kB)
    100% |████████████████████████████████| 102kB 13.9MB/s 
Collecting pyOpenSSL>=0.13 (from gsutil)
  Downloading https://files.pythonhosted.org/packages/01/c8/ceb170d81bd3941cbeb9940fc6cc2ef2ca4288d0ca8929ea4db5905d904d/pyOpenSSL-19.0.0-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 19.6MB/s 
Collecting python-gflags>=2.0 (from gsutil)
  Downloading https://files.pythonhosted.org/packages/df/ec/e31302d355bcb9d207d9b858adc1ecc4a6d8c855730c8ba4ddbdd3f8eb8d/python-gflags-3.1.2.tar.gz (52kB)
    100% |████████████████████████████████| 61kB 19.6MB/s 
Collecting retry_decorator>=1.0.0 (from gsutil)
  Downloading https://files.pythonhosted.org/packages/95/7a/807ac21749ecd26ae3337c3069ed6ac8658b9fbc85f109e419a812b18ab7/retry_decorator-1.1.0.tar.gz
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.5/dist-packages (from gsutil) (1.12.0)
Collecting SocksiPy-branch==1.01 (from gsutil)
  Downloading https://files.pythonhosted.org/packages/69/ed/3659a7e2cff38c3156cf919f8f6ee63360147ba97460c0a8c130f8b781e0/SocksiPy-branch-1.01.tar.gz
Requirement already satisfied: pyu2f in /usr/local/lib/python3.5/dist-packages (from google-reauth>=0.1.0->gsutil) (0.1.4)
Collecting pbr>=0.11 (from mock==2.0.0->gsutil)
  Downloading https://files.pythonhosted.org/packages/07/3e/22d1d35a4b51706ca3590c54359aeb5fa7ea60df46180143a3ea13d45f29/pbr-5.2.0-py2.py3-none-any.whl (107kB)
    100% |████████████████████████████████| 112kB 11.6MB/s 
Collecting pyasn1-modules>=0.0.5 (from oauth2client==4.1.3->gsutil)
  Downloading https://files.pythonhosted.org/packages/91/f0/b03e00ce9fddf4827c42df1c3ce10c74eadebfb706231e8d6d1c356a4062/pyasn1_modules-0.2.5-py2.py3-none-any.whl (74kB)
    100% |████████████████████████████████| 81kB 12.6MB/s 
Collecting rsa>=3.1.4 (from oauth2client==4.1.3->gsutil)
  Downloading https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.5/dist-packages (from oauth2client==4.1.3->gsutil) (0.4.5)
Collecting cryptography>=2.3 (from pyOpenSSL>=0.13->gsutil)
  Downloading https://files.pythonhosted.org/packages/5b/12/b0409a94dad366d98a8eee2a77678c7a73aafd8c0e4b835abea634ea3896/cryptography-2.6.1-cp34-abi3-manylinux1_x86_64.whl (2.3MB)
    100% |████████████████████████████████| 2.3MB 8.7MB/s 
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=2.3->pyOpenSSL>=0.13->gsutil)
  Downloading https://files.pythonhosted.org/packages/62/76/135eeffe0089e6724bdd65c1bf9f1654db9b47783e65b8d9f1454c540d8b/cffi-1.12.3-cp35-cp35m-manylinux1_x86_64.whl (429kB)
    100% |████████████████████████████████| 430kB 11.8MB/s 
Collecting asn1crypto>=0.21.0 (from cryptography>=2.3->pyOpenSSL>=0.13->gsutil)
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 13.7MB/s 
Requirement already satisfied: pycparser in /usr/lib/python3/dist-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.3->pyOpenSSL>=0.13->gsutil) (2.14)
Installing collected packages: httplib2, pyasn1-modules, rsa, oauth2client, cffi, asn1crypto, cryptography, pyOpenSSL, SocksiPy-branch, retry-decorator, gcs-oauth2-boto-plugin, google-apitools, pbr, mock, python-gflags, gsutil
  Found existing installation: httplib2 0.9.1
**Cannot uninstall 'httplib2'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.**

I know that this problem is caused by incompatibility between gsutil and distutil, and am wondering if anyone knows how I can uninstall httplib2 or circumvent this issue, thanks.

**Comment by busunkim96** [comment]
Hi @ajwitty! It sounds like you're having an issue with gsutil. That tool is maintained in a separate repository. Please add your issue to the gsutil [issue tracker](https://github.com/GoogleCloudPlatform/gsutil/issues).
