### ISSUE TITLE
BigQuery: Add Connection object to Magics Context

### ISSUE THREAD

**Issue by vimota** [googleapis/google-cloud-python#8024]
**Is your feature request related to a problem? Please describe.**
Our team (Kaggle) supports a Public Datasets BigQuery integration in Kernels (Jupyter Notebooks) using a proxy where we inject our own credentials. We currently expose a PublicBigQueryClient that handles this (https://github.com/Kaggle/docker-python/blob/master/patches/kaggle_gcp.py#L70) but we're unable to support Magics via this mechanism since we need to be able to pass in a Connection object to the client.
 **Describe the solution you'd like**
Being able to set either the client object or the Connection object of the Magic (like Context.set_credentials) would solve this.
 **Describe alternatives you've considered**
We've considered monkeypatching the magics client but that may cause more problems.

**Comment by tswast** [comment]
I'd be open to a PR that adds a `_connection` property to `Context`.

**Comment by tswast** [comment]
The reason I don't think `client` would be a good property for `Context` is that there are many default values on `Client` that are also present in `Context`. I gets too confusing to know which to set.

**Comment by tswast** [comment]
Fixed by #8192.
