### ISSUE TITLE
Firestore: links in docs, static code analysis and autocompletion in PyCharm are broken

### ISSUE THREAD

**Issue by cbenhagen** [googleapis/google-cloud-python#8035]
Due to docstrings formatted like this, static code analysis and autocomplete in PyCharm and the links in the [online Sphinx docs](https://googleapis.github.io/google-cloud-python/latest/firestore/client.html#google.cloud.firestore_v1beta1.client.Client.document) are broken:
https://github.com/googleapis/google-cloud-python/blob/de0103cedaf9fb9f03ddca9be801ac64635d7b74/firestore/google/cloud/firestore_v1/client.py#L250-L252

This should result in the same short name with a working link in the Sphinx docs and would not kill autocomplete etc:
```
Returns:
    :class:`~google.cloud.firestore_v1.document.DocumentReference`: A reference
    to a document in a collection.
```

**Comment by tseaver** [comment]
Thanks for the report.  For benefit of future self (or whoever):

```bash
$ git grep -l "~\." firestore/
firestore/google/cloud/firestore_v1/_helpers.py
firestore/google/cloud/firestore_v1/batch.py
firestore/google/cloud/firestore_v1/client.py
firestore/google/cloud/firestore_v1/collection.py
firestore/google/cloud/firestore_v1/document.py
firestore/google/cloud/firestore_v1/field_path.py
firestore/google/cloud/firestore_v1/gapic/firestore_client.py
firestore/google/cloud/firestore_v1/gapic/transports/firestore_grpc_transport.py
firestore/google/cloud/firestore_v1/query.py
firestore/google/cloud/firestore_v1/transaction.py
firestore/google/cloud/firestore_v1beta1/_helpers.py
firestore/google/cloud/firestore_v1beta1/batch.py
firestore/google/cloud/firestore_v1beta1/client.py
firestore/google/cloud/firestore_v1beta1/collection.py
firestore/google/cloud/firestore_v1beta1/document.py
firestore/google/cloud/firestore_v1beta1/field_path.py
firestore/google/cloud/firestore_v1beta1/gapic/firestore_client.py
firestore/google/cloud/firestore_v1beta1/gapic/transports/firestore_grpc_transport.py
firestore/google/cloud/firestore_v1beta1/query.py
firestore/google/cloud/firestore_v1beta1/transaction.py
```

**Comment by cbenhagen** [comment]
@tseaver please reopen this issue. It still does not work as you can see here: https://googleapis.github.io/google-cloud-python/latest/firestore/query.html#google.cloud.firestore_v1beta1.query.Query.stream

if you do need to prepend the tilde you have to write it this way:
```
:class:`~google.cloud.firestore_v1.document.DocumentReference`
```

**Comment by tseaver** [comment]
@cbenhagen Can you please try out the branch from #8102?

**Comment by cbenhagen** [comment]
lgtm
