### ISSUE TITLE
Pub/Sub: publish message hangs waiting for previous publish to timeout

### ISSUE THREAD

**Issue by asnr** [googleapis/google-cloud-python#8036]
#### Environment details

OS type and version: 4.9.125-linuxkit GNU/Linux
Python version and virtual environment information: Python 2.7.16
google-cloud-pubsub package version: 0.41.0

#### Steps to reproduce

1. Publish a (first) message to PubSub that fails
2. Timeout on the future object returned by the call to `publish()`, _before_ the grpc publish call in the batch thread returns
3. Publish a (second) message to the same topic. This call hangs until the previous call to grpc publish in the batch thread returns. As the default timeout is currently [10 minutes](https://github.com/googleapis/google-cloud-python/blob/4166ddbf1f8b07c2a5e2db8f7955457b5cedd82d/pubsub/google/cloud/pubsub_v1/gapic/publisher_client_config.py#L26) (!) this can take take 10 minutes to return.

Hanging for 10 minutes is surprising behaviour for an asynchronous API.

#### Code example

See this [gist](https://gist.github.com/asnr/36b7f6ee7e2f31f50b1d07020e6ba3f9) for code and instructions on how to reproduce this issue.

#### Wot I think is going on here

This is wild conjecture that I have no supporting evidence for.

That being said, I think the issue starts when the batch thread gets stuck in this [call](https://github.com/googleapis/google-cloud-python/blob/4166ddbf1f8b07c2a5e2db8f7955457b5cedd82d/pubsub/google/cloud/pubsub_v1/publisher/_batch/thread.py#L201) to grpc `publish`. At this point it is [holding onto](https://github.com/googleapis/google-cloud-python/blob/4166ddbf1f8b07c2a5e2db8f7955457b5cedd82d/pubsub/google/cloud/pubsub_v1/publisher/_batch/thread.py#L201) the lock `_state_lock` and will continue to hold on to it for 10 minutes until it the call to grpc `publish` times out.

When the client application calls `publish()` in the main thread for the second time, it will [try to acquire](https://github.com/googleapis/google-cloud-python/blob/4166ddbf1f8b07c2a5e2db8f7955457b5cedd82d/pubsub/google/cloud/pubsub_v1/publisher/_batch/thread.py#L280) the same lock `_state_lock`. As this lock is already being held by the batch thread, the main thread hangs and doesn't return from the call to `publish()`.

**Comment by plamut** [comment]
@asnr Thank you for the effort and the detailed steps to reproduce the issue.

I can confirm that the issue is reproducible, either by using the linked Docker application, or by simply disabling the internet connection and running the test publisher script (without creating the topic and subscription, that is).

The cause of the long delay is that the lock in the underlying batch (an object that batches publish requests) is held for too long. It also turned out that the fix for it is essentially the same as #7686.

I will open a follow-up PR that also includes tests, and mention the creators of the original PR as co-authors.

**Comment by plamut** [comment]
@Dan4London Just FYI, the [pull request](https://github.com/googleapis/google-cloud-python/pull/8234) for this issue that you [reported](https://github.com/googleapis/google-cloud-python/issues/7910#issuecomment-494450846) in the other thread has been created.
