### ISSUE TITLE
Pub/Sub: Outdated subscriber documentation.

### ISSUE THREAD

**Issue by Jofre** [googleapis/google-cloud-python#8080]
https://github.com/googleapis/google-cloud-python/blob/master/pubsub/docs/subscriber/index.rst

This documentation references pubsub_v1.subscriber.policy, which was deprecated on [this commit](https://github.com/googleapis/google-cloud-python/commit/0da12f692070258b652d8a807a5f00c44bdbe618).

This seems confusing when trying to follow the documentation.

**Comment by tseaver** [comment]
Thanks for the report!
