### ISSUE TITLE
Communicating ADH(Ads data hub) and BigQuery

### ISSUE THREAD

**Issue by sajal88241** [googleapis/google-cloud-python#8110]
Hi,

I have a table 'A' in BigQuery with schema {'UID': 'String'} I want to join this table on UID with a target table 'B' in ADH(Ads data hub) having schema 
{'UID': 'String',
'DC_ID': 'INT'}
and write the joined output to a new table in BigQuery. Can someone from the team guide me to implement the same in Python.

Thanks!

**Comment by tseaver** [comment]
@sajal88241 For ADH-related support, please see the ADS developers' site, e.g. [this page](https://developers.google.com/ads-data-hub/guides/join-your-data).
