### ISSUE TITLE
Pubsub: add 'PublisherClient.from_service_account_dict'

### ISSUE THREAD

**Issue by xrmx** [googleapis/google-cloud-python#8137]
**Is your feature request related to a problem? Please describe.**
I'd like to use the pubsub client on a webapp where i have the secrets in environment variables and not on disk.
 **Describe the solution you'd like**
I would like to have a classmethod added to Publisher to instantiate a client with the credentials passed from a dict instead of a json file path.

**Comment by tseaver** [comment]
@xrmx You should be able to create credentials via the `from_service_account_info` method, and pass them to the client constructor, e.g.:

```python
from google.oauth2.service_account import Credentials
from google.cloud.pubsub_v1 import PublisherClient

credentials = Credentials.from_service_account_info(your_dict)
publisher_client = PublisherClient(credentials=credentials)
```

**Comment by xrmx** [comment]
@tseaver sure I am currently doing this, but it would be nice to have already a wrapper to avoid digging into source code to find out where all this come from :)

**Comment by sduskis** [comment]
I think that this is a general auth problem.  There should be a simple way to configure auth.  IMHO, if there's a nee for a different auth configuration, there should be a clear and documented way to do more complex configuration.  The changes should probably adding more docs for auth, and then getting references to those docs from all of the clients.

**Comment by tseaver** [comment]
The [`PublisherClient` API docs](https://googleapis.github.io/google-cloud-python/latest/pubsub/publisher/api/client.html) should definitely document the args to `PublisherClient.__init__` more clearly, including passing a pre-created `credentials`.  Ditto for the [`SubscriberClient` API docs](https://googleapis.github.io/google-cloud-python/latest/pubsub/subscriber/api/client.html).

Given that we fix the docs, I'd say we don't need to add a `from_service_account_dict` method to either client.

**Comment by plamut** [comment]
FWIW, there is an [open PR](https://github.com/googleapis/google-cloud-python/pull/8429/files) that adds a quick example on how to use an other-than-default Credentials object. If that is deemed sufficient, we could close this issue.

Or, if "almost sufficient", the PR can be updated to cover this issue, too.

**Comment by xrmx** [comment]
@plamut commented on the PR, thanks!
