### ISSUE TITLE
BigQuery: Add dryrun option to magic.

### ISSUE THREAD

**Issue by jpallas** [googleapis/google-cloud-python#8143]
The BQ API supports the dry_run option, but the ipython magic does not.  It would be great if there were a parameter which, when set, would return the (sometimes vital) information about bytes to be read instead of running the query.  This would help put the Jupyter environment on a par with the BQ console.

**Comment by tswast** [comment]
FYI: there's an open PR at https://github.com/googleapis/google-cloud-python/pull/8179 which will add `context.default_query_job_config`, so that this will be possible to set globally.

I agree that a parameter would make sense for this option. See #8179 for implementation and testing patterns.

**Comment by tswast** [comment]
Likely for `--dryrun` queries we'll want to print out something other than an empty DataFrame the estimated bytes processed and maybe additional stats if relevant.

Maybe return a `QueryJob` instead of a `DataFrame` for inspection.

**Comment by jpallas** [comment]
Yes, my thinking was to provide (at least) the same cost feedback that the BQ console interface does.

**Comment by tswast** [comment]
Closed by #9067.
