### ISSUE TITLE
AutoML: PredictionServiceClient returns no predictions.

### ISSUE THREAD

**Issue by ddribes** [googleapis/google-cloud-python#8181]
Hi,

I am trying to use the model I've created using AutoML (BTW, thanks, great tool).
I've first tested the Android version, as proposed in the cloud.google.com/automl web interface through TF LITE (https://cloud.google.com/vision/automl/docs/tflite-android-tutorial).
The classification results are bad compared to the one given by the web interface.

To better understand where the problem could stand (e.g. Tablet performances, camera quality, conversion from BMP to bytes, ...) I've decided to try the Google Cloud version through a Python interface. 
I've first copied and paste the code proposed in the web interface with a slithy modification due to the use of Python3 on the print line:

```
import sys

from google.cloud import automl_v1beta1
from google.cloud.automl_v1beta1.proto import service_pb2


def get_prediction(content, project_id, model_id):
  prediction_client = automl_v1beta1.PredictionServiceClient()

  name = 'projects/{}/locations/us-central1/models/{}'.format(project_id, model_id)
  payload = {'image': {'image_bytes': content }}
  params = {}
  response = prediction_client.predict(name, payload, params)
  print("Prediction results:")
  for result in response.payload:
    print("Predicted class name: {}".format(result.display_name))
    print("Predicted class score: {}".format(result.classification.score))
  return response  # waits till request is returned

if __name__ == '__main__':
  file_path = sys.argv[1]
  project_id = sys.argv[2]
  model_id = sys.argv[3]

  with open(file_path, 'rb') as ff:
    content = ff.read()

  print (get_prediction(content, project_id,  model_id))
```

But I don't get any prediction.
The response list is empty (I've tried with a couple of images)

I think it might be due to the location: us-central1 as I am sitting here in Switzerland. But if I change this to: europe-west6, I get an error:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 562, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "List of found errors:	1.Field: name; Message: The provided location ID is not valid.	"
	debug_error_string = "{"created":"@1559036313.238837000","description":"Error received from peer ipv4:216.58.215.234:443","file":"src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"List of found errors:\t1.Field: name; Message: The provided location ID is not valid.\t","grpc_status":3}"

> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "GoogleVisionPredict.py", line 28, in <module>
>     print (get_prediction(content, project_id,  model_id))
>   File "GoogleVisionPredict.py", line 13, in get_prediction
>     response = prediction_client.predict(name, payload, params)
>   File "/usr/local/lib/python3.7/site-packages/google/cloud/automl_v1beta1/gapic/prediction_service_client.py", line 311, in predict
>     request, retry=retry, timeout=timeout, metadata=metadata
>   File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
>     return wrapped_func(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
>     on_error=on_error,
>   File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 179, in retry_target
>     return target()
>   File "/usr/local/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
>     six.raise_from(exceptions.from_grpc_error(exc), exc)
>   File "<string>", line 3, in raise_from
> google.api_core.exceptions.InvalidArgument: 400 List of found errors:	1.Field: name; Message: The provided location ID is not valid.

Below the version of the libraries and OS system used:

> Python 3.7.3
> google-api-core==1.9.0
> google-auth==1.6.3
> google-cloud-automl==0.2.0
> google-cloud-core==0.29.1
> google-cloud-language==1.2.0
> google-cloud-translate==1.4.0
> google-cloud-videointelligence==1.8.0
> google-cloud-vision==0.36.0
> googleapis-common-protos==1.5.9

> macOS Mojave - Version 10.14.4

I don't know what else I should try...
Thanks for the help!

**Comment by tseaver** [comment]
The location should match the one you used when creating the model.

@beccasaurus Can you suggest anything for the OP to try further.

**Comment by ddribes** [comment]
Thanks for the answer. 

> The location should match the one you used when creating the model.

Sorry but I don't find where is this information...
Thanks again!

**Comment by ddribes** [comment]
Hi all,

I've run the test today... changed nothing (see code above with us-central1)  and it is working!

Magic of Beta version!

Thanks a lot!
