### ISSUE TITLE
BigQuery: can I authenticate via access token?

### ISSUE THREAD

**Issue by sudhanshu88241** [googleapis/google-cloud-python#8185]
Hi,

I have `client_id` and `client_secret` I am having trouble in generating `access token` and authenticating my requests. Each time I make a request it redirect to the `browser` where it generates an `authorization_code` which further used to get `access_token`, but my code will be running as a service in background. So, is there a way to generate `access_token` without launching browser.

**Comment by tseaver** [comment]
@tswast I think you have some work underway to add support for using access tokens, but I'm not sure of the status.

**Comment by tswast** [comment]
@sudhanshu88241 I'm indeed working on making the Google-maintained way easier (the official way is a bit complicated: https://cloud.google.com/bigquery/docs/authentication/end-user-installed)

In the meantime, I suggest you try out [pydata-google-auth](https://pydata-google-auth.readthedocs.io/en/latest/). There's an example of using it with BigQuery on the main readme: https://github.com/pydata/pydata-google-auth

**Comment by tswast** [comment]
pydata-google-auth caches credentials to disk, so you only have to do the auth flow once (until you revoke the key or need expanded scopes).
