### ISSUE TITLE
Container: Add v1beta1 support.

### ISSUE THREAD

**Issue by evankanderson** [googleapis/google-cloud-python#8208]
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**

I'd like to be able to provision GKE clusters with beta features like Cloud Run and Istio.

 **Describe the solution you'd like**

Include definitions for the `container/v1beta1` API alongside the `container/v1` API; the v1beta1 API surface includes additional fields on objects like `AddonsConfig`:

https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#addonsconfig

vs

https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#addonsconfig

 **Describe alternatives you've considered**

Roll my own definitions and library. 😢 

 **Additional context**

Based on a customer request for performing automated cluster turnup in python. They are seeing the following error:
```
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/container_v1/gapic/cluster_manager_client.py", line 407, in create_cluster
    project_id=project_id, zone=zone, cluster=cluster, parent=parent
ValueError: Protocol message AddonsConfig has no "cloud_run_config" field.
```

**Comment by mlarrousse** [comment]
Hey thanks for logging this! We're trying to adopt Cloud Run but it's a bit clunky right now given that we already have a deployment pipeline for clusters set up that uses this client. The proposed solution sounds good as we're interested in other beta addons now and in the future.

**Comment by tseaver** [comment]
@JustinBeckwith Can you figure out why the bot thinks this issue needs triage?

**Comment by JustinBeckwith** [comment]
The robots are rebelling, we are trying to fix it 🤖 🔥

**Comment by tseaver** [comment]
![skynet](https://user-images.githubusercontent.com/242750/58903741-2137bb00-86d4-11e9-8e49-57662794b3f2.jpeg)

**Comment by sduskis** [comment]
@tseaver, what's the next steps on this issue?

**Comment by tseaver** [comment]
@sduskis See #8436
