### ISSUE TITLE
client.create_bucket with Bucket object does not work

### ISSUE THREAD

**Issue by dkajtoch** [googleapis/google-cloud-python#8224]
I wanted to create bucket with the Bucket object and it does not work. Basically, I wanted to reproduce this piece of code:

    bucket = storage.Bucket("my-bucket-name")
    bucket.location = "europe-west6"
    bucket.storage_class = "COLDLINE"

    client.create_bucket(bucket)

I get the following error: 

bucket = client.create_bucket(bucket)  # API request.
  File "/home/darekwhites/.local/lib/python3.6/site-packages/google/cloud/storage/client.py", line 284, in create_bucket
    bucket = Bucket(self, name=bucket_name)
  File "/home/darekwhites/.local/lib/python3.6/site-packages/google/cloud/storage/bucket.py", line 313, in __init__
    name = _validate_name(name)
  File "/home/darekwhites/.local/lib/python3.6/site-packages/google/cloud/storage/_helpers.py", line 37, in _validate_name
    if not all([name[0].isalnum(), name[-1].isalnum()]):
TypeError: 'Bucket' object does not support indexing

I can normally create the bucket if a pass a string into `create_bucket` method.
I looked into the code at it seems that it does not recognize that 'bucket' is a Bucket object. 
My configuration:
linux mint 19.1
python 3.6.5 Intel Corporation
google-cloud-storage==1.13.2

**Comment by tseaver** [comment]
@dkajtoch Thanks for the report.  Support for passing a `Bucket` instance to `Client.create_bucket` was added in [`google-cloud-storage 1.16.0`](https://github.com/googleapis/google-cloud-python/releases/tag/storage-1.16.0).  Please update to that release or later (current is 1.16.1).
