### ISSUE TITLE
Information on Dataproc Job Logs

### ISSUE THREAD

**Issue by hitesh1907nayyar** [googleapis/google-cloud-python#8274]
Hi,

I am new to dataproc. I will require an information as how can i see the logs of dataproc job that is submitted. I created a python script job that is executed on dataproc. I need to debug the script and for that i require logs. How can i see that ?

**Comment by tseaver** [comment]
Please see the API docs for [using Stackdriver Logging](https://cloud.google.com/dataproc/docs/guides/stackdriver-logging) and [accessing job driver output](https://cloud.google.com/dataproc/docs/guides/driver-output).
