### ISSUE TITLE
Pub/Sub: emulator push to local endpoint failing

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/google-cloud-python#8294]
Using the Pub/Sub emulator to push to a local endpoint used to work. But it seems to have stopped working now. Here are the steps to reproduce. 

#### Environment details

2. MacOS
3. `Python 3.7.3`
4. `google-cloud-pubsub==0.41.0`

#### Steps to reproduce

  1. `git clone https://github.com/GoogleCloudPlatform/python-docs-samples.git`, then create a virtualenv and install the necessary packages from `pip install -r pubsub/cloud-client/requirements.txt`. 
  2. Start a Pub/Sub emulator in one terminal where the virtualenv is activated:`gcloud beta emulator pubsub start`.
  3. In a separate terminal where the virtualenv is also activated, export the appropriate environment variables. `export PUBSUB_PROJECT_ID=my-project-id`, then `$(gcloud beta emulators pubsub env-init)`. The latter ensures that `PUBSUB_EMULATOR_HOST` takes the correct hostname and port number. 
  4. `cd pubsub/cloud-client`, then test out the emulator by creating a topic. `python publisher.py my-project-id topics create my-topic`. 

#### Describe the problem

![Screen Shot 2019-06-12 at 10 15 56 AM](https://user-images.githubusercontent.com/9518298/59372255-f06f0b80-8cfb-11e9-8fa3-e49c25e4e161.png)

After successfully creating a push subscription `liu` that points to `http://localhost:3000/apples`, I published some messages to the topic that `liu` is tied to. When I refreshed the page, I got `304` errors, telling me that the web resource had not been modified. In other words, the local endpoint did not receive any of the messages. Normal pull subscription still works though.

**Comment by sduskis** [comment]
This seems like an emulator problem, not a client issue.  Let's discuss this internally.

**Comment by anguillanneuf** [comment]
@sduskis I just check the `gcloud` [release notes](https://cloud.google.com/sdk/docs/release-notes), but didn't see anything for `gcloud beta emulators pubsub` specifically.

**Comment by gronnbeck** [comment]
I have the same problem when running tests against Pubsub Push Subscriptions. I get a Java stacktrace from the emulator. It seems like something is missing on its classpath. Hope the stacktrace helps:

```
[pubsub] Exception in thread "pool-1-thread-2" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
[pubsub] 	at com.google.cloud.pubsub.testing.v1.HttpEndpointPusher.toJsonStringForPush(HttpEndpointPusher.java:100)
[pubsub] 	at com.google.cloud.pubsub.testing.v1.HttpEndpointPusher.push(HttpEndpointPusher.java:53)
[pubsub] 	at com.google.cloud.pubsub.testing.v1.PushLoop.push(PushLoop.java:135)
[pubsub] 	at com.google.cloud.pubsub.testing.v1.PushLoop.dispatchMessages(PushLoop.java:116)
[pubsub] 	at com.google.cloud.pubsub.testing.v1.PushLoop.run(PushLoop.java:73)
[pubsub] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[pubsub] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[pubsub] 	at java.base/java.lang.Thread.run(Thread.java:834)
[pubsub] Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
[pubsub] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
[pubsub] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[pubsub] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[pubsub] 	... 8 more
[pubsub] Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
[pubsub] 	at com.google.cloud.pubsub.testing.v1.HttpEndpointPusher.toJsonStringForPush(HttpEndpointPusher.java:100)
[pubsub] 	at com.google.cloud.pubsub.testing.v1.HttpEndpointPusher.push(HttpEndpointPusher.java:53)
[pubsub] 	at com.google.cloud.pubsub.testing.v1.PushLoop.push(PushLoop.java:135)
[pubsub] 	at com.google.cloud.pubsub.testing.v1.PushLoop.dispatchMessages(PushLoop.java:116)
[pubsub] 	at com.google.cloud.pubsub.testing.v1.PushLoop.run(PushLoop.java:73)
[pubsub] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[pubsub] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[pubsub] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by clemens-smartparking** [comment]
Have the same issue with the emulator client using nodejs. @sduskis any update on this issue?

**Comment by car12o** [comment]
@sduskis I agree with you seems like an emulator problem, is the emulator code open source? If so could you please provide me the repo?

I have exatly the same stacktrace as @gronnbeck
```
pubsub-server    | [pubsub] INFO: Detected HTTP/2 connection.
pubsub-server    | [pubsub] Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
pubsub-server    | [pubsub] 	at com.google.cloud.pubsub.testing.v1.HttpEndpointPusher.toJsonStringForPush(HttpEndpointPusher.java:99)
pubsub-server    | [pubsub] 	at com.google.cloud.pubsub.testing.v1.HttpEndpointPusher.push(HttpEndpointPusher.java:52)
pubsub-server    | [pubsub] 	at com.google.cloud.pubsub.testing.v1.PushLoop.push(PushLoop.java:133)
pubsub-server    | [pubsub] 	at com.google.cloud.pubsub.testing.v1.PushLoop.dispatchMessages(PushLoop.java:114)
pubsub-server    | [pubsub] 	at com.google.cloud.pubsub.testing.v1.PushLoop.run(PushLoop.java:71)
pubsub-server    | [pubsub] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
pubsub-server    | [pubsub] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
pubsub-server    | [pubsub] 	at java.base/java.lang.Thread.run(Thread.java:830)
pubsub-server    | [pubsub] Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
pubsub-server    | [pubsub] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
pubsub-server    | [pubsub] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
pubsub-server    | [pubsub] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
pubsub-server    | [pubsub] 	... 8 more
```

**Comment by arlobryer** [comment]
Hi @tseaver, @tobioboye, @anguillanneuf - just wondering if there's any update on this issue? I've just encountered the same problem and stumbled across this thread trying to figure out what's going on.
Also saw this which seems like the same issue - https://groups.google.com/forum/#!msg/cloud-pubsub-discuss/6SHdoTn16Po/8a09QaGvDwAJ (I see @anguillanneuf is the last person to comment there).

**Comment by anguillanneuf** [comment]
@arlobryer @tobioboye @gronnbeck @clemens-smartparking @car12o Things are moving finally! Please expect an updated emulator in the `265.0.0` release of `gcloud sdk` on October 1. 

Thanks for all your patience!
