### ISSUE TITLE
Firestore: docs mentioning 'firestore.collection_group' are incorrect.

### ISSUE THREAD

**Issue by szeitlin** [googleapis/google-cloud-python#8433]
#### Environment details

# OS type and version
Mac OSX 10.14.5 

# Python version and virtual environment information:
python 3.7.3

#google-cloud-<service> version: 

google-api-core           1.12.0                   pypi_0    pypi
google-auth               1.6.3                    pypi_0    pypi
google-cloud-core         1.0.2                    pypi_0    pypi
google-cloud-firestore    1.2.0                    pypi_0    pypi
googleapis-common-protos  1.6.0

#### Steps to reproduce

1. Created a collection with documents and sub-collections
2. Created a composite index for collection group queries
3. Cannot figure out how to do a collection group query that returns any results

#### Code example

```python
from google.cloud import firestore
query = firestore.collection_group('mygroup') #directly from your docs
```

#### Stack trace
```
AttributeError: module 'google.cloud.firestore' has no attribute 'collection_group'
```

Thanks!

**Comment by tseaver** [comment]
@szeitlin Thanks for the report!
