### ISSUE TITLE
Firestore: Add equivalent of node's 'FieldPath.documentId()'.

### ISSUE THREAD

**Issue by puf** [googleapis/google-cloud-python#8437]
In JavaScript you can run a query for the document by its ID with `db.collection('books').where(firebase.firestore.FieldPath.documentId(), '==', 'fK3ddutEpD2qQqRMXNW5')`. Some other client libraries also seem to have this option. But it's missing from the Python library.

On Python you can accomplish the equivalent by querying on `__name__`, which happens to be the document ID's field name in the backend. But since we went through the trouble of hiding this implementation detail in other client libraries, we should to this in the Python SDK too.

Context: https://stackoverflow.com/q/56676006

**Comment by HemangChothani** [comment]
@tseaver , firebase.firestore.FieldPath.documentId() has to return '__name__' and it sent to the api as a field_path = "__name__", The same thing works with the order_by  but not with WHERE clause, I think it need a support from back-end also.
