### ISSUE TITLE
Bigtable: Separate row types to remove confusion around return types of row.commit

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#8451]
While @billyjacobson was working on https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2201 he noticed that the version of `commit` for `row.commit` only returned `None`. This got me digging into how this is authored. and if a change would be warranted.

### TL;DR
We have 3 different row types that are returned from `table.row` and they all have disparate returns types for commit. This is a bit confusing and I am curious if we can't converge these a bit. At minimum it seems maybe DirectRow should return something (rows modified count, the actual rows, True on success?).

### Details
Today, users author code like
```
table = instance.table(table_id)
row = table.row(row_key)
```
In the above case it will return a `DirectRow`. There are also `ConditionalRow` and `AppendRow` which will be returned if additional optional args are specified to a `table.row` call.

```
# default -> DirectRow
# filter set -> ConditionalRow
# append set -> AppendRow
class Table:
def row(self, row_key, filter_=None, append=False):
```

Each of these calls has different behaviors. 

- DirectRow: No return type today.

- ConditionalRow: Returns if the filter provided to `table.row` matched

- AppendRow: returns the new content of the modified cells as a dict.

Was this a conscious choice made to not return anything for `DirectRow.commit`? Do we want to make a change here to have it return a response?

Update: plan is to separate, not converge types.

**Comment by tswast** [comment]
DirectRow: I'd expect the row content to be returned on success, as seems to be the case for the other row types.

**Comment by sduskis** [comment]
See the proto: https://github.com/googleapis/googleapis/blob/master/google/bigtable/v2/bigtable.proto

- `DirectRow` used for `MutateRow` operations.  The operation effectively returns `Empty`
- `ConditionalRow` used for `CheckAndMutateRow`.  The operation returns a boolean `predicate_matched`
- `AppendRow` used for `ReadModifyWriteRow` with an `Append` type (instead of an `Increment` type).   The operation returns a `Row` proto (A Row containing the new contents of all cells modified by the request).

I believe that @tseaver developed the original set of Row objects.

**Comment by sduskis** [comment]
@crwilcox, @tswast: I suggest closing this issue.  Things are the way they are for a reason.  I don't believe that convergence in the Python API is desirable, since the Python API ought to match the service API.

**Comment by crwilcox** [comment]
Reopening this for a bit more disucssion. I understand that the API is that way. That doesn't make it easy for our customers to use. If we wanted to mirror the API exactly, we could generate this client :)

Today, calls to `table.row(..).commit()` can return None, a dict, a row. This makes using this surface a bit odd. The args to row do determine the return type, but this is very hard for language intelligence systems, and almost certainly won't work well with typing later. It is also likely hard to discover as a customer. The current return type of `table.row` is 
```
  :rtype: :class:`~google.cloud.bigtable.row.Row`
        :returns: A row owned by this table.
        :raises: :class:`ValueError <exceptions.ValueError>` if both
                 ``filter_`` and ``append`` are used
```
One solution might be describing how your return type changes based on args? 

There are also disagreements with exceptions. I see two of the commit types will  raise`ValueError <exceptions.ValueError>` and the other (`MutateRows`) specifies it will raise `~.table.TooManyMutationsError`

The seems hard to wield as a customer for me. based on the args to `table.row` the return and exception behavior changes?

**Comment by crwilcox** [comment]
A possible option to address this is also to remove the 'row' abstraction. This is the reason for the divergence in return types based on params. These different methods also have different performance characteristics. 

A possible option forward is to deprecate the existing rows method, and surface the 3 methods it is masking.

**Comment by sduskis** [comment]
+1 on 3 methods.

**Comment by mf2199** [comment]
@crwilcox The #8662 implementing the 3 methods has been merged. Would it make sense to revise the issue, possibly closing it now?

**Comment by tseaver** [comment]
Via #8662.
