### ISSUE TITLE
Spanner: Adjust timeouts for CreateDatabase and retries for other methods

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#8463]
As part of a recent change to GAPIC Configuration, timeouts and retries need to be updated. 

Ensure that the timeouts and retires specified in https://github.com/googleapis/googleapis/commit/cc233544aa39b8947c9b929819aeb08e2cb71feb#diff-4501db3e3507bcce8496c9aea2017d96 are reflected in this client library.

**Comment by tseaver** [comment]
Closed in #8445.
