### ISSUE TITLE
Spanner: no metadata or fields?

### ISSUE THREAD

**Issue by mxlei01** [googleapis/google-cloud-python#8540]
#### Environment details

1. Spanner
2. Ubuntu 18
3. Python 3.6.7
4. google-cloud-spanner==1.9.0

#### Steps to reproduce

  1. In a transaction, execute_sql
  2. Metadata is None, and calling the fields attributes raises an exception.

#### Code example

```python
# example
a = client.execute_sql(
    query,
    params=params,
    param_types=param_types
)
print(a.fields)
```

#### Stack trace
```
  File "<ipython-input-6-40ebb241ce0a>", line 182, in query_data
    print(a.fields)
  File "/home/ubuntu/python3_virtualenv/python3_env/lib/python3.6/site-packages/google/cloud/spanner_v1/streamed.py", line 59, in fields
    return self._metadata.row_type.fields
AttributeError: 'NoneType' object has no attribute 'row_type'
# example
```

I'm trying to get column names from the result, however the metadata attribute is None and the fields attribute raises an exception complaining that the metadata attribute is None.

**Comment by tseaver** [comment]
@mxlei01 Can you provide a clue as to how you are constructing the `client` object?  The one we would expect you to use (`google.cloud.spanner_v1.client.Client`) doesn't have an `execute_sql` method.  Instead, we would normally expect you to be using an instance of `google.cloud.spanner_v1.database.Database`, obtained from an instance. E.g.:

```python
from google.cloud.spanner_v1.client import Client

client = Client()
instance = client.instance('<your-instance-id>')
database = instance.database('<your-database-name>')
streamed_results = database.execute_sql(
    query,
    params=params,
    param_types=param_types
)
```

The `google.cloud.spanner_v1.streamed.StreamedResultSet` *does* have `metadata` and `fields` parameters, but they won't be set until after the first partial result set is fetched (i.e, the caller has to start iterating the stream).

**Comment by mxlei01** [comment]
Figured it out, the problem is that the query is executed but it needs to extract the data first by using the iterator first.
