### ISSUE TITLE
Language: Ability to detect language code (BCP-47 identifier)

### ISSUE THREAD

**Issue by ParkerShamblin** [googleapis/google-cloud-python#8541]
Hello, I'm trying to detect different dialects of spanish right now, however, I noticed whenever I use the google cloud language detect script located [here](https://cloud.google.com/translate/docs/detecting-language#translate_detect_language-python) that it always just comes back as spanish (es).

I was curious if it would be possible for it to return the different dialects of Spanish like the ones listed [here](https://cloud.google.com/speech-to-text/docs/languages) such as:

Español (Argentina) | es-AR | Spanish (Argentina)
Español (Bolivia) | es-BO | Spanish (Bolivia)
Español (Chile) | es-CL | Spanish (Chile)
Español (Colombia) | es-CO | Spanish (Colombia)
Español (Costa Rica) | es-CR | Spanish (Costa Rica)
Español (Ecuador) | es-EC | Spanish (Ecuador)
Español (El Salvador) | es-SV | Spanish (El Salvador)

**Comment by tseaver** [comment]
@ParkerShamblin The [list of language codes used by the Cloud Natural Language API](https://cloud.google.com/natural-language/docs/languages) does not include any of those variants.

@beccasaurus AFAIK, the detected language (in an [`AnnotateTextResponse`](https://cloud.google.com/natural-language/docs/reference/rpc/google.cloud.language.v1#google.cloud.language.v1.AnnotateTextResponse.language)) will be an entry from that list in the documentation.  Please reopen / follow up if I am wrong.
