### ISSUE TITLE
Storage: Add sensible connect (and maybe read) timeouts to avoid hanging

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#8571]
After some spelunking, started from reports like https://github.com/googleapis/google-cloud-python/issues/5909 where users have reported hanging on requests, I have uncovered that we don't have read or connect timeouts for our default requests session on storage.

I think adding a connect timeout is warranted for sure, and possible having a read timeout, makes sense? `urllib3` via `request.session` is what is controlling that which by default doesn't specify anything. https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#module-urllib3.util.timeout

I propose a connection timeout of 1 minute. I am less sure of read timeout as that would vary a bit between crud and streaming operations.

cc: @frankyn

**Comment by tseaver** [comment]
Upload / download retries should tie into the [`RetryStrategy` from `google-resumable-media`](https://github.com/googleapis/google-resumable-media-python/blob/34a36be0c53b7517bd3ddc2c281bdaaa5b9c4ef7/google/resumable_media/common.py#L94-L147).

**Comment by tswast** [comment]
Retry support tracked in https://github.com/googleapis/google-cloud-python/issues/7907

There's an open PR at https://github.com/googleapis/google-cloud-python/pull/8177, but not complete.

**Comment by tswast** [comment]
Per Tres's comment, BigQuery uses RetryStrategy here:

https://github.com/googleapis/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/client.py#L1603-L1606

**Comment by crwilcox** [comment]
@tswast to some extent this isn't about exposing retries. Currently, there are no timeouts for connecting. This is problematic and can cause clients to hang. Is this handled special in retry strategy? The way the storage client is configured, we are using the defaults from `urllib3` which has infinite timeout for both connect and read.

**Comment by tswast** [comment]
At least in GAPIC, the retry config sets a timeout as part of the request, though I'm not seeing it in the linked RetryStrategy class.

In BigQuery, we do have a separate timeout parameter for some operations. We should probably be more consistent about these.

https://github.com/googleapis/google-cloud-python/blob/d72161de6da2f9e545e7aac16e084ab2365ecf25/bigquery/google/cloud/bigquery/client.py#L1052-L1054

**Comment by tseaver** [comment]
Notes to future self:  [docs for `requests` timeout handling](https://3.python-requests.org/user/advanced/#timeouts).

**Comment by crwilcox** [comment]
Closing as I believe the PR in August resolved this.
