### ISSUE TITLE
ReadTheDocs /latest not redirecting to current documentation

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#8608]
Following various links when looking up the documentation for the Python Client for Stackdriver Monitoring API (for example), which points to https://google-cloud-python.readthedocs.io/en/latest/monitoring/

Renders an odd unstyled 404 page as does
https://google-cloud-python.readthedocs.io/en/latest/

Clicking through to the last "stable" link does work. As part of the redirector it seems some of the pages aren't properly populated.

**Comment by busunkim96** [comment]
This has been resolved. 

https://google-cloud-python.readthedocs.io/en/latest/monitoring/ redirects to https://googleapis.dev/python/monitoring/latest/index.html
