### ISSUE TITLE
Firestore: collection_group query with start_after passing a snapshot

### ISSUE THREAD

**Issue by deeppotato** [googleapis/google-cloud-python#8633]
Problem: start_after() does not work for collection group queries when passing a document snapshot.

#### Environment details

python 3.7
google-cloud-firestore version 1.2

#### Steps to reproduce

  1. Setup a Google Cloud project with Firestore in Native Mode.

#### Code example

```
parent_ref = db.collection('parents').document('parent')
parent_ref.set({})

child_data = {'name': 'Tom'}
child_ref = parent_ref.collection('children').document('child')
child_ref.set(child_data)

# works
db.collection_group('children').where('name', '==', 'Tom').stream()

# works
db.collection_group('children').where('name', '==', 'Tom').start_after(child_data).stream()

# does not work
child_snapshot = child_ref.get()
db.collection_group('children').where('name', '==', 'Tom').end_before(child_snapshot).stream()
```

#### Stack trace
```
Traceback (most recent call last):
  File "C:/Users/tombr/Documents/GitHub/trader-python/scripts/gcloud/firestore/test.py", line 22, in <module>
    db.collection_group('children').where('name', '==', 'Tom').end_before(child_snapshot).stream()
  File "C:\Users\tombr\Documents\GitHub\trader-python\venv\lib\site-packages\google\cloud\firestore_v1\query.py", line 529, in end_before
    return self._cursor_helper(document_fields, before=True, start=False)
  File "C:\Users\tombr\Documents\GitHub\trader-python\venv\lib\site-packages\google\cloud\firestore_v1\query.py", line 420, in _cursor_helper
    "Cannot use snapshot from another collection as a cursor."
ValueError: Cannot use snapshot from another collection as a cursor.
```

**Comment by tseaver** [comment]
@BenWhitehead Should `start_after` work in this case?

**Comment by BenWhitehead** [comment]
After a bit of testing, in the java client both `start_after` and `end_before` appear to be handled by the backend just fine with a port of this particular example. I'll check with someone from firestore to ensure that it is supposed to work.

**Comment by tseaver** [comment]
@BenWhitehead Maybe we need to add a conformance test that asserts it is OK.

**Comment by BenWhitehead** [comment]
I got confirmation that the python client should not be erroring in this scenario. Collection group queries are designed to span collections and thus shouldn't restrict the DocumentSnapshot based on what collection it comes from.

I've added an internal bug to create a new conformance-test for this scenario [b/138785241](http://b/138785241)

@tseaver Can you relax the client validation so that this can work?
