### ISSUE TITLE
(gsutil) 'Timing-Allow-Origin' header is not supported for setmeta.

### ISSUE THREAD

**Issue by nojvek** [googleapis/google-cloud-python#8648]
#### Steps to reproduce

  1. `gsutil setmeta -h "Timing-Allow-Origin: *" gs://bucket/somepath/somefile`

#### Expected

The header is set on object and gcs serves that header out.

### Actual
```
CommandException: Invalid or disallowed header (Timing-Allow-Origin).
Only these fields (plus x-goog-meta-* fields) can be set or unset:
['cache-control', 'content-disposition', 'content-encoding', 'content-language', 'content-type']
```

I can set the header manually in console.cloud.google.com but GCS still doesn't serve the header.

The chromium folks recommend that header is needed for native browser performance api to work properly.

I'd expect that the cloud part of google would nicely with recommendations of the browser part of google.

See: https://bugs.chromium.org/p/chromium/issues/detail?id=834083#c13

**Comment by tseaver** [comment]
@nojvek I'm afraid this repository is not the right location for reporting issues with `gsutil`.  Please use one of the [Storage support resources](https://cloud.google.com/storage/docs/getting-support), or perhaps the "Send Feedback" link at the top right of the [`gsutil sendmeta` reference docs page](https://cloud.google.com/storage/docs/gsutil/commands/setmeta).

**Comment by nojvek** [comment]
No worries: I filed  a bug in Cloud Storage's issue tracker: https://issuetracker.google.com/issues/137673895
