### ISSUE TITLE
BigQuery: Verify/implement list options for dataset and job collections

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-python#8685]
- Verify that "minCreationTime" and "maxCreationTime" filters are available for users of [jobs.list](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/list).

- Verify that label filtering (the "filter" param) is available for users of [datasets.list](https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets/list)

- If there are any tests or samples that blindly iterate across the jobs collection, we should add at least a reasonable `minCreationTime` filter to reduce test times and demonstrate how to limit results to an expected time window.

An example of the implementations in Java: https://github.com/googleapis/google-cloud-java/pull/5717

cc @tswast

**Comment by plamut** [comment]
> Verify that "minCreationTime" and "maxCreationTime" filters are available for users of jobs.list.

Confirmed, they are available - [source](https://github.com/googleapis/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/client.py#L1204-L1205).

> Verify that label filtering (the "filter" param) is available for users of datasets.list

Confirmed, the `filter` param is available - [source](https://github.com/googleapis/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/client.py#L247).

> If there are any tests or samples that blindly iterate across the jobs collection, we should add at least a reasonable minCreationTime filter to reduce test times and demonstrate how to limit results to an expected time window.

There seems to be no such problematic snippets or system tests.

The [snippet](https://github.com/googleapis/google-cloud-python/blob/master/bigquery/docs/snippets.py#L2692-L2725) for listing jobs uses a reasonable filter in all cases, and there seems to be no test in [system.py](https://github.com/googleapis/google-cloud-python/tree/master/bigquery/tests/system.py) that tries listing the jobs.

**Comment by shollyman** [comment]
Thanks for confirming.  I max_results appears to do the right thing, in that it bounds the result size rather than informing the max results per page.  Closing.
