### ISSUE TITLE
Data Catalog: Enable samplegen in synth.py.

### ISSUE THREAD

**Issue by tswast** [googleapis/google-cloud-python#8702]
We just merged a YAML for generated code samples for Data Catalog (internal change 258638993, originally https://github.com/ricardosm-cit/googleapis/pull/1). To generate Python samples, we'll need to add `generator_args=["--dev_samples"],` to `synth.py`. See: https://github.com/ricardosm-cit/google-cloud-python/pull/1/files#diff-f0f28abdbe15bf803a73d25699042c14

@ricardosm-cit Is this something you'd be willing to do? It'd be similar to your google-cloud-python PR, just based on the `master` branch of googleapis/googleapis once the internal change makes its way public.

**Comment by ricardosm-cit** [comment]
Sure, @tswast. Count on me!

**Comment by tseaver** [comment]
Via #8708.
