### ISSUE TITLE
BigQuery: The sample to create a BigQuery table is not working

### ISSUE THREAD

**Issue by happyhuman** [googleapis/google-cloud-python#8703]
1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
This sample to be exact: https://github.com/googleapis/google-cloud-python/blob/7ba0220ff9d0d68241baa863b3152c34dc9f7a1a/bigquery/samples/create_table.py

2. OS type and version 
MacOS Mojave

3. Python version and virtual environment information: `python --version`
Both 2.7.10 and 3.7

4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`
google-cloud-bigquery==1.9.0

#### Steps to reproduce
  1. set GOOGLE_APPLICATION_CREDENTIALS to my service account key
  2. Make sure "gcloud config list" items are correct.
  3. In the sample code, set table_id to: "{}.datalabeling.cont_eval".format(PROJECT_ID)
  4. Run the sample.

#### Code example

```
def create_big_query_table():
    schema = [
        bigquery.SchemaField("model", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("model_version", "INTEGER", mode="REQUIRED"),
    ]

    client = bigquery.Client()
    PROJECT_ID = 'my-gcp-project-id'
    table_id = "{}.datalabeling.cont_eval".format(PROJECT_ID)
    table = bigquery.Table(table_id, schema=schema)
    table = client.create_table(table)  # API request
    print(table)
```

#### Stack trace
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shahins/.virtualenvs/dl2/lib/python2.7/site-packages/google/cloud/bigquery/table.py", line 370, in __init__
    self._properties = {"tableReference": table_ref.to_api_repr(), "labels": {}}
AttributeError: 'str' object has no attribute 'to_api_repr'
```

(the line that throws this exception is bigquery.Table(.....))

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by ryanyuan** [comment]
I believe this has been fixed since 1.10.0 by having a string check in Table.__init__().

**Comment by tseaver** [comment]
@ryanyuan is correct:  the `Table` constructor has accepted strings formatted in that form since PR #7483 was merged, included in the [`google-cloud-bigquery 1.10.0` release](https://github.com/googleapis/google-cloud-python/releases/tag/bigquery-1.10.0)

**Comment by philippabaliman** [comment]
Still having the same issue on v1.26.1

**Comment by ryanyuan** [comment]
@philippabaliman No issue for me with google-cloud-bigquery==1.26.1. Can you post your stacktrace here?

**Comment by ikendoit** [comment]
check if when you assign a variables like table name, it is an actual string type.
I had this error too, because I had this line:
```
    table_full_path = "{}.{}".format(dataset_id, table_name),
```
notice the accidental comma at the end. That would make the variable to be tuple type instead of string.
