### ISSUE TITLE
Storage: Add support for emulators.

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-python#8728]
Add a way to connect to an emulator on host:port without TLS.

**Comment by tseaver** [comment]
See also #4840.

**Comment by crwilcox** [comment]
@jadekler is this still an issue? I seem to recall seeing an emulated endpoint without TLS.

**Comment by jadekler** [comment]
I think we're good now. Thanks!

**Comment by simonvanderveldt** [comment]
@crwilcox @jadekler How is this solved exactly? I don't see anything related to emulators in the [current storage client code](https://github.com/googleapis/google-cloud-python/blob/bda44b3c769142615aef2ddb49f8e0acb3ccd76d/storage/google/cloud/storage/client.py).
