### ISSUE TITLE
No module named 'google.api_core.client_options' while importing firestore

### ISSUE THREAD

**Issue by umer7** [googleapis/google-cloud-python#8781]
I am trying to use Firestore with Python. I have successfully installed the google-cloud-firestore. But when I am trying to import the library using `from google.cloud import firestore `. It is throwing me the error

> No module named 'google.api_core.client_options'

Note: I am not using the virtualenv Is there any way i can resolve this

I am stuck at this for weeks, Thanks in advance.

**Comment by tseaver** [comment]
Please upgrade `google-api-core` in your environment, e.g.:

```bash
$ /path/to/pip install --upgrade google-api-core
```
