### ISSUE TITLE
BigQuery: Use `google.cloud.bigquery_storage` not `google.cloud.bigquery_storage_v1beta1` in `to_dataframe` / `to_arrow`

### ISSUE THREAD

**Issue by tswast** [googleapis/google-cloud-python#8788]
At some point, the BigQuery Storage API is going to go GA. At that point people will want to use the GA endpoint from the BigQuery helpers that use it.

Currently `google.cloud.bigquery_storage` is more-or-less an alias for `google.cloud.bigquery_storage_v1beta1`. We should probably use `google.cloud.bigquery_storage` so that we're on the latest version in as many releases of `google-cloud-bigquery` as possible. I don't anticipate breaking changes for the BigQuery Storage API beta at the moment.

**Comment by tswast** [comment]
On second thought, I just read a doc that there might be some field and method renames. Let's hold off on this one until GA is closer.

**Comment by plamut** [comment]
@tswast Any updates on this, or are we still awaiting information?

**Comment by plamut** [comment]
Bump.

**Comment by tswast** [comment]
There's still talk of renaming some methods in the next beta release. I'm gonna close this issue out. We can reassess when we are ready to prepare for the GA release.
