### ISSUE TITLE
Firestore: Unable to import 'FieldValue.arrayUnion'.

### ISSUE THREAD

**Issue by punit-anvaya** [googleapis/google-cloud-python#8792]
I want to append data in array in Firebase Cloud Firestore. for that i am using `FieldValue.arrayUnion`.

I tired these imports but none of them worked

```
from firebase_admin import firestore
firebase_admin.firestore.FieldValue.arrayUnion()

AttributeError: module 'firebase_admin.firestore' has no attribute 'FieldValue'
```
```
from google.cloud import firestore
firestore.FieldValue.arrayUnion()

AttributeError: module 'firestore' has no attribute 'FieldValue
```
```
from google.cloud import firestore_v1 as firestore
firestore.FieldValue.arrayUnion()

AttributeError: module 'google.cloud.firestore_v1' has no attribute 'FieldValue'
```

Wants to know from where I have to import FieldValue

**Comment by tseaver** [comment]
```python
>>> from google.cloud import firestore
>>> firestore.ArrayUnion([1, 2, 3])
<google.cloud.firestore_v1.transforms.ArrayUnion object at 0x7f9ae01af510>
```

**Comment by punit-anvaya** [comment]
This i know, but am using that to store array of maps.

**Comment by tseaver** [comment]
@punit-anvaya I'm not sure what your last comment means:  you reported above that you couldn't figure out how to import `ArrayUnion`, and my example shows that.

**Comment by jlara310** [comment]
I'm also seeing similar behavior in that I can't use `ArrayUnion` or `ArrayRemove` unless I explicitly import them from `google.cloud.firestore_v1`.

Example 1:

`from google.cloud import firestore

# Use the application default credentials
db = firestore.Client('projectid')

city_ref = db.collection(u'cities').document(u'DC')

# Atomically add a new region to the 'regions' array field.
city_ref.set({u'regions': ArrayUnion([u'greater_virginia'])})

# // Atomically remove a region from the 'regions' array field.
city_ref.set({u'regions': ArrayRemove([u'east_coast'])})`

Leads to:

`Traceback (most recent call last):
...
    city_ref.set({u'regions': ArrayUnion([u'greater_virginia'])})
NameError: name 'ArrayUnion' is not defined`

Example 2, works:

`from google.cloud import firestore
from google.cloud.firestore_v1 import ArrayRemove, ArrayUnion

# Use the application default credentials
db = firestore.Client('projectid')

city_ref = db.collection(u'cities').document(u'DC')

# Atomically add a new region to the 'regions' array field.
city_ref.set({u'regions': ArrayUnion([u'greater_virginia'])})

# // Atomically remove a region from the 'regions' array field.
city_ref.set({u'regions': ArrayRemove([u'east_coast'])})`

Library version:

```
Name: google-cloud-firestore
Version: 1.3.0
```

**Comment by tseaver** [comment]
@jlara310 I cannot reproduce your report in a fresh virtual enviornment:

```bash
$ python3.5 -m venv /tmp/gcp/8792
$ /tmp/gcp/8792/bin/pip install --upgrade setuptools pip wheel
...
Successfully installed pip-19.2.1 setuptools-41.0.1 wheel-0.33.4
$ /tmp/gcp/8792/bin/pip install google-cloud-firestore==1.3.0
...
Successfully installed cachetools-3.1.1 certifi-2019.6.16 chardet-3.0.4 google-api-core-1.14.0 google-auth-1.6.3 google-cloud-core-1.0.2 google-cloud-firestore-1.3.0 googleapis-common-protos-1.6.0 grpcio-1.22.0 idna-2.8 protobuf-3.9.0 pyasn1-0.4.5 pyasn1-modules-0.2.5 pytz-2019.1 requests-2.22.0 rsa-4.0 six-1.12.0 urllib3-1.25.3
$ /tmp/gcp/8792/bin/pip list
Package                  Version  
------------------------ ---------
cachetools               3.1.1    
certifi                  2019.6.16
chardet                  3.0.4    
google-api-core          1.14.0   
google-auth              1.6.3    
google-cloud-core        1.0.2    
google-cloud-firestore   1.3.0    
googleapis-common-protos 1.6.0    
grpcio                   1.22.0   
idna                     2.8      
pip                      19.2.1   
protobuf                 3.9.0    
pyasn1                   0.4.5    
pyasn1-modules           0.2.5    
pytz                     2019.1   
requests                 2.22.0   
rsa                      4.0      
setuptools               41.0.1   
six                      1.12.0   
urllib3                  1.25.3   
wheel                    0.33.4  
$ /tmp/gcp/8792/bin/python -c "from google.cloud.firestore import ArrayUnion; print(ArrayUnion.__qualname__)"
ArrayUnion
```

**Comment by jlara310** [comment]
Thanks for looking into this. I still think there's something funky going on. Your example worked in my environment, too, but the following did not:

```
>>> from google.cloud import firestore
>>> db = firestore.Client('projectid')
>>> db.collection(u'cities').document(u'DC').set({u'regions': ArrayUnion([u'greater_virginia'])})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ArrayUnion' is not defined
>>>
```

Is it expected behavior that I need to import ArrayUnion on top of importing firestore?

```
>>> from google.cloud import firestore
>>> from google.cloud.firestore import ArrayUnion
>>> db = firestore.Client('myproject')
>>> db.collection(u'cities').document(u'DC').set({u'regions': ArrayUnion([u'greater_virginia'])})
update_time {
  seconds: 1564174589
  nanos: 5711000
}
```

**Comment by tseaver** [comment]
@jlara310 
> Is it intended behavior that I need to import ArrayUnion on top of importing firestore?

No, but if you don't import it explicitly, you need to access it as an attribute of `firestore` (Python imports are explicit, not implicit).  E.g.:

```python
>>> from google.cloud import firestore
>>> db = firestore.Client('projectid')
>>> db.collection(u'cities').document(u'DC').set({u'regions': firestore.ArrayUnion([u'greater_virginia'])})
```

**Comment by jlara310** [comment]
Thanks for clarifying. Opened a bug to clarify this in the docs, too.

https://cloud.google.com/firestore/docs/manage-data/add-data#update_elements_in_an_array
