### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'sort'

### ISSUE THREAD

**Issue by JoshSullivan11** [googleapis/google-cloud-python#8857]
Hi, I am running a script that uses google-cloud protobuf and I am receiving the following error. I have seen similar issues that relate to bad pip installs, but that does not seem to be the case here. I am coming here as a last resort before reimaging my computer, so any help is appreciated.

#### Environment details

1.Ubuntu 16.04.1 LTS
2.Python 3.5.2 
3. google-cloud-cloud version:  0.34.0

#### Stack trace
```
    import google.protobuf.text_format as proto
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

**Comment by tseaver** [comment]
@JoshSullivan11 What Google Cloud API(s) are you trying to use?  The old `google-cloud` umbrella package is deprecated, and no longer brings in any of the libraries.  For instance, to use [Cloud Storage](https://cloud.google.com/storage/):

```bash
$ python3.5 -m venv /path/to/venv
$ /path/to/venv/bin/pip install --upgrade setuptools pip
$ /path/to/venv/bin/pip install google-cloud-storage
```

Note that this example creates a separate virtual environment into which to install `google-cloud-storage`, which helps insulate your application from potential conflicts in the "system python".

**Comment by JoshSullivan11** [comment]
I don't believe I am trying to use any APIs at all with this script. This is simply just a quick test script we are supposed to run to ensure our environment is setup correctly and its failing. I've tried running this is a different environment which does not have any knowledge of the google-cloud and it runs just fine, but I am not able to do that in the long run due to procedures i must follow.

**Comment by tseaver** [comment]
Indeed, the traceback doesn't show any signs that any of the `google-cloud` libraries are in play.  Is there a way you can list the packages installed in the failing environment, e.g. via:

```bash
$ /usr/bin/python3 -m pip list
```

One of them installs something into the top-level `google` package without making it a namespace package, or else the installer is broken (really old `pip` / `setuptools`).

Given that this is not really a bug in any of the libraries maintained in this repository, I'm going to close the issue.  Please feel free to follow up as you find more informatoin.

**Comment by JoshSullivan11** [comment]
[piplist.txt](https://github.com/googleapis/google-cloud-python/files/3454103/piplist.txt)
This is the pip list, which hasn't changed since before this started failing.  So i have no idea which ones could possibly be doing that.
