### ISSUE TITLE
Add more messaging about 2.7 deprecation

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-cloud-python#8885]
Currently we mention 2.7 deprecation in the body of the README.rst files for APIs. There may be more actions we can take to signal to users that we will not be supporting Python 2 post Jan 1, 2020.

- [x] Make deprecation warning more prominent in README and library reference documentation. #9036 
- [ ] Add deprecation warning to top-level repo README.
- [ ] Raise warnings when Python < 3.5 is detected at install time, run time, or both.

See  https://python3statement.org/practicalities/ for more ideas.

**Comment by parthea** [comment]
I'm going to close this issue as we've dropped python 2 support in the default branch in most googleapis python repos but please feel free to re-open it.
