### ISSUE TITLE
BigQuery: deprecate `client.dataset()`

### ISSUE THREAD

**Issue by tswast** [googleapis/google-cloud-python#8989]
See: https://github.com/googleapis/google-cloud-python/pull/7753

We should recommend the simpler "use a string instead of a reference object" in most cases.

We still call `.dataset()` 96 times in our samples at `docs/snippets.py`. I would feel better about adding the deprecation notice after we update the rest of our samples.

**Comment by tswast** [comment]
As part of these sample updates, I'd also like to move the snippets to their own sample files in the `samples/` directory. See: https://github.com/googleapis/google-cloud-python/pull/7683 for examples.

**Comment by IlyaFaer** [comment]
@tswast, taken to work
