### ISSUE TITLE
PubSub: Release the first GA version

### ISSUE THREAD

**Issue by plamut** [googleapis/google-cloud-python#8990]
If no major issues are discovered during the ongoing bake-in period, the PubSub client should be released as GA.

Releasing a new version is done with the help of [releasetool](https://github.com/googleapis/releasetool). Prior to the GA release, the following must be done:

- Go through the checklist from the internal GA release doc, make sure everything is in order.
- Changes in the client lib files:
    - Update PubSub Python lib README to indicate semver just like Java library has
    - Update beta tag in PubSub Python lib README
    - Update beta tag in Python libs root
    - Set the release level to `ga` in `.repo-metadata.json`
    - Change beta label in code samples in clients page in Google Cloud website
    - Add to release notes (talk to @kir-titievsky)
    - Update any documentation on Cloudsite

**Comment by plamut** [comment]
@busunkim96 Is the list of all required file changes complete an accurate?

Please proof-read it, thanks!

**Comment by busunkim96** [comment]
@plamut Looks good to me!
