### ISSUE TITLE
Translate: ASCII output of results under 'v3beta1'.

### ISSUE THREAD

**Issue by MayuraVerma** [googleapis/google-cloud-python#9005]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

I am using translate_v3beta1 in python3.

I am running example problem in https://cloud.google.com/translate/docs/quickstart-client-libraries-v3

text = u'Book'

response = client.translate_text(
    parent=parent,
    contents=[text],
    mime_type='text/html',  # mime types: text/plain, text/html
    source_language_code='en',
    target_language_code='kn')

for translation in response.translations:
    print('Translated Text: {}'.format(translation))

Output in the terminal is in ASCII:

Translated Text: translated_text: "\340\262\252\340\263\201\340\262\270\340\263\215\340\262\244\340\262\225"

BUT the same translation in V2 is outputting in UTF-8 correctly.
translation = translate_client.translate(
    text,
    source_language='en',
    target_language='kn')

print(u'Text: {}'.format(text))
print(u'Translation: {}'.format(translation['translatedText']))

Output in the terminal is in unicode:
Text: Book
Translation: ಪುಸ್ತಕ

**Comment by tseaver** [comment]
@MayuraVerma Thanks for the report.  The `v3beta1` clients `translate_text` method returns a protobuf message of type [`TranslationTextResponse`](https://cloud.google.com/translate/docs/reference/rpc/google.cloud.translation.v3beta1#google.cloud.translation.v3beta1.Translation).  Rather than formatting it directly, use its `translation_text` field, e.g.:

```python
    for translation in response.translations:
        print('Translated Text: {}'.format(translation.translated_text))
```
