### ISSUE TITLE
Firestore: watch.unsubscribe() causes Google Cloud Function to timeout.

### ISSUE THREAD

**Issue by Kharms** [googleapis/google-cloud-python#9008]
#### Environment details

Environment: GCF python37 runtime
Version: google-cloud-firestore==1.4.0 

#### Steps to reproduce

1. Initialize a fs document:
2. Deploy a HTTP triggered GCF that creates a listener, then unsubscribes. 
3. View logs.

#### Code example

```python
from google.cloud import firestore


# Initialization code, run prior to deploy.
# fs_client = firestore.Client()
# doc_ref = fs_client.collection("test").document("subtest")
# doc_ref.set({"hello": "world"})


def abort_now_listener(doc_snapshot, changes, read_time):
    for doc in doc_snapshot:
        doc_vals = doc.to_dict()
        print(doc_vals["hello"])


# gcloud functions deploy watch_fs --runtime python37 --trigger-http
def watch_fs(request):
    print("creating client")
    fs_client = firestore.Client()
    doc_ref = fs_client.collection("test").document("subtest")
    print(doc_ref)
    watcher = doc_ref.on_snapshot(abort_now_listener)
    print("after watcher")
    watcher.unsubscribe()
    print("the end!")
    return "hello world"


```
GCF Logs attached. 

<img width="1353" alt="Screen Shot 2019-08-12 at 11 06 14 AM" src="https://user-images.githubusercontent.com/7454464/62875559-3abb3b80-bcf1-11e9-8d7a-6c01aa9fccc8.png">

**Comment by Kharms** [comment]
Might be related to the fix for https://github.com/googleapis/google-cloud-python/issues/7826

**Comment by Kharms** [comment]
Might be caused by this: https://github.com/googleapis/google-cloud-python/issues/9008

**Comment by tseaver** [comment]
@Kharms Thanks for the report, and for investigating rolling back.  As a workaround, I would recommend just avoiding the `unsubscribe` call

**Comment by jlara310** [comment]
Issue not dependent of Cloud Function environment, see https://stackoverflow.com/questions/58224392/detaching-firestore-listener-in-python-causes-program-to-freeze

**Comment by tseaver** [comment]
Via #9337.
