### ISSUE TITLE
Translation: how to get the source text in the V3 API?

### ISSUE THREAD

**Issue by MayuraVerma** [googleapis/google-cloud-python#9009]
How to get text in the source text with auto-detected language in python v3 as shown in the web.

I know the translated text and source text is same in this case. But not always. I want to capture the text in the source suggestion.

![image](https://user-images.githubusercontent.com/14062593/62895282-2a688800-bd14-11e9-92bd-2c23d51e89d2.png)

**Comment by tseaver** [comment]
The [Translation](https://cloud.google.com/translate/docs/reference/rpc/google.cloud.translation.v3beta1#google.cloud.translation.v3beta1.Translation) message does not contain that field.  You should be able to map it from the request, e.g. using your example from earlier today:

```python
def extract_translations(
        client,
        parent,
        target_language_code,
        *source_texts,
        mime_type='text/html',
        source_langage_code='en'):

    response = client.translate_text(
        parent=parent,
        contents=source_texts,
        mime_type=mime_type,
        source_language_code=source_language_code,
        target_language_code=target_language_code)

        assert len(texts) == len(response.translations)
        for source_text, translation in zip(texts, response.translations):
            print('Source Text: {}'.format(source_text))
            print('Translated Text: {}'.format(translation.translation_text))
```
