### ISSUE TITLE
Translate from same language

### ISSUE THREAD

**Issue by MayuraVerma** [googleapis/google-cloud-python#9019]
It is possible to translate the text from same language, target and destination = same language in the web.

But in Python, it throws an error.

If I download the code, will I be able to turn off the restriction.

Please assist.

**Comment by tseaver** [comment]
Can you show a sample of the Python code, and the full traceback?

**Comment by MayuraVerma** [comment]
1. Python Code: with source language =  (blank) 'auto detect'
project_id = <removed>
text = 'Maduve Maadikondu'
location = 'global'

#v3
parent = client.location_path(project_id, location)

response = client.translate_text(
    parent=parent,
    contents=[text],
    mime_type='text/html',  # mime types: text/plain, text/html
#    source_language_code='en',
    target_language_code='kn')
for translation in response.translations:
    print('Translated Text: {}'.format(translation.translated_text))

Output--> Translated Text: Maduve Maadikondu


2. Python Code: 
    source_language_code='kn',

Output-->     Failed
six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 Target language can't be equal to source language.

3. 2. Python Code: 
    source_language_code='en',
Output-->     Translated Text: ಮಧುವೆ ಮಡಿಕಂಡು
This is wrong translation.

4. From WEB
Text: Maduve Maadikondu

Expected Result: 
This is from the web.
It works both for Source language: 'Detect Language' or Kannada (kn)
![image](https://user-images.githubusercontent.com/14062593/62909028-7d583480-bd40-11e9-9b89-b169bd895e63.png)

![image](https://user-images.githubusercontent.com/14062593/62909259-7aaa0f00-bd41-11e9-851d-f3e5c5048882.png)

**Comment by tseaver** [comment]
@beccasaurus Can you help diagnose why the `translate` API returns a 400 for source language == target language, whereas the Web UI allows it?

**Comment by busunkim96** [comment]
@MayuraVerma translate.google.com has some more features that aren't available via the API. If this is of interest, you can file an issue on the Translation team's public [tracker](https://b.corp.google.com/savedsearches/559749)
