### ISSUE TITLE
Storage: How to get all versions of an object?

### ISSUE THREAD

**Issue by ijharulislam** [googleapis/google-cloud-python#9031]
I have to get all versions of a single object with a single request. Is there any way to do it? Similar old issue found here.
https://stackoverflow.com/questions/18734487/how-to-get-all-versions-of-an-object-in-google-cloud-storage-bucket

**Comment by tseaver** [comment]
You can call `Client.list_objects` (or the older `Bucket.list_objects`) passing `versions=True` and the full name of the object as `prefix`, e.g.:

```python
iterator = client.list_objects(
    '<YOUR BUCKET_NAME',
    prefix='<YOUR OBJECT NAME',
    versions=True,
    )
for obj_w_version in iterator:
   do_something_with(obj_w_version)
```

**Comment by ijharulislam** [comment]
@tseaver 
Thanks. Needed small change. `client.list_blobs()`.
