### ISSUE TITLE
BigQuery: Won't build in AWS lamba No module named 'google.protobuf'

### ISSUE THREAD

**Issue by ahonnecke** [googleapis/google-cloud-python#9061]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-python/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

AWS Lambda 3.6

#### Steps to reproduce

1. Write code that works on amazonlinux:2017.09 in a docker container (or 2018.03)
2. Execute `from google.cloud import bigquery` in a lambda function

#### Code example

```python
from google.cloud import bigquery
```

#### Stack trace
```
Unable to import module 'gbq_handler': No module named 'google.protobuf'
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by ahonnecke** [comment]
This issue does not seem to be present in 3.7.

**Comment by busunkim96** [comment]
@ahonnecke Which version of the BigQuery library are you using?

**Comment by tswast** [comment]
I would recommend trying to install the latest version of `pip` and `setuptools`. This appears to be a problem with namespaced packaging, which is better in later versions of those packages.

**Comment by msdinit** [comment]
Same happens with the latest vanilla versions of pip and setuptools:
```
FROM amazonlinux
WORKDIR /app
RUN yum install python3 -y
RUN python3 -m pip install --upgrade setuptools pip
COPY requirements.txt requirements.txt
RUN pip3 install --target . --upgrade --force-reinstall werkzeug && \
pip3 install --target . --upgrade --force-reinstall requests && \
pip3 install --target . --upgrade --force-reinstall -r requirements.txt && \
ls -lA google
```

**Comment by tswast** [comment]
Try using the `--user` option to install the packages, instead. I'm able to successfully build with the following:

```
FROM amazonlinux
WORKDIR /app
RUN yum install python3 -y
RUN python3 -m pip install --user --upgrade setuptools pip
COPY requirements.txt requirements.txt
RUN python3 -m pip install --user --upgrade --force-reinstall werkzeug && \
python3 -m pip install --user --upgrade --force-reinstall requests && \
python3 -m pip install --user --upgrade --force-reinstall -r requirements.txt && \
python3 -c "import google.cloud.bigquery; print(google.cloud.bigquery.__version__)"
```
