### ISSUE TITLE
Asset: Code examples are incomplete

### ISSUE THREAD

**Issue by rvandegrift** [googleapis/google-cloud-python#9071]
The code examples for cloud asset inventory are currently just marked TODO, without any examples of the expected payloads.  See the "Example" section at [1].  

This looks different from #5448 since it's an example, but feel free to close if I'm wrong.

Ross

[1] - https://googleapis.dev/python/cloudasset/latest/gapic/v1/api.html#google.cloud.asset_v1.AssetServiceClient.export_assets

**Comment by Emar-Kar** [comment]
Hello, sir. `# TODO:` in the **samples** shows and explains which part of the standard code user should change on his own to get the effect. Right now all libraries are constructing similarly. You can take a look for example at [BigQuery](https://googleapis.dev/python/bigquery/latest/usage/tables.html). It is marked as `# TODO(developer):` there. If you need the direct example for each argument, please check the **Parameters:** section. As I can see there are several, `such as ...`, instances and links to additional resources.

**Comment by Emar-Kar** [comment]
@rvandegrift Please feel free to reopen this issue if you are still running into problems in docs or misunderstandings.
