### ISSUE TITLE
BigQuery: Run lint and black on samples/ directory

### ISSUE THREAD

**Issue by tswast** [googleapis/google-cloud-python#9081]
We should make sure our code samples are linted, too.

I think we'll get a few flake8 errors for unused imports. Since we always want to show `from google.cloud import bigquery`, we can make those lines into comments when they are otherwise unnecessary.

Also, I forget if we use the templated files for `noxfile.py`. This update may need to be made at the synthtool templates repo if so.

**Comment by plamut** [comment]
It appears that snippets are already linted. Black already runs on them, while the flake8 check needs to be extended to the `docs/samples` directory:

```patch
diff --git a/bigquery/noxfile.py b/bigquery/noxfile.py
index 37611a5ce29..fc44db1c120 100644
--- a/bigquery/noxfile.py
+++ b/bigquery/noxfile.py
@@ -150,6 +150,7 @@ def lint(session):
     session.install("-e", ".")
     session.run("flake8", os.path.join("google", "cloud", "bigquery"))
     session.run("flake8", "tests")
+    session.run("flake8", os.path.join("docs", "samples"))
     session.run("flake8", os.path.join("docs", "snippets.py"))
     session.run("black", "--check", *BLACK_PATHS)
```

Noxfiles are auto-generated AFAIK, yes, thus the change needs to be made in the synthool repo.

**Comment by tswast** [comment]
FYI: the `noxfile.py` template lives here: https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/noxfile.py.j2
