### ISSUE TITLE
BigQuery: Convert Sphinx-style docstrings to Google style

### ISSUE THREAD

**Issue by plamut** [googleapis/google-cloud-python#9092]
Following the [comment thread](https://github.com/googleapis/google-cloud-python/pull/9067#discussion_r317214709) on another PR, it turned out that `job.py`, and possibly other modules as well, still use the Sphinx-style docstrings.

These docstrings should be converted to Google-style docstrings as the Python [coding style guideline](http://google.github.io/styleguide/pyguide.html#383-functions-and-methods) mandates.

Examples of Google-style docstrings:
https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html#example-google

**Comment by Patil2099** [comment]
@plamut @IlyaFaer  Can I work on this?

**Comment by IlyaFaer** [comment]
@Patil2099, I've already wrote raw script for massive docs updating. [Pushed](https://github.com/q-logic/google-cloud-python/pull/49) internally just a few minutes ago - was gonna show to @tswast and ask about how we should deal with this changes, and maybe there is something to do "by the way"

**Comment by IlyaFaer** [comment]
@Patil2099, I've already wrote raw script for massive docs updating. Pushed internally just a few minutes ago - was gonna show to @tswast and ask about how we should deal with this changes, and maybe there is something to do "by the way"

**Comment by Patil2099** [comment]
@iilyafaer Maybe I can help in that .

**Comment by plamut** [comment]
@IlyaFaer I've already done quite some work on this in BigQuery, but if we are going to use a mass update script, I'll put that aside. Thanks for mentioning the script here!

@Patil2099 I am fine with you working on this, just please coordinate with @IlyaFaer to not unnecessarily repeat any work.

**Comment by IlyaFaer** [comment]
Had a word with @tswast. There are no more old-styled comments in `bigquery/google/cloud` folder. I've also checked `bigquery_datatransfer`, `bigquery_storage` and `datacatalog`, they are Google-styled. So, I assume, we should close the issue

**Comment by plamut** [comment]
@IlyaFaer Indeed, the issue can be closed now. Thanks for the cleanup!
