### ISSUE TITLE
How to get cloud speech api response in python if I only have the operation name?

### ISSUE THREAD

**Issue by helloworldkr** [googleapis/google-cloud-python#9101]
**scenario**:
I am sending a long speech recognition file for speech recognition.
operation = client.long_running_recognize(config, audio)
operation_name = operation._operation.name

**Issue**
There is another file where I have to use operation_name (returned by google speech API) to get back the response again.

I tried get_operation method of the "Long-Running Operations Client":

from google.api_core import operations_v1
api = operations_v1.OperationsClient()
name = ...
response = api.get_operation(name)

ref: [stackoverflow Link](https://stackoverflow.com/questions/53317626/python-way-of-polling-longrunning-operations-from-operation-name-in-google-cloud)

but I get the following error:
----> 1 api = operations_v1.OperationsClient()
TypeError: init() missing 1 required positional argument: 'channel'

**Comment by helloworldkr** [comment]
Got the answer to it on GoogleCloudPlatform/python-docs-samples GitHub repo:

`from google.cloud import speech
client = speech.SpeechClient()

from google.api_core import operations_v1
api = operations_v1.OperationsClient(client.transport.channel)
name = ...
response = api.get_operation(name)`

Thanks to @nnegrey 

[Link](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2361) to the issue discussion

**Comment by bahmanalidadi** [comment]
I have an error in this line when deploy on gcloud function:
api = operations_v1.OperationsClient(client.transport.channel)

It says:
AttributeError: 'SpeechClient' object has no attribute 'transport'

It is very wonderful for me, this script now running in cloud function, but now I'm trying to deploy, it show me this error.

**Comment by Grandolf49** [comment]
> I have an error in this line when deploy on gcloud function:
> api = operations_v1.OperationsClient(client.transport.channel)
> 
> It says:
> AttributeError: 'SpeechClient' object has no attribute 'transport'
> 
> It is very wonderful for me, this script now running in cloud function, but now I'm trying to deploy, it show me this error.

@bahmanalidadi I'm facing the same issue. Were you able to resolve it?
Is it a version issue of the library?

**Comment by Grandolf49** [comment]
> > I have an error in this line when deploy on gcloud function:
> > api = operations_v1.OperationsClient(client.transport.channel)
> > It says:
> > AttributeError: 'SpeechClient' object has no attribute 'transport'
> > It is very wonderful for me, this script now running in cloud function, but now I'm trying to deploy, it show me this error.
> 
> @bahmanalidadi I'm facing the same issue. Were you able to resolve it?
> Is it a version issue of the library?

Turns out, it is indeed a version problem. I was using `google-cloud-speech` version `2.0.1` in which `SpeechClient` object doesn't have `transport` attribute. Downgrading this version to `1.3.2` works perfectly.

In my case, I need to use `speech_v1p1beta1` which is only available in `2.x.x` so downgrading is not an option for me. So I used `google-api-core` version `1.25.1` to get the operation response:

```python
from googleapiclient import discovery
speech_service = discovery.build('speech', 'v1p1beta1')
operation_name = '...'
operation = speech_service.operations().get(name=operation_name).execute()
```

This is equivalent to performing a REST API call and obtaining results as defined [here](https://cloud.google.com/speech-to-text/docs/reference/rest/v1p1beta1/operations/get). Returns a response as defined [here](https://cloud.google.com/speech-to-text/docs/reference/rest/Shared.Types/ListOperationsResponse#Operation)
