### ISSUE TITLE
Datastore: unable to add enteries to from GCP compute instance.

### ISSUE THREAD

**Issue by hemantpandey17** [googleapis/google-cloud-python#9146]
Getting the following error:

ERROR: { Error: Request had insufficient authentication scopes.
   at Http2CallStream.call.on (/home/node_modules/@grpc/grpc-js/build/src/client.js:96:45)
   at Http2CallStream.emit (events.js:187:15)
   at process.nextTick (/home/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
   at process._tickCallback (internal/process/next_tick.js:61:11)
 code: 7,
 details: ‘Request had insufficient authentication scopes.’,
 metadata:
  Metadata {
    options: undefined,
    internalRepr: Map { ‘www-authenticate’ => [Array] } } }

The script is working fine in my local machine.

Anybody familiar with this ?

**Comment by busunkim96** [comment]
It looks like you don't have sufficient permissions. How are you doing authentication?

Did you mean to file this against the [NodeJS client](https://github.com/googleapis/nodejs-datastore)?

**Comment by jhallard** [comment]
Hi OP, I think you need to add permissions to access datastore while creating the Virtual Machine. When you are on the "Create Instance" page, try selecting this option

![image](https://user-images.githubusercontent.com/7551586/64219819-ed5b6580-ce7b-11e9-8fa8-a9473ececf9e.png)

"Enable" the Cloud Datastore permission.

**Comment by tseaver** [comment]
@hemantpandey17 Please follow-up / reopen if @jhallard's suggestion doesn't resolve your issue.
