### ISSUE TITLE
Vision: Operation returned from 'purge_product: raises TypeError in 'done'.

### ISSUE THREAD

**Issue by dizcology** [googleapis/google-cloud-python#9150]
#### Environment details

1. Vision API, Product Search, Purge Product
2. OSX
3. 2.7.14
4. google-cloud-vision 0.39.0

#### Steps to reproduce

  1. Run tests or either of the purge product samples from this PR: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2349
  1. The LRO fails at `operation.done()`

#### Code example

see PR linked above.

#### Stack trace
```
Traceback (most recent call last):
  File "/Users/yuhanliu/projects/dpe-github/python-docs-samples/vision/cloud-client/product_search/product_in_product_set_management_test.py", line 88, in test_purge_products_in_product_set
    PROJECT_ID, LOCATION, PRODUCT_SET_ID, force=True)
  File "/Users/yuhanliu/projects/dpe-github/python-docs-samples/vision/cloud-client/product_search/product_in_product_set_management.py", line 153, in purge_products_in_product_set
    if operation.done():
  File "/Users/yuhanliu/.virtualenvs/vision-ga/lib/python2.7/site-packages/google/api_core/operation.py", line 162, in done
    self._refresh_and_update()
  File "/Users/yuhanliu/.virtualenvs/vision-ga/lib/python2.7/site-packages/google/api_core/operation.py", line 154, in _refresh_and_update
    self._set_result_from_operation()
  File "/Users/yuhanliu/.virtualenvs/vision-ga/lib/python2.7/site-packages/google/api_core/operation.py", line 131, in _set_result_from_operation
    self._result_type, self._operation.response
  File "/Users/yuhanliu/.virtualenvs/vision-ga/lib/python2.7/site-packages/google/api_core/protobuf_helpers.py", line 69, in from_any_pb
    any_pb.__class__.__name__, pb_type.__name__
TypeError: Could not convert Any to Empty
```

**Comment by tseaver** [comment]
@dizcology At the point that the exception is raised, can you print out the repr of `self.operation.response`?

**Comment by dizcology** [comment]
Thanks @tseaver 

When the exception is raised I got this:

```
ipdb> pp self.operation.response
type_url: "type.googleapis.com/google.cloud.vision.v1.PurgeProductsRequest"
value: "\n-projects/rising-sea-112358/locations/us-west1\030\001 \001"

ipdb> pp type(self.operation.response)
<class 'google.protobuf.any_pb2.Any'>
```

it might be that the library was trying to convert the response to type Empty?

**Comment by tseaver** [comment]
@dizcology Looks to me like the [`.proto` for the `PurgeProducts` RPC](https://github.com/googleapis/googleapis/blob/abea8146b9561efd7c408b4d2095f87509fb5e78/google/cloud/vision/v1/product_search_service.proto#L336-L346) is missing the comment markup to indicate the type of the response.  E.g., see the [`.proto` for the `ImportProductSets` RPC](https://github.com/googleapis/googleapis/blob/abea8146b9561efd7c408b4d2095f87509fb5e78/google/cloud/vision/v1/product_search_service.proto#L299-L313), which contains this line:

```protobuf
  // `Operation.response` contains `ImportProductSetsResponse`. (results)
```

**Comment by dizcology** [comment]
Thanks @tseaver - does this mean that the comment markup is used in GAPIC library generation for specifying the message types?

**Comment by tseaver** [comment]
@dizcology I'm not sure:  the code which actually parses all that out (in repo https://github.com/googleapis/gapic-generator/) is too arcane for me to read.

**Comment by tseaver** [comment]
@lukesneeringer, @busunkim96 Can one of you confirm that the comment in the `.proto` file is used to generate the response type for LRO-returning RPCs?

**Comment by dizcology** [comment]
Some more information:

Comparing with the import product set call (which also returns an LRO), I am seeing different `_result_type` on the LRO.  

For import product set:
```
ipdb> pp operation._result_type
<class 'google.cloud.vision_v1.types.ImportProductSetsResponse'>
```

Whereas for purge product:
```
ipdb> pp operation._result_type
<class 'google.protobuf.empty_pb2.Empty'>
```

What I am having a hard time tracking down is how and where this `_result_type` is set.

**Comment by busunkim96** [comment]
@dizcology Would you expect the response to be `Empty` here, or should it be one of the Responses?

**Comment by busunkim96** [comment]
It looks like the return types are set in the GAPIC config: 

https://github.com/googleapis/googleapis/blob/abea8146b9561efd7c408b4d2095f87509fb5e78/google/cloud/vision/v1/vision_gapic.yaml#L547-L566

There is also a way to specify return type via proto annotations using `operation_info`, but it doesn't look like the Vision protos do this.

I see other APIs with [similar configurations for LROs](https://github.com/googleapis/googleapis/search?p=1&q=return_type%3A+google.protobuf.Empty&unscoped_q=return_type%3A+google.protobuf.Empty) that don't seem to have issues. :thinking:

**Comment by busunkim96** [comment]
This has been resolved with a change in the Backend.
