### ISSUE TITLE
Refresh Token is null after authenticating user account

### ISSUE THREAD

**Issue by shahanaz873** [googleapis/google-cloud-python#9171]
Hi, I am trying to restrict the download and upload of files in google storage by using user authentication. I am using below code to authenticate the user account and getting the account details to connect with the cloud. But while getting the details from the account , refresh token is coming null. Do I need to configure anything to get refresh token.

    appflow = flow.InstalledAppFlow.from_client_secrets_file(client_secrets_file, 
    scopes='https://www.googleapis.com/auth/cloud-platform'])
    listen_port = 8080
    creds = appflow.run_local_server(
                    port=listen_port,
                    authorization_prompt_message=prompt,
                    success_message=success)
    data = {           
            'refresh_token': creds.refresh_token,
            'token_uri': creds.token_uri,
            'client_id': creds.client_id,
            'client_secret': creds.client_secret,
            'scopes': creds.scopes
        }
        store_credentials(data, creds_file)

**Comment by tseaver** [comment]
@shahanaz873 I'm afraid this report is out of scope for the `google-cloud-*` Python libraries.  Can you please [open the issue against the `google-auth-library-python-oauthlib` repo](https://github.com/googleapis/google-auth-library-python-oauthlib/issues/new) instead?
