### ISSUE TITLE
Automl: InvalidArgument: 400 when passing ml_use_column_spec_id

### ISSUE THREAD

**Issue by swcoding** [googleapis/google-cloud-python#9232]
#### Environment details
python version: 3.6

#### What I want to do
I was trying to use python API to set the __data_split__ column. I found __ml_use_column_spec_id__ in the Automl documents but I don't know how to pass the argument correctly.

#### Here's my code

```python
data_split_column_name = 'data_split'

update_dataset_dict = {
            'name': AUTOML_DATASET_ID,
            'tables_dataset_metadata':{
                'target_column_spec_id': label_column_id,
                'ml_use_column_spec_id': data_split_column_name
            }
        }
        
update_dataset_response =client.update_dataset(update_dataset_dict)
```
#### Error
```python 
InvalidArgument: 400 List of found errors:	1.Field: dataset.tables_dataset_metadata.ml_use_column_spec_id; Message: Value of key `dataset.tables_dataset_metadata.ml_use_column_spec_id` must be in long format.
```

There was nothing wrong when I only passed target_column_spec_id in tables_dataset_metadata. However, it threw error after adding __ml_use_column_spec_id__ arguments.

I'm sure that the column __data_split__ only includes TRAIN, TEST, VALIDATION.

I will be appreciated if there is any comments, thank you.

**Comment by tseaver** [comment]
@beccasaurus Can you provide some guidance here?

**Comment by lwander** [comment]
@swcoding, are you providing the name `'data_split'` as the value for `ml_use_column_spec_id`? You need to provide the column's ID, not literal name for this to work.

An easier solution might be to use the new client wrapper, which accepts a column name (e.g. "data_split") as an argument for the test/train column (ml_use). See the docs here: https://googleapis.github.io/google-cloud-python/latest/automl/gapic/v1beta1/tables.html#google.cloud.automl_v1beta1.tables.tables_client.TablesClient.set_test_train_column

**Comment by tseaver** [comment]
@swcoding Please follow-up / reopen if @lwander's response doesn't answer your question completely.
