### ISSUE TITLE
Docs: Top-level redirects from RTD broken.

### ISSUE THREAD

**Issue by olsgaard** [googleapis/google-cloud-python#9266]
Where is the documentation for the Python Client library supposed to live?

# Latest missing from readthedocs
Given that documentation for "latest" versions of the python library no longer exist on readthedocs, are we to understand that read the docs is depricated as a home for documentation? [1] but you can still access "stable" [2], but now this does not give the reader confidence about if stable is actually referring to the newest stable version.

# Top level documentation missing from googleapis.dev
Many (if not all) of the sub componenents (big query, storage, etc) have a page on www.googleapis.dev, but there is no top level page for the client library, and therefore no top level entry to the documentation, e.g. [2] is missing from googleapis.dev

# Incoming links are confusing or dead.
Trying to get to the documentation from the GCP webpage is difficult. 

Error messages from the Python Client will point to a documentation URL that does not exist[3]. 

To me that is an indication that it is unclear to other developers and Google marketing where the documentation actually lives.

[1] https://google-cloud-python.readthedocs.io/en/latest/,
[2] https://google-cloud-python.readthedocs.io/en/stable/
[3] In the newest google-cloud-storage release available on pypi (1.19.2), if you try to sign a URL using credentials that only contains a token, you are asked to go to https://google-cloud-python.readthedocs.io/en/latest/core/auth.html?highlight=authentication#setting-up-a-service-account, which doesn't exist.

**Comment by tseaver** [comment]
@olsgaard Thanks for the report.  A couple of things:

- There *is* not top-level client library any longer, only the libraries for the various APIs and a couple of libraries they use (`google-api-core` and `google-cloud-core`).  I agree that the top-level RTD pages should redirect to *somewhere* useful.
- The invalid signing error URL was fixed in PR #9164 (not yet released). (BTW, there is no `google-cloud-storage 1.19.2` release on PyPI:  I assume you meant `1.19.1`).

**Comment by busunkim96** [comment]
@olsgaard Thank you for the feedback. I agree that RTD should redirect to the current documentation. I am actively working on that redirect .The documentation for these clients originally lived on RTD, were redirected to point to GitHub pages, and now lives in googleapis.dev. The gh-pages -> googleapis.dev redirects are active, but the RTD -> googleapis.dev redirects are not.

The best place to get to the 'latest' documentation, for now, is to go to the READMEs in this repository and click on the link for 'client library documentation'.

For [3], could you provide more details on how you were sent to that RTD link? Is it a warning raised in the codebase? As far as I can tell all the links on the latest release of storage (https://pypi.org/project/google-cloud-storage/1.19.1/) are to googleapis.dev. 

https://googleapis.dev/python/storage/latest
https://googleapis.dev/python/storage/latest/index.html
https://googleapis.dev/python/google-api-core/latest/auth.html

**Comment by rvandegrift** [comment]
Please back a top-level index - it's unnecessarily difficult to find each tool on googleapis.dev.  Are users expected to just try typing different URLs until they find what they're looking for?

**Comment by busunkim96** [comment]
@rvandegrift Apologies for any friction this is causing. There won't be a top-level index in the near term at googleapis.dev, though we'd like to add one eventually. I'll open a PR to add ref doc links to the [top-level README](https://github.com/googleapis/google-cloud-python#google-cloud-python-client) to reduce the number of clicks.

> Are users expected to just try typing different URLs until they find what they're looking for?

Every package's README has a link to the documentation on googleapis.dev. This is also what gets shown on PyPI as the project description. You'll want to follow the `Client Library Documentation` link. 

https://pypi.org/project/google-cloud-spanner/

**Comment by busunkim96** [comment]
RTD docs (stable and latest) are now redirecting to googleapis.dev.

There are also links to the reference documentation in the top level README. #9387
