### ISSUE TITLE
Translate: Provide alternative translations.

### ISSUE THREAD

**Issue by dpinol** [googleapis/google-cloud-python#9267]
Hi,
I suggest the translation API to provide more than 1 translation, ideally with a confidence score.
Otherwise, when translating a single word the engine may to always guess the right meaning for polysemic words

thankds

**Comment by tseaver** [comment]
@dpinol This repository manages the Python client library for the translate API, but isn't the correct place to make feature requests for that API (the back-end engineers don't see these issues).  Please file your request as specified on the [Translate API support page](https://cloud.google.com/translate/docs/getting-support#file_bugs_or_feature_requests).
