### ISSUE TITLE
BigQuery, Storage: Question on when to upgrade.

### ISSUE THREAD

**Issue by asokratis** [googleapis/google-cloud-python#9271]
This is a general question related to Bigquery and Google Cloud Storage API I am currently using from this repository.

I am currently using the following versions in my requirements.txt
```shell
google-cloud-bigquery==0.22
google-cloud-storage==0.22
```

And I am currently using the above libraries in Python 2.

I am planning to upgrade my code to Python 3 as Python 2 is going to not be supported by the end of this year.

**However, at the same time, do I need to update the existing versions of the libraries for the above library apis I am using in order to be supported for the next year, next two years, and so on?**

I currently have no issues with the code so far and no issues for years.  I am worried if it will ever break if I do not update the current version 0.22 for those library apis I currently have. I tried to upgrade the version while in python 2 but my code breaks because I need to adjust the code for the newer version changes. So upgrading them will take a lot of time on my end and I do not need currently any of the new features at this moment. In this case, do I still need to upgrade and will this repository give me a warning in advance about which version may not work anymore later on?

I am not sure if this question was answered elsewhere. If there is any reference to it, let me know. Thanks.

**Comment by tseaver** [comment]
@asokratis The libraries reached [GA status](https://github.com/googleapis/google-cloud-python/blob/master/README.rst#general-availability) as follows:

- `google-cloud-storage 1.0.0`, 2017-03-31
- `google-cloud-bigquery 1.0.0`, 2018-04-11

It is extremely unlikely that we would ever publish a bugfix release against the original `0.22` release.  I would recommend updating to the most recent 1.x release of each library while porting to Python3.

**Comment by asokratis** [comment]
Thanks for the advise. It makes sense to switch my libraries from `Beta` to `GA` from the looks of it. Seems its worth the effort to do the transition to the latest version where I can also use the latest Python 3 version as well.

I think my question has already been answered. Thanks for the answer. The issue can be closed.
