### ISSUE TITLE
Vision: leaking files when creating many instances of 'ImageAnnoatorClient'.

### ISSUE THREAD

**Issue by HarvsG** [googleapis/google-cloud-python#9286]
#### Environment details

1. Specify the API at the beginning of the title: Cloud-vision API
2. OS type and version. Ubuntu 18.04
3. Python version and virtual environment information: Python 3.6.4 :: Anaconda custom (64-bit)
4. google-cloud-<service> version: Name: google-cloud-vision Version: 0.39.0

#### Steps to reproduce

  1.  Iterate any function that calls vision.ImageAnnotatorClient.from_service_account_json() enough times

#### Code example

```python
def ocr(uri):
    """some function that will be iterated """
        image = vision.types.Image()
        image.source.image_uri = uri
        image_context = vision.types.ImageContext(language_hints="en")
        client = vision.ImageAnnotatorClient.from_service_account_json('Creds.json')
        response = client.document_text_detection(image=image, image_context=image_context)
        texts = response.text_annotations
        return texts[0].description
results = []
for url in urls:
   results.append(ocr(url))
```

#### Stack trace
Gives an OS error limiting the number of files open
Solutions would be to accept a json object as well as a file path. To support the use of `with` or to close the file properly.

Thanks!

**Comment by tseaver** [comment]
@HarvsG Looking at `ImageAnnotatorClient.from_service_account_file`: https://github.com/googleapis/google-cloud-python/blob/bfb957cfe869e96a89934cd560193225b825e1bd/vision/google/cloud/vision_v1/gapic/image_annotator_client.py#L58-L74

The `google-cloud-vision` library does not explicitly open any file there: it instead relies on [`google.oauth2.service_account.Credentials.from_service_account_file`](https://github.com/googleapis/google-auth-library-python/blob/21b4f1c5f3f15962a7565519697e581a1d0bca34/google/oauth2/service_account.py#L451-L465) which forwards to [`google.auth._service_account_info.from_filename`](https://github.com/googleapis/google-auth-library-python/blob/21b4f1c5f3f15962a7565519697e581a1d0bca34/google/auth/_service_account_info.py#L59-L73).  That function clearly closes the file.

Perhaps the file wasn't closed in some earlier version of the `google-auth` library.  Can you provide the output of `pip list` in the environment where you find this error?

As a "best practice" which would work around this issue, we recommend creating a single instance of the client and reusing it, which will also reduce the number of gRPC connections you are using.  E.g., for your example above:

```python
def ocr(client, uri):
    """some function that will be iterated """
        image = vision.types.Image()
        image.source.image_uri = uri
        image_context = vision.types.ImageContext(language_hints="en")
        response = client.document_text_detection(image=image, image_context=image_context)
        texts = response.text_annotations
        return texts[0].description
results = []
client = vision.ImageAnnotatorClient.from_service_account_json('Creds.json')
for url in urls:
   results.append(ocr(client, url))
```

**Comment by tseaver** [comment]
I believe the error you were seeing was due to the number of open *sockets* (one per gRPC connection in each client) rather than leaks of the actual credentials file.  Please follow-up / reopen if you can provide other information.
