### ISSUE TITLE
Storage: download_as_string documentation says that it downloads a string, instead of bytes

### ISSUE THREAD

**Issue by olsgaard** [googleapis/google-cloud-python#9290]
For google-cloud-storage, in the documentation for [`download_as_string()`](https://github.com/googleapis/google-cloud-python/blob/53d692517345979b2b4621872d76c1184c987b92/storage/google/cloud/storage/blob.py#L714) method on blobs, it says [on line 715](https://github.com/googleapis/google-cloud-python/blob/53d692517345979b2b4621872d76c1184c987b92/storage/google/cloud/storage/blob.py#L715): 

        """Download the contents of this blob as a string.

This is not true. The confusingly named method downloads the content as bytes, not string.

On [line 731](https://github.com/googleapis/google-cloud-python/blob/53d692517345979b2b4621872d76c1184c987b92/storage/google/cloud/storage/blob.py#L731), the return type is correctly declared as bytes, but reading the documentation, you are still presented with conflicting information.

**Comment by HemangChothani** [comment]
@tseaver is it ok to change method's name ,Please suggest.

**Comment by tseaver** [comment]
@HemangChothani We *cannot* change the method's name:  that would be a breaking change.  Note that we chose that method name explicitly for compatibility with the API of the AWS / S3 `boto` library.

We *can* update its docstring to indicate its actual semantics.
