### ISSUE TITLE
Create mechanism for upper level libraries to tag themselves and track usage

### ISSUE THREAD

**Issue by zhitaoli** [googleapis/google-cloud-python#9320]
I am an engineer who works on an open source library (https://www.tensorflow.org/tfx). Our goal is to be able to track usage of our library on various GCP services (CMLE, Dataflow, etc)

One hack we've found comes from KFP team, which [patches the user agent through http.py](https://github.com/kubeflow/pipelines/blob/master/components/gcp/container/component_sdk/python/patches/http.patch) and aggregator number of jobs through weblog.

However, there is several issues with such a short term solution:
1. Not every project can patch python libraries this way: our project does not use docker image 100% and a pure pip installed package cannot patch its environment like this;
2. this would be broken if google-cloud-python chooses a different http library;
3. we can only use one user agent, but what happens if framework A submits a job through framework B? How can both framework track its usage?

I think (1) some guidance on how this should handled holistically across all projects and (2) a proper documented API solution will really help.

I'm happy to discuss further, with the PM and eng from the KFP team too.

Thanks.

**Comment by busunkim96** [comment]
Hi @zhitaoli,

The current way to set the user-agent on the client libraries is through [client_info](https://github.com/googleapis/google-cloud-python/blob/master/api_core/google/api_core/client_info.py#L34). There is a `user_agent` argument that you can set. As long as you are instantiating the client you should have control over what the value is.

Feel free to reach out internally over chat/email if you have more questions about setting the user agent.
