### ISSUE TITLE
Storage: Retrieve project_id in addition to project_number 

### ISSUE THREAD

**Issue by manesioz** [googleapis/google-cloud-python#9358]
**Is your feature request related to a problem? Please describe.**
Despite the fact that each project has the unique identifiers `project_id` and `project_number`, the current api support only returns `project_number`. This is very inconvenient, since the mapping of `project_id` and `bucket_id` is a very common use-case.  

**Current solutions** 
It is possible to parse the JSON config file that was made by via your service account but that's obviously not ideal. Also, you can make another API request via `cloudresourcemanager` to retrieve `project_id` and `project_number` and then you can parse the results. Again, this should be simpler and dealt with inside the `storage` API.  

 **Describe the solution you'd like**
Have a field `projectID` returned from a storage bucket resource request. 
 Example: 
```json
{
  "kind": "storage#bucket",
  "id": string,
  "selfLink": string,
  "projectNumber": unsigned long,
  "projectID": string, 
  ...
}
```

**Comment by tseaver** [comment]
The [storage API resource representation for buckets](https://cloud.google.com/storage/docs/json_api/v1/buckets) doesn't provide that feature, which means we can't map it here.

Please use the resources from the [GCS "Getting Support" page](https://cloud.google.com/storage/docs/getting-support) to request that the back-end API add that feature.

**Comment by manesioz** [comment]
Ok, thanks!
