### ISSUE TITLE
AutoML: How to create file with JSONL extension on Jupyter for AUTOML NLP? 

### ISSUE THREAD

**Issue by Schrodinger-cat-kz** [googleapis/google-cloud-python#9363]
Hi, everyone.
I need to create a JsonL file from my dataframe on Jupyter in python, how can I do this? Any clues how to create file with JSONL extension on Jupyter for parsing it to AUTOML NLP?

**Comment by busunkim96** [comment]
Hi @MekeSakensky,

Are you looking for documentation on the JSON format AutoML Natural Language expects?

**Comment by MekeSakensky** [comment]
well it is clearly told on official site that it has to be JsonL file, plz correct me if it is not.

**Comment by MekeSakensky** [comment]
plz see it under the "Formatting training items" subtopic on the link provided below:
https://cloud.google.com/natural-language/automl/entity-analysis/docs/prepare

**Comment by busunkim96** [comment]
You probably want to look at the panda's documentation on exporting to JSON. https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_json.html 

Note that this repository is generally for client library questions. You will probably get a better answer to product questions elsewhere.

**Comment by MekeSakensky** [comment]
thank you very much!

**Comment by MekeSakensky** [comment]
> You probably want to look at the panda's documentation on exporting to JSON. https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_json.html
> 
> Note that this repository is generally for client library questions. You will probably get a better answer to product questions elsewhere

where can I get answers to questions about AutoML natural language entity extraction?

**Comment by MekeSakensky** [comment]
This is becoming annoying,
I just need easier way to create a JsonL file in python or in whatever with UNlabeled plain texts and that file has to be as AutoML natural Language Entity Extraction expects?
A script in python provided on official website is just horrible plz, see it below:
https://cloud.google.com/natural-language/automl/entity-analysis/docs/scripts/input_helper_v2.py
Any clues for easier way?
plz, see the expected format:
https://cloud.google.com/natural-language/automl/entity-analysis/docs/prepare

**Comment by MekeSakensky** [comment]
I searched almost through everything and didnt get anything. Data preparation cant be that weird as it is shown on official website provided above...

**Comment by tseaver** [comment]
@Schrodinger-cat-kz [`pandas.DataFrame.to_json`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_json.html) has a `lines` argument: if True, it returns [JSONL](http://jsonlines.org/).  E.g.:

```python
jsonl = df.to_json(orient='records', lines=True)
```

Closing because this issue is not about the `google-cloud-automl` / `google-cloud-language` client libraries.

**Comment by busunkim96** [comment]
@Schrodinger-cat-kz The  best way to submit feedback for documentation on cloud.google.com is to follow the 'send feedback' link at the very bottom of the page. The team that manages the documentation will see your report.

https://cloud.google.com/natural-language/automl/entity-analysis/docs/prepare
![image](https://user-images.githubusercontent.com/8822365/66063097-891dd700-e4f7-11e9-9dad-994750c5e88e.png)

**Comment by PaacMaan** [comment]
Hello @Schrodinger-cat-kz I'm facing the same problem and I'm following exactly the steps as described in Google documentation on Natural Language, how were you able to solve it please ??

**Comment by diptej** [comment]
Hi All,
Same Problem, stuck at point that we should convert PDF or other files to JSONL. Please let us know how to do it. Or comment if it is not possible.

**Comment by BennZoll** [comment]
3BMEXqGpG4FxBA1KWhRFufXfSTRgzfDBhJ

**Comment by StraigenDaigen** [comment]
I have the same problem, how to solve it?

**Comment by sunamo91** [comment]
Same problem. Please suggest how to solve it.

**Comment by winter-code** [comment]
I found the script very difficult to use as well, so I have written a blog with the help of my mentor. It has examples to convert a single pdf or plain text file to jsonl format, and also multiple files together. Here's the blog link - [A step by step for converting PDFs to JSONL](https://winter-code.medium.com/automl-nlp-convert-pdfs-to-jsonls-c01f1da0899) 

Hope it's useful.
