### ISSUE TITLE
PubSub: Add system test for streaming pull using an account with pubsub.subscriber role

### ISSUE THREAD

**Issue by plamut** [googleapis/google-cloud-python#9382]
A PubSub regression (#9339) was introduced in the 1.0.1, and fixed in the `1.0.2` release. The fix should be covered by a proper system test.

The test should run a simple streaming pull scenario using a service account that only has the `pubsub.subscriber` role, and no other additional permissions. This implies creating a service account, and adding it to the Kokoro environment (contact @busunkim96 for more info).

**Side question:** How to easily share the same account(s) with developers that need/want to run system tests locally?

**Resources:**
- [PubSub roles](https://cloud.google.com/pubsub/docs/access-control#roles)

**Comment by busunkim96** [comment]
@plamut Will look into getting this added to the Kokoro environment today.

As for sharing the account with external developers, I think we'll have to provide instructions on how to re-create the service account?

**Comment by plamut** [comment]
@busunkim96 Thanks!

Re: service account - one potentially annoying thing here is that the system test suite needs to be run using two different service accounts (this new test specifically need a service account with limited info).

Manually switching from a "default" service account and another one for this specific test (and back) can prove tedious, and we should ideally avoid that, if achievable with a reasonable effort. I am thinking of the automatic service account switch at test runtime - is that possible?
