### ISSUE TITLE
AutoML: NL EE(entity extraction) throws an error during import

### ISSUE THREAD

**Issue by Schrodinger-cat-kz** [googleapis/google-cloud-python#9391]
Hi,
1. I am trying to import my training data to the AutoML NL EE according to the instructions provided on official website of AutoML NL EE(entity extraction). It throws following error:
**Error:** **ImportData stopped due to too many errors.**
I've done followings:
a. I saved plain text (just one paragraph) written in word as PDF
b. uploaded it to Bucket
c. saved following script in Jupyter (python3) as Jsonl file pointing on URI  of PDF as described in instructions
{
  "document": {
    "input_config": {
      "gcs_source": {
        "input_uris": [ "gs://micro-access-254201-lcm/txt1.pdf" ]
      }
    }
  }
}
d. created and uploaded csv pointing on Jsonl file
e. then during the importing it threw **error shown above**

**Cant figure out where is my mistake?** I did Everything EXACTLY in compliance with instructions

2. Secondly, say I am somehow successfull with importing one paragraph of text via PDF, how shall I do it for multiple texts. Should I upload for each texts seperate pdf and what should be the format of Jsonl file for this task?

**Comment by tseaver** [comment]
@Schrodinger-cat-kz How were you doing the import?  I don't see any Python code in your example.

**Comment by Schrodinger-cat-kz** [comment]
I did it interactively via UI, just copy pasted the code (see it below) on the official website to the Jupyter, saved as dictionary, pointed to the PDF uploaded to the Bucket with uri, saved as JsonL file then upploaded it to Bucket, afterwards created and uploaded CSV file pointing to JsonL and tried to impport it, then it threw error as mentioned in my post
{
  "document": {
    "input_config": {
      "gcs_source": {
        "input_uris": [ "gs://cloud-ml-data/NL-entity/sample.pdf" ]
      }
    }
  }
}

**Comment by busunkim96** [comment]
@Schrodinger-cat-kz It looks like you're using AutoML Natural Language Entity Extraction via the cloud console. Since you are not using the Python library `google-cloud-automl`, please direct your question to the [Natural Language discussion group](https://groups.google.com/forum/#!forum/cloud-nl-discuss). The group is linked at the bottom of [this page](https://cloud.google.com/natural-language/automl/entity-analysis/docs/). 

They have product experts who will be able to help you.

**Comment by tseaver** [comment]
@Schrodinger-cat-kz We don't directly support the AutoML back-end API here in this repositoiry, which is for the development of the Python clients for the various Google Cloud APIs.

Normally, we ask that you use the support resources for that API:  however, I don't see them linked in the AutoML docs.   @busunkim96, can you find out why not?  The general [Google Cloud support docs](https://cloud.google.com/support/docs/community) might be helpful for you, however.

In this particular case, JSONL is *one line per record*, e.g. everything from the outermost curly brace to is closing curly brace must be on the same line.
