### ISSUE TITLE
BigQuery: UNNEST from `list_rows`

### ISSUE THREAD

**Issue by nocibambi** [googleapis/google-cloud-python#9460]
**Problem description**
I prefer querying tables from parameters and, for that, I prefer using `client` modules to SQL queries. Accordingly, I would expect to be able to do UNNEST from `list_rows` or from another client module but, currently, I cannot.  (Or maybe I just cannot find the way to do it?)

**An imagined solution**
Using the bitcoin dataset as an example:
```python
dataset_ref = client.dataset(
    "bitcoin_blockchain", project="bigquery-public-data"
)
dataset = client.get_dataset(dataset_ref)

table_ref = dataset_ref.table("transactions")
table = client.get_table(table_ref)

# `unnest` parameter (boolean or `str` of nested table name)
df = client.list_rows(table, max_results=10, unnest='inputs').to_dataframe()
```

**Alternatives**
I am aware only of the 'SQL query' method to do UNNEST, which I am not sure how to parameterize effectively.

**Comment by tswast** [comment]
We don't currently have an unnest feature for `list_rows` or `to_dataframe`.

Related: If you prefer using client modules to writing SQL queries, I personally like Ibis. https://cloud.google.com/blog/products/data-analytics/ibis-and-bigquery-scalable-analytics-comfort-python Unfortunately, the unnest operation isn't yet supported there, either. https://github.com/ibis-project/ibis/issues/1146

**UNNEST for Row objects**:

[`list_rows`](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client.list_rows) returns a [RowIterator](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.table.RowIterator.html#google.cloud.bigquery.table.RowIterator) (actually an iterable, not an iterator), which you can treat as a sequence of [Row](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.table.Row.html#google.cloud.bigquery.table.Row) objects.

I'd suggest using a helper function like the following:

```
def unnest_row(row, column_name):
    row_items = list(row.items())
    # TODO: remove `column_name` from `row_items`
    nested_values = row[column_name]
    for nested_value in nested_values:
        for subcolumn, subvalue in nested_value.items():
            row_items.append(
                (
                    "{}.{}".format(column_name, subcolumn),
                    subvalue,
                )
            )
    return dict(row_items)
```

**UNNEST for `to_dataframe`**:

This would take quite a bit of complexity to be performant. I acknowledge that this would be a useful feature in some cases, but client-side processing like this is outside the scope of this library at this time.
