### ISSUE TITLE
BigQuery: Install client libraries from github

### ISSUE THREAD

**Issue by yiga2** [googleapis/google-cloud-python#9463]
I'd like to test/use some features in the bigquery library (e.g. parentJobId in client.list_jobs) that are not yet included in a release, hence not available through Pypi.

How can one install the bigquery only ?

`pip install git+https://github.com/googleapis/google-cloud-python.git` installs them all !

**Comment by tswast** [comment]
Pip allows you to specify a sub-directory, like so:

`git+https://github.com/googleapis/google-cloud-python.git#egg=version_subpkg&subdirectory=bigquery`

**Comment by yiga2** [comment]
I had read this too but `pip install git+https://github.com/googleapis/google-cloud-python.git#egg=bigquery&subdirectory=bigquery` still clones the whole repo, not just the subdirectory.
