### ISSUE TITLE
BigQuery: pyarrow warning about schema argument 

### ISSUE THREAD

**Issue by tswast** [googleapis/google-cloud-python#9485]
samples/tests/test_query_to_arrow.py::test_query_to_arrow
  /tmpfs/src/github/google-cloud-python/bigquery/google/cloud/bigquery/_pandas_helpers.py:383: FutureWarning: Schema passed to names= option, please pass schema= explicitly. Will raise exception in future
    return pyarrow.RecordBatch.from_arrays(arrays, column_names)

**Comment by les69** [comment]
Hello everyone! I'm experiencing the same issue non-deterministically and it seems to be linked to a reduction in the downloading performance (from ~200k rows per second to ~20k).
Is there any workaround for the moment?

Thank you

**Comment by plamut** [comment]
@les69 In which `pyarrow` version does that happen? Does it also happen in an earlier version, e.g. `0.14.1` (i.e. the performance regression, not the warning)?

The warning itself seems pretty benign, it's just the way parameters are passed to one of the `pyarrow`'s methods, and `pyarrow` [resolves that](https://github.com/apache/arrow/blob/master/python/pyarrow/table.pxi#L759-L760) on its own (but will eventually stop doing that).

It might be, however, that performance is different when using a `pyarrow` schema as opposed to just the column names ([source](https://github.com/googleapis/google-cloud-python/blob/dce13268e9bdf2df6a3c7a2df6db3b8a1bb51f75/bigquery/google/cloud/bigquery/_pandas_helpers.py#L388)), and the distinction between these two cases became more visible with the warning introduced in `pyarrow` 1.15.0.
