### ISSUE TITLE
Datastore: No module named 'google.type'

### ISSUE THREAD

**Issue by karlbateman** [googleapis/google-cloud-python#9496]
#### Environment Details

**OS version:** Ubuntu 18.04.3 LTS
**Python version:** Python 3.7.3
**google-cloud-datastore version:** 1.10.0

#### Steps to reproduce

1. Create a virtual environment using the following command:
```bash
python3.7 -m venv venv
```
2. Activate the virtualenv:
```bash
source venv/bin/activate
```
3. Install the `google-cloud-datastore` client:
```bash
pip3 install google-cloud-datastore
```
4. Using the following [example code](https://googleapis.dev/python/datastore/latest/index.html#example-usage) create the file `main.py`:
```python
from google.cloud import datastore

client = datastore.Client()
key = client.key('EntityKind', 1234)
entity = datastore.Entity(key=key)
entity.update({
    'foo': 'bar'
})
client.put(entity)

result = client.get(key)
print(result)
```
5. Run the `main.py` file:
```bash
python3.7 main.py
```
6. See the error displayed in the terminal:
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from google.cloud import datastore
  File "/home/karlbateman/Workspace/karlbateman/gcloud-datastore/venv/lib/python3.7/site-packages/google/cloud/datastore/__init__.py", line 62, in <module>
    from google.cloud.datastore.batch import Batch
  File "/home/karlbateman/Workspace/karlbateman/gcloud-datastore/venv/lib/python3.7/site-packages/google/cloud/datastore/batch.py", line 24, in <module>
    from google.cloud.datastore import helpers
  File "/home/karlbateman/Workspace/karlbateman/gcloud-datastore/venv/lib/python3.7/site-packages/google/cloud/datastore/helpers.py", line 24, in <module>
    from google.type import latlng_pb2
ModuleNotFoundError: No module named 'google.type'
```

I'm not entirely sure what the issue is as I've attempted to follow an example using the `google-cloud-datastore` client with Python3.7, perhaps I've missed something?

**Comment by busunkim96** [comment]
@karlbateman Would you mind showing us the results of a `pip freeze`?

**Comment by karlbateman** [comment]
@busunkim96 Thanks for getting back to me so soon. Please see the following:
```
cachetools==3.1.1
certifi==2019.9.11
chardet==3.0.4
google-api-core==1.14.3
google-auth==1.6.3
google-cloud-core==1.0.3
google-cloud-datastore==1.10.0
googleapis-common-protos==1.6.0
grpcio==1.24.1
idna==2.8
pkg-resources==0.0.0
protobuf==3.10.0
pyasn1==0.4.7
pyasn1-modules==0.2.7
pytz==2019.3
requests==2.22.0
rsa==4.0
six==1.12.0
urllib3==1.25.6
```

**Comment by karlbateman** [comment]
I've resolved the issue, my `PYTHONPATH` was being set due to needing the Python2 AppEngine SDK `appcfg.py` tooling. After removing where this was being set everything is working as expected. Hopefully this helps someone who has a similar issue. I'll close this now, thanks for the support :smile:
