### ISSUE TITLE
BigQuery: Encryption configuration docs are not included in any TOC tree

### ISSUE THREAD

**Issue by plamut** [googleapis/google-cloud-python#9505]
Generating the docs locally:
```
$ nox -f noxfile.py -s docs
```
results in the following `SphinxWarning` which is treated as an error:

> sphinx.errors.SphinxWarning: ... bigquery/docs/generated/google.cloud.bigquery.table.EncryptionConfiguration.rst:document isn't included in any toctree

This needs to be addressed for the `docs` nox session to pass successfully.

**Comment by HemangChothani** [comment]
@plamut  The `google.cloud.bigquery.table.EncryptionConfiguration` class is moved to an independent file `google.cloud.bigquery.encryption_configuration.EncryptionConfiguration` so i delete that file manually from generated folder as no more needed and and it works for me.

**Comment by plamut** [comment]
@HemangChothani Removing the `docs/generated` directory, and re-running the command works, thanks. :+1:

I thought that the command starts from scratch on each run, but apparently this is not the case, and any obsolete files are kept in the `generated/` directory.

Closing as a non-issue then.
