### ISSUE TITLE
Cloud Functions: No way to set http-triggered function to private before deployment

### ISSUE THREAD

**Issue by MartinWan** [googleapis/google-cloud-python#9512]
Thanks for stopping by to let us know something could be better!

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title: Cloud Functions CLI
2. OS type and version: Debian GNU/Linux 10
3. Python version and virtual environment information: Python 2.7.16
4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`

#### Steps to reproduce

  1. `gcloud beta functions deploy foo --entry-point Foo
    --source srcdir --trigger-http --runtime go111`

  2. The function is public, even though  --allow-unauthenticated is not set.

This is problematic, as it seems there is no way to deploy a function without making it public immediately. Sure you can use  `gcloud beta functions remove-iam-policy-binding` but this is after the function is already deployed and completely public.

**Comment by tseaver** [comment]
@MartinWan I'm afraid this repository is not the right place for your report:  here we maintain the `google-cloud-*` client libraries, not the `gcloud` utility.  Please use one of the [Cloud Functions support resources](https://cloud.google.com/functions/docs/getting-support) or the [Cloud SDK support resources](https://cloud.google.com/sdk/docs/getting-support) to resolve your issue.
