### ISSUE TITLE
Storage: Add support for Archive storage class

### ISSUE THREAD

**Issue by tritone** [googleapis/google-cloud-python#9532]
GCS is adding a storage class called "archive" to the [existing options for object storage](https://cloud.google.com/storage/docs/storage-classes) (coldline, standard, etc). Support for this should be added to this client library.

This should be straightforward as ARCHIVE should just mirror existing valid storage classes. I see the following places where changes are required in order to accomplish this:
* https://github.com/googleapis/google-cloud-python/blob/master/storage/google/cloud/storage/constants.py (add new constant)
* https://github.com/googleapis/google-cloud-python/blob/master/storage/google/cloud/storage/bucket.py  (add import, update STORAGE_CLASSES, update documentation).
* https://github.com/googleapis/google-cloud-python/blob/master/storage/google/cloud/storage/blob.py (same as above)
* Incorporate ARCHIVE into unit tests as appropriate.

This has already been implemented in the C++ client library; reference commit [here](https://github.com/googleapis/google-cloud-cpp/pull/3197)

**Comment by tseaver** [comment]
@tritone What should the descriptive text be for the `ARCHIVE_STORAGE_CLASS` constant?

**Comment by tseaver** [comment]
@tritone I made a guess at the descriptive text here: https://github.com/googleapis/google-cloud-python/blob/d31eeb9fac3542286e487a9d26e42b1f26540688/storage/google/cloud/storage/constants.py#L28

**Comment by tritone** [comment]
Hi @tseaver, yep that is correct! For additional context, I shared you on a doc with some relevant info; also, the preliminary public description is in the blog post here: https://cloud.google.com/blog/products/storage-data-transfer/whats-cooler-than-being-cool-ice-cold-archive-storage .

We may also want to add a link to the public documentation at https://cloud.google.com/storage/docs/storage-classes since there are specific policies around availability and minimum storage duration for each class (archive will be added here once launched).

**Comment by tseaver** [comment]
@tritone  I added the link to all storage class constants in https://github.com/googleapis/google-cloud-python/pull/9533/commits/8272f9f0d78761269032e23fd52b2785bf4f81ea .
