### ISSUE TITLE
feat(bigquery) - relax get_table() arg - allow string as table_id

### ISSUE THREAD

**Issue by yiga2** [googleapis/google-cloud-python#9542]
`client.get_table('mydataset.mytable') `

is easier than

`client.get_table(bigquery.TableReference(self.dataset('mydataset'), 'mytable'))`

If project is omitted, the client one would be used, and dataset could also become optional if a default dataset can be set.

**Comment by Emar-Kar** [comment]
@yiga2 If I get you right, then this feature is already realized. If you are using a string format and your `default_project` is not set, then just use **"your-project.your_dataset.your_table"** implementation, on the over hand, if `default_project` is set it should be **"your_dataset.your_table"** variant. Can you check this out, please, and confirm that everything works properly in your case?

![image](https://user-images.githubusercontent.com/46078689/67679888-30791700-f99b-11e9-89ef-c67aa5a62b11.png)
![image](https://user-images.githubusercontent.com/46078689/67679985-6c13e100-f99b-11e9-847f-cb571d5357c0.png)

**Comment by yiga2** [comment]
Hmm. You're right when I look at the GitHub source. I used and relied on the documentation which is not up-to-date (https://google-cloud-python.readthedocs.io/en/0.32.0/bigquery/reference.html).
However here it is indeed referenced: https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client.get_table

Will close and not use readthedocs.io going forward.
Thanks

**Comment by yiga2** [comment]
Hmm. You're right when I look at the GitHub I was looking at outdated d(old release) documentation.
Silly me

**Comment by Emar-Kar** [comment]
Don't worry. Glad to help you.
