### ISSUE TITLE
Translate: the string representation of the TranslateTextResponse and Translation objects is misleading

### ISSUE THREAD

**Issue by verhovsky** [googleapis/google-cloud-python#9585]
```python
from google.cloud.translate import TranslationServiceClient
from google.oauth2 import service_account

CREDENTIALS_FILE = "creds.json"

_google_translate_credentials = service_account.Credentials.from_service_account_file(CREDENTIALS_FILE)
PROJECT_ID = "projects/" + _google_translate_credentials.project_id

_google_translate = TranslationServiceClient(credentials=_google_translate_credentials)

result = _google_translate.translate_text(
    ["This is not very useful", "This is not very accurate"],
    target_language_code="ru",
    source_language_code="en",
    mime_type="text/plain",
    parent=PROJECT_ID,
)

print(result)
print(repr(result))
```

produces the same output for both `print(result)` (which implicitly does `str(result)`) and `print(repr(result))`:

```text
translations {
  translated_text: "\320\255\321\202\320\276 \320\275\320\265 \320\276\321\207\320\265\320\275\321\214 \320\277\320\276\320\273\320\265\320\267\320\275\320\276"
}
translations {
  translated_text: "\320\255\321\202\320\276 \320\275\320\265 \320\276\321\207\320\265\320\275\321\214 \321\202\320\276\321\207\320\275\320\276"
}

```

What is that format? It's like JSON, but not. It looks like a list of objects but you access it with `result.translations` to get the list, `translations {` being listed multiple times makes that confusing. There's no indication that it's an object that contains a list of `Translation` objects. You need to read the docs to figure any of this out.

Normally in Python when you return an object, its string representation looks more like `TranslateTextResponse(translations=[Translation(translated_text="readable text here)  ...])` or something along those lines. I'm not sure what exactly you should do, (I would just returns a list of dictionaries, like the v2 API...) but they definitely don't look like that. They also don't have trailing newlines `repr(22) -> '22'`. 

Those things that look like escape sequences are not valid Python escape sequences.

```
>>> "\320\255\321\202\320\276 \320\275\320\265 \320\276\321\207\320\265\320\275\321\214 \320\277\320\276\320\273\320\265\320\267\320\275\320\276"
'Ð\xadÑ\x82Ð¾ Ð½Ðµ Ð¾Ñ\x87ÐµÐ½Ñ\x8c Ð¿Ð¾Ð»ÐµÐ·Ð½Ð¾'
```

There is nothing wrong with just printing UTF-8 characters to the terminal.

**Comment by tseaver** [comment]
The generated V3 client returns protobuf messages (instances of type `google.cloud.translate_v3.types.TranslateTextResponse`).  The `__str__` and `__repr__` methods for protobuf messages are defined in the `google.protobuf` library:  there is nothing we can do here to change them.

**Comment by verhovsky** [comment]
Okay.
