### ISSUE TITLE
Datastore: projection queries do not return the same number of records.

### ISSUE THREAD

**Issue by klausmyrseth** [googleapis/google-cloud-python#9600]
OS: ubuntu 19.04
Python: 3.7.3
Client library: google-cloud-datastore 1.10.0

#### Steps to reproduce

  1. Import data into datastore (fairly big records with many fields, actually datex 2 compatible data for situations)
  2. Query all data and count the records.
  3. Make a projection query for 3-4 of the fields
  4. Create the suggested index.
  5. Run the projection query and count the records.

I seem to get only 25% of the records using the projection query, which I cant understand, for the same filter and options only by using the exact same settings as the first query.

#### Code example

```python
  query = client.query(kind='TestData', namespace='TestNamespace1')
  data = query.fetch()
  run1 = len(list(data))
  query = client.query(kind='TestData', namespace='TestNamespace1')
  query.projection = ['field1', 'field2', 'field3', 'field4']
  data = query.fetch()
  run2 = len(list(data))
  print('%s should be like %s' % (run1, run2))
```

#### Stack trace
You dont get stacktrace outside of the initial one that gives you the hint for the correct index to create in the database. I created the suggested one.

All fields outside of 1 is string or number one is lat long position using the datastore type.

Considering none projection query runs in 6 seconds and returns a result set of 18Mb I would prefer to get this working with the projection query coupled with gzip which run in 200ms where the result set should be 54Kb :)

**Comment by tseaver** [comment]
@klausmyrseth I suspect that you are running into a known [restriction on projection queries](https://cloud.google.com/datastore/docs/concepts/queries#restrictions_on_queries):

> Entities lacking a property named in the query are ignored

> Entities of the same kind need not have the same properties. To be eligible as a query result, an entity must possess a value (possibly null) for every property named in the query's filters and sort orders. If not, the entity is omitted from the indexes used to execute the query and consequently will not be included in the query's results.

Can you verify that any of the omitted entities have all four of the projection fields set with an explicit value?

**Comment by klausmyrseth** [comment]
Yes all these properties are on all entities, however some of them are null they are still present. When I create the index i see all entries are processed but when querying I get 18% of them as a result.

Some of the returned entities from the projection query is also with null values so that seems to work.

**Comment by tseaver** [comment]
@klausmyrseth Glad to hear that we found an explanation before complete baldness set in.

Please follow-up / reopen if the reduced result set reappears with fully-populated entities.
