### ISSUE TITLE
BigQuery: Add support for configuring Hive partitioning options

### ISSUE THREAD

**Issue by plamut** [googleapis/google-cloud-python#9610]
As a BigQuery client user, I would like to have an easy way of configuring Hive partitioning options.

I would like a new `HivePartitioningOptions` class for setting the tables' [external data config](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#ExternalDataConfiguration) as defined by the API.

**Comment by akmittal006** [comment]
Hi plamut, 
I require this feature right now, is there a way i can do this using existing client library?
If so can you please help or suggest alternative.

**Comment by plamut** [comment]
@akmittal006
A [pull request](https://github.com/googleapis/google-cloud-python/pull/9626) that will add this feature will probably be merged in the next few days (cc: @tswast). When merged, you can then install a pre-release version of the BigQuery client with a GitHub link pointing to that specific commit (at least until a new version of the client is released).

Would that work for you?

**Comment by akmittal006** [comment]
I ended up using your code from pull request for my quick fix. This saved me a lot of time. Thanks @plamut .

**Comment by plamut** [comment]
@akmittal006 Glad to hear that that it fixed your problem!
Just make sure to switch to a regular install once this feature is released in order to potentially benefit from other new features and bugfixes.
