### ISSUE TITLE
BigQuery: Valid `google-resumable-media` versions conflict with Cloud Storage

### ISSUE THREAD

**Issue by daniel-humu** [googleapis/google-cloud-python#9786]
It looks like #9572 introduced a dependency conflict for `google-resumable-media` between the latest `google-cloud-storage` and `google-cloud-bigquery` releases.

#### Environment details

1. Python 3.7

#### Steps to reproduce

1. `pip install google-cloud-storage` (latest release is `1.23.0`)
2.`pip install google-cloud-bigquery` (latest release is `1.21.0`)
3. Try to import both libraries in the same python 

#### Issue

Today, `google-cloud-storage 1.23.0` was released. It depends on `google-resumable-media >= 0.5.0, < 0.6dev`. The current `google-cloud-bigquery` version, depends on `google-resumable-media >= 0.3.1, != 0.4.0, < 0.5.0dev`

Therefore, the `setup.py` files for these two libraries will 2nd level dependency conflict when you attempt to `pip install`.

This can be fixed by releasing a new `google-cloud-bigquery` version. (to pick up the changes in  #9572)

**Comment by tseaver** [comment]
@tswast Are we at a good spot to release a new version of `google-cloud-bigquery`?

**Comment by tseaver** [comment]
@daniel-humu Thanks for the report!

**Comment by icymai** [comment]
Hello Daniel! Thank you for providing the solution. I have a small question related to this error. What does it mean "**google-resumable-media >= 0.3.1, != 0.4.0, < 0.5.0dev**"? Why does this description mention 3 different versions?

**Comment by daniel-humu** [comment]
@icymai Are you asking how version specifiers work? The dependency `google-resumable-media >= 0.3.1, != 0.4.0, < 0.5.0dev` means that the package depended on versions greater than or equal to `0.3.1`, less than `0.5.0dev` and excluding the `0.4.0` version.

You can read more documentation on [version specification on the Python website](https://www.python.org/dev/peps/pep-0440/#version-specifiers).

**Comment by icymai** [comment]
Cool! I haven't read this doc before. Thank you :D
