### ISSUE TITLE
BigQuery: add project parameter to create_dataset method

### ISSUE THREAD

**Issue by adamcunnington-2sixty** [googleapis/google-cloud-python#9802]
Please add a project= parameter for the create_dataset method. The methods that start jobs already support this but it's not an accepted arg for create_dataset.

**Comment by Emar-Kar** [comment]
@adamcunnington-2sixty According to your request:

![create_dataset](https://user-images.githubusercontent.com/46078689/68945579-c4334b80-07c1-11ea-93db-495a3ebf389b.png)

![image](https://user-images.githubusercontent.com/46078689/68946154-50923e00-07c3-11ea-88d1-f260973fb9dc.png)

You can pass `Dataset`, `DatasetReference` classes or string as the `dataset` parameter in the `create_dataset` method. The result will depend on the value of `default_project` and whether you pass the direct `project_id` yourself.

Or have you got another idea for the `project=` use?

**Comment by adamcunnington-2sixty** [comment]
Hi @Emar-Kar - all of what you are referring to there relates to the project that the dataset belongs to. The purpose of project= for the create_dataset method relates to the project id in which the request is SENT. The same with creating jobs; the jobs can affect an arbitrary project but you need to choose a project to send the request FROM.

I was sort of surprised that this is needed for creating datasets because there is no job/query to bill and so it doesn't seem relevant but i get an error when creating dataset if i create it using a client that is authorised by a service account with a default project id that is **different** to the project id that the dataset that I am trying to create belongs to.

I fixed this by doing:
```my_client.project_id = foo```
before calling:
```my_client.create_dataset(dataset)```

**Comment by Emar-Kar** [comment]
Thank you for the detailed description. Is it possible for you to send me the error trace which you're receiving during the `create_dataset `call without this workaround?

**Comment by adamcunnington-2sixty** [comment]
Frustratingly, I can't reproduce this right now... the error message was something like:

'myProjectId' in content does not agree with value sharedProjectId'. This can happen when a value set through a parameter is inconsistent with a value set in the request."

**Comment by Emar-Kar** [comment]
@adamcunnington-2sixty good day again. I was trying to reproduce the error conditions:

![Screenshot from 2019-11-16 16-03-38](https://user-images.githubusercontent.com/46078689/68994081-db406f00-088f-11ea-8150-64c5fbdaf15d.png)

Also, as I can see there is no attribute `project_id` in the `Client` class, so I assume that you switched the `project` instead. Can you tell me what dataset value you're passing in the `create_dataset` request? And the error trace can be really helpful in this issue.

**Comment by Emar-Kar** [comment]
@adamcunnington-2sixty Please feel free to reopen this issue if you are still running into this issue.
