### ISSUE TITLE
DataStore: Protobuf decode performance for large amounts of data.

### ISSUE THREAD

**Issue by Subaku** [googleapis/google-cloud-python#9868]
I'm regularly performing queries that yield a lot of data. Right now in my testing it's only around 48k entities but it'll grow quite a bit later. This is to support our reporting mechanisms. When I profiled my code I noticed a lot of time is spent in protobuf decoding. Not surprising as deserializing can be pretty expensive. 

So I'm wondering if there's anything I can consider to increase this performance. Pouring through documentation and other tickets I'm not finding anything that stands out.

Here's an image of my profiling an endpoint in my API that fetches said 48k entities for reference.
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/1900930/69260171-5184f000-0b74-11ea-8a19-18b62d3a289e.png">

This is being done within my Flask API and here are some versions of the installed google packages.

google-api-core==1.13.0
google-auth==1.6.3
google-cloud-core==1.0.2
google-cloud-datastore==1.8.0
google-api-python-client==1.7.9
googleapis-common-protos==1.6.0

Appreciate any guidance!

**Comment by IlyaFaer** [comment]
I suppose, this issue is mostly about Protobuf
@rafi-kamal, PTAL, maybe you have something that can help in this case

**Comment by Subaku** [comment]
Thanks for getting back to me.

Looks like I'm installing `protobuf==3.8.0` in my requirements.txt. I'm guessing the answer to your question is no although I'm unsure of how to verify. Let me know if there's something I can check for you.

**Comment by rafi-kamal** [comment]
@anandolee who is working on Python Protobuf.

**Comment by IlyaFaer** [comment]
@Subaku, take a look at [here](https://github.com/protocolbuffers/protobuf/blob/master/python/README.md). It describes how to install C++ implementation. C++ should be few times faster than pure Python.

**Comment by Subaku** [comment]
I'll give that a shot and let you know how it goes. Might be a few weeks before I get around to it though but I'll report back. 

Thanks!

**Comment by Subaku** [comment]
"Few" time faster he says... It now takes 1.32 seconds. Nice! :)

Thanks for pointing that out to me. Million times better.
