### ISSUE TITLE
BigQuery: Issue with running tests on ARM64 platform

### ISSUE THREAD

**Issue by ossdev07** [googleapis/google-cloud-python#9871]
**Tried to build and test the Bigquery package in aarch64 platform.**

**Followed below steps :**
1. Git clone google-cloud-python package.
2. Installed successfully using command "python3 setup.py install". 
3. Ran "Nox" command to test the package but getting below error.

```ImportError while importing test module '/google-cloud-python/bigquery/tests/unit/test__pandas_helpers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/unit/test__pandas_helpers.py:31: in <module>
    import pyarrow
E   ModuleNotFoundError: No module named 'pyarrow'


FAIL Required test coverage of 97% not reached. Total coverage: 17.99%
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
1 error in 11.94s"
```
**To resolve above  issue followed below steps:**

As pyarrow is not available for aarch64 . In order to test the package we need to install it manually  from source.

**Steps to install the pyarrow package in aarch64 are** :
I have installed pyarrow from source cloned from https://github.com/apache/arrow. I have followed the document https://github.com/apache/arrow/blob/master/docs/source/developers/python.rst for installing arrow and pyarrow. 

Ran git clone "https://github.com/apache/arrow.git".
cd arrow
Followed link  https://stackoverflow.com/questions/48157198/how-can-i-statically-link-arrow-when-building-parquet-cpp/48278906#48278906?newreg=d222eb3d38894d1997810fade572f4cf to install some dependencies and installed arrow c++ libraries
 
1) sudo apt-get install libjemalloc-dev libboost-dev libboost-filesystem-dev libboost-system-dev libboost-regex-dev python-dev autoconf flex bison libssl-dev libcrypto++-dev
2) export ARROW_HOME= /usr/local
3) export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH   
4) mkdir arrow/cpp/build
5) pushd arrow/cpp/build
6) cmake -DCMAKE_INSTALL_PREFIX=$ARROW_HOME \
      -DCMAKE_INSTALL_LIBDIR=lib \
      -DARROW_FLIGHT=ON \
      -DARROW_GANDIVA=ON \
      -DARROW_ORC=ON \
      -DARROW_WITH_BZ2=ON \
      -DARROW_WITH_ZLIB=ON \
      -DARROW_WITH_ZSTD=ON \
      -DARROW_WITH_LZ4=ON \
      -DARROW_WITH_SNAPPY=ON \
      -DARROW_WITH_BROTLI=ON \
      -DARROW_PARQUET=ON \
      -DARROW_PYTHON=ON \
      -DARROW_PLASMA=ON \
      -DARROW_BUILD_TESTS=ON \
      ..
7) make -j4
8) make install
9) popd

**After building c++ libraries, installed pyarrow**:

10) pushd arrow/python
11) export PYARROW_WITH_FLIGHT=1
12) export PYARROW_WITH_GANDIVA=1
13) export PYARROW_WITH_ORC=1
14) export PYARROW_WITH_PARQUET=1
15) python setup.py build_ext --inplace
16) python setup.py install  
17) popd

**Steps to install and test google-cloud-bigquery package in both platforms**:
1. cd bigquery/
2. python3 setup.py install
3. python3 setup.py test

**Conclusion :**  
Nox command is creating a virtual environment which installs all dependencies in that environment and it is not importing the pyarrow package as it is installed in local system. So, Installed pyarrow manually by following above mentioned steps and  tested the package using command **"python setup.py test"**.

**Comment by tswast** [comment]
This looks more like an issue for pyarrow than BigQuery. Pandas and PyArrow are both only optional dependencies, but if you want to use them on Arm, then it is up to those communities to publish packages for Arm.

I think conda-forge was working on building Arm support, so you might want ot start there.
