### ISSUE TITLE
Storage : Module google/cloud/storage/blob.py is importing RawDownload which is not avaiable

### ISSUE THREAD

**Issue by elangovankrishna** [googleapis/google-cloud-python#9891]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-python/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version
3. Python version and virtual environment information: `python --version`
4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`

#### Steps to reproduce

We have an Airflow setup using Docker image with other packages needed for Airflow along with && pip install --upgrade google-cloud-storage \ to pull in the latest changes, i have to add more modules to my docker file like gcsfs and rebuilt the docker image which pulled in the latest changes from new release of `google-cloud-storage 1.23.0 ` committed 3 days ago.

#### Stack trace
`Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 202, in process_file
webserver_1  |     m = imp.load_source(mod_name, filepath)
webserver_1  |   File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
webserver_1  |     module = _load(spec)
webserver_1  |   File "<frozen importlib._bootstrap>", line 684, in _load
webserver_1  |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
webserver_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
webserver_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
webserver_1  |   File "/home/airflow/dags/bq_to_es_index/bigquery_to_es_indexing.py", line 4, in <module>
webserver_1  |     from config_util.IngestDagFactory import IngestDagFactory
webserver_1  |   File "/home/airflow/dags/config_util/IngestDagFactory.py", line 11, in <module>
webserver_1  |     from config_util.IngestItem import IngestItem, IngestItemSchema
webserver_1  |   File "/home/airflow/dags/config_util/IngestItem.py", line 10, in <module>
webserver_1  |     from config_util.util import render_templated_fields
webserver_1  |   File "/home/airflow/dags/config_util/util.py", line 8, in <module>
webserver_1  |     from airflow.contrib.hooks.gcs_hook import GoogleCloudStorageHook
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/contrib/hooks/gcs_hook.py", line 25, in <module>
webserver_1  |     from google.cloud import storage
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/google/cloud/storage/__init__.py", line 39, in <module>
webserver_1  |     from google.cloud.storage.blob import Blob
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 46, in <module>
webserver_1  |     from google.resumable_media.requests import RawDownload
webserver_1  | ImportError: cannot import name 'RawDownload'

I could see the there is no module named RawDownload on https://github.com/googleapis/google-resumable-media-python/tree/master/google/resumable_media/requests

I could see the module google/cloud/storage/blob.py was updated 3 days ago with this import 
from google.resumable_media.requests import RawDownload

Please correct me if I am missing anything this is my first issue being reported.
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by HemangChothani** [comment]
@elangovankrishna  The error is due to older version of `google-resumable-media`, please install updated  version  of `google-resumable-media==0.5.0` , it will work.

**Comment by elangovankrishna** [comment]
@HemangChothani I have the latest version of `google-resumable-media==0.5.0` installed it's when I got this error.

**Comment by HemangChothani** [comment]
@elangovankrishna  The `RawDowload` module is in  the [https://github.com/googleapis/google-resumable-media-python/blob/master/google/resumable_media/requests/download.py](https://github.com/googleapis/google-resumable-media-python/blob/master/google/resumable_media/requests/download.py) file. I have tested it and also tried to import other classes from the same file and it works fine for me , could you please try to import classes manually?

![Screenshot from 2019-11-26 18-56-59](https://user-images.githubusercontent.com/50404902/69637618-02acee00-107f-11ea-9cb3-ae685ef545d6.png)

**Comment by HemangChothani** [comment]
@elangovankrishna Did you try that manually, Any update?

**Comment by crwilcox** [comment]
I have attempted to repro this in a brand new python3.7 venv.

```
$ python -m venv venv
$ source venv/bin/activate
$ python -m pip install google-cloud-storage
$ python -m pip freeze
cachetools==3.1.1
certifi==2019.11.28
chardet==3.0.4
google-api-core==1.14.3
google-auth==1.7.2
google-cloud-core==1.1.0
google-cloud-storage==1.23.0
google-resumable-media==0.5.0
googleapis-common-protos==1.6.0
idna==2.8
protobuf==3.11.1
pyasn1==0.4.8
pyasn1-modules==0.2.7
pytz==2019.3
requests==2.22.0
rsa==4.0
six==1.13.0
urllib3==1.25.7
```

And the imports work as expected.

```
Python 3.7.4 (default, Aug  9 2019, 10:24:13) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud.storage.blob import Blob
>>> from google.resumable_media.requests import RawDownload
```

Please verify via `python -m pip freeze` that this python environment has up to date packages. In a clean environment this seems to work.
