### ISSUE TITLE
please add commit convention description in CONTRIBUTING.rst

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-python#9897]
CONTRIBUTING.rst has no mention of the commit convention. That makes it quite hard to create a proper commit to this repo first time around.

**Comment by IlyaFaer** [comment]
@paul1319, this is a good issue for the first task

**Comment by tswast** [comment]
I believe we are following: https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md

I think this would make sense to document at https://github.com/googleapis/google-cloud-common/tree/master/contributing

**Comment by IlyaFaer** [comment]
> I think this would make sense to document at https://github.com/googleapis/google-cloud-common/tree/master/contributing

I assume, it should be mentioned in both python/CONTRIBUTING.md and common/CONTRIBUTING.md, as new people are usually coming right to the concrete language repo, and they may not even suspect google-cloud-common repo exists.

Other languages, as I see, are now using this convention too, so we probably should mention it in other language specific repos, to make sure it's on a prominent place.

**Comment by tswast** [comment]
That proposal makes sense to me.
