### ISSUE TITLE
Core: Add timeout parameter to connection's api_request() method

### ISSUE THREAD

**Issue by plamut** [googleapis/google-cloud-python#9914]
As a client library developer, I want to have an easy way of specifying the timeout at the transport level for HTTP requests.

**Motivation:**
If the transport layer makes an HTTP request that gets stalled, it can block the client. Any timeouts and retries on top of it cannot come into play, because the transport layer blocks them while waiting for the response without any timeout specified.

One of the manifestations of the problem in the BigQuery client: https://github.com/googleapis/google-cloud-python/issues/7831

**Comment by tswast** [comment]
We’ll want to cut a release for this. Do you have releasetool setup, @plamut ?

**Comment by plamut** [comment]
@tswast I have the tool, last used in September IIRC to release a PubSub client. I can start releasing Core.
