### ISSUE TITLE
Storage: Signed URL generated with generate_signed_url always responds with SignatureDoesNotMatch

### ISSUE THREAD

**Issue by Tohaker** [googleapis/google-cloud-python#9947]
#### Environment details

OS type and version: __Windows 10__ and __GCP Cloud Functions__
Python version and virtual environment information: __3.7__
google-cloud-storage version:  __1.23.0__

#### Steps to reproduce

  1. I used the example provided [here](https://cloud.google.com/storage/docs/access-control/signing-urls-with-helpers) as implemented in my [own GCP Function](https://github.com/Tohaker/yugiohbot-function-signed-url/blob/master/yugiohbot/main.py). Calling this function simply returns the SignedURL
2. I then make a PUT request using Axios on Node.JS React: 
```js
const url =
    "https://us-east1-yugiohbot.cloudfunctions.net/yugiohbot_signed-url";

  await axios
    .post(url, {
      bucket: "yugiohbot-images/pending",
      filename: file.name,
      contentType: file.type
    })
    .then(response => {
      console.log(response)
      axios
        .put(response.data.signed_url, file, {
          headers: {
            "Content-Type": file.type
          }
        })
        .then(response => {
          console.log("success : ", response);
        })
        .catch(error => {
          console.log("errorSubmitImage : ", error);
        });
    })
    .catch(error => {
      console.log("errorSignedURL : ", error);
      return "";
    });
```
3. I'm then returned the following error:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Message>

<StringToSign>GOOG4-RSA-SHA256
20191208T095342Z
20191208/auto/storage/goog4_request
21903a0d1ce8ea5f4904f57413a91018496e3584e20cc5242f3f4656f5ef9adb</StringToSign>

<CanonicalRequest>PUT
/yugiohbot-images/pending/testimage.jpg
X-Goog-Algorithm=GOOG4-RSA-SHA256&amp;X-Goog-Credential=signed-url-generator%40yugiohbot.iam.gserviceaccount.com%2F20191208%2Fauto%2Fstorage%2Fgoog4_request&amp;X-Goog-Date=20191208T095342Z&amp;X-Goog-Expires=29&amp;X-Goog-SignedHeaders=content-type%3Bhost
content-type:image/jpeg
host:storage.googleapis.com

content-type;host
UNSIGNED-PAYLOAD</CanonicalRequest>
</Error>
```

I've searched around for a long time, and everyone else's problems seems to have been solved by the inclusion of the Content-Type header - however this has not been the case for me.

I'm obviously missing something, can anyone spot it?

**Comment by HemangChothani** [comment]
@Tohaker Things you missed like if you want to upload a file through `signedurl` than you have to pass keyword argument `method="RESUMABLE"` in [generate_signed_url](https://github.com/Tohaker/yugiohbot-function-signed-url/blob/master/yugiohbot/main.py#L35) method and then first need to hit post request , if `response code = 201` then hit put request.

Sample Code:

    axios.post(url, { bucket: "praful-test-bucket/images/pending", filename: "sample-file"}) 
    .then((response) => {   
      const options = {
          headers: {"x-goog-resumable": "start"}
      };
     axios.post(response.data.signed_url, {},options)
     .then(axiosResponse => {     // make sure axiosResponse.status = 201
        axios.put(axiosResponse.headers.location, "file",{headers: {"Content-Type": "application/json", 'Content-Length': 4}}).then(postResponse => {
          console.log("success : ", postResponse);
        }).catch(error => {
          console.log("put : ", error);
        });
    }).catch(error => {
      console.log("post : ", error);
      return "";
    }).catch(err => console.warn(err));
        })
        .catch(error => {
          console.log("errorSubmitImage : ", error);
        });

**Comment by HemangChothani** [comment]
@Tohaker if sample code  wouldn't helpful to solve the problem feel free to reopen.

**Comment by Tohaker** [comment]
@HemangChothani Thanks so much for this code. Apologies for the delay but I only just managed time to test it out.
I'm getting a CORS error when trying to POST to the signedURL I get back from my function: 
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at <signed_url>
```
Is this something I have to set up in my Bucket?

**Comment by HemangChothani** [comment]
@Tohaker  The cors in [bucket document](https://cloud.google.com/storage/docs/json_api/v1/buckets#resource-representations) would be helpful.

**Comment by Tohaker** [comment]
Hmm, so I've changed my CORS config for my bucket as so:
```
[
	{
		"origin": ["*"],
		"responseHeader": [
			"Content-Type",
			"Access-Control-Allow-Origin",
			"x-goog-resumable"
		],
		"method": ["PUT", "POST"],
		"maxAgeSeconds": 60
	}
]
```
But I'm still getting these errors from the initial POST:
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Message><StringToSign>GOOG4-RSA-SHA256
20191223T191021Z
20191223/auto/storage/goog4_request
ceaba90f2a41d91727f7258f870ba9c416a757b3f5e1af3e1e0f382d040a246d</StringToSign><CanonicalRequest>POST
/yugiohbot-images/pending/testimage.jpg
X-Goog-Algorithm=GOOG4-RSA-SHA256&amp;X-Goog-Credential=signed-url-generator%40yugiohbot.iam.gserviceaccount.com%2F20191223%2Fauto%2Fstorage%2Fgoog4_request&amp;X-Goog-Date=20191223T191021Z&amp;X-Goog-Expires=29&amp;X-Goog-SignedHeaders=content-type%3Bhost%3Bx-goog-resumable
content-type:application/json;charset=utf-8
host:storage.googleapis.com
x-goog-resumable:start

content-type;host;x-goog-resumable
UNSIGNED-PAYLOAD</CanonicalRequest></Error>
```

Any idea what I'm missing this time?

**Comment by HemangChothani** [comment]
@Tohaker  Not sure what you have missed . but the  [sample code](https://github.com/googleapis/google-cloud-python/issues/9947#issuecomment-563969186) is working fine for me.
