### ISSUE TITLE
TablesClient: make predict no longer call `get_model` and remove related arguments [breaking change]

### ISSUE THREAD

**Issue by helinwang** [googleapis/google-cloud-python#9971]
Currently, for every [`predict`](https://github.com/googleapis/google-cloud-python/blob/master/automl/google/cloud/automl_v1beta1/tables/tables_client.py#L2593-L2603) call, two API requests are made:
1. [`get_model`](https://github.com/googleapis/google-cloud-python/blob/master/automl/google/cloud/automl_v1beta1/tables/tables_client.py#L221-L232)
2. `predict`

`get_model` is costly, often 0.5s, but sometimes 10s in my tests (when the project contains huge number of models).

Planning to never do `get_model` call in `predict`, and the user has to do a manual `get_model` call before making (repeated) predictions. So the cost is explicit and the user will never be caught off guard.

This will be a breaking change, we will need to bump the major version.

CC: @busunkim96 @sirtorry

**Comment by busunkim96** [comment]
@helinwang Have you seen customers filing issues about this?

Technically since the AutoML library is pre-GA (currently 0.9.0) you can make a breaking change in a minor bump.

**Comment by helinwang** [comment]
@busunkim96 we found this issue and think it's important to fix, since predict is commonly called and get_model is only required to be called once. We don't want the user to be caught off guard.
Good to know we have the option to only bump the minor version.
I suspect most of the `predict` calls will be broken because most of the users will use `model_name`, which will be removed. Do you recommend bump minor or major version?

**Comment by busunkim96** [comment]
The minor bump is what matches our policy now. I'd still anticipate folks being caught off guard and filing issues. We had folks filing issues for translate even though we did make the breaking change in a major version, for instance.

We will be doing a major bump across the board as we drop support for Python 2. At that point we might start making breaking changes pre-GA a major version bump.

**Comment by helinwang** [comment]
Thanks @busunkim96 , sounds good.

**Comment by helinwang** [comment]
It's a good to have feature, but since TablesClient is in maintenance mode, I am closing this issue.
