### ISSUE TITLE
BigQuery: TypeError when instantiating a Client

### ISSUE THREAD

**Issue by rafa-acioly** [googleapis/google-cloud-python#9983]
#### Environment details

Ubuntu 18.04.3 LTS
python3.7
google-cloud-bigquery==1.23.0

#### Steps to reproduce

Trying to create a new bigquery Client with "custom" credential.

#### Code example'

```python
key_path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")

from google.cloud import bigquery
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    key_path,
     scopes=["https://www.googleapis.com/auth/cloud-platform"],
)

client = bigquery.Client(
    credentials=credentials,
    project=credentials.project_id,
)
```

#### Stack trace
```
TypeError: __init__() takes 2 positional arguments but 3 were given
```

The `TypeError` is raised from `bigquery.Client` ;

```py
kw_args = {"client_info": client_info}
        if client_options:
            if type(client_options) == dict:
                client_options = google.api_core.client_options.from_dict(
                    client_options
                )
            if client_options.api_endpoint:
                api_endpoint = client_options.api_endpoint
                kw_args["api_endpoint"] = api_endpoint

        # Error occurs here, the kw_args variable is {"client_info": None}
        self._connection = Connection(self, **kw_args)  
```

The code example used came from the docs-samples;

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/1a87fb3e076d60ec6bde274c9aecf7dc5296a43b/bigquery/cloud-client/authenticate_service_account.py

**Comment by plamut** [comment]
Following the sample code, I was not able to reproduce the issue with the very latest BigQuery release (1.23.1) locally. It could be something specific to my setup, though.

@rafa-acioly Could you please try with the latest version to see if you can still reproduce the issue with it? Thanks!

**Comment by tswast** [comment]
This sounds like an old version of the google-api-core package.

**Comment by rafa-acioly** [comment]
@plamut with the version 1.23.1 it worked

**Comment by plamut** [comment]
@rafa-acioly Great, thanks for the update! Seems like we can mark this ticket as resolved then.
