### ISSUE TITLE
storage: google.cloud.storage.batch.Batch _do_request not updated  

### ISSUE THREAD

**Issue by aldeirm2** [googleapis/google-cloud-python#9986]
Storage: 

After **google-cloud-core** was updated to version 1.1.0, the `_make request()` function in `JSONConnection` has a new argument called `timeout` which it passes to `_do_request()`.

The `Batch `class in the latest version of **google-cloud-storage** 1.23.0 overrides the method `_do_request()` from `JSONConnection` however does not have a 'timeout' argument which is causing errors when calling the blob.delete() method under a batch context with the error: 

`TypeError: _do_request() got an unexpected keyword argument 'timeout'`

I think the **google-cloud-storage** wheel needs to be updated to be in line with the updates from google-cloud-core. 

Right now as a work around I have to use the old version of core( 1.0.3) until this is fixed on the storage side.

Env: python3.6

Thanks

**Comment by busunkim96** [comment]
@aldeirm2 Thank you for filing an issue!

@crwilcox @frankyn Would one of you be able to make this change?

**Comment by HemangChothani** [comment]
duplicate issue of [9951](https://github.com/googleapis/google-cloud-python/issues/9951),so closing this issue.
