### ISSUE TITLE
BigQuery: DATETIME columns invalid when uploaded with `load_table_from_dataframe`

### ISSUE THREAD

**Issue by tswast** [googleapis/google-cloud-python#9996]
https://github.com/googleapis/google-cloud-python/issues/9920#issuecomment-566642042

**Comment by tswast** [comment]
See:

https://github.com/googleapis/google-cloud-python/blob/2dabc2dcc606e3867e25fd86ede21614cdcaaa04/bigquery/google/cloud/bigquery/_pandas_helpers.py#L55

and

https://github.com/googleapis/google-cloud-python/blob/2dabc2dcc606e3867e25fd86ede21614cdcaaa04/bigquery/google/cloud/bigquery/_pandas_helpers.py#L79

The fix is likely to change the pyarrow type to `ns` to match pandas behavior. We'll definitely want a system test to verify the fix.

**Comment by tswast** [comment]
One thing to consider: the full range of DATETIME is not supported when nanosecond precision is used.

We need to check the input precision and make sure it matches the Arrow precision we use.

**Comment by emkornfield** [comment]
@tswast I think the short term fix would be to change datetime64 to TIMESTAMP instead of datetime64?

**Comment by HemangChothani** [comment]
@tseaver   `pyarrow.timestamp("ns", tz=None)` doesn't help to resolve the issue, I've also tried with manually generated files but unable to find the resolution, I'm not sure but there may be something related to the backend as well?

**Comment by emkornfield** [comment]
@HemangChothani Can you try changing https://github.com/googleapis/google-cloud-python/blob/2dabc2dcc606e3867e25fd86ede21614cdcaaa04/bigquery/google/cloud/bigquery/_pandas_helpers.py#L55 to be TIMESTAMP.

**Comment by HemangChothani** [comment]
@emkornfield I have tried with the change and it's working fine.

**Comment by emkornfield** [comment]
I'll let others chime in, but in the short term I think this might be a reasonable fix.  The main downside is that it doesn't allow round-tripping "datetime64[ns]", but at least data is preserved.

**Comment by tswast** [comment]
If you manually specify TIMESTAMP in the job_config, does that work?

I’d prefer to keep time zone less columns mapping to DATETIME and fix the conversion.

**Comment by HemangChothani** [comment]
@tswast  Yes it works if i manually specify `TIMESTAMP` in the job_config.

**Comment by tswast** [comment]
OK, thanks. Since we have a workaround, I'll drop the priority to P2.

**Comment by tswast** [comment]
For system tests of this fix, I'd like to see supported types added to https://github.com/googleapis/google-cloud-python/blob/master/bigquery/samples/load_table_dataframe.py and the tests for that sample updated to read and verify the table data.

I'll work on updating the tests for currently-supported data types.

**Comment by tswast** [comment]
Created draft PR https://github.com/googleapis/google-cloud-python/pull/10028 to hopefully reproduce this issue in a system test.

**Comment by tswast** [comment]
I see in the unit tests for this that uploading DATETIME columns was blocked by https://issues.apache.org/jira/browse/ARROW-5450, so once this issue is fixed, we'll require the latest version of `pyarrow` to upload DATETIME columns.

**Comment by tswast** [comment]
I investigated this further by capturing the Parquet file that is generated by `_pandas_helpers.dataframe_to_parquet`.

**client.py**
```
            if pyarrow and job_config.schema:
                if parquet_compression == "snappy":  # adjust the default value
                    parquet_compression = parquet_compression.upper()

                _pandas_helpers.dataframe_to_parquet(
                    dataframe,
                    job_config.schema,
                    tmppath,
                    parquet_compression=parquet_compression,
                )
                import shutil
                shutil.copyfile(tmppath, "/Users/swast/Desktop/dataframe.parquet")
            else:
```

[dataframe.parquet.zip](https://github.com/googleapis/google-cloud-python/files/4017466/dataframe.parquet.zip)

When I upload `dataframe.parquet` via the web interface, I'm not able to reproduce the issue. There must be something different with how we upload the data file from Python.

**Comment by tswast** [comment]
I'm able to reproduce this with the command-line:

```
bq load --source_format=PARQUET --schema=wikidata_id:STRING,title:STRING,release_year:INTEGER,length_minutes:FLOAT,release_date:TIMESTAMP,dvd_release:DATETIME my_dataset.monty_python dataframe.parquet
```

**Comment by tswast** [comment]
Since I'm able to reproduce this error with the command-line, I believe it is a backend issue. I've filed internal bug 147108331 for the backend engineers to investigate.

**Comment by tswast** [comment]
I was able to create a Parquet file with nanosecond-precision DATETIME columns, but the backend still multiplies the values by 1000. It seems we can't write DATETIME columns from Parquet without a backend fix.

[dataframe_nanos.parquet.zip](https://github.com/googleapis/google-cloud-python/files/4017608/dataframe_nanos.parquet.zip)

**Comment by tswast** [comment]
After all this, I think the best option is to write `datetime[ns]` dtype columns as TIMESTAMP, since I'm not able to write correct DATETIME columns with parquet files. I've updated my draft PR with this workaround.

**Comment by tswast** [comment]
Talked with the backend engineers. DATETIME is not supported for uploading from Parquet (treating my request as a feature request), so changing the dtype to TIMESTAMP is the correct solution.
